### ISSUE TITLE
Publishing from Cascade to Twitter and Facebook

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#183]
Hey @mwengstrom and @c-schwarze 

Can you guys do a little investigating for us?

In a dream world, I'd love to have a fields in Cascade that would publish out content to Twitter and Facebook.

So for example, someone could be loading a news story and there would be a field where they could add text for a Tweet right in Cascade. Then when they publish the story, it would be published to Twitter automatically along with a link back to the news story.

Does that kind of make sense?

I'd love to know if it's possible and how difficult it might be to implement.

Thanks so much!
KL

**Comment by e-jameson** [comment]
Can we close this?

**Comment by e-jameson** [comment]
we aren't not doing this because we don't want all or nothing.
