### ISSUE TITLE
Stories - Story Hub

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#244]
Here is an issue for the Stories hub.

This is the latest update from @c-schwarze:

@ErikGruber 

Here is a working Profile Story Hub page (#4 above). It is lacking in the test data, but there are the 3-columns you asked for. Also, it puts each profile story on each school it matches.

http://staging.bethel.edu/_testing/caleb-test-folder/profile-story-hub

It is super rough, but it has just a tiny bit of cleaning up to do.

**Comment by e-jameson** [comment]
Hey @mwengstrom can you start looking into this?

**Comment by annmarieven** [comment]
Anyone know what this is?

**Comment by c-schwarze** [comment]
Well, it was supposed to be a page where you can view all profile stories by school. Do we need it anymore?

**Comment by c-varberg** [comment]
https://staging.bethel.edu/_testing/calebv/StoryHub
I moved the code into velocity, but it still looks exactly the same

**Comment by e-jameson** [comment]
@ErikGruber can you review this sometime.

**Comment by e-jameson** [comment]
Going to close this. I'm guessing it will resurface for text o' media someday but oh well.
