### ISSUE TITLE
Cleaning up asset factories

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#302]
Hey all,

I believe we have a few asset factories that we're not using:

Carousel Viewer
Proof Point pageblock
Quote pageblock

I think the Collections have replaced all of these so I'd like to delete them.

Let me know if you think otherwise!

**Comment by annmarieven** [comment]
I'm going to schedule a meeting to clean up data defs, content types, config sets, asset factories, etc. that we're not using.

**Comment by c-schwarze** [comment]
Has this meeting been scheduled?

**Comment by e-jameson** [comment]
We had it and @annmarieven has a list of todo's to assign.

**Comment by annmarieven** [comment]
working on collection clean up.

**Comment by annmarieven** [comment]
@a-parrott do you want to work towards making job posting feeds and faculty feeds blocks instead of pages?

job posting:
https://cms.bethel.edu/entity/relationships.act?id=619f5c8d8c5865130c130b3a88351726&type=contenttype

faculty:
https://cms.bethel.edu/entity/relationships.act?id=e15649578c5865137938fc88b6f25aaa&type=contenttype

**Comment by a-parrott** [comment]
Pages are blocks now. Before I complete the last steps, a couple things:

Faculty job postings are now missing headings:
No headings: https://staging.bethel.edu/employment/openings/faculty
Headings: https://www.bethel.edu/employment/openings/faculty

I was unable to delete the faculty feed page: No outputs selected— https://cms.bethel.edu/entity/open.act?id=e5cadb6f8c5865137938fc885b8da72f&type=page

Please assign back to me when that's fixed, and I'll finish up the last steps. Thanks!

**Comment by c-schwarze** [comment]
The 2 links you posted look the same to me. Which headings are you referring to?

I deleted the faculty feed page. I had to manually delete it on the server though. It was being finicky.

**Comment by a-parrott** [comment]
Oh. I don't remember publishing to production, but now unfortunately, they do look the same. 

Previously, the job postings were listed by school versus just alphabetically. So the College or Arts and Sciences, the College of Adult and Professional Studies, etc. were the headings and the corresponding jobs were listed under the school headings.

**Comment by c-schwarze** [comment]
It looks like Display all jobs needs to be set to Yes, in order to choose the Group by school option.

**Comment by a-parrott** [comment]
All right. I think my part in this shindig is done. 

@e-jameson did you complete whatever needed to be done with the job posting feed?

**Comment by e-jameson** [comment]
Yep.
