### ISSUE TITLE
Health Services Launch and Site Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#303]
We're launching Health Services. We're doing testing in Chrome, FF, and Safari. This is a very basic site so we're not testing IE.

https://www.bethel.edu/health-services/

Note any problems here!

**Comment by annmarieven** [comment]
@ale73233 can you make a list of redirects for this site:
https://bethelnet.bethel.edu/health-services/index/@@index.html
to the respective pages in the new health services site? https://www.bethel.edu/health-services/

Create the list here: https://docs.google.com/a/bethel.edu/spreadsheets/d/18pErtI6ySzi5gw13sSsBb_2eFl4JJAY3eDUhizTuiVc/edit#gid=0

Then assign this issue to @e-jameson for redirecting.

**Comment by annmarieven** [comment]
Also, once those are redirected, @ale73233 can you close the content in bethelnet?

**Comment by ale73233** [comment]
Can you do these redirects and let me know when they are done? 
https://docs.google.com/a/bethel.edu/spreadsheets/d/18pErtI6ySzi5gw13sSsBb_2eFl4JJAY3eDUhizTuiVc/edit#gid=0

Thanks!

**Comment by ale73233** [comment]
redirects done, closed health-services in old silva
