### ISSUE TITLE
Basic plus phase out

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#319]
Hey! 

I'm going to get started moving us away from basic plus. I'll work on getting everything in Basic that needs to move there. 

After that, we'll get working on the pages that need to move to flex.

**Comment by kelslundberg** [comment]
@johjacb would it be possible for us to have a caption on basic pages to use with videos? It used to be a part of basic plus template for something like this:

https://www.bethel.edu/undergrad/academics/faculty

And I kind of thought we wouldn't need it, but then I changed my mind.

I'm trying to rebuild the same page here. There's a caption field there, but it's not doing anything right now. If we want to keep it, I can move it below the block chooser in the data def so it's in the proper order.

https://cms.bethel.edu/entity/open.act?id=c62a0d508c58651375fc4ed289accb81&type=page

**Comment by kelslundberg** [comment]
Can we move Maps and Directions from basic plus content type to something else?

I think I need help with this one :) @e-jameson or @johjacb 

https://cms.bethel.edu/entity/open.act?id=ba13b80c8c586513100ee2a718241435&type=page&

I made a copy and tried to switch to basic or flex, but neither worked for me.

**Comment by kelslundberg** [comment]
Is this page working? It needs to move from basic plus too:

https://cms.bethel.edu/entity/open.act?id=17f06f818c586513742d45fdaa4f34ea&type=page

**Comment by kelslundberg** [comment]
This one too...

(admissions app)

https://cms.bethel.edu/entity/open.act?id=ff7ce1fb8c58651375fc4ed2568fd965&type=page

I don't really get how it's working :)

**Comment by kelslundberg** [comment]
Sorry, another one here...

(proof points search)

https://cms.bethel.edu/entity/edit.act?id=ba13bdfb8c586513100ee2a70669535a&type=page

**Comment by kelslundberg** [comment]
I'll recap my thread of comments above :)

Except for one page that's sitting with a contributor in workflow, I need some help moving these pages out of basic plus. I tried to move a few of them to flex, but it didn't appear to be successful for me :)

Maps and directions
https://cms.bethel.edu/entity/open.act?id=ba13b80c8c586513100ee2a718241435&type=page&

Page Counter
https://cms.bethel.edu/entity/open.act?id=17f06f818c586513742d45fdaa4f34ea&type=page

Admissions App
https://cms.bethel.edu/entity/open.act?id=ff7ce1fb8c58651375fc4ed2568fd965&type=page

Proof Points Search
https://cms.bethel.edu/entity/edit.act?id=ba13bdfb8c586513100ee2a70669535a&type=page

**Comment by e-jameson** [comment]
These should all be working now. Proof point search doesn't seem to load fast enough within Cascade. I published and it works well.

**Comment by kelslundberg** [comment]
Yay! Awesome! Thank you :)

@annmarieven - what do you want to do with Nadine's page that's still in workflow? Should I just delete the workflow and move the page to flex?

**Comment by annmarieven** [comment]
She's past her deadline so you can delete the workflow. Thanks :)

**Comment by kelslundberg** [comment]
Done and done. Closing this. Yep.
