### ISSUE TITLE
How to apply pages for adult programs

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#328]
I've built a data definition for how to apply pages based on our conversations. 

https://cms.bethel.edu/entity/open.act?id=7bf868f28c5865130c130b3a5efc79ff&type=structureddatadefinition

and I have it mapped out here in google docs:

https://docs.google.com/a/bethel.edu/spreadsheet/ccc?key=0AvCfERcmdTwpdHdzSXBnaGlDdEI0bXI0OVMzMG9ldkE#gid=16

Next steps:

@ErikGruber is going to finalize the default headings and instructions for each step. 

And @e-jameson will need to look at banner integration. Step 1 should automatically pull in Admissions Requirements for the program and Step 3 will pull in the Admissions Checklist.

**Comment by annmarieven** [comment]
These are no longer working.

**Comment by c-schwarze** [comment]
It should be fixed. I didn't really know what it was supposed to look like -- I just patched it up.

Let me know if it looks right!

**Comment by annmarieven** [comment]
I've checked a few others, but the mba one seems to be the only one that got fixed. And I have published a few times and checked in an incognito window.

https://staging.bethel.edu/graduate/academics/education-doctorate/how-to-apply

**Comment by e-jameson** [comment]
There is no data in Banner for most anymore. It disappeared. @hamtim said they were working on it (?)

http://wsapi.bethel.edu/capsgs-checklist/2-MS-PASG/2

**Comment by hamtim** [comment]
I'm not sure why updating the items has been so difficult for admissions. I'm meeting with Vickie this afternoon and will tell her that they need to figure it out because we're launching with whatever is on those pages. #fail
