### ISSUE TITLE
Individual Courses - Banner Integration

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#330]
This is part of the GS site, but it's outside of the program pages. So we'll need to figure out how we want to set it up in Cascade:

http://gs.bethel.edu/academics/individual-courses/

Thanks!
KL

**Comment by annmarieven** [comment]
@e-jameson where is this at? I went to your jmo/basic page but it looks like it's a test for proof points now.

**Comment by e-jameson** [comment]
https://staging.bethel.edu/_testing/jmo/block-pages/individual-courses

**Comment by e-jameson** [comment]
@c-varberg this can be set to autoCache for 12 hours.

**Comment by c-varberg** [comment]
alright, it appears to be working now. 
I used the same page and block. The format I used it here. 
/_cascade/formats/blocks/blocks-without-data-definitions/individual-courses

**Comment by e-jameson** [comment]
@c-varberg can you push your code to GitHub?

**Comment by c-varberg** [comment]
oh yea sorry. I forgot I added to the php

**Comment by e-jameson** [comment]
@hamtim @annmarieven @ErikGruber @johjacb This is ready to be looked at.

Only thing I know we need to ad is the little expand / collapse buttons.

**Comment by annmarieven** [comment]
@e-jameson  can you look at why this is blank? 

https://staging.bethel.edu/_testing/jmo/block-pages/individual-courses

Can you show me how to set this up for caps and gs so it's pulling the right content?

**Comment by e-jameson** [comment]
Its not blank anymore?

**Comment by c-schwarze** [comment]
Didn't know an issue was open for this. Fixed this.

**Comment by annmarieven** [comment]
@johjacb can you add the little expand / collapse buttons?

**Comment by johjacb** [comment]
I updated the html - expand button should be there now

**Comment by e-jameson** [comment]
@annmarieven do we need this issue open still?

**Comment by annmarieven** [comment]
looks good!
