### ISSUE TITLE
Adding groups to majors/minors for emphases

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#354]
We need to change (or add) to the 4 questions about majors/minors so people can answer the questions for multiple emphases.

We'll also need to have an anchor link automatically created based on the heading of the specific emphasis so a list at the top of the page could link down to each one. Then we can also link from other places in the dept site to that specific emphasis.

Things @e-jameson and I talked about - 
Do we want to leave the first set of questions there for majors/minors that don't have emphases?
Do NOT move the current fields into groups or all the current content will disappear.

I will talk with @kelslundberg too to decide on the best way to do this.

**Comment by annmarieven** [comment]
Can we take a look at the anchor link thing now? Here's the note from the original request:

Once that's formatted correctly, we also want an anchor automatically created based on the heading of the specific emphasis so a list at the top of the page could link down to each one. Then we can also link from other places in the dept site to that specific emphasis. I'm not sure how this will work. Assuming something @e-jameson would do?

**Comment by e-jameson** [comment]
Added anchor links and list at the top

https://cms.bethel.edu/entity/open.act?id=2ff013ff8c58651365fd6823f37c718d&type=page

**Comment by annmarieven** [comment]
Put into bulleted list, place below intro paragraph.

I will talk with @parlau about a heading for this section. "Choose an Emphasis" or something like that.

**Comment by e-jameson** [comment]
updated

**Comment by annmarieven** [comment]
Emailed Lauren and will wait to hear back on the heading.

**Comment by annmarieven** [comment]
This is done and is ready to go @parlau! Closing issue.

Feel free to reopen if you run into any issues :)
