### ISSUE TITLE
Homecoming Site Launch & Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#360]
I'm going to work with @a-gundy to migrate the Homecoming site.

**Comment by annmarieven** [comment]
@c-schwarze or @e-jameson can you migrate this site for @a-gundy to work on since @mwengstrom isn't in again until Monday? Sometime today before 1 would be awesome!

**Comment by e-jameson** [comment]
The homecoming site does't really link to the site at all? Our download tool only got the index page and two images. I'm not sure how helpful its going to be without more linking throughout the site.

**Comment by annmarieven** [comment]
Can you run it from this url? https://www.bethel.edu/events/homecoming/reunions/ so it gets these few things too?

**Comment by e-jameson** [comment]
Okay, I pulled what I could. It isn't much at all. @c-schwarze will migrate this morning.

**Comment by annmarieven** [comment]
Where is it in Cascade? I can't find it..

**Comment by e-jameson** [comment]
I don't think he has migrated yet

**Comment by c-schwarze** [comment]
Migrated. There is almost nothing in it though... It is under 'homecoming'

**Comment by annmarieven** [comment]
@a-gundy, can you clean up what was pulled over for the homecoming site?

There are a few other pages we'll have to manually build as well:
https://www.bethel.edu/events/homecoming/alumni-scholarship/
https://www.bethel.edu/events/homecoming/registration
https://www.bethel.edu/events/homecoming/schedule

These can all be shown in the navigation and site maps (they're hidden now which is why they didn't get automatically migrated)

You can try to do what you can for the index page but most likely you will need some assistance from @johjacb so feel free to tag him in here when you're done with everything else and if you need help finishing it up.

Reassign to me when you're finished. We'll do a final proof and take care of launching :)

Thanks!!

**Comment by a-gundy** [comment]
@johjacb would you check this page in cascade (https://cms.bethel.edu/entity/edit.act?id=c55a0fe88c5865132a1de4ef988075f4&type=page) and let me know if I need to do anything to make it match up better with the Silva page (https://www.bethel.edu/events/homecoming/).

Thanks!

**Comment by johjacb** [comment]
i shuffled a few things around. probably about as good as it needs to be for now

**Comment by a-gundy** [comment]
Reassigning to @annmarieven for proofing.

**Comment by annmarieven** [comment]
**https://staging.bethel.edu/events/homecoming/schedule**
fix p tags

**https://staging.bethel.edu/events/homecoming/alumni-scholarship/**
unhide title
fix donate now button

republish everything to staging and do a final run through, then reassign to me :) Thanks @a-gundy !!

**Comment by a-gundy** [comment]
Everything looks good to me. Reassigning to @annmarieven.

**Comment by annmarieven** [comment]
This site is ready to launch on Thursday. No redirects or rules will be needed.

@johjacb the only question I have is the large space at the top of the header image. https://staging.bethel.edu/events/homecoming/

**Comment by johjacb** [comment]
yep - that's going to stay as is unfortunately. 

That is the space that launched a 1,000 ships. aka, changing everything to One and Flex and eliminating extra Content Types, etc etc. Basically I've been working for like 2 months to eliminate it.

It will be gone with Soda.

**Comment by annmarieven** [comment]
@kelslundberg will look at Firefox
I will look at Safari

Final proof will be done in Chrome.

**Comment by kelslundberg** [comment]
We'll also proof in Soda:

Chrome on Android 4.4.4
Safari on iOS 8.1.3

**Comment by kelslundberg** [comment]
Looks good in Firefox

**Comment by annmarieven** [comment]
Looks good in Safari

**Comment by kelslundberg** [comment]
Good on android

**Comment by annmarieven** [comment]
Looks good in Safari on iOS 8.1.3.

Not crazy about the header image but that will all be changing before we begin promotion for 2015.

**Comment by kelslundberg** [comment]
Site published

Emailing web author

Closing the githubs
