### ISSUE TITLE
Family Weekend Site Launch & Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#361]
I'm going to work with @a-gundy to migrate the Family Weekend site.

**Comment by a-gundy** [comment]
I think the site is ready for launching. 
Cascade link:
https://cms.bethel.edu/entity/open.act?id=c4c8d8ad8c5865132a1de4ef03b51eae&type=folder&
Silva link:
https://editor.its.bethel.edu/silva/www/events/family-weekend/edit/tab_edit

**Comment by annmarieven** [comment]
Assigning to myself for proofing.

**Comment by annmarieven** [comment]
@a-gundy can you take care of the following:
**https://staging.bethel.edu/events/family-weekend/**
hide the page title
adjust headings to be h2

Just fyi, I unhid the left hand nav items.

This site is ready to go once these 2 things are done! Thanks @a-gundy!!

You can reassign it to me and we will take care of launch over here. :)

**Comment by a-gundy** [comment]
Ready for launching.

**Comment by annmarieven** [comment]
@kelslundberg will check FF. I will look at Safari. Final proof in Chrome.

**Comment by kelslundberg** [comment]
FF looks gooooood

**Comment by annmarieven** [comment]
Safari looks swell. publishing to prod, setting up workflows and access.

**Comment by annmarieven** [comment]
This site is live! Closing issue.
