### ISSUE TITLE
Summer Employee Events Site Launch & Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#363]
@mwengstrom,
can you run the migration tool on this site tomorrow (Dec 11)?
https://editor.its.bethel.edu/silva/www/events/summer-staff/edit/tab_edit

Assign the job to @a-gundy when you're done.

Thanks!

**Comment by annmarieven** [comment]
@a-gundy can you take care of the following?
**https://staging.bethel.edu/events/summer-staff/index**
hide the page title
look for larger images - maybe contact Michelle if you can't find them in Flickr. Or use photos with a creative commons license (which means we can use them w/o breaking copyright laws). Or check the images we use in the header to see if you can crop parts of those photos to use on the homepage.

**https://staging.bethel.edu/events/summer-staff/summer-chapel**
enter a display name as "Summer Chapel"

**https://staging.bethel.edu/events/summer-staff/mini-golf**
enter a display name as "Mini Golf Open"

**Other**
Reorder left hand nav so mini golf is first

**Comment by annmarieven** [comment]
Once those things are done this site is ready to launch. Good work @a-gundy!

**Comment by annmarieven** [comment]
Oops. Forgot one thing for you @a-gundy. All headings that were h3 in Silva need to be converted to h2 in Cascade. And any headings that were h4 in Silva should be h3 in Cascade. Since this site doesn't have many, we can manually change them. For Homecoming, we should be able to run something so it does it automatically.

**Comment by a-gundy** [comment]
@annmarieven I was able to fix everything except the pictures and the left hand nav. I replaced the pictures with larger images (cropped from the header images or under creative commons license), but I think the cache needs to be cleared out before the change shows up in staging. 

Would you explain how changing the left nav works in cascade? I haven't done it before.

**Comment by annmarieven** [comment]
This site is ready for launch. @kelslundberg will look over in FF and I'll do Safari.

**Comment by kelslundberg** [comment]
FF looks groovy

**Comment by annmarieven** [comment]
Safari looks great. Publishing to prod.

**Comment by annmarieven** [comment]
This site is live!
