### ISSUE TITLE
Automatic titles on Cascade pages

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#365]
@vedmic just noticed that our Cascade pages don't have the "| Bethel University Minnesota" piece in our titles.

In Silva we had that and had the site title too. So, "MBA | Graduate Academics | Bethel University Minnesota"

@e-jameson is this something you have to take care of?

**Comment by kelslundberg** [comment]
We're going to try to do this next week.

**Comment by annmarieven** [comment]
Closing issue.
