### ISSUE TITLE
Migration Tool - Residence Life

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#374]
Hey @e-jameson 

It would be awesome to migrate the Res Life site tomorrow.

https://www.bethel.edu/undergrad/student-life/residence-life/

All pages are full width except for the hall pages, which are 60/40:

https://www.bethel.edu/undergrad/student-life/residence-life/halls/arden-village

Don't know if you want to run it twice? Otherwise I can build the hall pages by hand if that's a lot of work.

Thanks!
KL

**Comment by e-jameson** [comment]
I ran this before break.
