### ISSUE TITLE
Preload forms

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#377]
What all do we need to do to have preload forms fully tested?

I'd love to get those up and running in Cascade since the functionality has been built!

There are some in the res life site here:

https://cms.bethel.edu/entity/open.act?id=978800bf8c5865132a1de4ef6e9c35c7&type=page&

https://cms.bethel.edu/entity/open.act?id=978fbb638c5865132a1de4eff5bc4dde&type=page

**Comment by e-jameson** [comment]
I glanced at those pages and noticed they didn't require auth. Right now a form block that has "preload" selected but embedded on a page without requiring auth will not work correctly. Other than that everything should be ready to test.

**Comment by e-jameson** [comment]
@hamtim and I chatted and we are going to add a warning to handle the case above

**Comment by e-jameson** [comment]
The warning is in place.

**Comment by kelslundberg** [comment]
Great! All of the forms set to preload for Res Life appear to be loading...

Should I close this?

**Comment by e-jameson** [comment]
I think we should indeed close this.
