### ISSUE TITLE
Wordpress Feed

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#379]
We need to create some kind of feed that will pull blog posts from Wordpress. Let me know if you need more information :)

@e-jameson can you set priority on this? It's for the Library site.

**Comment by e-jameson** [comment]
We are going to hold off on an official block for this. Library can implement this themselves in the meantime via JS and the HTML block.

**Comment by annmarieven** [comment]
Followed up with Betsy. closing issue.
