### ISSUE TITLE
Dining Services Site Launch & Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#381]
We're launching this site:
https://staging.bethel.edu/dining-services/

@c-schwarze or @e-jameson, can you test the menu in IE? https://staging.bethel.edu/dining-services/locations/monson/menu

**Comment by e-jameson** [comment]
Menu looks good

**Comment by annmarieven** [comment]
Safari looks good. Need to add Enter Text Here into media + text asset.

**Comment by kelslundberg** [comment]
Chrome and Firefox look good

**Comment by kelslundberg** [comment]
Publishing....

**Comment by annmarieven** [comment]
@e-jameson can you put the rule in? I will take care of the redirects.
https://docs.google.com/a/bethel.edu/spreadsheets/d/1_RPJ87jcCgvLbkgl-VY0H6G7m4ezPxHcWUYlRHVVewg/edit#gid=0

**Comment by e-jameson** [comment]
Rule is done

**Comment by annmarieven** [comment]
Redirects in place. Final proof done. Looks good - closing issue.
