### ISSUE TITLE
Residence Life Site Launch & Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#382]
We're getting ready to launch this site: 
https://staging.bethel.edu/undergrad/student-life/residence-life/

I will do Safari.
@kelslundberg does Firefox.
Final proof was done in Chrome.

No IE testing needed. No new features here but we will check the preload forms specifically.

**Comment by kelslundberg** [comment]
Firefox is good.

**Comment by kelslundberg** [comment]
Publishing...

**Comment by kelslundberg** [comment]
Redirects in place. And there's no rule needed here.

**Comment by kelslundberg** [comment]
preload forms don't appear to be loading

https://staging.bethel.edu/undergrad/student-life/residence-life/ra-selection/apply/returning-application

**Comment by e-jameson** [comment]
I was working with Jay on wufoo earlier. I'll take a look as this is probably an unintended side effect.

**Comment by kelslundberg** [comment]
Working now. Thanks @e-jameson 

Closing

this

git
