### ISSUE TITLE
Gainful Employment Migration

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#383]
@e-jameson, we need to migrate this site.
https://www.bethel.edu/academics/gainful-employment/

I'd like Allie to do it but we need to know how we can create something in Cascade that functions the way these do in Silva: https://www.bethel.edu/academics/gainful-employment/14-15/anglican-studies

The files were pdfs but we loaded them so they would show up as an actual page, rather than a pdf to be downloaded. I think legally we needed to do it this way. https://editor.its.bethel.edu/silva/www/academics/gainful-employment/14-15/anglican-studies/edit/tab_edit

Can you show Allie how to do this in Cascade so she can migrate the site?

**Comment by annmarieven** [comment]
@ale73233 can you start migrating this site by creating a gainful-employment folder in Cascade under the academics section with an index page?

**Comment by e-jameson** [comment]
All we need is an asset factory to upload and publish an HTML file.

**Comment by annmarieven** [comment]
But I think we had them as pdfs and that was it?

**Comment by e-jameson** [comment]
Are you sure? The edit version has all the HTML in there:

https://editor.its.bethel.edu/silva/www/academics/gainful-employment/14-15/anglican-studies/edit/tab_edit

**Comment by annmarieven** [comment]
Yeah, she just was loading the pdfs and all the code appeared there. Now that we have the code though we can just copy and paste that, right? How do I create an asset factory for an HTML file?

**Comment by e-jameson** [comment]
Are you sure they were PDF's? Silva usually reports it as a PDF file type, not HTML like the page above:

https://editor.its.bethel.edu/silva/web-development/chapin/test-pdf/edit

Here is an asset factory for HTML files. I just copied the PDF one and replaced the plugin to force .html instead of .pdf

https://cms.bethel.edu/entity/open.act?id=cfc19a1e8c58651324d9038d3151a96d&type=assetfactory

**Comment by annmarieven** [comment]
@ale73233 can you try loading one of the pdfs using the HTML asset Eric just created? It's in the Files folder within the new menu.

**Comment by ale73233** [comment]
The html asset worked, I will upload the rest of them on Monday!

**Comment by ale73233** [comment]
I uploaded all of the html files into cascade and linked them onto the
gainful employment index page.

**Comment by annmarieven** [comment]
@ale73233, can you change the heading on the index page to h2 instead of h3? 

We changed our heading styles so what would be h3 and h4 in Silva are now h2 and h3 in Cascade.

**Comment by annmarieven** [comment]
@ale73233 somehow the rest of the html files were uploaded incorrectly because when I try to go to them on the live page (https://www.bethel.edu/academics/gainful-employment), they're all broken except nurse educator which we loaded together last week. let's fix this first thing tomorrow morning. Try loading one and see if you can fix it (publish it then check it live) and if you can't figure it out I can take a look with you :)

Then I'll have you implement these redirects and we'll be good to go! https://docs.google.com/a/bethel.edu/spreadsheets/d/1CJJLy6B9qPnfZlJYZM2KhSr-3-QQo8IsiHNvqAOdrjg/edit#gid=0

**Comment by ale73233** [comment]
The links are all up and working and I did the redirects! :)

**Comment by annmarieven** [comment]
Perfect! @ale73233 can you close the whole gainful employment folder in Silva and then close this issue?

Thank you!!

**Comment by ale73233** [comment]
I closed the folder in silva, closing this issue
