### ISSUE TITLE
IRB Site Launch & Issues

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#384]
@annmarieven and I are going to learn how to use the migration tool on Monday.

We can use this site as a test:

https://www.bethel.edu/academics/irb/

And then @a-gundy can help us with the clean up. @a-gundy - we'll update this github when it's ready for you!

**Comment by annmarieven** [comment]
This site has been migrated.
https://cms.bethel.edu/entity/open.act?id=e4ecdac78c58651324d9038d9d176c7d&type=folder

@a-gundy can you take care of the clean up and reassign to me when it's ready for proofing? Let me know if you have any questions along the way :)

Here is the migration grid which you can use to track the status of each page and make any notes on the pages/files. https://docs.google.com/a/bethel.edu/spreadsheets/d/1BxUTjlDdgBKo-XZrOHhx-DhXHSCBCzRLGZ4S9KyuyyI/edit#gid=1866014171

**Comment by a-gundy** [comment]
Reassigning to AnnMarie for proofing.

**Comment by annmarieven** [comment]
Looks great @a-gundy ! Can you test all the links on staging and then reassign to me? https://staging.bethel.edu/academics/irb/

**Comment by a-gundy** [comment]
Checked all of the links in staging. Reassigning to @annmarieven.

**Comment by annmarieven** [comment]
This site is ready to launch on Thursday. No rule or redirects are needed.

**Comment by annmarieven** [comment]
I will test in Safari and iOS 8 (safari)
@kelslundberg in Firefox and Android 4 (chrome)

**Comment by annmarieven** [comment]
Looks good in Safari and iOS 8 in staging and soda

**Comment by kelslundberg** [comment]
All groovy in Firefox and Android 4 Chrome

**Comment by annmarieven** [comment]
Site published.
@kelslundberg will annotate.
I contacted web author.
