### ISSUE TITLE
Classroom Oversight Committee Site Launch & Issues

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#386]
And one last site for @a-gundy to help with...

https://www.bethel.edu/academics/classroom-oversight/

And again, we'll decide who will migrate on Monday.

**Comment by annmarieven** [comment]
This site has been migrated.
https://cms.bethel.edu/entity/open.act?id=e4e4cd078c58651324d9038d1868ea29&type=folder

@a-gundy can you take care of the clean up and reassign to me when it's ready for proofing? Let me know if you have any questions along the way :)

Here is the migration grid which will give you some important info as you get started. https://docs.google.com/a/bethel.edu/spreadsheets/d/1BxUTjlDdgBKo-XZrOHhx-DhXHSCBCzRLGZ4S9KyuyyI/edit#gid=498516232

**Comment by a-gundy** [comment]
Assigning to @annmarieven for proofing. I made classroom-details a redirect, but it looks like you may have been looking for something else. Let me know.

**Comment by annmarieven** [comment]
@a-gundy Can you make it a basic page and then assign to @kelslundberg for some content for it? Or you could write something basic and put it on there. We just need some content to link people to the room booking service.

**Comment by a-gundy** [comment]
@kelslundberg I've cleaned up the pages for the site. I made a simple page to link to the Virtual EMS (https://cms.bethel.edu/entity/open.act?id=e8e366fd8c58651324d9038d99de6adf&type=page&). Let me know if you have new content you want me to put in.

**Comment by kelslundberg** [comment]
I just made a few tweaks! Should be good to go!

AMV, does this go back to you for proofing? Let me know if you need help with anything else.

**Comment by annmarieven** [comment]
@a-gundy can you make the headings h2/3 instead of h3/4? Then publish it to staging and do a final proof of it there.

**https://staging.bethel.edu/academics/classroom-oversight/projects**
rogue bullet point on this page.

Reassign to me when it's good to go :)

Thanks!

**Comment by a-gundy** [comment]
Proofed in staging. Reassigning to @annmarieven.

**Comment by annmarieven** [comment]
This site is ready to launch on Thursday.

**Comment by annmarieven** [comment]
@kelslundberg proofing on Firefox and Android 4 - Chrome
I am proofing on Safari and iOS 8 - Safari

---
Safari looks good in iOS 8 in staging and soda.

**Comment by kelslundberg** [comment]
Looks good in FF and in Android 4 Chrome

**Comment by annmarieven** [comment]
Site published.
@kelslundberg will annotate.
I contacted web author.
