### ISSUE TITLE
Teaching & Learning Technology Site Migration

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#389]
We're going to migrate this site and have @a-gundy clean it up:
https://www.bethel.edu/offices/learning-technology/

@e-jameson is site sucking it now. :) I will migrate it once that's done.

**Comment by annmarieven** [comment]
@a-gundy this site is ready for clean up and will probably need a lot of help.. : )

https://cms.bethel.edu/entity/open.act?id=ee3558658c5865132b154c9ecf157acf&type=folder&

**Comment by annmarieven** [comment]
Don't pull over the arrows on the homepage.

**Comment by a-gundy** [comment]
Reassigning to @annmarieven  for proofing.

**Comment by annmarieven** [comment]
**https://staging.bethel.edu/learning-technology/**
Can this be an office homepage?
Make the intro sentence a teaser.
Adjust time and phone numbers to Bethel style.
Make the "How can we help you?" go next to the wordle (using the media + text in the office homepage) -- we'll see how this looks.

**https://staging.bethel.edu/learning-technology/digital-media**
Unhide tittle.

**https://staging.bethel.edu/learning-technology/online-course-registration**
adjust sentence to "Use our Google form to [register online] for teaching and learning technology faculty development courses.

Reorder left hand nav and republish whole site to staging again.

Thanks @a-gundy!

**Comment by a-gundy** [comment]
@annmarieven, I made the changes you suggested. I don't think the media + text thing works very well on the index page ("How can we help you?" is way down at the bottom of the page), but see what you think.

**Comment by annmarieven** [comment]
@a-gundy sorry I'm just now getting back to this. What if we found photos for each of these items - help me decide, classroom support, general requests, and self service and made them all media + texts in the office hompage template.

Then make the how can we help you a media text on it's own and embed it in the feature zone.

The individual contacts can go to the 'additional content' section at the bottom of the page. 

Touch base with me on Flickr photos tomorrow so we can talk about what kind of pictures to find.

**Comment by a-gundy** [comment]
@annmarieven, I think it looks a lot better.

If you want different images of the classroom, this shot is pretty good (https://www.flickr.com/photos/betheluniversity/14120565122). A search for "active learning classroom" brings up a bigger list in Flickr if you want more options.

Thanks!
Abi

**Comment by annmarieven** [comment]
@e-jameson can you put a rule in for
https://www.bethel.edu/offices/learning-technology/

to go here:
https://www.bethel.edu/learning-technology/

**Comment by e-jameson** [comment]
donel

**Comment by annmarieven** [comment]
@a-gundy can you put a note in analytics that we launched this site on 3/17?

**Comment by a-gundy** [comment]
Done!
