### ISSUE TITLE
News breadcrumb broken links

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#391]
If you click on 2014 in the breadcrumb here you are redirected to bethel.edu/news:
https://www.bethel.edu/news/articles/2014/december/intersections

Can we implement that same functionality to all existing (and future) year and month folders and the 'articles' folder as well?

Or is there a way we can choose an option like, hide from breadcrumb so it would just be "Home > News > Story Name"

**Comment by annmarieven** [comment]
I need to respond in job 13674 before this issue is closed.

**Comment by e-jameson** [comment]
Looks like the redirect is just a tinker redirect. nothing fancy. We could add a "Skip in breadcrump" metadata option for folders if everyone is okay with that.

**Comment by annmarieven** [comment]
That would be useful for news and events and job postings. Does anyone have any objections? @johjacb @vedmic @kelslundberg?

**Comment by kelslundberg** [comment]
That's cool with me!

**Comment by annmarieven** [comment]
Alright, back to you @e-jameson

**Comment by e-jameson** [comment]
Can you add the metadata option and configure some folders properly before i work on the code? Easier to test if it's already in place.

**Comment by kelslundberg** [comment]
I've added this to basic and robust metadata sets: 

skip-breadcrumb
default: no

I didn't think we'd need it for job postings or event pages...but I can update those two if it's needed!

**Comment by annmarieven** [comment]
I think we should use it for job postings - https://www.bethel.edu/employment/openings/postings/2014/november/adjunct-faculty click on job postings, 2014, or november in the breadcrumb.

And events - https://www.bethel.edu/events/2015/library/lyndacom-panel-discussion (if you click on 2015 or library events)

**Comment by annmarieven** [comment]
Oops. This only applies to folders, not the actual content itself. So we should be good with it just on basic metadata because that's all folders use.

**Comment by e-jameson** [comment]
I've updated the code and tested. 

https://cms.bethel.edu/entity/open.act?id=3b44ca928c5865131faa2077a1a2a396&type=page

I did notice some folders are using default (2014 folder for example) so those won't work until they are switched over and set properly.

https://cms.bethel.edu/entity/open.act?id=d652a7a88c58651375fc4ed2337cbbcd&type=folder

And the pages will need to be published once all the folders / metadata are set correctly

**Comment by e-jameson** [comment]
Here is the list of things that use Default metadata

https://cms.bethel.edu/entity/open.act?id=0add24618c58651313b6fe6bc1a2e257&type=page

**Comment by annmarieven** [comment]
Opened a job for @ale73233  to work on these. 

@kelslundberg is going to create new asset factories for our web authors who need them (news, events, employment)

**Comment by kelslundberg** [comment]
I crated new asset factories:

Event Folder
Job Posting Folder 
News Folder

I gave access to Event Approver, Employment and News groups.

@annmarieven - would you like me to restrict folder placement? I guess it doesn't matter for events, but for Job Postings I can limit it to the postings folder and for news, I can limit it to the articles folder.

**Comment by annmarieven** [comment]
I restricted placement of the news folder and job posting folder. Closing issue.
