### ISSUE TITLE
Collapsible list description

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#393]
A little while ago we had talked about moving the description from the bottom of the content (when you expand an item) to the top. Can we do that?

https://soda.bethel.edu/undergrad/financial-aid/types/scholarships/

**Comment by e-jameson** [comment]
@johjacb, could you update that page so that the description doesn't need ".collapsible-block" for spacing. Once that is done we can update the JS accordingly.

**Comment by johjacb** [comment]
tightened things up a bit

**Comment by e-jameson** [comment]
@johjacb, could you update the JS to the code below. Once that is updated I can put the description above the expand content

function hasClass(elem, cls) {
   var str = " " + elem.className + " ";
   var testCls = " " + cls + " ";
   return(str.indexOf(testCls) != -1) ;
}

function nextByClass(node, cls) {
   while (node = node.nextSibling) {
       if (hasClass(node, cls)) {
           return node;
       }
   }
   return null;
}

collapsibleBlock = function(e) {
   e.preventDefault();
   // var subList = this.('.collapsible-block');
   this.classList.toggle('open-block');
   var next = nextByClass('collapsible-block');
   next.nextElementSibling.classList.toggle('open-block');
};

[].forEach.call(document.querySelectorAll('.collapsible-heading'), function(el){
   el.addEventListener('click',collapsibleBlock);
});

**Comment by johjacb** [comment]
added and live

**Comment by e-jameson** [comment]
@annmarieven this is done and the publishset was published (currently 39%). Closing

**Comment by annmarieven** [comment]
These are all broken again :( Did you test it @e-jameson ?

**Comment by annmarieven** [comment]
Some sample pages:
https://www.bethel.edu/undergrad/financial-aid/types/scholarships/
https://www.bethel.edu/undergrad/financial-aid/types/grants

**Comment by e-jameson** [comment]
Try clearing cache. I tested and just tested again.

**Comment by annmarieven** [comment]
Awesome. I see them now :) Thanks!
