### ISSUE TITLE
News story not posting

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#394]
From Suzanne in job 13715. 
Hello,

On Friday afternoon I posted a news story with an update on the new BUILD
program set to launch in the fall and it still hasn't appeared on the
website. From the Cascade side of things, everything looked correct and it
said that was added so I'm not sure why it is not appearing. I have no
error message to pass along with this one!

------
I tried to see if I could figure out why it didn't post but it appears the article itself was published and it's listed in the xml. Looks like the xml hasn't published since Dec 10 but there are other stories out since then so I have a feeling that's not it.

@e-jameson can you take a look? We have to get this figured out because if there's ever a bethel alert (a real one) that needs to go out or something and it *doesn't work*, we're in trouble.

**Comment by e-jameson** [comment]
The XML isn't publishing to prod apparently. Story is working fine on dev

https://staging.bethel.edu/

**Comment by annmarieven** [comment]
Did that change recently?

**Comment by e-jameson** [comment]
I'm not sure it would be in a workflow config or publish set or something.

**Comment by annmarieven** [comment]
It says: Publish to all enabled Destinations

The content type says: Publish the following Outputs to:
fixed:
Production bethel.edu (Web URL: http://www.bethel.edu)
staging.bethel.edu (Web URL: http://staging.bethel.edu)
responsive:
soda.bethel.edu

**Comment by annmarieven** [comment]
content type: https://cms.bethel.edu/entity/open.act?id=69447a438c5865132786f4d088200154&type=contenttype&

publish set: https://cms.bethel.edu/entity/open.act?id=f5e806a68c58651313b6fe6ba40d5c03&type=publishset

**Comment by e-jameson** [comment]
Does the workflow need to do anything special to publish to production? That isn't checked by default usually (not sure if workflows get special treatment or not)

https://cms.bethel.edu/entity/publish.act?id=f5e806a68c58651313b6fe6ba40d5c03&type=publishset

**Comment by e-jameson** [comment]
Manual publish to prod of the publish set was successful so it must be something in the workflow not triggering prod correctly.

**Comment by annmarieven** [comment]
Here's the workflow - https://cms.bethel.edu/admin/workflowbuilder.act?type=workflowdefinition&id=f5e8ef208c58651313b6fe6be0665cb5 Normally workflows publish everywhere by default. We only have to specify if we only want it to publish to one server over the other. For example, the publish to staging step at the bottom of this workflow: https://cms.bethel.edu/admin/workflowbuilder.act?type=workflowdefinition&id=69c0920d8c5865132786f4d01e856008

**Comment by e-jameson** [comment]
You were looking at the wrong content type:

https://cms.bethel.edu/entity/open.act?id=6dfca09e8c5865132786f4d077035653&type=contenttype

I changed it from "All destinations" to listing each one like the Article content type. No idea if that is going to make a difference though. Also not really sure how to test...

**Comment by e-jameson** [comment]
I ran a test and it still didn't publish to production. Do we have any other workflows publishing a Content Type with XML like this one? Looking at the server most of the assets haven't been published in quite a while.

**Comment by annmarieven** [comment]
I think faculty bios do something similar? But why was it working in the past? Like with the Jan 9, 12, and 15th stories?

**Comment by e-jameson** [comment]
After some testing I updated the memory limit for Cascade and it worked okay. So the real issue was that the system memory was full and publishing failed. The Jan 12, 15th stories must not have had a similar issue. Keeping the memory limit should hopefully help temporarily. But in a year or two we might have the same issue again. So we might want to think about alternative solutions in the meantime. 

going to leave open for @annmarieven to respond to the case.

**Comment by annmarieven** [comment]
closing issue.
