### ISSUE TITLE
Bethel Google Map Update - Floors

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#396]
Brooke Jameson noticed that on the Google map, you can click on the different floors and the respective floor plan will be displayed. http://screencast.com/t/ggc8y3wTmr

Can we do this on our map? https://www.bethel.edu/about/maps-directions/

**Comment by e-jameson** [comment]
There is no entry in the API for floor controls on the web, but there is for iOS. Our map still has the old style controls, so I'm guessing this feature will be available when the API version 4 is released. They haven't announced when that would be. 

https://developers.google.com/maps/documentation/ios/map#floor_picker
