### ISSUE TITLE
Bethel Google Map Update - List Offices within location

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#397]
Brooke Jameson would like to know if we can include the offices that can be found at some locations. For example, in townhouse I it would be great to say that Academic Affairs is there. http://screencast.com/t/21ulPwy0p

We can put that information into the address field but then 'See Directions' also appears because it assumes that info is an address. Can we have additional text like that without the link to directions?

**Comment by e-jameson** [comment]
Can you modify the Data Definition to something that works for you all? And then enter some data and we can adjust the code accordingly.

**Comment by annmarieven** [comment]
I added an offices field in the main campus > building section.
