### ISSUE TITLE
This Week at Bethel event feed

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#398]
Is there any way we can adjust the event feed (https://cms.bethel.edu/entity/open.act?id=1bdf107c8c586513742d45fd3cc795c7&type=page&) on this page: bethel.edu/events to only look 10 days into the future?

It's called "This Week at Bethel" but it's set to display 10 items. So if we're in a slow season, it could possibly show events that are weeks and weeks into the future.

I realize that if it is a slow week then it may only show a few events but this is how it was setup in Silva and that seemed to work fine.

Thoughts?

**Comment by c-schwarze** [comment]
We can add another option easily. I guess it would be an option instead of the "start date" and "end date" fields. The event feed is getting super cluttered though.

**Comment by e-jameson** [comment]
Lets just rename it "Upcoming Events at Bethel" :D

**Comment by annmarieven** [comment]
I renamed it. That's good enough for me. :)
