### ISSUE TITLE
Art Event News Feed 

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#400]
This page is supposed to be pulling Johnson/Olsen gallery news feed but it's not.
https://cms.bethel.edu/entity/open.act?id=f260a1948c5865137725e12fdb04b1ef&type=page
These are the news event feed pages:
Johnson: https://cms.bethel.edu/entity/open.act?id=11d4e9ab8c586513742d45fd11847198&type=page&
Olsen: https://cms.bethel.edu/entity/open.act?id=11d2878f8c586513742d45fd0aecab5c&type=page&
They are tagged correctly but the index still isn't pulling them.

**Comment by c-schwarze** [comment]
There are no events that match the Olson gallery. 

The Johnson Gallery is displaying now. ( I didn't change anything though )

Should we have something appear? "There are no available events" when none appear?

**Comment by annmarieven** [comment]
Maybe let's have it say "There are no upcoming events."

That's odd. @ale73233 and I were working on it for a while this morning and nothing was showing up. Maybe it just needed time.... :-P

Once that's done you can close this issue. Thanks @c-schwarze!

**Comment by c-schwarze** [comment]
Reopen if any more issues arise.
