### ISSUE TITLE
Expandable lists not working

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#401]
https://www.bethel.edu/graduate/financial-aid/types/grants-scholarships/

Nothing expands when I click on the plus sign.

I have to respond in job 13750.

**Comment by e-jameson** [comment]
sorry fixed. republished that page

**Comment by annmarieven** [comment]
uuhh... now it's gone completely ? https://www.bethel.edu/graduate/financial-aid/types/grants-scholarships/

**Comment by e-jameson** [comment]
That one is back. The rest probably need to be republished.

**Comment by kelslundberg** [comment]
FYI for the future - There is a publish set already created for these pages - Financial Aid/Types 

So if something like this happens again with these, it's a pretty quick republish!

I republished it now.
