### ISSUE TITLE
Image bank settings in Cascade

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#402]
Okay!

Based on our convo today, we're updating the setup block so that someone could choose to have an image bank display throughout the full site or just the homepage. And if no block is selected, then no images display.

I've updated the data definition here:

https://cms.bethel.edu/entity/open.act?id=ba13cfec8c586513100ee2a75200607f&type=structureddatadefinition

There's a new block chooser that we can use so we can add new banks, test them out in soda, and get it all prepped for go live without affecting the current sites.

And I've added an option for full site vs homepage only.

If people have other terms they'd like to use, feel free to suggest changes. 

Thanks!
Kelsey

**Comment by e-jameson** [comment]
@kelslundberg I'll show you where we are at on this today sometime.

**Comment by e-jameson** [comment]
@johjacb asked for a 3:1 ratio. Right now Thumbor is automatically doing 1200x400 right now but we'll probably change that because that is too big for mobile.

**Comment by kelslundberg** [comment]
This is on my plate to test....

**Comment by kelslundberg** [comment]
Hey @e-jameson - is this something you were still working on? I added a test image bank to my testing site and linked it up through the Site Images chooser in the setup. I'm not seeing the images right now...

https://soda.bethel.edu//_testing/kelsey-testing/basic

**Comment by e-jameson** [comment]
It was working last I looked at it. I'll check it out after lunch.

**Comment by kelslundberg** [comment]
Super! Thanks!

**Comment by e-jameson** [comment]
This is working again. Part of the code was commented for some reason.

**Comment by kelslundberg** [comment]
Awesome! Thanks for looking at it.

This is what we're going to be doing tomorrow so I appreciate the
quickness. I'll double check it today.
