### ISSUE TITLE
Image bank changes 

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#403]
Hey @annmarieven 

I've gone through and made my suggestions for image banks for each site in the "Suggested Image Location" column. If you could review, make changes, and talk to MV about any that you are unsure of, that would be awesome. 

Maybe by mid-week next week? 

Thanks!
KL

**Comment by kelslundberg** [comment]
Maybe by first week of Feb....if we're going to find and pull images the second week.

**Comment by annmarieven** [comment]
I added a couple notes to the grid. Maybe we can touch base on Thursday if @vedmic will be at our Cascade meeting.

**Comment by annmarieven** [comment]
We gathered images today. Assigning to @johjacb for determining crop size.

**Comment by annmarieven** [comment]
We're going to test a site today with real images, cropping to 3:1.

Top middle is the anchor point on the image.

**Comment by kelslundberg** [comment]
This is done...I think....
