### ISSUE TITLE
Featured event not showing up

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#407]
I am trying to put a featured event here: https://www.bethel.edu/events/

I entered one here: https://cms.bethel.edu/entity/open.act?id=1bdf107c8c586513742d45fd3cc795c7&type=page& and republished the index page but it's not showing up.

@e-jameson confirmed it wasn't appearing for him either. Any ideas why?

**Comment by c-schwarze** [comment]
I republished the page and it works.
