### ISSUE TITLE
Footer and global nav content changes

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#408]
Hey @e-jameson,

Just a reminder that I'd love to see the stats on the footer/drawer - the stuff that we added tracking for - whenever it's convenient!

Thanks :)

KL

**Comment by kelslundberg** [comment]
Hey @e-jameson - would it be possible to get/see this info sometime today?

Just let me know! Thanks!

**Comment by johjacb** [comment]
here's a report: https://www.google.com/analytics/web/?hl=en#report/content-pages/a1888141w85160958p88298654/%3Fexplorer-table.filter%3Dfooter%26explorer-table.plotKeys%3D%5B%5D/

**Comment by kelslundberg** [comment]
Why, thank you!

**Comment by e-jameson** [comment]
Thanks Jake. You can modify the search to look for "toolbox" or "breadcrumb" to see those as well.

**Comment by kelslundberg** [comment]
Hey everyone @johjacb @annmarieven @e-jameson @vedmic @ErikGruber @c-schwarze @hamtim @a-parrott 

I mapped out the navigation based on what we talked about today:

https://docs.google.com/a/bethel.edu/spreadsheets/d/1xOYlNqFtsxsye3I36n51dD9TpZY6Mg9LqCxz4ZfSIfU/edit#gid=0

I also added a second worksheet as a little sample mock up of the school navigation we want to test.

Feel free to add anything or change anything.

We'll chat more on Monday!
