### ISSUE TITLE
Staff embedding page 

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#410]
I am trying to embed a staff bio page onto another page but it's not working could you help? thanks!

Here's the page were trying to embed: https://cms.bethel.edu/entity/open.act?id=3ba8f0a48c5865131faa207783832db9&type=page

and here's the page we are trying to embed it on: https://cms.bethel.edu/entity/open.act?id=272cd1d88c5865130f1c0f8f130c7154&type=page&

**Comment by c-schwarze** [comment]
Try it now.
