### ISSUE TITLE
Offices dropdown in map

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#411]
We'd like to add an offices dropdown in our map that Brooke Jameson can update. 

I think "Select an Office" directly under the select a location field would be good.

Let's make sure it doesn't get published out until Brooke has populated the field with some information. Thanks!!

**Comment by c-schwarze** [comment]
Okay I have it working. Its not published, but the offices can be entered now.

**Comment by annmarieven** [comment]
Emailed Brooke to let her know.
