### ISSUE TITLE
Staff listing id displaying

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#412]
It looks like the id for staff listings might be displaying at the top of the list?

https://cms.bethel.edu/entity/open.act?id=df09a8ef8c5865137725e12f0ef16ecd&type=page

Thanks!!

KL

**Comment by e-jameson** [comment]
That is the text entered in "Group Heading" in the block.

https://cms.bethel.edu/entity/open.act?id=eeb0fde18c5865137725e12fbba07827&type=block&

**Comment by kelslundberg** [comment]
Wow strange that it would have been live like that for a while....
