### ISSUE TITLE
Faculty images gone from lists

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#413]
It appears our faculty images are being wonky and have disappeared from the lists.
https://www.bethel.edu/undergrad/academics/business-economics/faculty

Also, @parlau said yesterday on the live site she saw this message at the bottom of the page: "Waiting for my.spectate.com..."

**Comment by c-schwarze** [comment]
Faculty images: It appears that the faculty bios do not have the images linked...
https://cms.bethel.edu/entity/edit.act?id=ba13c7ae8c586513100ee2a739d6187c&type=page

**Comment by parlau** [comment]
Then the links have broken since I went in and fixed those that had been updated via Tinker (and double-checked others). The actual pages must be recalling the cached copies, because if you go to his URL, the image is there: https://www.bethel.edu/academics/faculty/essenburg-tim. That's the case for multiple departments and profiles I've checked.

**Comment by c-schwarze** [comment]
Ah! I know what it is. When I used tinker to update the description automatically before, it must have messed up the images.

The images should be restored on both the faculty bios and the faculty listing pages (currently being republished)

Also, I know nothing about the "Waiting for my.spectate.com..."

**Comment by annmarieven** [comment]
Now all the images are gone off the bio pages themselves. :weary:
You can click through to some here - https://www.bethel.edu/undergrad/academics/art/faculty

I republished one and the image showed up: https://www.bethel.edu/academics/faculty/carlson-g-w

**Comment by c-schwarze** [comment]
I setup the publish set and everything, I just forgot to publish before I left yesterday. Try them now.

**Comment by parlau** [comment]
Whew! Looks like it's all restored. Marvelous, thank you!

**Comment by c-schwarze** [comment]
Closing. 
Reopen if more issues arise.

**Comment by parlau** [comment]
Richard Peterson's profile was updated via Tinker (yesterday, I think) and his photo is gone again. On both the list page and the profile page. The image is not linked anymore.

https://www.bethel.edu/undergrad/academics/physics/faculty
https://www.bethel.edu/academics/faculty/peterson-richard

**Comment by e-jameson** [comment]
@parlau, @annmarieven : Not sure when the issue was introduced, but I've fixed it. I relinked Richard Peterson's page and submitted an edit with no changes. The image remain linked. I also tested a brand new submission with an image. Going to close but feel free to re-open.
