### ISSUE TITLE
News Archive for Departments

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#414]
@vedmic would like to be able to create a news archive but only pull stories tagged from a specific department.

**Comment by c-schwarze** [comment]
We currently have a 'year' select box. Do we want to add each school's department as select boxes?

Or rather do it by metadata? As in choose your department in the metadata on creation of a news archive.

**Comment by e-jameson** [comment]
Probably by metadata.

**Comment by c-schwarze** [comment]
Updated.

**Comment by e-jameson** [comment]
@vedmic I'm closing this but hopefully you read this in your inbox
