### ISSUE TITLE
Main Admissions Site Launch and Issues

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#415]
We're going to launch this today, too.

**Comment by annmarieven** [comment]
I will test in Safari and iOS 8 (safari)
@kelslundberg in Firefox and Android 4 (chrome)

**Comment by kelslundberg** [comment]
Looks good in Firefox and on Android 4 in Chrome

**Comment by annmarieven** [comment]
Looks good in Safari and on iOS 8 in Safari

**Comment by kelslundberg** [comment]
Launcie launchie
