### ISSUE TITLE
Academics Routing Page Launch

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#416]
We're launching the academics routing page and who studies:

https://staging.bethel.edu/academics/
https://staging.bethel.edu/academics/who-studies

@annmarieven to test in Safari and iOS 8 (safari)
KL in Firefox and Andriod 4 (chrome)

**Comment by annmarieven** [comment]
Looks good in Safari in staging and soda.

Looks ok in soda in Safari on iOS 8. Need to add a title when we launch responsive and image bank goes away.

**Comment by kelslundberg** [comment]
Looks good in Firefox and Android 4

**Comment by kelslundberg** [comment]
Published
