### ISSUE TITLE
Text over media asset and collection

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#417]
Okay! I created a draft of a data definition for this new feature. I called it Banner Collection, but we can call it whatever we want:

https://cms.bethel.edu/entity/open.act?id=4bfd38f68c58651302818aa9aa9aaf22&type=structureddatadefinition

I modeled it similar to media + text. The idea is that you choose your background (image or video), add the text you want displaying over your media, and create a button with a link to either watch a video or go to a webpage. 

You can use the + button to create multiple of these that users can click through just like the current stories collection.

I made some notes on this doc about the specific items in the data definition:

https://docs.google.com/a/bethel.edu/spreadsheet/ccc?key=0AvCfERcmdTwpdDNYckdLd3pET0E2b21kVDhEUmhSdFE#gid=7

Of course, we can rename and move/add things.

A few questions:

When we have a video that we want people to click and watch are we okay with the main button being a link to watch that video? Or would we want a play button AND a separate button calling them to another action...for example, see UNL http://www.unl.edu/. They have a Play Video button alongside another call to action. Personally, I don't like the way theirs is executed. I'd prefer a single call to action. But there might be a way for us to have a play icon or something somewhere as well as a call to action button.

What other text options would we want users to have? Right now I just have options for text alignment.

Should I put this data definition in the Collections folder?

That's it for now - @e-jameson and @johjacb take a look and let me know what questions you have! I also put some initial content here you can use to test. No worries if you change the data def and we lose stuff. No bigs.

https://cms.bethel.edu/entity/open.act?id=4c2619658c58651302818aa9bd0dcaae&type=folder&

**Comment by kelslundberg** [comment]
@e-jameson I'm assigning to you because I'm guessing first step is to get all of the info to pull in and then Jake would do the beauty work. But feel free to assign to whoever!

**Comment by e-jameson** [comment]
I'll work on this today. Is there any chance calling it "Banner collection" will get confused. We have this type of banner:

http://sweetclipart.com/multisite/sweetclipart/files/imagecache/middle/banner_white.png

And this type of Banner:

https://docs.oracle.com/cd/E17781_01/server.112/e18804/img/version_banner.jpg

**Comment by e-jameson** [comment]
@johjacb here is a rough start on this. 
https://cms.bethel.edu/entity/open.act?id=5011c2288c58651302818aa9a6b12df8&type=page&

Here is the format with all the variables created. So it just needs some love and styling.

https://cms.bethel.edu/entity/open.act?id=5016e2988c58651302818aa9dcd532db&type=format

**Comment by kelslundberg** [comment]
That's a good point, @e-jameson. 

I'm open to any ideas...Text over media collection is probably most descriptive. But it's kind of long...

**Comment by ErikGruber** [comment]
Can we change the name to Feature Collection?

**Comment by kelslundberg** [comment]
We're going to change this up so we have assets and a collection separately. I'll update the data definition for the asset itself and attach metadata and such. Then we'll need to build a separate collection asset for pulling these in either using metadata or manual selection.

**Comment by kelslundberg** [comment]
We also talked about if it's linking to a video then it pulls up the video in a light box.

**Comment by kelslundberg** [comment]
Not a light box. We're going to figure out something else :)

**Comment by kelslundberg** [comment]
@e-jameson and I talked about this. We updated the data definition so text over media will be single assets. Then we'll create a collection where you can choose your items by metadata or manual selection.

**Comment by e-jameson** [comment]
@johjacb here are some examples to look at. They need some styling help.

https://soda.bethel.edu//_testing/jmo/banner-collection/index
https://soda.bethel.edu//_testing/jmo/banner-collection/index-10 (this webm is mostly black --rendering error)

Here is the format:

https://cms.bethel.edu/entity/open.act?id=5016e2988c58651302818aa9dcd532db&type=format&

**Comment by ErikGruber** [comment]
Hey @e-jameson and @kelslundberg, I need a change to this. 

Adding a button with a link needs to be optional. 

If a button isn't added, then the image itself needs to be linked.

**Comment by kelslundberg** [comment]
Makes sense to me. @e-jameson, let me know if you need anything from me here!

**Comment by e-jameson** [comment]
updated

**Comment by annmarieven** [comment]
@e-jameson you were working on these to have the school homepages link to school specific sites rather than sending someone back out to bethel.edu/admissions, for example.

I published the undergrad school to staging and this is the link on the button: https://staging.bethel.edu/$internal_link.asset.path

Doesn't appear to be working the way it should :blush:

**Comment by e-jameson** [comment]
fixed

**Comment by annmarieven** [comment]
yay! it's working. closing issue.
