### ISSUE TITLE
Quote submission form updates for Development

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#419]
Hey @annmarieven and @ErikGruber 

Let's get the Wufoo form for quotes updated to include donor info:

https://betheluniversity.wufoo.com/forms/web-services-quote-submission/

How do we want to do this?

Add donor to the drop down? What if they're also an alum? Should we capture any specific info from donors?

Anything we want to add on the data definition side of things?

https://cms.bethel.edu/entity/open.act?id=ba13cfda8c586513100ee2a747b8ea8e&type=structureddatadefinition

Let me know your thoughts!

**Comment by annmarieven** [comment]
Maybe we should make that a checkbox instead of a dropdown. Thoughts on that?

**Comment by ErikGruber** [comment]
I've been thinking about how much we want to keep reusing this form. Maybe we should meet for a few minutes. The form was created for a specific use, so there are length limitations on it. Does it make sense to keep using it for everything?

**Comment by kelslundberg** [comment]
Yeah we can do that! Friday at 11:30.

**Comment by annmarieven** [comment]
@ErikGruber is going to come up with changes to be made to the quote form and we will take care of those for him.

He's also going to create a form for collecting homepage stories and either create it or send the info to me so either I or a student can create it.

**Comment by annmarieven** [comment]
We created the form.
