### ISSUE TITLE
Image and video captions on basic pages

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#420]
I think it might be nice to have optional captions for images or video on our basic pages.

We used to have it, but then I think it went away when we did the basic-plus merger.

There is still a field for it in the data def:

https://cms.bethel.edu/entity/open.act?id=4bfb51a68c58651302818aa98015c5ee&type=page

Do we think we could get this added back? Let me know if anyone has thoughts on the matter.

**Comment by johjacb** [comment]
should be back in on soda

**Comment by kelslundberg** [comment]
Thanks @johjacb. Looks good!
