### ISSUE TITLE
Site Feature Url error

### ISSUE THREAD

**Issue by a-gundy** [betheluniversity/cascade#421]
Lauren has been getting the following error message when she tries to publish the index for the music department (https://cms.bethel.edu/entity/open.act?id=afcd616f8c5865132467e6ffcb7669fa&type=page&):
![screenshot2015-02-03at11 09 01am_20150203111409_669493](https://cloud.githubusercontent.com/assets/9537391/6042976/bf854c7e-ac4e-11e4-856a-8cccd48084b7.png)

Is there something wrong with the formatting of the url in the feature she was adding to the site, site-feature-music-recordings (https://epay.bethel.edu/C20433_ustores/web/store_main.jsp?STOREID=13&SINGLESTORE=true)? Everything publishes, but the site feature doesn't show up.
 
(Footprints job 13875)

**Comment by e-jameson** [comment]
This should be fixed.

**Comment by a-gundy** [comment]
Responded to Lauren.
