### ISSUE TITLE
Giving - Officer Forms

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#422]
Hey @a-gundy 

I'm working on migrating the Giving site, and I'd love some help.

Could you move this folder of docs/forms from Silva into Cascade:

https://www.bethel.edu/giving/forms/

Cascade location
https://cms.bethel.edu/entity/open.act?id=504a427c8c58651302818aa97f32a676&type=folder&

I think you already moved some of these forms when you were working on the preload stuff.

Let me know if you have any questions!
Kelsey

**Comment by a-gundy** [comment]
@kelslundberg 
I moved the forms over to Cascade. Let me know if you want me to migrate anything else on the Giving site.
