### ISSUE TITLE
Faculty Bio Updates

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#424]
- [x] Change title to h1. 
- [x] Change headers to h2.

Add the following fields:
- [x] Courses Taught
- [x] Presentations
- [x] Professional Organizations, Committees, and Boards

If I add these to the data definition will the automatically appear on Tinker? Or do you need to do something to make that happen?

**Comment by c-schwarze** [comment]
Feel free to add those to the data def, then I can add them to tinker. We will have to manually add them to tinker, but it should be simple.

**Comment by c-schwarze** [comment]
Also, all faculty bios'  title/header are updated and published.

**Comment by annmarieven** [comment]
@a-parrott can you add the above fields to the faculty bio data definition?

They should go in this order:
I'm thinking this might be a good order:
Biography
Courses Taught
Awards
Publications
Presentations
Certificates and Licenses
Professional Organizations, Committees, and Boards

They'll need to be setup with logic by adding check boxes to the 'what would you like to add' field and then specifying which field should appear if the box is checked.

Let me know if that doesn't make sense :)

**Comment by a-parrott** [comment]
Added and set!

**Comment by c-schwarze** [comment]
Updated and pushed live. Let me know if any changes need to be made

**Comment by annmarieven** [comment]
@parlau check this out and let us know if anything needs to be changed!

**Comment by parlau** [comment]
Looks great! Thanks!
