### ISSUE TITLE
Program Block

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#426]
We created a data definition and an asset factory for the program details block.

https://cms.bethel.edu/entity/open.act?id=703ebc8d8c5865132395524d89bfaeb9&type=structureddatadefinition&

@e-jameson and @johjacb - time to work your magic!

**Comment by e-jameson** [comment]
The blocks are ready to be loaded. Here is a sheet with the relevant issue:

https://docs.google.com/a/bethel.edu/spreadsheets/d/1j_vEh9YnXDgL3Hl71i9-tanx-QmhT-8Lif6ERLrdR2Q/edit

**Comment by annmarieven** [comment]
@ale73233 and @a-gundy can you create a 'program-details' folder in every graduate, adult-undergrad, and seminary program folder? Then within that program-details folder, there should be flex index page.

For example, within the physician-assistant folder, there is a program-details folder with an index.
https://cms.bethel.edu/entity/edit.act?id=711876cb8c5865132dfb57c86905a1e1&type=folder

Title of both the page and the folder should be "Program Details"

**Comment by ale73233** [comment]
I finished adding all of the folders and indexes to all of the programs.

**Comment by annmarieven** [comment]
@ale73233 for every caps and gs program folder, can you create a program block in the shared-content/program-block/ folder? 

system name: program-name-program
title: Program Name

ex: teaching-program, Teaching or physician-assistant-program, Physician Assistant

**Comment by ale73233** [comment]
I created the program blocks and linked them up to the index pages.

**Comment by e-jameson** [comment]
My block-population code is ready to test as soon as the program codes are loaded.

**Comment by annmarieven** [comment]
I added a new field. :confused: sorry @e-jameson 

It's called "program_description" and should only show up at the top of the program-details/index page.

**Comment by annmarieven** [comment]
The cas nursing major is showing up on the gs nursing page: https://staging.bethel.edu/graduate/academics/nursing/

**Comment by annmarieven** [comment]
- [ ] Is the word "concentration" hard coded in here? If so, can we remove it?
https://staging.bethel.edu/graduate/academics/mba/program-details/mba
I'm wondering if we don't need a heading at all since the title of the page will suffice. Thoughts?

- [ ] Space before and after comma
https://staging.bethel.edu/graduate/academics/special-education/program-details/

- [ ] Program length isn't populating 'avg. completion time'

- [ ] H and F2 delivery codes aren't populating anything in the delivery label field

- [ ] concentration names probably need to be shortened up
https://staging.bethel.edu/graduate/academics/mba/

- [ ] the block is being duplicated on this page
https://staging.bethel.edu/graduate/academics/mba/program-details/global-management

- [ ] many programs don't have cost per credit

**Comment by annmarieven** [comment]
@c-schwarze and @e-jameson, can you guys look at these and check them off if/when they've been fixed?

**Comment by e-jameson** [comment]
@vedmic was going to look into having them change the Concentration Names.

**Comment by c-schwarze** [comment]
Republished all graduate/academics/PROGRAM/program-details/ folders. If you see anything on the list that is checked off but shouldn't be, let us know.

**Comment by annmarieven** [comment]
@c-schwarze - just to staging, right? :)

**Comment by c-schwarze** [comment]
Yep!

**Comment by a-parrott** [comment]
@c-schwarze - do the above changes affect CAPS programs as well (once republished)?

**Comment by c-schwarze** [comment]
Yep

**Comment by annmarieven** [comment]
- [ ] Change 'cost per credit' heading to "Average cost per credit"

**Comment by a-parrott** [comment]
@c-schwarze It looks like the program description field is appearing on the homepage. The program description should just be on the program-details index page.

**Comment by c-schwarze** [comment]
Fixed.

**Comment by annmarieven** [comment]
@e-jameson since we link the block to the concentration pages, can the block just pull the concentration page title as the "concentration name" for now? (until the catalog launches then we'll use that data)

or does that fall apart if there is only one option and the info lives on the program details page?

Let's chat when you're back in the office.

**Comment by c-schwarze** [comment]
Like this? https://staging.bethel.edu/graduate/academics/mba/program-details/

**Comment by annmarieven** [comment]
yes, but could we get it to show up in all listings? like here: https://staging.bethel.edu/graduate/academics/mba/ and here: https://staging.bethel.edu/_testing/caleb-test-folder/online-programs

**Comment by c-schwarze** [comment]
Yep. The first page just needed to be published. 

The online one is updated and published.

**Comment by annmarieven** [comment]
is it too much work to make it strip out "program details"? this will only appear if there's just one option for the program and no additional concentrations
see nurse-midwifery: https://staging.bethel.edu/graduate/academics/nurse-midwifery/
https://staging.bethel.edu/_testing/caleb-test-folder/online-programs

**Comment by annmarieven** [comment]
also, I totally did republish that page! :angry: :stuck_out_tongue_closed_eyes:

**Comment by c-schwarze** [comment]
Updated.

Cascade is just messing with you :P

**Comment by annmarieven** [comment]
beautiful! you're the best! :grinning:

**Comment by e-jameson** [comment]
I think everything in this issue is done.
