### ISSUE TITLE
List of pages hidden from nav

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#427]
Hey @c-schwarze - can you pull a list/report of all of the basic pages that are hidden from navigation?

@e-jameson said to use the query api

Just holler if you have any questions!
KL

**Comment by c-schwarze** [comment]
Let me know if you need anything else with this. It pulls in any page/block/file/folder that has the 'hide-from-nav' metadata set to "Hide".

https://cms.bethel.edu/entity/open.act?id=36b1c6d28c58651302818aa9d731dd81&type=page
https://staging.bethel.edu/_testing/caleb-test-folder/locate-page-hidden-from-nav

**Comment by kelslundberg** [comment]
This is great! Thanks so much!

**Comment by kelslundberg** [comment]
@a-parrott is going to start looking at these pages that are hidden from nav in Soda

**Comment by a-parrott** [comment]
Looked at the hidden pages. They look good.
