### ISSUE TITLE
Faculty listing pages for CAPS and GS programs

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#428]
Hey @a-parrott 

Can you add faculty listing pages to all of our adult undergrad and graduate program sites?

There's an asset factory for Faculty listing in the Academics folder when you select New to add a new asset in Cascade.

All you need to do is add a page title "Faculty" and then tag it with the appropriate school and program.

Here's a sample in CAS so you can see what it looks like:
https://cms.bethel.edu/entity/edit.act?id=af52bd238c5865132467e6fff54d0981&type=page

Because it's a feed, you won't see anything in preview. So we'll need to publish a few out to stage to make sure they're working. It looks like Abi has loaded faculty for MBA and Nurse-Midwifery. So we could test those two programs.

Let me know if you have any questions! Thanks so much!
Kelsey

**Comment by kelslundberg** [comment]
Oh and here is an example of what a faculty listing looks like live on the site!

https://www.bethel.edu/undergrad/academics/anthropology-sociology-reconciliation/faculty

It pulls in all of the page info automatically depending on the school/program selected.

**Comment by a-parrott** [comment]
All done!
