### ISSUE TITLE
ID lookup for giving site

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#429]
Hey @e-jameson,

How can I make this form in Cascade:
https://cms.bethel.edu/entity/open.act?id=55c101938c58651302818aa9b463224b&type=page&

Function like it does in Silva:
https://www.bethel.edu/giving/phonathon/donation

Thanks for your help :)

KL

**Comment by e-jameson** [comment]
Go to wufoo.bethel.edu, and select "lookup" values from the dropdown.

Normal values will populate the person that visited the page, "lookup" values will populate based on the ID that was entered.

Any for with "lookup" values select will show like the current Phonathon page.

**Comment by kelslundberg** [comment]
It looks like there are only lookup values for First and Last name. Should there be more?

Sorry! I didn't work with preload forms in Silva so I'm a little out of context :)

**Comment by e-jameson** [comment]
Ah, they probably got left behind. I've added all of them but address. That will take a while longer because it isn't the SQL return set yet.

**Comment by kelslundberg** [comment]
sounds good :) I think it's address we need for the phonathon form - but we can always leave it in Silva until it's ready

**Comment by e-jameson** [comment]
I've asked Lisa to add the address fields to the SQL output. Whenever she gets back to me it won't take long to add the new fields.

**Comment by annmarieven** [comment]
@e-jameson has this been finished? It'd be great to get this form out of Silva -- https://www.bethel.edu/giving/phonathon/donation

**Comment by e-jameson** [comment]
I've asked Lisa again to add address values.

**Comment by e-jameson** [comment]
This form is ready to be moved over now. We should probably test it a bit more than a normal form.

**Comment by annmarieven** [comment]
I entered a few IDs but the information doesn't populate.. am I missing something?

https://staging.bethel.edu/giving/phonathon/
https://cms.bethel.edu/entity/open.act?id=55c101938c58651302818aa9b463224b&type=page
https://cms.bethel.edu/entity/open.act?id=55c269188c58651302818aa941656393&type=block&

**Comment by annmarieven** [comment]
Waiting for country to work. One side note - the message about the form not loading still shows even after the lookup field and button appear.

**Comment by e-jameson** [comment]
Country now preloads United States correctly, the rest will fail. They should also failed in Silva. I'll look at the message when I get a chance.

**Comment by annmarieven** [comment]
Country still isn't loading for me. The lookup field loads REALLY slow and then once I enter an ID, the form loads REALLY slowly too.

**Comment by e-jameson** [comment]
Country is fixed. 

It seems just as fast or slow as the current version to me: 

https://www.bethel.edu/giving/phonathon/donation

Its kind of a slow process, unfortunately.

**Comment by annmarieven** [comment]
Tested and launched the phonathon form. Woo!

**Comment by annmarieven** [comment]
Can we add a few more fields to the lookup?

Based on this form -- https://editor.its.bethel.edu/silva/www/undergrad/student-life/withdrawal/withdraw-stop-out

We need:
Residence hall
Residence number
Middle name

Also, the form shows the note about not loading until after you enter the ID and hit the 'lookup' button.
Here's the Cascade version I'm working on: https://www.bethel.edu/undergrad/student-life/withdraw-stop-out

**Comment by annmarieven** [comment]
@e-jameson This form is no longer working in Silva, which is why it's high priority. :(

**Comment by e-jameson** [comment]
I added Middle Name - Lookup, and put in a request for Residence Hall and Residence Number to be put into the SQL Result set.

**Comment by e-jameson** [comment]
I asked Jay for an update on this.

**Comment by e-jameson** [comment]
this was finished last week. forgot to close issue.
