### ISSUE TITLE
YouTube videos on vimeo block

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#430]
We need to add the functionality to embed a YouTube video. I've added a youtube field on the vimeo block (which once this is done, we'll change to be 'video block' instead of vimeo).

Let me know if you need anything else from me!

Also, what from YouTube will be entered in the field?

**Comment by c-schwarze** [comment]
We can have the field either of these formats:
1) https://www.youtube.com/embed/cHHbdy0uOqM (full youtube url)
2) cHHbdy0uOqM (youtube's url code)

Here is a working example
https://cms.bethel.edu/entity/open.act?id=999f1f028c5865132395524d5a289f3a&type=page

**Comment by e-jameson** [comment]
I've updated this so it works with both the full-URL and just the code. Meaning we don't have to choose to always do one or the other. 

page for proof:

https://cms.bethel.edu/entity/open.act?id=9d6390288c5865132395524db1dec20c&type=page

@annmarieven go ahead and close this when you see it.

**Comment by annmarieven** [comment]
haha awesome test video @c-schwarze  :)

Looks good to me. FYI all, this youtube field is hidden so only admin can see it right now. 

And, I changed the block name to 'Video' instead of 'Vimeo-Block'
