### ISSUE TITLE
How to apply - override and extra steps

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#431]
Hey @e-jameson 

So How to Apply pages were all set up to pull in Banner data, like you said. I had tested and forgot :) 

But there are two things in the data def that that aren't working...

https://staging.bethel.edu//graduate/academics/physician-assistant/how-to-apply

1) Overriding default text - I have step 2 set to NOT display default, but it looks like it is...

2) I have a 5th step here that's not showing up...

Thanks!
KL

**Comment by e-jameson** [comment]
Hey KL these are updated.

**Comment by kelslundberg** [comment]
Hey @e-jameson - It's looking better! But it looks like the info I have for step 4 is showing up twice instead of the info for step 5...maybe I did something wrong :)

**Comment by kelslundberg** [comment]
I think this is done :)
