### ISSUE TITLE
Make all header / footer links https

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#433]
The ones that go to www.bethel.edu

**Comment by c-schwarze** [comment]
done and published.

**Comment by c-schwarze** [comment]
Oops. I mean the global header and footer are published. However, the navigation header ( the one right above the image) will only be updated on a full site publish.

**Comment by e-jameson** [comment]
@c-schwarze can you make sure everything in Soda is https? It looks like some things in the footer aren't. Go ahead and close it after that and it'll get update with the new design in a few weeks.

**Comment by c-schwarze** [comment]
www, soda, and staging should all have https for links for header/footer/global-nav.
