### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#434]
@e-jameson is going to move over the search page as it is - and then we'll figure out what we need to do to spruce it up

**Comment by e-jameson** [comment]
@johjacb here is a search page that needs a little styling. 

https://soda.bethel.edu/search/?cx=017681067239267367526%3Achqo5ugqj90&ie=UTF-8&q=test&sa=Search

**Comment by e-jameson** [comment]
@johjacb is this something you'd like @josiahtillman to look at when he has time?

**Comment by e-jameson** [comment]
@josiahtillman is this done?

**Comment by josiahtillman** [comment]
Oops! Forgot to close this.  It is done! ^^
