### ISSUE TITLE
Confluence search block

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#435]
From job 14069:

As we are developing the ITS web site we would like to support user self
service by providing a search feature on the web site similar to the
knowledge base search in Blink. I understand this will need to be created
for the content management system.

Randal Swanson
ITS Help Desk
Bethel University

651.635.8772
r-swanson@bethel.edu

**Comment by e-jameson** [comment]
I had the code for this in Silva so I moved it quick:

Here is the test page:
https://staging.bethel.edu//_testing/jmo/block-pages/confluence-search

And the block:
https://cms.bethel.edu/entity/open.act?id=bc20c0248c5865132802f161b7112fcb&type=block

Feel free to move the block.

**Comment by annmarieven** [comment]
I think people will want to be able to limit searches to a specific space. So for example, if the search box is on the TLT page, it only searches within the TLT space.

This is still low priority.

**Comment by c-varberg** [comment]
I updated it to search for specific spaces 

Test Page: 
https://staging.bethel.edu//_testing/calebv/basic1?

Block: the space is currently set to nothing, so the test page will just search through everything
https://cms.bethel.edu/entity/open.act?id=d77f12ef8c586513575344826cd390d8&type=block&

The block takes a "Specific Space" attribute. These can be found by going to confluence and searching for anything and then applying a "where" filter that will show up on the right side after searching. After the filter is applied the URL will include "&where=" somewhere within it. Whatever comes after the equals and before the next '&' is what the Specific Spaces should be called. (eg. ITS Knowledge Base = ITSKB, Student Life = stulife, Teaching and Learning = TLT, etc...)

**Comment by e-jameson** [comment]
@annmarieven do we need this issue open anymore?
