### ISSUE TITLE
Updating page titles for Majors

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#436]
Hey @a-gundy 

Wondering if you could help make some updates to the page titles on all of our CAS major pages?

Take a look at this one here:

http://soda.bethel.edu//undergrad/academics/art/majors-minors/art

I think if we added the word "Major" to the page title so it read "Art Major", it would help provide more context in the new design. I don't think we need to add it to the display title - so those can just stay as they are.

If something is tagged in the metadata as a "Program" (engineering for example), I'm pretty sure we're going to have to use Program instead of Major since it's not an official major.

All of our minors already have "Minor" in the title so don't worry about those. I'd also leave specific degree names like Bachelor of Fine Arts alone since that already provides good context. 

You can probably either go through the academic sites individually and use the charts on the homepage to update all majors/programs for each department or look at the relationships tab for the Major or Minor content type.

Let me or @annmarieven know if you have any questions!

Thanks!
KL

**Comment by a-gundy** [comment]
@kelslundberg, 
I added major/program to the titles of the undergrad sites. If there was already something listed (like B.A. or B.F.A.), I didn't add anything.

Thanks,
Abi
