### ISSUE TITLE
Giving Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#437]
staging.bethel.edu/giving

@kelslundberg  looked at it in Chrome in staging and soda.

I will check Safari and iPhone 6 iOS 8.

@kelslundberg will look on her droid.

**Comment by kelslundberg** [comment]
Droid looks good

**Comment by annmarieven** [comment]
Safari and iOS 8 look good.

**Comment by kelslundberg** [comment]
Launched. Redirects in. Done.

**Comment by annmarieven** [comment]
@a-gundy can you put a note on our analytics?

**Comment by a-gundy** [comment]
Noted in google analytics.
