### ISSUE TITLE
Faculty carousel

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#438]
We're going to build a collection/carousel where we can pull in faculty to feature.

Name (linked to faculty bio page)
Job Title
Image

Maybe something else down the road, but I want to see what this looks like to start.

And we're thinking it would pull in at random any faculty member who had all of these items....

**Comment by kelslundberg** [comment]
@e-jameson and I talked about this a little bit. I think we're good to start building something based on the above requirements - the only change would be to pull in random faculty members based on meta data. That way we could have CAS faculty show up on the Undergrad homepage and Graduate faculty on the Graduate School homepage and so on...

**Comment by e-jameson** [comment]
@johjacb here is a faculty carousel work in progress. 

https://soda.bethel.edu//_testing/jmo/block-pages/faculty-feed

Relevant code:

https://github.com/betheluniversity/cascade-php/blob/master/collections/php/faculty.php

**Comment by e-jameson** [comment]
@kelslundberg @ErikGruber @annmarieven do you have any feedback on this?

**Comment by ErikGruber** [comment]
@kelslundberg @johjacb @e-jameson I added this to the page

https://soda.bethel.edu//undergrad/index-new

Thoughts?

**Comment by annmarieven** [comment]
We launched with this. Closing issue.
