### ISSUE TITLE
Video Captions in Flex

### ISSUE THREAD

**Issue by kelslundberg** [betheluniversity/cascade#439]
Hey @c-schwarze -

Can you help me get video captions to show up on Flex pages?

I added a Caption field to the video block. And have a video embedded with a caption here in the Enroll section:

https://soda.bethel.edu/undergrad/admissions/

We do have Caption as a field on our Basic pages. I'm guessing we can just use the same styles? Here's an example of that:

https://soda.bethel.edu/undergrad/academics/faculty

**Comment by c-schwarze** [comment]
Updated.

**Comment by ErikGruber** [comment]
@johjacb @kelslundberg do we want any styling on the caption? I feel like it looks different from captioned photos on our site, but I can't find one.

**Comment by kelslundberg** [comment]
It looks like that's the style @johjacb has set for Soda. I'm fine with it. But if you feel like it needs something different, feel free to suggest!

https://soda.bethel.edu//undergrad/academics/faculty

**Comment by ErikGruber** [comment]
Looks good. I was seeing something different at first.
