### ISSUE TITLE
Working copy view not working

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#440]
@e-jameson, I have no idea if this is something we may have unknowingly broke on our end or if it's a bigger Cascade issue. So I'm submitting it both places.

When approving assets in a workflow, the working copy no longer shows the user's updates. Instead it just shows me the current version of the asset. In addition, sometimes there is a yellow bar that appears at the top that says "No Changes Detected" but when the page is published, then I see there were actually changes on the asset.

I have done some testing and can't seem to figure out why the working copy view or the compare with current view isn't working.

**Comment by e-jameson** [comment]
This sounds like something that wasn't working in the past, but I don't remember what we did to fix it. Cascade should have an answer though (at least they knew last time)

**Comment by annmarieven** [comment]
From the Cascade guy:
I looked over this briefly in your instance but didn't see anything glaring. I'll probably need to spend some more time working with a local copy of your Workflow to see if I can reproduce the issue.

In the meantime, are you aware of when you started noticing this behavior? Was it after a particular upgrade or was a Format recently edited that the Page uses to display the DEFAULT content?

**Comment by e-jameson** [comment]
"was a Format recently edited" 

ha. yeah. a few of them :)

**Comment by annmarieven** [comment]
Does that ring a bell enough for you to know what to fix?

http://help.hannonhill.com/discussions/bug-reports/2521-working-copy-view-doesnt-show-most-recent-updates

**Comment by e-jameson** [comment]
I think its a private discussion so I can't view it.

**Comment by annmarieven** [comment]
Contacted Tim again via the discussion above because we really gotta get this fixed :confused:

**Comment by e-jameson** [comment]
I gave Tim an export of our DB so they can look into this more.

**Comment by e-jameson** [comment]
Tim from H.H.

**Comment by e-jameson** [comment]
Waiting for Mike Johnson to get a database backup to HH.

**Comment by johjacb** [comment]
is this working?

**Comment by e-jameson** [comment]
@johjacb did you update the file Hannon Hill Tim sent over? @annmarieven did you get a chance to test it?

**Comment by e-jameson** [comment]
Sounds like the fix worked.

**Comment by e-jameson** [comment]
For future reference.

![image](https://cloud.githubusercontent.com/assets/6525585/18011415/b1d89788-6b7a-11e6-82ca-1f7f3465f4d7.png)

![image](https://cloud.githubusercontent.com/assets/6525585/18011424/bd0da102-6b7a-11e6-8050-acbfccfd1a4b.png)

**Comment by c-schwarze** [comment]
This issue was resolved again, due to removing our code of setting the $currentPage variable.
