### ISSUE TITLE
Prayer Initiative Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#441]
@a-gundy is going to migrate this site. https://www.bethel.edu/prayer-initiative/

**Comment by a-gundy** [comment]
@annmarieven, 
Take a look and let me know what you want changed (especially look at image sizes for some of the images from the old site that don't exist in Flickr). 

https://cms.bethel.edu/entity/open.act?id=471514e78c5865134252346a067ba505&type=folder&

**Comment by annmarieven** [comment]
@a-gundy Looking good!! I love the photos you chose for the header and the prayer walk! 

Can you list all the redirects we need here:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1HE_qm8gkamBZo4pZ1Halc2y8oBeomqwxU4Sq55DmpYk/edit#gid=0

I noted which pages we're not migrating and will need redirects here:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1OQFAOAbkUk8FPhJ1CYVNb8P45dEjzmvUzFc-1XYDrso/edit#gid=1060048568

**Comment by annmarieven** [comment]
Then you can reassign to me. I will have Allie put the redirects in when we launch, hopefully next Tuesday!

**Comment by a-gundy** [comment]
@annmarieven, the redirect grid is ready!

**Comment by annmarieven** [comment]
Launched the site. Will do basic testing in Chrome, Firefox and Safari. The site is very basic so there aren't any new assets being used.

**Comment by annmarieven** [comment]
Looks good in Chrome, Firefox, and Safari on iPhone 6 iOS 8 - Safari.

@ale73233 put in redirects.
@a-gundy optimized all the images and put a note in google analytics.

Access and permissions are all set up for training.
