### ISSUE TITLE
Academic Enrichment Support Center (AESC) Migration

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#444]
@a-gundy can you use these directions to migrate this site? https://docs.google.com/a/bethel.edu/document/d/1G6Lm4p8gvjqOP-eVh1Gu_0nMvKitrtViO6C4XU6XK7g/edit

@e-jameson will need to give you a zip file of the site.

https://www.bethel.edu/undergrad/academics/support/

**Comment by e-jameson** [comment]
I've sent the zip to Abi in a Slack DM

**Comment by a-gundy** [comment]
The grid I'm working with: 

https://docs.google.com/a/bethel.edu/spreadsheets/d/1638zkuIoM27Z0C2AN2YcBaEidc5GFHnDkkJoSUp_t7E/edit#gid=757457493

**Comment by a-gundy** [comment]
@annmarieven,
Would you proof this site? https://staging.bethel.edu/undergrad/academics/support/
Let me know what changes need to be made.

**Comment by c-schwarze** [comment]
@annmarieven this issue is almost a year old...is this done?

**Comment by annmarieven** [comment]
@emily-johnson we're going to pick this one back up again and try to get it out the door. Here are a few things I'm hoping you can tackle:

- [ ] recreate site image bank - looks like the images are cropped to the wrong size. also see if any of the photos in the gallery can be used in the site image bank. i don't want 2 galleries on here and it'd be great to use some of their original photos.
- [ ] remove individual page photos (business, science)
- [ ] check all times are in Bethel format
- [ ] give CWC a title and display name
- [ ] give nursing a title and display name to match old site
- [ ] remove help sessions heading and include it in the first 2 headings on the page (ex: Introductory Physics Help Sessions)
- [ ] not crazy about the massive photo on this page. can we do anything different with it?
- [ ] change caps/gs display name to "Adult Undergrad and Graduate". title "Adult Undergrad and Graduate Academic Resource Center"
- [ ] update links to caps and gs academic support
- [ ] update contact us page to match old site
- [ ] create redirect grid (https://docs.google.com/spreadsheets/d/1uBg6prbJ3ifFe2YfoPcZqYbBoV16v_u-_FmA6qNuimM/edit#gid=0) -- every file will need to be redirected, check urls of old site and compare with urls of new pages
- [ ] make sure every live asset in old site has been moved to Cascade

**Comment by emily-johnson** [comment]
Notes/questions: 
- CWC had the same title & display name on the old site, so I didn't add a display name
- We do not have images for Kristin Nichols-Besel or Michelle Steffenhagen

- @annmarieven which "massive image on this page"?
- Are we trusting the old site over our build-out one? For example, the room listed for the math lab is different, and other times
- Are we moving all of the pdfs and other files over?

**Comment by kathrynmagnuson** [comment]
Added information to the new contact us page that was on the old one, but didn't remove additional information on the new one that isn't on the old (let me know if that doesn't make sense :).

**Comment by emily-johnson** [comment]
- Removed the "massive image"
- Went through all the pages and updated locations, times and other details according to the live site

**Comment by annmarieven** [comment]
@emily-johnson can we change the title to "Christianity and Western Civilization"? (or whatever the full title is. maybe confirm that) display name should still be CWC.

@kathrynmagnuson let's remove the additional information on the new one that isn't on the old. (your comment above)

**Comment by emily-johnson** [comment]
- Created the redirect grid
- Changed the CWC title
- I was looking at content while doing the times/locations earlier, and I think everything looks good, but it's probably good to have @kathrynmagnuson go through

**Comment by c-schwarze** [comment]
Where is this at? Nothing has been posted for 4 months.

**Comment by emily-johnson** [comment]
Ready to send _testing site to Sam Mulberry, but debating holding off until we have the staging links fixed (or temporarily fixed)

**Comment by emily-johnson** [comment]
Looks like I never heard back from Sam, sent another email

**Comment by c-schwarze** [comment]
@emily-johnson where is this at?

**Comment by emily-johnson** [comment]
The site is up and Sam was trained in as the web author, closing
