### ISSUE TITLE
Alert Notification for Cascade

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#445]
We had class for a construction alert in Silva -- <p class="alert-message"><strong></strong>Alert: The east gate is closed due to construction. Please use the main entrance.</p> (https://editor.its.bethel.edu/silva/www/about/maps-directions/construction-alert/edit/tab_edit)

Can we do something like that for Cascade? https://cms.bethel.edu/entity/edit.act?id=ba13b80c8c586513100ee2a718241435&type=page

**Comment by johjacb** [comment]
You can now manually add an .alert class.

**Comment by annmarieven** [comment]
Published to prod.
