### ISSUE TITLE
Proof Points not appearing on some academic pages

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#447]
Proof point collection:
https://cms.bethel.edu/entity/open.act?id=cca96c588c5865137ca4729016ad58c9&type=page&

Proof point that should be showing up:
https://cms.bethel.edu/entity/open.act?id=8d82a2f78c58651375fc4ed26b4c563c&type=block_STRUCTUREDDATA

Live page with no proof points appearing:
https://www.bethel.edu/undergrad/academics/physics/

@ErikGruber said there are others where this is happening too.

It's working on some department pages:
https://www.bethel.edu/undergrad/academics/english/

**Comment by c-schwarze** [comment]
Fixed.
