### ISSUE TITLE
Corporate Partnerships Site Launch and Issues

### ISSUE THREAD

**Issue by a-gundy** [betheluniversity/cascade#451]
I'll be manually migrating the Corporate Partnerships site (https://www.bethel.edu/academics/partnerships/corporate/) to Cascade.

**Comment by a-gundy** [comment]
@annmarieven,
Do you think we could put all of the partners into a single Office Homepage as media+text instead of giving them each their own page?  

https://cms.bethel.edu/entity/open.act?id=70293ec88c5865132dfb57c8f98d29a4&type=page&

**Comment by a-gundy** [comment]
@annmarieven,
Assigning to you for proofing. I'm not super happy with the alignment on the Partners' pages.
https://staging.bethel.edu/academics/partnerships/corporate/
https://cms.bethel.edu/entity/open.act?id=6b1f9c6f8c5865137a0a4916ed177dd4&type=folder&

**Comment by annmarieven** [comment]
Reviewed this site. I don't think we can list all the partners on one page because each business needs their own unique url to send to their employees.

Everything looks good except for a minor space issue on the media + text. We're going to launch as is and @johjacb will fix it within a week or 2.

**Comment by annmarieven** [comment]
This site launched on June 5. Forgot to update github.

@johjacb assigning to you for the spacing issue on the media + text.

example page:
https://www.bethel.edu/academics/partnerships/corporate/partners/allina-health

**Comment by johjacb** [comment]
this should be fixed

**Comment by annmarieven** [comment]
added to analytics. closing issue.
