### ISSUE TITLE
Quotes - include grad year and current job/grad school

### ISSUE THREAD

**Issue by ErikGruber** [betheluniversity/cascade#452]
Hey @c-schwarze , could we change quotes to display the grad year and the current job/grad school fields?

**Comment by ErikGruber** [comment]
Like this - 

"blah blah blah blahb blaha"

-Erik Gruber '06
Current Job: Senior Web Content Specialist, Bethel University

**Comment by c-schwarze** [comment]
Updated and live. Test page: https://www.bethel.edu/undergrad/academics/biblical-theological/
