### ISSUE TITLE
Broken Link to Seminary Admissions Blog

### ISSUE THREAD

**Issue by vedmic** [betheluniversity/cascade#453]
Caleb, it looks like the block for the seminary admissions blog wasn't set up for external links and instead of linking to: http://blogs.bethel.edu/seminary-admissions/  it's linking to: https://www.bethel.edu/http://blogs.bethel.edu/seminary-admissions/  Could you take a look at it. 

Thanks. 

Location of the Block is: https://www.bethel.edu/seminary/admissions/

**Comment by annmarieven** [comment]
@vedmic you just have to republish the site and it will be fixed :)

**Comment by annmarieven** [comment]
@vedmic fixed this.
