### ISSUE TITLE
Course Catalogs Page Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#454]
@a-gundy can you migrate this page?
https://editor.its.bethel.edu/silva/www/academics/catalog/edit/tab_edit

Assign it to me for proofing before launch.

After launch, I will reassign the issue to you so you can close it down in Silva.
Let me know if you have any questions!

**Comment by annmarieven** [comment]
I will update this grid when it's launched:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1BxUTjlDdgBKo-XZrOHhx-DhXHSCBCzRLGZ4S9KyuyyI/edit#gid=1762576728

**Comment by a-gundy** [comment]
@annmarieven,
I migrated the page. I think the links will all need to be updated after Sem, GS, and CAPS are migrated.

**Comment by annmarieven** [comment]
@a-gundy Looking good! Can you unlink the title of the cas one? That way it's consistent with the rest. Once they're all in Cascade then we can probably link the titles back up. Also, hide the site navigation so we don't have the crazy left hand nav. Publish to staging so you can proof it.

Then publish to production, test the links, close the Silva page, mark the page as launched here: https://docs.google.com/a/bethel.edu/spreadsheets/d/1BxUTjlDdgBKo-XZrOHhx-DhXHSCBCzRLGZ4S9KyuyyI/edit#gid=1762576728, and close this github.

Thanks!

**Comment by a-gundy** [comment]
Launched!
