### ISSUE TITLE
Military Partnerships Migration

### ISSUE THREAD

**Issue by a-gundy** [betheluniversity/cascade#456]
I'll be migrating this site/page. https://www.bethel.edu/academics/partnerships/military/

**Comment by a-gundy** [comment]
@annmarieven,
I'm assigning this to you for proofing. 

https://staging.bethel.edu/academics/partnerships/military/

https://cms.bethel.edu/entity/open.act?id=757eaa0e8c5865132dfb57c8f6541c80&type=page&

**Comment by annmarieven** [comment]
launched. updated grid here: https://docs.google.com/a/bethel.edu/spreadsheets/d/1BxUTjlDdgBKo-XZrOHhx-DhXHSCBCzRLGZ4S9KyuyyI/edit#gid=1762576728
