### ISSUE TITLE
Security & Safety Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#458]
@ale73233 can you put together a list of redirects for Security & Safety? List them in this google doc:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1XXSrOpnEwapEWnS8IGE1t9DruxrrJIiuZCCk-QIrgcY/edit#gid=0

The old urls will be found in these 2 sites:
http://bethelnet.bethel.edu/security-safety (these redirects should be listed on the sheet but you won't be able to enter them into Tinker because they are bethelnet -- you'll need to ask @e-jameson to do these)
https://www.bethel.edu/campus-security/ (these redirects should be listed on the sheet and you can enter them into Tinker)

We'll need to redirect every item in those sites (you may need to go through Silva to find all the pages).

The new site is here:
https://www.bethel.edu/security-safety/

Thanks!

**Comment by ale73233** [comment]
On the Active Alerts page "Image" is showing up and needs to be removed: https://www.bethel.edu/security-safety/active-alerts

**Comment by ale73233** [comment]
-I created the redirects and sent them to eric
-created the other redirects and put them into tinker
-assigned the github to caleb to fix Active Alerts pages

**Comment by annmarieven** [comment]
Waiting for one more redirect (to be done by @ale73233) and the active alerts page to be fixed (to be done by @c-schwarze).

**Comment by c-schwarze** [comment]
The information correctly displays now (the Images bold title no longer appears). It might need some formatting help.

**Comment by ale73233** [comment]
I finished the last redirect!:)

**Comment by annmarieven** [comment]
Because Caleb fixed the images item, @ale73233 can you submit a sample active alert and publish the 'active-alerts' page to staging so we can see how it looks?

https://cms.bethel.edu/entity/open.act?id=9dceb3cf8c5865132395524dda452251&type=block&

**Comment by ale73233** [comment]
Hi Caleb,
The active alerts page isn't working, https://staging.bethel.edu/security-safety/active-alerts
The image isn't showing up and "There are currently no active alerts" should not be showing up as well.

**Comment by c-schwarze** [comment]
1) The image chosen is a pdf. Can you guys choose an actual image instead?

2) The text "There are currently no active alerts" is appearing because that is what is entered in the WYSIWYG. Do you want that to automatically be hidden? Otherwise you can just delete that text.

**Comment by annmarieven** [comment]
@ale73233 can you choose an image instead of a pdf? :)

@c-schwarze oops! it doesn't need to be automatically hidden. the web author can just remove it. thanks for clarifying ;)

**Comment by ale73233** [comment]
I closed this site, http://bethelnet.bethel.edu/security-safety 
Eric is doing one last redirect.
Eric can you close this site? https://www.bethel.edu/campus-security/

**Comment by e-jameson** [comment]
The redirect is done. I'm not sure what you mean by close this site?

**Comment by annmarieven** [comment]
Can you go into Silva and close it? We can't access it anymore because it just redirects on us :stuck_out_tongue: I'm assuming you have a work around to get into the site.

**Comment by e-jameson** [comment]
https://cms-editor.bethel.edu/silva/www/campus-security/edit ?

**Comment by annmarieven** [comment]
@ale73233 can you get in with the url jame-o included above?

**Comment by ale73233** [comment]
I got in and closed the site!
