### ISSUE TITLE
Run Migration Tool locally

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#459]
Here is the quick instructions on how to run Hannon Hill's migration tool locally.

* Download the most recent tarfile at https://github.com/hannonhill/Universal-Migration-Tool/releases 
  * (something like Universal-Migration-Tool-7.12.3.tar.gz     ~13.6 MB)
* Open the tar file, which will create a "Universal-Migration-Tool" folder.
  * Move this folder to where ever you want to keep it.
* Use terminal to cd into the folder: 
  * cd Universal-Migration-Tool/tomcat/bin
* run this command
  * ./startup.sh
* It should work! Go to this url in your browser:
  * http://localhost:8081/

**Comment by c-schwarze** [comment]
Abi, here are the instructions to run the migration tool locally. Let me know if you have any questions! Also, I was pretty sure you were the one who needed it, but if not let me know!

**Comment by a-gundy** [comment]
Caleb, thank you for the instructions! Is this something we'll have to do every time we have to do every time we want to run the migration tool locally or is once enough for each computer?

**Comment by c-schwarze** [comment]
You may have to run the ./startup.sh command each time you want to use the tool.

**Comment by a-gundy** [comment]
It works. Added these instructions to the documentation.
