### ISSUE TITLE
Video on CAPS/GS Academic Homepages

### ISSUE THREAD

**Issue by a-parrott** [betheluniversity/cascade#461]
Videos are not loading on the CAPS and GS academic homepages. I have checked different pages and videos. 

Current pages with this issue: https://cms.bethel.edu/entity/open.act?id=c0ed981b8c5865132a1de4ef51796e26&type=page

https://cms.bethel.edu/entity/open.act?id=133d366d8c5865130f1c0f8fb8e30bb2&type=page&

**Comment by e-jameson** [comment]
fixed.
