### ISSUE TITLE
New GIF for Event Confirmation Submission

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#462]
Time for a new gif here!
https://tinker.bethel.edu/event/confirm

**Comment by e-jameson** [comment]
my vote: http://i.imgur.com/uqeDrzw.gifv

**Comment by annmarieven** [comment]
hahaha that one has my vote :point_up:

**Comment by annmarieven** [comment]
@c-schwarze can you update the gif?

**Comment by c-schwarze** [comment]
Added the ram gif.

**Comment by annmarieven** [comment]
Time for a new June gif here!
https://tinker.bethel.edu/event/confirm

anyone know where that one of the hyper little goat jumping over and on top of the other goats?

**Comment by annmarieven** [comment]
@c-schwarze can you add this one? http://stream1.gifsoup.com/view3/4010102/buttercup-goat-gif-o.gif

**Comment by c-schwarze** [comment]
Added goat gif for June!

**Comment by annmarieven** [comment]
Reopening this for a new November gif. Suggestions anyone?

**Comment by c-schwarze** [comment]
how about this one? https://i.imgur.com/8myao4z.gif

**Comment by e-jameson** [comment]
Couple more options: http://i.imgur.com/532t5X0.gifv or http://i.imgur.com/Tz0SC1b.gifv

**Comment by annmarieven** [comment]
I vote this one! http://i.imgur.com/Tz0SC1b.gifv

yikes. sorry for the delay. :)

**Comment by e-jameson** [comment]
http://i.imgur.com/rzP4WVC.gifv

**Comment by c-schwarze** [comment]
Added https://i.imgur.com/Jh7P9Fz.jpg
