### ISSUE TITLE
Areas of Study icon missing

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#463]
Hi caleb, we received a footprints job (14537) with this issue: 
The icons for "areas of study" aren't appearing on CAS program pages like
this one;

https://www.bethel.edu/undergrad/academics/athletic-training/

**Comment by annmarieven** [comment]
@c-schwarze did you see this?

**Comment by c-schwarze** [comment]
Yeah. Asking @johjacb . The connection is correct (from what I can tell). But the image isn't where it should be...

**Comment by johjacb** [comment]
should be back in place
