### ISSUE TITLE
Old Event Page No Crawl

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#464]
Brooke's request:
I have been getting a few requests for old event page to be deleted (for recurring events). Most recently the New Student Welcome page from 2014 because Liz had a parent get confused on the date because they landed on the 2014 page through search I think and didn't read the 2014 part or something. 

I know we don't want to delete the pages so I'm not sure there is much we could do. I thought about maybe just adding 2014 to the tile of the event, or adding a 'if you are looking for 2015' type of link in the description. Either way I don't want to do that for every event and remember every year so it is not very sustainable.

Is there anything we could do that is automated like a 'This event has passed' banner message on the page? It seems like a silly issue to me but from the number or questions I get about it I thought it was worth bringing up.

@vedmic's suggestion:
Mike wants @e-jameson  to put a no crawl on event pages after the year has passed so they don't show up in searches. Or can it be immediately after the event has passed?

**Comment by e-jameson** [comment]
I'm not sure I like this solution. If we are going to prevent crawling we might as well just delete them...?

**Comment by e-jameson** [comment]
Added this to sitemap
