### ISSUE TITLE
Photo galleries not showing up

### ISSUE THREAD

**Issue by a-gundy** [betheluniversity/cascade#466]
The photo gallery on https://www.bethel.edu/dining-services/promotions/cooking-classes/cooking-class-14 works fine, but when I republished it to staging, the gallery disappeared. 
(https://cms.bethel.edu/entity/open.act?id=a1a55ab58c5865132a1de4ef20cb11f8&type=page)

I've also been having trouble getting photo galleries to show up in staging for other pages.

**Comment by c-schwarze** [comment]
Fixed.
