### ISSUE TITLE
Sitemap content types and config sets

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#468]
@e-jameson is going to look at these to determine if they're still needed:

https://cms.bethel.edu/entity/open.act?id=1e9e73d18c58651313b6fe6ba78100ac&type=contenttypecontainer&
https://cms.bethel.edu/entity/open.act?id=ef6a1df58c58651375fc4ed26949ed3b&type=contenttype&

**Comment by annmarieven** [comment]
Check these config sets too:

https://cms.bethel.edu/entity/open.act?id=ef6a1df58c58651375fc4ed26949ed3b&type=contenttype&
https://cms.bethel.edu/entity/open.act?id=1e9e73d18c58651313b6fe6ba78100ac&type=contenttypecontainer&

**Comment by e-jameson** [comment]
These are all deleted.
