### ISSUE TITLE
Summer School Site Launch & Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#471]
@parlau I've published the site. Can you include a google sheet with redirects in this issue to finish the launch?

Thanks!

**Comment by parlau** [comment]
Are we able to edit the department headers? For example: Anthro, Soc, and Rec Studies. I know that's how it is in Banner... 

Redirects are on the sheet labeled "4.21.15." (Those MWL ones also need to be done--I had already started another list.) https://docs.google.com/a/bethel.edu/spreadsheets/d/1a23esJ3_S7hLfwt1Hwp5TXqVZ23jCZ3U4bOBXD17Oow/edit#gid=962366028

**Comment by parlau** [comment]
Let me/Tim know when things are ready so the email can be sent with the new URL.

**Comment by annmarieven** [comment]
@parlau unfortunately we can't change the headers since it's pulling right from banner..

**Comment by annmarieven** [comment]
@ale73233 can you go through the silva site here: cas.bethel.edu/summer-school/edit and make sure we have all the pages accounted for on the redirects grid? https://docs.google.com/a/bethel.edu/spreadsheets/d/1a23esJ3_S7hLfwt1Hwp5TXqVZ23jCZ3U4bOBXD17Oow/edit#gid=962366028

**Comment by ale73233** [comment]
I looked through the site and they all were there except this page:
http://cas.bethel.edu/summer-school/descriptions/
I added it to the grid.

**Comment by parlau** [comment]
@annmarieven okay, 

It seems to just be me, but every time I type in the new url or click the link from the left nav on https://www.bethel.edu/undergrad/academics/majors-minors, I still get kicked back to the old page. ?? I can get to the subpages, but the Summer School index keeps going back to the cas.bethel page. I've tried on Chrome, Safari, and Firefox.

**Comment by annmarieven** [comment]
@e-jameson can you put the redirects in for this site?

@parlau it's redirecting because we haven't done the redirects yet.

**Comment by e-jameson** [comment]
done.

**Comment by annmarieven** [comment]
@parlau and @hamtim redirects are finished and the site is officially launched!

closing issue.
