### ISSUE TITLE
Changing Major List assets' data definition

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#472]
Go here for the list of all the major lists:
https://cms.bethel.edu/entity/relationships.act?id=c4c088b38c5865130c130b3adca79d02&type=structureddatadefinition

1. Edit each one, change the data definition to "include format"
2. Paste this into the name of format field: 
**list-majors-minors**
3. Submit (don't send to workflow)

Reassign this issue to me when it's done.

**Comment by ale73233** [comment]
Finished!:)

**Comment by annmarieven** [comment]
Deleted data defintion. Closing issue.
