### ISSUE TITLE
Changing Event and News Feeds to Blocks

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#473]
all schools start with gs
Go through undergrad academics
create new event feed in every folder
system name: parent folder id of site (art-event-feed)
delete page one and rename block
Title: site name (Art Event Feed)
open in firefox and chrome
look at settings of the page feed
look in department tag it
check heading, copy and paste
no work flow
submit
delete event feed page uncheck unpublish content
go into index page to link up new block
news and events - link up block 
submit 

Start at education k-12 in gs

**Comment by ale73233** [comment]
finished gs and caps, start undergrad tomorrow,

**Comment by ale73233** [comment]
undergrad, caps, gs are all done. Seminary doesn't have any news feeds. Human Kinetics in undergrad didn't have a news feed page.

**Comment by annmarieven** [comment]
@ale73233 can you do the same thing with news feeds? Create new news article feed blocks, link them to the homepage of each site, and then delete the news feed **page**?

**Comment by annmarieven** [comment]
all schools start with gs
Go through [school]/academics
create new news article feed in every folder
system name: parent folder system name of site (art-news-article-feed)
Title: site name (Art News Article Feed)
open in existing news article feed page in a new window
look at settings of the page feed
look in department/program tag
check heading, copy and paste
look at number of articles, and articles expire after X days
HIDE when there are no articles
no work flow
submit
delete news article feed page uncheck unpublish content
go into index page to link up new block
news and events - link up block 
submit

**Comment by ale73233** [comment]
finished graduate/adult undergrad news feeds
start in undergrad

**Comment by annmarieven** [comment]
@ale73233 After you're done updating all the news and events feeds, can you create both a news article feed block and an event feed block for all of the Seminary programs?

Thank you!!

**Comment by ale73233** [comment]
I'm waiting to do the undergrad news and events feeds this afternoon so I can do them all at once. I tried adding an event feed to a seminary program but in the event feed block, there is no seminary block with listed programs to tag, can that be added somehow?

**Comment by ale73233** [comment]
I finished undergrad news and event feeds. I did all of the Seminary article feeds, the sem event feeds need seminary program tagging box.

**Comment by annmarieven** [comment]
@ale73233 Now that we've done all academics, we have to clean up the rest of the random feeds :)

Using these links, can you go through and create blocks in place of the pages? Embed the newly created blocks where the pages were, delete the feed pages, and republish the page with the feed on it. View it at www to make sure everything is working right.

event feeds -
https://cms.bethel.edu/entity/relationships.act?id=40e8c46b8c5865137464be9ccd5d4564&type=contenttype

news article feeds - 
https://cms.bethel.edu/entity/relationships.act?id=6a5d0d368c5865132786f4d0aedff03d&type=contenttype

p.s. any feed pages inside of the testing folder can just be deleted.
p.p.s. let @e-jameson know when this is done.

Thanks!!

**Comment by ale73233** [comment]
still working on this

**Comment by ale73233** [comment]
Hi Eric,
I finished adding all of the event and news article feeds.

**Comment by annmarieven** [comment]
@ale73233 I think you may have forgotten this step - "Embed the newly created blocks where the pages were, delete the feed pages, and republish the page with the feed on it. View it at www to make sure everything is working right."

Maybe not on all of them but the few that I checked hadn't been done. I took screenshots of the items before you went through so you'll have to work off this list -- 
![screen shot 2015-04-29 at 2 38 41 pm](https://cloud.githubusercontent.com/assets/6526079/7522312/00a213b4-f4ba-11e4-9a0b-ccd0f1b9b438.png)
![screen shot 2015-04-29 at 2 38 22 pm](https://cloud.githubusercontent.com/assets/6526079/7522316/0484daa2-f4ba-11e4-9be6-45ce46e061ec.png)

Let me know if you have questions about this last step!

**Comment by annmarieven** [comment]
@ale73233 I've had to go and do some of these as people emailed saying their feeds were broken, so you'll run into a few that have already been done. just fyi

**Comment by annmarieven** [comment]
@ale73233 Touch base with me before you start doing this. Thanks!

**Comment by ale73233** [comment]
Finished linking them! This is a list of ones with no relations:
/seminary/admissions/admissions-event-feed
/graduate/admissions/admissions-event-feed
/undergrad/admissions/admissions-event-feed
/_homepages/adult-undergrad-event-feed
/_testing/kelsey-testing/cas-homepage-event-feed
/_cascade/base-assets/pages/event-feed
/_homepages/seminary/seminary-event-feed
 /_homepages/seminary/seminary-news-article-feed 
/_homepages/graduate/graduate-news-article-feed
/_homepages/adult-undergrad/adult-undergrad-news-article-feed
/undergrad/admissions/admissions-homepage-event-feed
/_homepages/seminary/seminary-info-session-event-feed
/_homepages/graduate/graduate-event-feed
/_homepages/graduate/graduate-info-session-event-feed

This page won't let me publish it:
/seminary/academics/marriage-family-therapy/index

**Comment by a-gundy** [comment]
/seminary/academics/calendars/st-paul/2014-2015-event-feed is pulling all seminary events, not just St. Paul.

/seminary/academics/calendars/san-diego/2014-2015-event-feed has pulled Ed.D. Online Information Session for some reason, also pulling events with past dates.

/events/arts/upcoming-events is showing some unrelated events (i.e. Sem commencement) and some events with past dates.

/undergrad/bsg/events has some strange events (Spring Break 2016?), but it might be fine.

got to /president/projects/strategic-plan/

**Comment by a-gundy** [comment]
/seminary/academics/calendars/st-paul/2014-2015-event-feed is OK, the event was named wrong so it looked like it was pulling from BSSD. 

/seminary/academics/calendars/san-diego/2014-2015-event-feed had the date range a little off, fixed it. The seminary calendars are booth pulling past dates, but I'm assuming that is OK. The Ed.D. event was tagged wrong. Do we need to republish calendar xml to get the change to show up?

/events/arts/upcoming-events is tagged to show Benson Great Hall events (as well as other Art events), so SEM commencement is going to keep showing up unless that changes.

**Comment by annmarieven** [comment]
@a-gundy 
/events/arts/upcoming-events let's untag Benson Great Hall on this feed

if the ed.d. event was changed and republished, the change should show up on the bssd calendar feed. if it doesn't, try publishing the page and the xml.

**Comment by annmarieven** [comment]
events and news feeds have been changed.
