### ISSUE TITLE
Create list of events without descriptions

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#474]
AnnMarie requested:

"Can we pull a report of events that don't have something in the description field?"

Either use the Query API tool or just recursively check.

@c-varberg let me know if you have any questions.

**Comment by c-varberg** [comment]
This is the list of events I was able to Query for that don't have a description. Let me know if this isn't what you were looking for.

events/2015/bsg/cosmic-valentines-bowling
events/2014/bsg/residence-hall-co-ed-dodgeball-competition
events/2015/academic-dates/finals-spring-cas
events/2015/academic-dates/summer-term-c-begins
events/2015/academic-dates/second-half-spring-classes-begin
events/2014/bsg/homecoming-dance
events/2015/ms-in-nurse-midwifery-online-information-session2
events/2014/mpc-cio-fall-meeting
events/2014/rn-bsn-online-information-session
events/2015/academic-dates/intensivesreading-and-research-weeks-end
_cascade/base-assets/pages/event
events/2016/academic-dates/final-examinations1
events/2016/academic-dates/final-examinations2
events/2015/academic-dates/term-b-begins
events/2014/academic-dates/mid-summer-classes-end
events/2015/academic-dates/intensivesreading-and-research-weeks-end-for-traditional-and-inministry
events/2015/academic-dates/mid-summer-classes-end
events/2014/cru-inner-city
events/2015/academic-dates/spring-classes-resume
events/2014/young-artist-world-piano-festival
events/2015/academic-dates/summer-terms-a--b-begin
events/2016/academic-dates/last-day-of-spring-classes
events/2016/academic-dates/final-examinations3
events/2016/academic-dates/term-a-begins
events/2014/chapel1
events/2015/academic-dates/classes-resume
events/2016/academic-dates/classes-resume
events/2015/academic-dates/first-half-spring-classes-end-for-sempm
events/2014/mft-licensure-prep
events/arts/theatre/2014/the-spitfire-grill
events/2014/seventh-day-baptist-general-conference
events/2014/academic-dates/fall-reading-and-research-weeks
events/2014/chapel2

Format used is here https://cms.bethel.edu/entity/open.act?id=fb708e398c5865130265fd802063964d&type=format&

**Comment by e-jameson** [comment]
@c-varberg: Great work!

@c-schwarze can you work with V. to get this on a staging page in _testing somewhere and make the links go to the staging pages?

**Comment by c-varberg** [comment]
Caleb already left, but this is what I was able to come up with 
https://staging.bethel.edu/_testing/calebv/events/events-without-description-page

**Comment by c-varberg** [comment]
I just realized there is a metadata description as well as an event description in the data definition. The page is currently searching for empty metadata description. Which one did we want it to look through?

**Comment by e-jameson** [comment]
@annmarieven how does that list look and do you know the answer to @c-varberg question?

**Comment by annmarieven** [comment]
We want a list of items without something in the metadata description.

**Comment by annmarieven** [comment]
also, thanks!! this is exactly what we needed :)
