### ISSUE TITLE
GS Academics MBA Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#475]
We are going to launch this site: https://staging.bethel.edu/graduate/academics/mba/

I will do testing on the most recent versions of Chrome, FF, Safari, and iOS 8 on iPhone 6.

@a-parrott can you browse through the site on your phone and note in here what kind of phone it is?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=1821310238

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1n16b11Kvwv54A9uFgFnv2Bmv9gP9IV2BHzF-s0O5adM/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Tag analytics @a-gundy 
- [x] Close footprints job 13035
- [x] Close and archive old site @a-gundy

**Comment by annmarieven** [comment]
Off to a good start... :wink: I did a final publish to staging before I started testing and now the homepage is completely blank except for the page title. :stuck_out_tongue_closed_eyes: @e-jameson or @johjacb can you take a look?

**Comment by a-parrott** [comment]
Looking good so far! My phone is a Moto G Android 4.4.

**Comment by annmarieven** [comment]
Chrome, FF and Safari all look good (except for haven't proofed the homepage)

**Comment by annmarieven** [comment]
@johjacb 
Minor issues on iOS 8:
massive space between program details list and spotlight paragraph. 
https://files.slack.com/files-pri/T02513GQF-F04HZLDRT/slack_for_ios_upload.jpg


Major issue on iOS 8:
Quotes not appearing 
https://files.slack.com/files-pri/T02513GQF-F04HBSMEG/slack_for_ios_upload.png

**Comment by annmarieven** [comment]
Site launched, reviewed, and everything looks good! Rule and redirects have been put in place.

**Comment by annmarieven** [comment]
@a-gundy just a few minor things left to do and then you can close this issue.

Thank you!

**Comment by a-gundy** [comment]
Tagged in analytics and archived site in Silva.
