### ISSUE TITLE
Transportation Site Migration

### ISSUE THREAD

**Issue by a-gundy** [betheluniversity/cascade#476]
I'm moving the Transportation site from old Silva to Cascade. 

Migration grid: https://docs.google.com/a/bethel.edu/spreadsheets/d/1OQFAOAbkUk8FPhJ1CYVNb8P45dEjzmvUzFc-1XYDrso/edit#gid=714966338

Location in Cascade: https://cms.bethel.edu/entity/open.act?id=dcc119768c5865130265fd80fa096ffc&type=folder&

Redirect grid: https://docs.google.com/a/bethel.edu/spreadsheets/d/1Zgo_g5L4LXodhceWQpRBFpttNIrD32C0GfrbdmHnR08/edit#gid=0

Current URL: https://www.bethel.edu/transportation/

**Comment by a-gundy** [comment]
@annmarieven, would you look at this site? https://staging.bethel.edu/transportation/
Let me know what kind of changes you'd like me to make.

**Comment by annmarieven** [comment]
This site is ready to launch. Plan to launch next week. Just need to update the redirect grid.

**Comment by annmarieven** [comment]
Redirect grid updated. No rule needed. This site is ready to go! No rule needed.

Will launch 6/22 at 1 p.m. Training scheduled for the following week.

**Comment by annmarieven** [comment]
Site launched, redirects in place, note added to google analytics.
