### ISSUE TITLE
layout differences flex vs basic

### ISSUE THREAD

**Issue by ErikGruber** [betheluniversity/cascade#477]
Hey @johjacb , I noticed that the top content on basic pages is even with the blue box - https://www.bethel.edu/graduate/academics/mba/networking

and it drops down a bit in flex - https://www.bethel.edu/graduate/academics/mba/program-details/

Let me know if that didn't make sense.

**Comment by johjacb** [comment]
yes this is a known issue. any Section automatically gets padding added on all sides, including top padding on the first Section of the page.

**Comment by johjacb** [comment]
should be fixed
