### ISSUE TITLE
Sort Location and Delivery

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#478]
@c-schwarze can you sort location and deliveries alphabetically on these pages:

https://www.bethel.edu/graduate/academics/mba/

**Comment by e-jameson** [comment]
@c-varberg you could look into this too. Check out /_cascade_formats/blocks_programs/ for examples on sorting.

**Comment by c-varberg** [comment]
It's sorted now on that page. Did you also want them sorted on the individual concentration pages?
Like this one 
https://staging.bethel.edu/graduate/academics/mba/program-details/global-management

**Comment by c-varberg** [comment]
the concentration pages are also sorted now.
