### ISSUE TITLE
GS Academics MA in Gerontology Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#480]
We are going to launch this site on 4/28: https://staging.bethel.edu/graduate/academics/gerontology

I will do testing on the most recent versions of FF, Safari, and iOS 8 on iPhone 6.

@ErikGruber can you browse through the site on Chrome?
@a-parrott can you browse through the site on your Android 4?
@mwengstrom can you browse through the site on IE 11?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=1912566838

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1qGM5WhQmQJ0kzlHdmpCkLDyTkShCY2CZ3tvztqJ2TEQ/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Tag analytics @a-gundy
- [x] Close footprints job 13175
- [x] Close and archive old site @a-gundy
- [x] Relink news article feed (this afternoon, once @c-schwarze fixes it)

**Comment by ErikGruber** [comment]
I'm thinking that news story shouldn't be there?

**Comment by annmarieven** [comment]
News feeds are a little messed up. @c-schwarze were you taking a look at those?

**Comment by ErikGruber** [comment]
is the Faculty link in the left nav broken for anyone else?

**Comment by ErikGruber** [comment]
and How to Apply?

**Comment by annmarieven** [comment]
No?

**Comment by c-schwarze** [comment]
Yeah I'm working on the news feeds.

**Comment by a-parrott** [comment]
Android 4.4 - Image bank is missing on the homepage
The homepage does not scroll past the main image 
Recent News and Upcoming Events headings appear, though they are set to hide

Everything else looks great!

**Comment by a-parrott** [comment]
Android 4 - On the homepage, the quotes are partially cut.

**Comment by annmarieven** [comment]
Same with iPhone 6 (iOS 8). I think it has something to do with the new carousel we're using..?

**Comment by annmarieven** [comment]
This is live and looking good. Passing to you @a-gundy :)

Also, @mwengstrom can you do testing on IE when you get in today?

**Comment by a-gundy** [comment]
Archived site and added analytics tag. 

@mwengstrom,
Reassign to @annmarieven when you're done testing in IE.

**Comment by mwengstrom** [comment]
On the homepage, 

The proof point is not showing animation and the text is offset.
![image](https://cloud.githubusercontent.com/assets/5014864/7380221/14d81b36-edc0-11e4-87c9-354f91df5594.png)

Some images are not displaying
![image](https://cloud.githubusercontent.com/assets/5014864/7380182/c101752a-edbf-11e4-9e80-0c46edbf6696.png)
vs.
![image](https://cloud.githubusercontent.com/assets/5014864/7380198/eb35b64e-edbf-11e4-8f44-d0aaf72e82da.png)

**Comment by mwengstrom** [comment]
Other than that it looks good, reassigning to @annmarieven

**Comment by annmarieven** [comment]
@ale73233 can you link up the news feed to the index (site is in issue title)? then publish the page, check off the box at the top of this issue and that's it! 

Assign to @johjacb when you're done so he can look at the IE issues.

**Comment by annmarieven** [comment]
@ale73233 can you look at this?

**Comment by ale73233** [comment]
I linked up the news feed to the index and published the page!

**Comment by annmarieven** [comment]
@johjacb do you want to do anything about @mwengstrom's testing in IE 11?

**Comment by johjacb** [comment]
icons are in place on 11 and  the proof point should be fixed

**Comment by annmarieven** [comment]
Awesome! Closing issue.
