### ISSUE TITLE
CAPS Academics BS in Nursing (RN to BS) Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#481]
We are going to launch this site on 4/28: https://staging.bethel.edu/adult-undergrad/academics/nursing

I will do testing on the most recent versions of FF, Safari, and iOS 8 on iPhone 6.

@ErikGruber can you browse through the site on Chrome?
@a-parrott can you browse through the site on your Android 4?
@mwengstrom can you browse through the site on IE 11?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/13YMTx5qrCCXtTerntuDIguVhKPH6mcQK0plCeaNbCh4/edit#gid=1824291459

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1xV-ldZihXJS772wNAyWIJUfA9SeW3uqurdOqnHcuHVM/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Tag analytics @a-gundy
- [x] Close footprints job 13205
- [x] Close and archive old site @a-gundy
- [x] Relink news article feed (this afternoon, once @c-schwarze fixes it)

**Comment by annmarieven** [comment]
site image banks appear to be broken on staging - https://staging.bethel.edu/adult-undergrad/academics/nursing/ @c-schwarze or @e-jameson ?

**Comment by c-schwarze** [comment]
Oops. My bad. Should be fixed now (mostly).

**Comment by annmarieven** [comment]
Everything looks good in FF, Safari, and iOS 8 except for the quote carousel cutting off quotes on mobile devices.

**Comment by a-parrott** [comment]
Looking good on Android 4.

**Comment by annmarieven** [comment]
This is live and looking good. Passing to you @a-gundy :)

**Comment by a-gundy** [comment]
Added analytics note and archived silva site. 

@mwengstrom,
Assigning to you for IE testing. Reassign to @annmarieven when you are done.

**Comment by mwengstrom** [comment]
On the homepage, the images above 'Skills', 'Careers', and 'Employers' do not appear in IE

**Comment by annmarieven** [comment]
@johjacb can you take a look at the IE issues?

**Comment by annmarieven** [comment]
@ale73233 can you link up the news feed to the index (site is in issue title)? then publish the page, check off the box at the top of this issue and that's it! keep it open for jake.

**Comment by annmarieven** [comment]
@ale73233 can you look at this?

**Comment by ale73233** [comment]
I linked up the news feed to the index and published the page.

**Comment by annmarieven** [comment]
@johjacb do you want to do anything with @mwengstrom's testing in IE 11? If not, close the issue.

**Comment by johjacb** [comment]
icons are in place

**Comment by annmarieven** [comment]
Great! Closing issue.
