### ISSUE TITLE
GS Academics MS in Nurse-Midwifery Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#482]
We are going to launch this site on 4/29: https://staging.bethel.edu/graduate/academics/nurse-midwifery

I will do testing on the most recent versions of FF, Safari, and iOS 8 on iPhone 6.

@ErikGruber can you browse through the site on Chrome?
@a-parrott can you browse through the site on your Android 4?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=1195836228

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1yMvGtP24zScKokO3nBONFwcArlp5oTzr2VPXzT1ID1c/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Close footprints job 13039
- [x] Tag analytics @a-gundy 
- [x] Close and archive old site @a-gundy

**Comment by annmarieven** [comment]
Looks good on FF and Safari

**Comment by annmarieven** [comment]
There's just one issue with the delivery code pulling both O and OI when Dave believes it should only be OI. He said he fixed it and the sync ran last night but O and OI are still both in the program block. I'm following up with @e-jameson to see if it's something on our end or if we need to talk to Dave again.

**Comment by ErikGruber** [comment]
Looks good in Chrome

**Comment by a-parrott** [comment]
Android 4 - One of the quotes (the one with the photo) is cut short.

**Comment by e-jameson** [comment]
rule is done.

**Comment by annmarieven** [comment]
Site launched, redirects in, things look good. Passing to you @a-gundy

**Comment by a-gundy** [comment]
Tagged and archived. @annmarieven, does this need to be proofed in IE or can we close this issue?

**Comment by annmarieven** [comment]
We don't need to keep proofing all of them in IE. closing.
