### ISSUE TITLE
GS Academics Ed.D. Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#483]
We are going to launch this site on 4/29: https://staging.bethel.edu/graduate/academics/education-doctorate

I will do testing on the most recent versions of FF, Safari, and iOS 8 on iPhone 6.

@ErikGruber can you browse through the site on Chrome?
@a-parrott can you browse through the site on your Android 4?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=655090050

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1UB9Aue59INR57VNjM5aTAc8C-TOEOrU3ssfNNCuehEY/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Close footprints job 12902
- [x] Tag analytics @a-gundy 
- [x] Close and archive old site @a-gundy

**Comment by a-parrott** [comment]
Android 4 - Concentration descriptions appear to be missing from the homepage; quotes cut short.

**Comment by annmarieven** [comment]
My quotes were cut off on my iPhone but a republish has fixed this. I'm assuming it's fixed for @a-parrott too :)

Firefox and Safari look good.

Getting ready to launch.

**Comment by ErikGruber** [comment]
Everything looks good in Chrome, except the delivery description being wrong.

**Comment by annmarieven** [comment]
The site has been launched.

@vedmic how do we do the floodlight tag since it was 2 different sites before and now there's only 1?

**Comment by annmarieven** [comment]
@a-gundy this is ready for you now.

**Comment by annmarieven** [comment]
Mike and I talked, I've created the floodlight tag.

**Comment by a-gundy** [comment]
Tagged launch and archived the three Ed.D. sites. Closing issue.
