### ISSUE TITLE
CAPS Academics BS in Accounting Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#484]
We are going to launch this site on 4/29: https://staging.bethel.edu/adult-undergrad/academics/accounting/

I will do testing on the most recent versions of FF, Safari, and iOS 8 on iPhone 6.

@ErikGruber can you browse through the site on Chrome?
@a-parrott can you browse through the site on your Android 4?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/13YMTx5qrCCXtTerntuDIguVhKPH6mcQK0plCeaNbCh4/edit#gid=1150659402

Redirects:
NONE - site didn't exist before

- [x] Create floodlight tag
- [x] Close footprints job 13039

**Comment by a-parrott** [comment]
Android 4 - The homepage doesn't scroll past Recent News, the news heading appears although there isn't any news, the image bank is gone. 

But all other pages look great!

**Comment by a-parrott** [comment]
Fixed via republish. Thanks @annmarieven

**Comment by annmarieven** [comment]
FF, Safari, and iOS 8 on iPhone 6 look good.

**Comment by annmarieven** [comment]
@vedmic there is no tracking code in the google doc from haworth so I wasn't able to put in a floodlight tag.

**Comment by annmarieven** [comment]
Site launched, looking good. Passing to you @a-gundy 

You can assign it to @vedmic when you're done so he can take care of the floodlight tag.

**Comment by annmarieven** [comment]
Oops. There was no old site. So.... nothing to tag in analytics or close/archive in Silva. :stuck_out_tongue:

**Comment by ErikGruber** [comment]
good in chrome

**Comment by vedmic** [comment]
Sent Floodlight tag to AMV.

**Comment by annmarieven** [comment]
floodlight tag added. closing issue.
