### ISSUE TITLE
Online Programs

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#485]
@ErikGruber  passing this off to you. Let me know what changes you would like.

https://staging.bethel.edu/_testing/caleb-schwarze/online-programs

**Comment by ErikGruber** [comment]
Let's change the title to Online Programs

**Comment by ErikGruber** [comment]
@johjacb is probably going to want to take a look at styling.

**Comment by johjacb** [comment]
caleb cleaned up the page style a little

**Comment by ErikGruber** [comment]
Looks alright to me. @vedmic or @hamtim ?

**Comment by c-schwarze** [comment]
@johjacb passing this to you for any more changes. 

https://staging.bethel.edu/adult-undergrad/academics/online
https://staging.bethel.edu/graduate/academics/online

**Comment by johjacb** [comment]
no design changes needed just need to add a image bank. I think @ErikGruber was going to look for some photos?

**Comment by annmarieven** [comment]
This is live. Closing.
