### ISSUE TITLE
GS Academics MA in Teaching Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#487]
We are going to launch this site on 5/5: https://staging.bethel.edu/graduate/academics/teaching

I will do testing on iOS 8 on iPhone 6.

@ale73233 can you browse through the site on Chrome, FF and Safari?
@a-parrott can you browse through the site on your Android 4?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=2029899063

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1mtPqIATTjvyfQBrA6xcGa6r3rUQdJX-Bv3SWyldWhx8/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Close footprints job 13173
- [x] Tag analytics @a-gundy
- [x] Close and archive old site @a-gundy

**Comment by ale73233** [comment]
FF: These links aren't working in FF:
https://www.bethel.edu/graduate/academics/teaching/faculty
https://www.bethel.edu/graduate/academics/teaching/program-details/

still need to look at chrome and safari

**Comment by ale73233** [comment]
Everything looks good in chrome and safari.

**Comment by e-jameson** [comment]
The www versions or staging? They aren't meant to be live yet correct?

**Comment by ale73233** [comment]
The staging!

**Comment by a-parrott** [comment]
Android 4 - Quotes cut short.

Making a list for registrar of courses in the course description with ?s.

**Comment by annmarieven** [comment]
@a-parrott I republished the site to staging - can you see if that fixes the quotes thing?

**Comment by a-parrott** [comment]
Cleared the cache, but the quotes are still cut short on my phone. Also, the Recent News heading appears although there are no articles (the feed is set to hide).

**Comment by c-schwarze** [comment]
News/Event feeds should hide properly now

**Comment by annmarieven** [comment]
Quotes are cut off on my iPhone 6 too. @c-schwarze @johjacb @e-jameson can one of you look at this?

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
The site has been launched and looks good! Passing to you @a-gundy

**Comment by a-gundy** [comment]
Tagged and archived. Closing issue.
