### ISSUE TITLE
GS Academics MA in Strategic Leadership Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#489]
Getting ready for launch: https://staging.bethel.edu/graduate/academics/strategic-leadership/

I will do testing on iOS 8 on iPhone 6, Chrome, FF and Safari.
@a-parrott can you browse through the site on your Android 4?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=29744874

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1rC4DlQTSmu1bocWuYuk1nSBMeoFsabLv0fcBHndhILY/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Close footprints job 13037
- [x] Tag analytics @a-gundy
- [x] Close and archive old site @a-gundy

**Comment by annmarieven** [comment]
Looks good in Chrome, FF, Safari, and iOS 8 on iPhone 6. Even the quote isn't cut off. This one doesn't have an image so I wonder if that has something to do with it.

**Comment by a-parrott** [comment]
Looks good on Android 4!

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
this site is launched and looks good! passing to @a-gundy

**Comment by a-gundy** [comment]
Tagged and archived. Closing.
