### ISSUE TITLE
CAPS Academics BA in Christian Ministries Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#490]
Getting ready for launch: https://staging.bethel.edu/adult-undergrad/academics/christian-ministries/

I will do testing on iOS 8 on iPhone 6 and Safari.
@ErikGruber will you do Chrome and FF?
@a-parrott can you browse through the site on your Android 4?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/13YMTx5qrCCXtTerntuDIguVhKPH6mcQK0plCeaNbCh4/edit#gid=1108329628

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1908qIIAC0Aw6RoLhjd_aD1fymJ8_VwL_88NO49fZdsI/edit#gid=0

- [x] Create floodlight tag -- no data -- not doing
- [x] Create redirects
- [x] Close footprints job 13307
- [x] Tag analytics @a-gundy
- [x] Close and archive old site @a-gundy

**Comment by ErikGruber** [comment]
In Chrome, there's no space between the white "Online" box and Courses

https://staging.bethel.edu/adult-undergrad/academics/christian-ministries/program-details/

**Comment by ErikGruber** [comment]
Same issue in FF

**Comment by ErikGruber** [comment]
Course descriptions - 

Understanding the Bible (BIBL360)
Communication in Ministry (CHMN451)

have question marks instead of apostrophes

**Comment by ErikGruber** [comment]
In Chrome - the quote info is displaying wrong - it isn't displaying the person's name, and the grad year and current job are on the same line

**Comment by a-parrott** [comment]
Android 4 - the quote is cut short.

**Comment by annmarieven** [comment]
I sent the courses to Dave for fixing. The quotes are also fixed.

@johjacb can you look at the spacing issue that @ErikGruber mentioned?

**Comment by annmarieven** [comment]
Safari has the same spacing issue E mentioned above. Other than that, looks good. iOS 8 on iPhone 6 looks good too.

**Comment by annmarieven** [comment]
@vedmic I don't see Christian Ministries in this grid for the floodlight tag - https://docs.google.com/spreadsheets/d/1Dt3mn1YIFCuAVjFI9CRzZSowiAgrjxftWjFnEiA1BxI/edit#gid=0

**Comment by e-jameson** [comment]
rule is done

**Comment by ale73233** [comment]
redirects are done

**Comment by annmarieven** [comment]
done and passing to @a-gundy!

**Comment by a-gundy** [comment]
Tagged and archived. Closing issue.
