### ISSUE TITLE
CAPS Academics BA in Human Services Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#491]
Getting ready for launch: https://staging.bethel.edu/adult-undergrad/academics/human-services/

I will do testing on iOS 8 on iPhone 6 and Safari.
@ErikGruber will you do Chrome and FF?
@a-parrott can you browse through the site on your Android 4?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/13YMTx5qrCCXtTerntuDIguVhKPH6mcQK0plCeaNbCh4/edit#gid=1462047950

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1POYtIqCoJJBPepXNIK4M5x7nxC2bb0rV6fEvrIfO74o/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Close footprints job 13182
- [x] Tag analytics @a-gundy
- [x] Close and archive old site @a-gundy

**Comment by ErikGruber** [comment]
In Chrome - the quote info is displaying wrong - it isn't displaying the person's name, and the grad year and current job are on the same line

**Comment by ErikGruber** [comment]
In Chrome, there's no space between the white "Online" box and Courses

https://staging.bethel.edu/adult-undergrad/academics/human-services/program-details/

**Comment by ErikGruber** [comment]
same issue in FF

**Comment by e-jameson** [comment]
Are time to completion and credits coming back before these go live? Thats probably why the spacing is strange.

**Comment by ErikGruber** [comment]
Course descriptions w/ question marks:

Individual and Family Psychopathology (HUSE350)

Counseling Microskills (HUSE440)

**Comment by e-jameson** [comment]
Are time to completion and credits coming back before these go live? Thats probably why the spacing is strange.

**Comment by a-parrott** [comment]
Android 4 - quotes are cut short

**Comment by annmarieven** [comment]
I sent the courses to Dave for fixing. 

iOS 8 on iPhone 6 looks good and so does Safari

**Comment by annmarieven** [comment]
Quotes have been fixed. Going to launch with the ? in the course descriptions. Dave will fix shortly.

**Comment by e-jameson** [comment]
rule is done

**Comment by ale73233** [comment]
redirects are done!

**Comment by annmarieven** [comment]
Done and passing to @a-gundy

**Comment by a-gundy** [comment]
Tagged and archived. Closing issue.
