### ISSUE TITLE
CAPS Academics BA in Organizational Leadership Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#492]
Getting ready for launch: https://staging.bethel.edu/adult-undergrad/academics/organizational-leadership/

I will do testing on iOS 8 on iPhone 6 and Safari.
@ale73233 will you do Chrome and FF?
@a-parrott can you browse through the site on your Android 4?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/13YMTx5qrCCXtTerntuDIguVhKPH6mcQK0plCeaNbCh4/edit#gid=1557122749

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1VsASTmQ_N7LOxbBjkdVgQzgkBgeAA1M4vp57hwIBuac/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Close footprints job 13309
- [x] Tag analytics @a-gundy
- [x] Close and archive old site @a-gundy

**Comment by ale73233** [comment]
everything looks good in FF and Chrome!

**Comment by a-parrott** [comment]
Android:
Short quotes
Courses with question marks: ORGL462, HUSE350

**Comment by annmarieven** [comment]
Submitted the courses to Dave. Proofed on iOS 8 on iPhone 6 and Safari.

Found an issue with quotes but we may launch without a fix for now.
http://www.screencast.com/t/AH2bChuwdTPb - when your screen is small on a desktop.
https://files.slack.com/files-pri/T02513GQF-F04PY7GJT/slack_for_ios_upload.png - a lot of padding makes for a really long skinny quote section.

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
Woo! Site launched. Will open a separate job for the minor quote issues.

Passing to @a-gundy

**Comment by a-gundy** [comment]
Tagged and archived. Closing issue.
