### ISSUE TITLE
CAPS Academics BS in Business Management Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#493]
Getting ready for launch: https://staging.bethel.edu/adult-undergrad/academics/business-management/

I will do testing on iOS 8 on iPhone 6 and Safari.
@ale73233 will you do Chrome and FF?
@a-parrott can you browse through the site on your Android 4?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/13YMTx5qrCCXtTerntuDIguVhKPH6mcQK0plCeaNbCh4/edit#gid=166836598

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1dke9OqshlxQZKmfBnsusamin_hcFzS_55x3NXaQbB_s/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Close footprints job 13180
- [x] Tag analytics @a-gundy
- [x] Close and archive old site @a-gundy

**Comment by ale73233** [comment]
FF and Chrome: on the faculty page, https://staging.bethel.edu/adult-undergrad/academics/business-management/faculty Denise Fleming's photo is oval and all of the rest are circle.
FF and Chrome: the "request info" button on the bottom of the pages says "request infor"

**Comment by e-jameson** [comment]
Looks like her image is a rectangle not a square:

https://cdn2.bethel.edu/resize/unsafe/1400x0/smart/https://www.bethel.edu/academics/faculty/images/fleming-denise.jpg

@johjacb anything we can do or does she just need a square image?

**Comment by a-parrott** [comment]
Android 4:
Quotes cut short
Course with question marks: BUSN575

**Comment by ale73233** [comment]
Fixed the info button.

**Comment by annmarieven** [comment]
Fixed Denise Fleming's photo. Ran into some caching issues though so it might not appear fixed to everyone, even though I cleared the cache here:
https://tinker.bethel.edu/cache-test/academics/faculty/images/fleming-denise.jpg

Sent course to Dave.
Allie fixed the request info button.

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
Site launched, looks good.

Passing to @a-gundy!

**Comment by a-gundy** [comment]
Tagged and archived. Closing issue.
