### ISSUE TITLE
List all events with "all-day"

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#494]
@c-varberg could you create a list of all events that have "all-day" checked?

You will probably have to recursively do this as opposed to using the query API tool (it only returns 500 items max, and there are 600+ events)   :(

**Comment by c-schwarze** [comment]
If you could also link the results to the specific cms edit page, that would be great.

**Comment by c-varberg** [comment]
This is the list I came up with 
https://staging.bethel.edu/_testing/calebv/events/events-without-description-page

**Comment by c-schwarze** [comment]
Finished working with Brooke on this one. Closing.
