### ISSUE TITLE
GS Academics MA in Counseling Psychology Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#496]
Getting ready for launch: https://staging.bethel.edu/graduate/academics/counseling-psychology/

I will do testing on iOS 8 on iPhone 6.
@ale73233 will you do Chrome, FF, and Safari?
@a-parrott can you browse through the site on your Android 4?

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=0

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1Y5v3I5XmwocIpsUlfXu6eBQ1t438xt09Km_Ud__Fwfo/edit#gid=0

- [x] Create floodlight tag
- [x] Create redirects
- [x] Close footprints job 14150
- [x] Tag analytics @a-gundy
- [x] Close and archive old site @a-gundy

**Comment by ale73233** [comment]
looks good!

**Comment by e-jameson** [comment]
rule has been done for a while. forgot to update the ghub.

**Comment by annmarieven** [comment]
Site launched and looks good! Passing to @a-gundy

**Comment by a-gundy** [comment]
Tagged and archived. Closing issue.
