### ISSUE TITLE
Quote issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#498]
http://www.screencast.com/t/AH2bChuwdTPb - when your screen is small on a desktop.
https://files.slack.com/files-pri/T02513GQF-F04PY7GJT/slack_for_ios_upload.png - a lot of padding makes for a really long skinny quote section.

on Android 4 @a-parrott reported the quotes are getting cut off.

**Comment by e-jameson** [comment]
I'm somewhat confident we fixed this (it was only an issue in staging(?)). 

Would you mind double checking the pages?
