### ISSUE TITLE
Add Cluster to Robust Metadata

### ISSUE THREAD

**Issue by hamtim** [betheluniversity/cascade#499]
To automate program listings, we'll need to add a cluster option to the robust metadata. Clusters:

Business & Leadership
Education
Health Sciences & Human Services

I'll open another issue for tagging.

**Comment by hamtim** [comment]
Realized we also need to add, I think, "Program Title/Name" and URL

**Comment by annmarieven** [comment]
Per our conversation on 5/28/15...

Healthcare
Education
Business and Leadership

**Comment by annmarieven** [comment]
Per our conversation on 6/4/15 we are putting these in the data definition - not metadata.

**Comment by annmarieven** [comment]
Changed my mind about the location of the cluster. We want it in the metadata because we need to be able to tag the program and then also tag the cluster in the feed. However, it will just be visible rather than inline.
