### ISSUE TITLE
Total credits not showing

### ISSUE THREAD

**Issue by a-gundy** [betheluniversity/cascade#501]
Total credit info isn't showing up on the live site (or staging) even when it is in the program block.
https://cms.bethel.edu/entity/edit.act?id=9a60534e8c58651357534482f316a934&type=block
https://staging.bethel.edu/graduate/academics/education-doctorate/program-details/higher-education

For some reason it was showing up for some of the programs, but not for others and then it disappeared again when I republished the program details page.

**Comment by c-schwarze** [comment]
I believe we removed showing total credits. @annmarieven can you verify this?

**Comment by annmarieven** [comment]
We took it out of the banner data because we were getting incorrect information. We're manually entering that info now. Can it appear if we have manually entered something into the program block?

**Comment by c-schwarze** [comment]
Oh gotcha. Should be showing up now on page publish.

**Comment by a-gundy** [comment]
Republished the program-details pages. Looks good!
