### ISSUE TITLE
CAPS Academics Associates Degree Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#502]
Getting ready to launch this site: https://staging.bethel.edu/adult-undergrad/academics/associates/

I will do testing on the most recent versions of Safari, and iOS 8 on iPhone 6.

@a-parrott can you browse through the site on your Android 4, Chrome, and FF?

Migration grid: 
https://docs.google.com/spreadsheets/d/13YMTx5qrCCXtTerntuDIguVhKPH6mcQK0plCeaNbCh4/edit#gid=705000123

Redirects:
https://docs.google.com/spreadsheets/d/1K7TENQrleME8ko8i41ZyCT6WSAOVfMexL2ZnEnos2iM/edit#gid=0

- [ ] Create floodlight tag @vedmic 
- [x] Create redirects
- [x] Close footprints job 13305
- [x] Tag analytics @a-gundy
- [x] Close and archive old site @a-gundy

**Comment by a-parrott** [comment]
Looks really good!

**Comment by annmarieven** [comment]
Safari and iOS 8 on iPhone 6 look good. Getting ready for launch!

**Comment by e-jameson** [comment]
rules are done

**Comment by annmarieven** [comment]
Woo! Site :rocket: 

Passing to @vedmic for floodlight tag.
@a-gundy you can do your thing too :)

**Comment by a-gundy** [comment]
Tagged and archived (including the General Studies folder since I think it was combined with Associate content).

**Comment by annmarieven** [comment]
Passing to @vedmic for floodlight tag.

**Comment by e-jameson** [comment]
reminder: @vedmic

**Comment by vedmic** [comment]
This is done.
