### ISSUE TITLE
GS Academics MA in Education Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#503]
Getting ready to launch this site: https://staging.bethel.edu/graduate/academics/education-k12/

I will do testing on the most recent versions of Safari and iOS 8 on iPhone 6.
@a-parrott can you browse through the site on your Android 4, Chrome, and FF?

Migration grid: 
https://docs.google.com/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=116567737

Redirects:
https://docs.google.com/spreadsheets/d/1LjCXtnQi_xLLgBfA108zRevZZVp_YaCmdKlphxHkYJM/edit#gid=0

- [ ] Create floodlight tag @vedmic 
- [x] Create redirects
- [x] Close footprints job 13134
- [x] Tag analytics @a-gundy
- [x] Close and archive old site @a-gundy

**Comment by a-parrott** [comment]
Firefox: Site images appeared broken. After a republish the images appear narrow: http://screencast.com/t/7psQyXtWclbv

**Comment by a-parrott** [comment]
Chrome: Looks great!

**Comment by a-parrott** [comment]
Android 4: Looking good!

**Comment by annmarieven** [comment]
Proofed on Safari and iOS 8 on iPhone 6. looks good!

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
Site :rocket:

Passing to @vedmic for the floodlight tag.
@a-gundy you can take care of your things when you get a chance :)

**Comment by a-gundy** [comment]
Tagged and archived.

**Comment by vedmic** [comment]
Haworth tag added and published.
