### ISSUE TITLE
GS Academics MS in Nurse Educator Site Launch and Issues

### ISSUE THREAD

**Issue by hamtim** [betheluniversity/cascade#504]
Getting ready to launch this site: https://staging.bethel.edu/graduate/academics/nursing/

I will do testing on the most recent versions of Safari, and iOS 8 on iPhone 6.

@a-parrott can you browse through the site on your Android 4, Chrome, and FF?

Migration grid: 
https://docs.google.com/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=400511749

Redirects:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1DbqIVmcPmX_ERwC7HWClae6U_LmDzaYlRV0o5BKLRds/edit?usp=drive_web

- [ ] Create floodlight tag @vedmic
- [x]  Create redirects
- [x]  Close footprints job 13041
- [x]  Tag analytics @a-gundy
- [x]  Close and archive old site @a-gundy

**Comment by annmarieven** [comment]
Proofed in Safari and iOS 8. Looks fantastic.

**Comment by annmarieven** [comment]
Chrome looks good too

**Comment by a-parrott** [comment]
Firefox: Looking good!
Android 4: Also super.

**Comment by e-jameson** [comment]
rule is done.

**Comment by annmarieven** [comment]
Passing to @vedmic for the floodlight tag and @a-gundy for archiving and analytics.

**Comment by a-gundy** [comment]
Tagged and archived the site.

**Comment by vedmic** [comment]
Haworth Tag added and published
