### ISSUE TITLE
Event Feed Block

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#505]
Hey Eric,
I'm linking up event feeds and in /career-development/index we changed the event feed page to an event feed block, I linked up the block but the event feed is still not showing up on the live version. Annmarie had to change the data def from a page chooser to a block chooser.

**Comment by e-jameson** [comment]
@c-schwarze can you look at this?

**Comment by c-schwarze** [comment]
Fixed. All office homepages will need to be republished @ale73233 or @annmarieven

**Comment by annmarieven** [comment]
republished all office homepages.

@ale73233 can you proof a few to make sure the event feeds are showing up appropriately and pull the right events?

go to -- administration > content type > office homepage > relationship tab

**Comment by ale73233** [comment]
I proofed them and they are showing up correctly!:)
