### ISSUE TITLE
New Programs Data Def

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#506]
@annmarieven could you create a new data definition for our new program block. Let keep our old one around until we finish building the new one. 

Also, it would be fantastic to have a test block as well.

Let me know if you have any questions! Thanks!

**Comment by annmarieven** [comment]
data definition: https://cms.bethel.edu/entity/open.act?id=53b9a3ba8c5865130265fd80943a90a1&type=structureddatadefinition

test block: https://cms.bethel.edu/entity/open.act?id=53e2c9418c5865130265fd800df3c24a&type=block

**Comment by annmarieven** [comment]
I removed program name because that is just the title of the block. :)
