### ISSUE TITLE
View all content with degree type tag

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#507]
Can we get a list of any and all content with a degree type selected in the metadata?

We're going to change the metadata but I need a list so we know what was tagged before we lose it all.

Let me know if you need more info from me!

**Comment by c-schwarze** [comment]
@c-varberg can you look at this when you have a chance?

**Comment by c-schwarze** [comment]
Next time we publish all of our pages, i should be able to get this done.

For whatever reason, Cascade is just too slow to do it properly (20,000+ pages is too much for it to scan manually now)

**Comment by c-schwarze** [comment]
Let me know if you would like the list in a different way. But here are the pages that has degree type tagged: 

/_testing/caleb-schwarze/another-caleb-testing-folder/cas-department
/_testing/caleb-schwarze/major-minor
/_testing/mark-test/testtwitterbio
/undergrad/academics/biokinetics/majors-minors/biokinetics
/undergrad/academics/anthropology-sociology-reconciliation/majors-minors/third-world-studies
/undergrad/academics/anthropology-sociology-reconciliation/majors-minors/sociocultural-studies
/undergrad/academics/anthropology-sociology-reconciliation/majors-minors/reconciliation-studies-minor
/undergrad/academics/anthropology-sociology-reconciliation/majors-minors/reconciliation-studies
/undergrad/academics/education/majors-minors/education-k-12
/undergrad/academics/education/majors-minors/elementary-education-preprimary
/undergrad/academics/education/majors-minors/education-5-12
/undergrad/academics/education/majors-minors/elementary-education
/undergrad/academics/education/majors-minors/elementary-education-middle-level
/undergrad/academics/education/majors-minors/elementary-education-early-childhood
/undergrad/academics/psychology/majors-minors/psychology
/undergrad/academics/music/majors-minors/applied-performance
/undergrad/academics/music/majors-minors/music-education
/undergrad/academics/music/majors-minors/music
/undergrad/academics/world-languages/majors-minors/tesl
/undergrad/academics/world-languages/majors-minors/spanish-education-k-12
/undergrad/academics/world-languages/majors-minors/spanish
/undergrad/academics/world-languages/majors-minors/linguistics
/undergrad/academics/world-languages/majors-minors/tefl
/undergrad/academics/history/majors-minors/history
/undergrad/academics/history/majors-minors/social-studies
/undergrad/academics/physics/majors-programs/physics-education
/undergrad/academics/physics/majors-programs/applied-physics
/undergrad/academics/physics/majors-programs/physics-ba
/undergrad/academics/physics/majors-programs/physics-bs
/undergrad/academics/theatre/majors-minors/theatre-arts
/undergrad/academics/health-physical-education/majors-minors/physical-education
/undergrad/academics/health-physical-education/majors-minors/health-education
/undergrad/academics/nursing/majors-minors/nursing
/undergrad/academics/english/majors-minors/journalism
/undergrad/academics/english/majors-minors/arts-literature-education
/undergrad/academics/english/majors-minors/literature
/undergrad/academics/english/majors-minors/literature-writing
/undergrad/academics/biblical-theological/majors-minors/missional-ministries
/undergrad/academics/biblical-theological/majors-minors/biblical-theological
/undergrad/academics/biology/majors-minors/biochemistry-molecular
/undergrad/academics/biology/majors-minors/environmental-studies
/undergrad/academics/biology/majors-minors/biology-ba
/undergrad/academics/biology/majors-minors/biology-bs
/undergrad/academics/biology/majors-minors/life-science-education
/undergrad/academics/biology/majors-minors/environmental-science
/undergrad/academics/social-work/majors-minors/social-work
/undergrad/academics/business-economics/majors-minors/economics
/undergrad/academics/business-economics/majors-minors/accounting-finance
/undergrad/academics/business-economics/majors-minors/business
/undergrad/academics/business-economics/majors-minors/economics-finance
/undergrad/academics/math-cs/majors-minors/mathematics
/undergrad/academics/math-cs/majors-minors/computer-science-ba
/undergrad/academics/math-cs/majors-minors/software-project-management
/undergrad/academics/math-cs/majors-minors/computer-science-bs
/undergrad/academics/math-cs/majors-minors/math-education
/undergrad/academics/chemistry/majors-minors/chemistry-bs
/undergrad/academics/chemistry/majors-minors/chemistry-education
/undergrad/academics/chemistry/majors-minors/chemistry-ba
/undergrad/academics/chemistry/majors-minors/biochemistry
/undergrad/academics/chemistry/majors-minors/chemical-engineering
/undergrad/academics/athletic-training/majors-minors/athletic-training
/undergrad/academics/political-science/majors-minors/political-science
/undergrad/academics/political-science/majors-minors/business-political-science
/undergrad/academics/political-science/majors-minors/international-relations
/undergrad/academics/art/majors-minors/art
/undergrad/academics/art/majors-minors/fine-arts
/undergrad/academics/art/majors-minors/graphic-design
/undergrad/academics/art/majors-minors/arts-education
/undergrad/academics/communication/majors-minors/media-production
/undergrad/academics/communication/majors-minors/independent-filmmaking
/undergrad/academics/communication/majors-minors/communication-studies
/undergrad/academics/communication/majors-minors/organization-communication
/undergrad/academics/philosophy/majors-minors/philosophy
/adult-undergrad/academics/christian-ministries/index
/adult-undergrad/academics/organizational-leadership/index
/adult-undergrad/academics/nursing/index
/adult-undergrad/academics/human-services/index
/adult-undergrad/academics/associates/index
/adult-undergrad/academics/business-management/index
/adult-undergrad/academics/accounting/index
/graduate/academics/education-k12/index
/graduate/academics/gerontology/index
/graduate/academics/counseling-psychology/index
/graduate/academics/nursing/index
/graduate/academics/teaching/index
/graduate/academics/physician-assistant/index
/graduate/academics/nurse-midwifery/index
/graduate/academics/special-education/index
/graduate/academics/strategic-leadership/index

**Comment by annmarieven** [comment]
After writing out what the new degree type list would look like, I would like to NOT change the metadata.

A.A.
B.A.
B.M.
B.S.
B.F.A
Certificate
Post-grad Certificate
M.A.
M.S.
M.D.
D.Min.
Ed.D. (??)

It is not clear or user friendly. We'll need to code on the back end if we want the original list to display differently on a page:
<dropdown>
	<item>Select</item>
	<item>Associate of Arts</item>
	<item>Bachelor of Arts</item>
	<item>Bachelor of Music</item>
	<item>Bachelor of Science</item>
	<item>Bachelor of Fine Arts</item>
	<item>Certificate</item>
	<item>Post-grad Certificate</item>
	<item>Master of Arts</item>
	<item>Master of Science</item>
	<item>Master of Divinity</item>
	<item>Doctor of Ministry</item>
	<item>Doctor of Education</item>
</dropdown>

I will bring this up on Thursday.

**Comment by annmarieven** [comment]
Decision made to keep degree type as is.

**Comment by c-schwarze** [comment]
The new list. However, any page that was NOT publishable, will also NOT appear in this list.

staging.bethel.edu/undergrad/academics/biokinetics/majors-minors/biokinetics
staging.bethel.edu/undergrad/academics/anthropology-sociology-reconciliation/majors-minors/third-world-studies
staging.bethel.edu/undergrad/academics/anthropology-sociology-reconciliation/majors-minors/sociocultural-studies
staging.bethel.edu/undergrad/academics/anthropology-sociology-reconciliation/majors-minors/reconciliation-studies-minor
staging.bethel.edu/undergrad/academics/anthropology-sociology-reconciliation/majors-minors/reconciliation-studies
staging.bethel.edu/undergrad/academics/education/majors-minors/education-k-12
staging.bethel.edu/undergrad/academics/education/majors-minors/elementary-education-preprimary
staging.bethel.edu/undergrad/academics/education/majors-minors/education-5-12
staging.bethel.edu/undergrad/academics/education/majors-minors/elementary-education
staging.bethel.edu/undergrad/academics/education/majors-minors/elementary-education-middle-level
staging.bethel.edu/undergrad/academics/education/majors-minors/elementary-education-early-childhood
staging.bethel.edu/undergrad/academics/psychology/majors-minors/psychology
staging.bethel.edu/undergrad/academics/music/majors-minors/applied-performance
staging.bethel.edu/undergrad/academics/music/majors-minors/music-education
staging.bethel.edu/undergrad/academics/music/majors-minors/music
staging.bethel.edu/undergrad/academics/world-languages/majors-minors/tesl
staging.bethel.edu/undergrad/academics/world-languages/majors-minors/spanish-education-k-12
staging.bethel.edu/undergrad/academics/world-languages/majors-minors/spanish
staging.bethel.edu/undergrad/academics/world-languages/majors-minors/linguistics
staging.bethel.edu/undergrad/academics/world-languages/majors-minors/tefl
staging.bethel.edu/undergrad/academics/history/majors-minors/history
staging.bethel.edu/undergrad/academics/history/majors-minors/social-studies
staging.bethel.edu/undergrad/academics/physics/majors-programs/physics-education
staging.bethel.edu/undergrad/academics/physics/majors-programs/applied-physics
staging.bethel.edu/undergrad/academics/physics/majors-programs/physics-ba
staging.bethel.edu/undergrad/academics/physics/majors-programs/physics-bs
staging.bethel.edu/undergrad/academics/theatre/majors-minors/theatre-arts
staging.bethel.edu/undergrad/academics/health-physical-education/majors-minors/physical-education
staging.bethel.edu/undergrad/academics/health-physical-education/majors-minors/health-education
staging.bethel.edu/undergrad/academics/nursing/majors-minors/nursing
staging.bethel.edu/undergrad/academics/english/majors-minors/journalism
staging.bethel.edu/undergrad/academics/english/majors-minors/arts-literature-education
staging.bethel.edu/undergrad/academics/english/majors-minors/literature
staging.bethel.edu/undergrad/academics/english/majors-minors/literature-writing
staging.bethel.edu/undergrad/academics/biblical-theological/majors-minors/missional-ministries
staging.bethel.edu/undergrad/academics/biblical-theological/majors-minors/biblical-theological
staging.bethel.edu/undergrad/academics/biology/majors-minors/biochemistry-molecular
staging.bethel.edu/undergrad/academics/biology/majors-minors/environmental-studies
staging.bethel.edu/undergrad/academics/biology/majors-minors/biology-ba
staging.bethel.edu/undergrad/academics/biology/majors-minors/biology-bs
staging.bethel.edu/undergrad/academics/biology/majors-minors/life-science-education
staging.bethel.edu/undergrad/academics/biology/majors-minors/environmental-science
staging.bethel.edu/undergrad/academics/social-work/majors-minors/social-work
staging.bethel.edu/undergrad/academics/business-economics/majors-minors/economics
staging.bethel.edu/undergrad/academics/business-economics/majors-minors/accounting-finance
staging.bethel.edu/undergrad/academics/business-economics/majors-minors/business
staging.bethel.edu/undergrad/academics/business-economics/majors-minors/economics-finance
staging.bethel.edu/undergrad/academics/math-cs/majors-minors/mathematics
staging.bethel.edu/undergrad/academics/math-cs/majors-minors/computer-science-ba
staging.bethel.edu/undergrad/academics/math-cs/majors-minors/software-project-management
staging.bethel.edu/undergrad/academics/math-cs/majors-minors/computer-science-bs
staging.bethel.edu/undergrad/academics/math-cs/majors-minors/math-education
staging.bethel.edu/undergrad/academics/chemistry/majors-minors/chemistry-bs
staging.bethel.edu/undergrad/academics/chemistry/majors-minors/chemistry-education
staging.bethel.edu/undergrad/academics/chemistry/majors-minors/chemistry-ba
staging.bethel.edu/undergrad/academics/chemistry/majors-minors/biochemistry
staging.bethel.edu/undergrad/academics/chemistry/majors-minors/chemical-engineering
staging.bethel.edu/undergrad/academics/athletic-training/majors-minors/athletic-training
staging.bethel.edu/undergrad/academics/political-science/majors-minors/political-science
staging.bethel.edu/undergrad/academics/political-science/majors-minors/business-political-science
staging.bethel.edu/undergrad/academics/political-science/majors-minors/international-relations
staging.bethel.edu/undergrad/academics/art/majors-minors/art
staging.bethel.edu/undergrad/academics/art/majors-minors/fine-arts
staging.bethel.edu/undergrad/academics/art/majors-minors/graphic-design
staging.bethel.edu/undergrad/academics/art/majors-minors/arts-education
staging.bethel.edu/undergrad/academics/communication/majors-minors/media-production
staging.bethel.edu/undergrad/academics/communication/majors-minors/independent-filmmaking
staging.bethel.edu/undergrad/academics/communication/majors-minors/communication-studies
staging.bethel.edu/undergrad/academics/communication/majors-minors/organization-communication
staging.bethel.edu/undergrad/academics/philosophy/majors-minors/philosophy
staging.bethel.edu/adult-undergrad/academics/christian-ministries/index
staging.bethel.edu/adult-undergrad/academics/organizational-leadership/index
staging.bethel.edu/adult-undergrad/academics/nursing/index
staging.bethel.edu/adult-undergrad/academics/human-services/index
staging.bethel.edu/adult-undergrad/academics/associates/index
staging.bethel.edu/adult-undergrad/academics/business-management/index
staging.bethel.edu/adult-undergrad/academics/accounting/index
staging.bethel.edu/graduate/academics/education-k12/index
staging.bethel.edu/graduate/academics/gerontology/index
staging.bethel.edu/graduate/academics/counseling-psychology/index
staging.bethel.edu/graduate/academics/nursing/index
staging.bethel.edu/graduate/academics/teaching/index
staging.bethel.edu/graduate/academics/physician-assistant/index
staging.bethel.edu/graduate/academics/nurse-midwifery/index
staging.bethel.edu/graduate/academics/special-education/index
staging.bethel.edu/graduate/academics/strategic-leadership/index

**Comment by annmarieven** [comment]
@emily-johnson can you go through the most recent list of content (above) and check that the degree field in the metadata is correct? You should be able to look at the title of the page (or title of the site) to see what type of degree it is.

We'll also need to go through all of the program blocks (in the _shared content folder in cascade) AND all of the setup blocks for each program site. Could you track any ones you change in a google doc and share it with me?

Let me know if you want/need more direction from me!

**Comment by emily-johnson** [comment]
I went through and checked/updated everything, changes are recorded in the google doc I shared with you

**Comment by e-jameson** [comment]
@annmarieven can we close this?

**Comment by annmarieven** [comment]
@hamtim can you look at this google doc, specifically the items highlighted in yellow? we gave our best guess on whether certain things were programs or majors but for a lot of caps, we weren't 100% sure. can you confirm?

https://docs.google.com/document/d/1RkW4JoTy785apLvGxM8EUZnbxPP5Rpt9bCHz2gUs6Nc/edit

**Comment by e-jameson** [comment]
@hamtim have you had a chance to look at this?

**Comment by annmarieven** [comment]
@emily-johnson can you look at the ones we put comments next to, make those changes (to the index page and block), and then close the issue?

**Comment by emily-johnson** [comment]
Done, the only things that were still marked as majors were the Business Management and Christian Ministries blocks
