### ISSUE TITLE
GS Academics MA in Special Education Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#508]
Getting ready to launch this site: https://staging.bethel.edu/graduate/academics/special-education/

I will do testing on the most recent versions of Safari, and iOS 8 on iPhone 6.

@a-parrott can you browse through the site on your Android 4, Chrome, and FF?

Migration grid: 
https://docs.google.com/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=223990650

Redirects:
https://docs.google.com/spreadsheets/d/1ezwPE02n65Y5HmPXBFEQyFIiX0o1FMVhmISlAXzSrzo/edit#gid=0

- [x] Create floodlight tag @vedmic
- [x]  Create redirects
- [x]  Close footprints job 13131
- [x]  Tag analytics @a-vennerstrom
- [x]  Close and archive old site @c-schwarze

**Comment by e-jameson** [comment]
rule is done

**Comment by a-parrott** [comment]
Firefox: The proof points do not animate.

**Comment by a-parrott** [comment]
Chrome: Looks good!

**Comment by a-parrott** [comment]
Android 4: Also looks good!

**Comment by annmarieven** [comment]
Looks great in Safari and iOS on iPhone 6.

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
site launched. looks good!

@vedmic can you do the floodlight tag on this one?

**Comment by vedmic** [comment]
Haworth tag added and published.

**Comment by annmarieven** [comment]
@c-schwarze can you close and archive the site in Silva?

**Comment by c-schwarze** [comment]
@e-jameson I will pass this off to you :)

**Comment by e-jameson** [comment]
Didn't realize this was waiting for me. Done.
