### ISSUE TITLE
Massive enrollment counselor images

### ISSUE THREAD

**Issue by a-gundy** [betheluniversity/cascade#509]
Enrollment counselor images are massive for all the schools in Firefox (v. 38.0.1). It looks much better in Chrome. 

https://www.bethel.edu/undergrad/admissions/counselors/east
https://www.bethel.edu/graduate/admissions/advisors/erica-hering
https://www.bethel.edu/adult-undergrad/admissions/advisors/josh-daubenmeyer
https://www.bethel.edu/seminary/admissions/team/terry-stephens

![enrollment-issues](https://cloud.githubusercontent.com/assets/9537391/7705568/a7ac2a60-fe0a-11e4-9498-a9e992e56397.png)

**Comment by johjacb** [comment]
This has been fixed, but the pages need to be republished :disappointed:

**Comment by annmarieven** [comment]
This will be taken care of next time we do a whole-site publish (sometime next week).
