### ISSUE TITLE
Updating quote collection pages to blocks

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#510]
@ale73233 
Using the link below, can you go through and create blocks in place of the pages? 
1. Check the metadata of the collection page
2. Create a collection block and tag the collection block with the same exact metadata (it will be named 'associates-quote-collection1' and that's okay for now)
3. Embed the newly created blocks where the page was. You can find out where the collection page was embedded by going to the 'relationships' tab of the asset. If you come across anything that doesn't have a relationship, include it in here.
**don't delete anything yet**

https://cms.bethel.edu/entity/relationships.act?id=8a4122d28c5865135c5c083d367d1a8e&type=contenttype

Any pages inside of the testing folder can just be deleted.
Reassign the issue to me when it's done. 
Let me know if you have any questions or if you encounter things like last time, where you couldn't embed the block because it was a page chooser instead of a block chooser, etc.

**Comment by a-gundy** [comment]
/undergrad/academics/biology/biology-quote-collection manually selected a quote, but there are multiple quotes it could automatically pull. 

honors-quote-collection and index-quote-collection don't have any relationships

Assigning to @annmarieven

**Comment by ale73233** [comment]
left off in education in undergrad

**Comment by annmarieven** [comment]
Still working on cleaning up/getting rid of old quote collection pages.

**Comment by annmarieven** [comment]
Finished quote collection transition from pages to blocks.
