### ISSUE TITLE
News Feed RSS feed

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#511]
We need to be able to publish RSS pages for our news feeds.

**Comment by hamtim** [comment]
We need to figure out how to exclude Bethel Alert news stories.... Let's
chat.


----------
Timothy Hammer
Senior Strategist
Web & Creative Services

Bethel University
3900 Bethel Drive
St. Paul, MN 55112
o: 651.638.6784 c: 515.971.5659

**Comment by e-jameson** [comment]
@c-schwarze Can you maybe work with Josiah maybe later next week or whenever he has some free time to start working on this. There is an "RSS" content type already created that we can use, just need to support news feeds.

**Comment by hamtim** [comment]
@annmarieven is adding a Bethel Alert category that we can exclude (or I guess rather, not include) in the RSS feed

**Comment by annmarieven** [comment]
Category added.

**Comment by josiahtillman** [comment]
I’ve got the rss feed up! Here’s the xml of my test.  It has the parameters of being of school type bethel university and of unique-news type homepage

Josiah Tillman [11:34 AM]
https://staging.bethel.edu/_testing/josiah-tillman/test-news.xml

**Comment by josiahtillman** [comment]
Changed it to have no school type parameters.  It will now post any that are of unique-news type homepage.

**Comment by hamtim** [comment]
Looking good. Can we add the teaser/description @josiahtillman?

**Comment by josiahtillman** [comment]
Do you want the teaser or the description? They are normally pretty similar, so we don't probably need both,, do we?

**Comment by hamtim** [comment]
Can you give me examples of each? Not in the code, just want it would
return from one of our stories?


----------
Timothy Hammer
Senior Strategist
Web & Creative Services

Bethel University
3900 Bethel Drive
St. Paul, MN 55112
o: 651.638.6784 c: 515.971.5659

**Comment by josiahtillman** [comment]
Teaser: The founder-director emeritus of the Center for Faith & Work shares insights about work from the book of Genesis. 
Description: Bethel’s “Faith in the Public Square” Convocation series continued with Katherine Leary Alsdorf, an expert in the field of faith and work, who spoke in chapel last week about the connection between the Old Testament book of Genesis and our work.

We can probably prioritize one and then check for the other if the first one doesn't exist

**Comment by hamtim** [comment]
maybe the description?


----------
Timothy Hammer
Senior Strategist
Web & Creative Services

Bethel University
3900 Bethel Drive
St. Paul, MN 55112
o: 651.638.6784 c: 515.971.5659

**Comment by josiahtillman** [comment]
@hamtim :
Okay! I got it to show the description and then the teaser if there is no description! Same link will work to see it
https://staging.bethel.edu/_testing/josiah-tillman/test-news.xml

**Comment by hamtim** [comment]
I think this will work nicely. Can we move it into production?

-t


----------
Timothy Hammer
Senior Strategist
Web & Creative Services

Bethel University
3900 Bethel Drive
St. Paul, MN 55112
o: 651.638.6784 c: 515.971.5659

**Comment by josiahtillman** [comment]
Alrighty, they're all good to go! Here is the folder for the rss feeds:
https://cms.bethel.edu/entity/open.act?id=e2cfc1fe8c5865134da7f0bc9f3dc791&type=folder&

We also moved the job posting rss feeds here as well to keep them all together.

**Comment by e-jameson** [comment]
Assigning @hamtim

**Comment by crossonrose** [comment]
No way!
