### ISSUE TITLE
Reconciliation Studies major/minor

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#515]
The Reconciliation Studies major button is linked to the minor and the minor doesn't show up in the table.

https://www.bethel.edu/undergrad/academics/anthropology-sociology-reconciliation/

Any idea why? Could this be happening elsewhere too?

**Comment by c-schwarze** [comment]
Fixed. The reconciliation studies minor was tagged as major. I retagged it as a minor.
