### ISSUE TITLE
GS Academics MS in Physician Assistant Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#517]
We are getting ready to launch this site: https://staging.bethel.edu/graduate/academics/physician-assistant/

I will do testing on the most recent versions of Chrome, FF, Safari, and iOS 8 on iPhone 6.

Migration grid: 
https://docs.google.com/a/bethel.edu/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=2036050991

Redirects:
https://docs.google.com/spreadsheets/d/1EtNkiFK6PZXJ19a5UlU-UcJ7B57kItpQKTECyT5z70s/edit#gid=0

- [ ] Create floodlight tag
- [x] Create redirects
- [x] Close footprints job 13136
- [x] Tag analytics
- [x] Close and archive old site @c-schwarze

**Comment by annmarieven** [comment]
All the testing looks good.

**Comment by annmarieven** [comment]
Site launched. @vedmic can you put the floodlight tag in? Don't close the issue yet because we still need to archive the old site.

Check the box above after you've put in the tag.

**Comment by e-jameson** [comment]
Site has been archived. @vedmic you can close the issue after the tag has been added.

**Comment by vedmic** [comment]
AMV can you assign the floodlight tag.

**Comment by annmarieven** [comment]
floodlight tag added. closing issue.
