### ISSUE TITLE
Program Feed

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#518]
We need to create a block that will pull certain programs based on metadata tagged.

For example, I need to create a page for each degree type (doctorate, masters, certificates, bachelors for caps, etc.). I want to be able to tag the metadata (school and degree type) and have an automated list of the programs that fit those 2 categories.

The end result will look something like this:
http://caps.bethel.edu/academics/bachelors/
http://gs.bethel.edu/academics/masters/
http://gs.bethel.edu/academics/certificates/

This is for the caps and gs academic sites but will also be used on the marketing landing pages, admissions, etc.

What do we need to do to get this started?

**Comment by josiahtillman** [comment]
@annmarieven Alright! I created a block for this! 

Here is an example of what it does: 
https://staging.bethel.edu/_testing/josiah-tillman/programfeedpage

Here is the block that it is pulling from:
https://cms.bethel.edu/entity/edit.act?id=df581d0d8c5865134da7f0bcd80a0f2b&type=block

I also created an Asset Factory:
https://cms.bethel.edu/entity/open.act?id=df56eb1a8c5865134da7f0bc16b9fa7e&type=assetfactory&

Any suggestions or comments?

**Comment by annmarieven** [comment]
Hm.. why is your list all neat and clean? 
https://cms.bethel.edu/entity/open.act?id=e349b62b8c5865134da7f0bc437ec381&type=page&

Mine has funky names, pulling concentrations, etc.

Also, what if I want my list to pull all masters programs (including MA and MS)?

**Comment by annmarieven** [comment]
Here's the data definition for the program feed:
https://cms.bethel.edu/entity/edit.act?id=f89c4ca08c5865134da7f0bccee1c882&type=structureddatadefinition

**Comment by annmarieven** [comment]
We need an asset factory created for this but I don't know how to do that without a specific data definition. I think we'd use the 'include format' one but don't know what to do with that.

**Comment by c-schwarze** [comment]
Josiah already created an asset factory (link above ^^ ) :)

 And it is exactly as you stated it. You use the 'include format' data definition and type "program-feed".

**Comment by annmarieven** [comment]
@emily-johnson can you create a folder 'program-feeds' in the shared content folder?

Then create one program feed for each degree type, organized within school folders.
gs masters (all) (graduate-masters)
gs doctorate
gs certificates
gs licensures

caps bachelors (all) (adult-undergrad-bachelors)
caps cert

seminary masters (all) (seminary-masters)
seminary certificates
seminary doctorate

**Comment by e-jameson** [comment]
I think this isn't assigned to me?

**Comment by emily-johnson** [comment]
Done!

**Comment by emily-johnson** [comment]
@josiahtillman Can we hide the title of the program feed on this page? https://staging.bethel.edu/graduate/academics/masters
Even if we changed it to make sense here, we will use the block on other sites. Thanks!

**Comment by emily-johnson** [comment]
(We want it hidden anywhere we embed it, not just on that page)

**Comment by josiahtillman** [comment]
Alright, they should all be hidden now :D

**Comment by emily-johnson** [comment]
@josiahtillman /adult-undergrad/academics/certificates/index is pulling the HR management cert (which is not labeled as a certificate in the metadata) but NOT pulling the alcohol/drug counseling cert (which does have correct metadata). And some of the other pages are not pulling anything:

https://staging.bethel.edu/adult-undergrad/academics/bachelors/
https://staging.bethel.edu/graduate/academics/certificates/
https://staging.bethel.edu/graduate/academics/licensures/

Would you mind taking a look at the block to see if it's messing something up? I've checked everything and can't find anything wrong on my end.

**Comment by josiahtillman** [comment]
Ok, I believe this is fixed now.  The block should also now output "No Programs to List" If it didn't find any programs in your department(s).

**Comment by emily-johnson** [comment]
@josiahtillman They still aren't pulling anything, the three I listed above all say No Programs to List. I've checked the metadata of the degrees/certs/licenses and they seem to be set up just how they should be to be getting pulled. Can you tell us why they aren't getting pulled in?

**Comment by annmarieven** [comment]
One other minor thing, when it says No Programs to List, it looks like a link but doesn't actually link to anything. Can we remove that?

Reassign to @emily-johnson when it's ready for proofing again

**Comment by josiahtillman** [comment]
Alright, the links you sent me have been fixed, and it no longer looks like a link when it says "No Programs to List."

**Comment by emily-johnson** [comment]
Looks great, thanks!!

**Comment by annmarieven** [comment]
After talking with Jake, we need to go about this differently. We won't be able to just have one set of blocks in the shared content because of the way they look on the pages (especially flex pages). We'll need to create them wherever we need them, based on the unique headings they need.

@josiahtillman can you make the title of the block show up as a heading 2 again?

@emily-johnson can you build the masters, doctoral, certificates, and licenses program feed blocks in graduate/academics for the graduate programs? then embed them on the respective pages (basically copying what it looks like in Silva: gs.bethel.edu/academics) then do the same for caps and seminary. can you delete the program feed folder out of shared content?

sorry for going back and forth. this sometimes happens with brand new assets as we try something but don't realize the full implications of it :) Thanks!!

**Comment by josiahtillman** [comment]
Ok! It's a heading 2 once again~!

**Comment by emily-johnson** [comment]
Ok the graduate feeds look good (the master's page isn't showing the title only because it won't let me publish to staging). I'll work on sem and caps

**Comment by emily-johnson** [comment]
They are all moved to their academics folders and the caps feeds are renamed and all set up. We'll have to go back and work on the sem feeds once we know for sure what we are doing with the folder structure.
