### ISSUE TITLE
Hide from Calendar not working

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#520]
From Jan Jessup in job 14953:
For the Chemistry Dept Open House event I posted on the calendar for October 10, I selected yes for "Hide from Calendar," but I still see it on the calendar. I'd like this to appear on the department's event feed but not on the calendar. I will be posting ten more Homecoming open houses like this that should appear on various dept feeds--too many for one day on the calendar (the Homecoming posting/website will contain links to the open house pages).

**Comment by josiahtillman** [comment]
Fixed it~! :D
