### ISSUE TITLE
Construction alert on event pages

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#521]
Per Jan Jessup's request in job 14953.

Is it possible to only have the alert show for events through august 2015? By October the construction will be done but the alert is showing on those pages as well.

**Comment by e-jameson** [comment]
@annmarieven: we aren't checking month (difficult) only year (easy). The idea was to remove the alert and then republish all 2015 events when construction was done. Is that okay or do we need to only target now through August. I belive the language on the page had a timeframe.

**Comment by annmarieven** [comment]
I followed up with Jan to explain and see what she's okay with.

**Comment by annmarieven** [comment]
Sounds like they're okay leaving as is. Closing issue.
