### ISSUE TITLE
Faculty lists

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#523]
Can we make it so if I just select a school, the faculty list will pull all faculty with that school chosen?

https://staging.bethel.edu/adult-undergrad/academics/faculty

https://cms.bethel.edu/entity/open.act?id=01d111c58c5865137c9c2c89fea8d13a&type=page

**Comment by josiahtillman** [comment]
Alrighty! I made it so all faculty in the specified school will be displayed if no departments are chosen :)
