### ISSUE TITLE
News Archive not Archiving.

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#524]
https://www.bethel.edu/news/news-archive

@c-schwarze, @josiahtillman could probably work on this with some context.

**Comment by c-schwarze** [comment]
What is the feed supposed to do?

**Comment by e-jameson** [comment]
https://www.bethel.edu/president/announcements/

**Comment by c-schwarze** [comment]
The feed was not marked as a news archive. 

Updated to a news archive and published.
