### ISSUE TITLE
Left hand nav error

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#527]
Someone is having issues with the left hand nav. They are reporting and have taken a screen shot of it appearing all the way at the bottom of the page. I can't replicate the issue. Any ideas what's going on?

Page: gs.bethel.edu/academics/individual-courses/

Screenshots are here:
https://footprints.bethel.edu/MRcgi/MRTicketPage.pl?USER=celanna&MRP=z4Hh4CV&MAJOR_MODE=EDIT&MAXMININC=&LASTID=7201&MR=14949&PROJECTID=9&RUNNING_IN_POPUP=1

Note from user:
It is working in Firefox just fine, but not in Google Chrome (version -
43.0.2357.124 m). I have also refreshed the page and cleared out my
cache/cookies with Chrome with no improvement.

Everything looks great in Firefox and IE, just not Chrome.

**Comment by e-jameson** [comment]
I can't replicate this either and it should be in Cascade soon. Ignore unless we hear move complaints?

**Comment by c-schwarze** [comment]
I am able to see the issue in Chrome...but I can't figure out why its formatting like that.

**Comment by annmarieven** [comment]
hm.. since we were able to replicate it, can we look into it further?

**Comment by johjacb** [comment]
I also cannot replicate in any browser. 

How long before this is in cascade?
