### ISSUE TITLE
Event date formatting update

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#529]
Wednesday, July 01, 2015
https://www.bethel.edu/events/2015/admissions/online-information-session-for-online-seminary-programs

For single digit dates, can we get rid of the 0 in front?

So it would read: Wednesday, July 1, 2015

**Comment by c-schwarze** [comment]
Do we want this to apply to our event feed single digit dates?

Check a few out here https://www.bethel.edu/events/

**Comment by josiahtillman** [comment]
They now leave off the 0! The link caleb shared is unchanged, do you want me to change that one as well?

**Comment by c-schwarze** [comment]
Yeah. All event feeds should be updated as well

**Comment by josiahtillman** [comment]
Fixed~! :)
