### ISSUE TITLE
Blog feed

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#530]
Is there a way to do a blog feed in Cascade?

**Comment by annmarieven** [comment]
@e-jameson is going to ask @pstjean about the RSS feed when he gets back.

**Comment by e-jameson** [comment]
http://blogs.bethel.edu/bethel-library/feed/rss/

**Comment by e-jameson** [comment]
@pstjean said the RSS format might change when we update our Wordpress version, so they might want to hold off until that is done. Hopefully the update will be done Wednesday evening.

**Comment by annmarieven** [comment]
Followed up with Betsy.
