### ISSUE TITLE
Tweaking tables

### ISSUE THREAD

**Issue by johjacb** [betheluniversity/cascade#531]
We need to tweak our responsive tables a bit. Caleb uncovered 5 pages that have a table. Please add any more if you know of any.

dining-services/locations/monson/prices
- No changes needed, the table should look fine with the new format

dining-services/meal-plans/plans
- this table will probably need to be broken into two tables, and given the small numbers, we may be able to get away without making them responsive

seminary/financial-aid/after-awarded/compare-loans
- Can this table be reworked? We should probably only have one Header column

seminary/admissions/partnerships/young-life
- Can we switch columns so that the Course title is the first column?

seminary/admissions/partnerships/campus-crusade
- Can this just be a regular table?

@annmarieven let's discuss

**Comment by annmarieven** [comment]
more pages with tables:
graduate/academics/special-education/prerequisites
graduate/academics/physician-assistant/prerequisites
/graduate/financial-aid/after-awarded/compare-loans
/undergrad/financial-aid/after-awarded/compare-loans
/adult-undergrad/financial-aid/after-awarded/compare-loans

**Comment by c-schwarze** [comment]
Those tables aren't responsive tables fyi.

**Comment by annmarieven** [comment]
Was this issue only for tables that were already responsive?

**Comment by johjacb** [comment]
yes

**Comment by johjacb** [comment]
ok all of these tables have been converted

**Comment by annmarieven** [comment]
Should this code be applied to other tables on our site as well?

**Comment by johjacb** [comment]
I changed the table at : https://www.bethel.edu/graduate/financial-aid/after-awarded/compare-loans

The table at : https://www.bethel.edu/undergrad/financial-aid/after-awarded/compare-loans

is very large. Could we pull out 'Bethel's Advice'? And maybe move the more info links to a list below the table?

**Comment by annmarieven** [comment]
I will do this after we get something figured out. There are some major issues going on with tables that we've tweaked. Attached are screenshots. Check FP job 15145 for more info.

![image_20150709105013_485554](https://cloud.githubusercontent.com/assets/6526079/8679287/607e1dba-2a1f-11e5-988f-8f25f609184f.png)
![image_20150714113212_941764](https://cloud.githubusercontent.com/assets/6526079/8679289/61e3f4ea-2a1f-11e5-9c32-a9b064d1fab1.png)

**Comment by annmarieven** [comment]
@johjacb see the issues above.

**Comment by johjacb** [comment]
the scrollbars have been changed. now they should only show on IE when the content actually overflows. 

On macs, the scrollbars are hidden, on IE, the scrollbars will be visible. Its yucky. :disappointed: 

The best way to avoid this is to adjust the table.

**Comment by annmarieven** [comment]
Can you show me how I would adjust the tables to fix this? Let's look at it sometime next week.

**Comment by johjacb** [comment]
I think these tables have all been fixed. reopen if new issues surface
