### ISSUE TITLE
ITS Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#532]
We're launching this site tomorrow - https://staging.bethel.edu/its/

I will proof the site in Chrome, FF, Safari, and on iOS 8 - iPhone 6. This site is all basic pages and forms so I don't anticipate any issues.

Redirect grid: https://docs.google.com/spreadsheets/d/16yMgP4BX_ABVlhOIfJgMK9rwwiJuF1FpuC4zvf5ANT0/edit#gid=0

- [x] Create redirects
- [x] Tag analytics
- [x] Close old site @e-jameson

**Comment by annmarieven** [comment]
After cleaning up a heck of a lot of nasty html from copying/pasting from google docks, Chrome looks good. Moving onto the others.

**Comment by annmarieven** [comment]
FF, Safari, and iOS 8 - iPhone 6 look mostly good. 

I ran into one item on my phone. This page title is too long and gets cut off --

https://bethel.slack.com/files/a-vennerstrom/F071HDJVC/slack_for_ios_upload.png

@johjacb what can we do about that?

Otherwise, the site is ready to launch.

**Comment by annmarieven** [comment]
Site launched! Run through looked good, all the redirects are in too.

@e-jameson can you close the old site?

**Comment by annmarieven** [comment]
@e-jameson did this get moved or closed?

**Comment by e-jameson** [comment]
Moved to /its-old in old silva.
