### ISSUE TITLE
Student Worker Permissions - ITS page

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#533]
Randy would like this page moved to Cascade. Right now we don't have this ability in Cascade.

Is it something we want to/can support?

https://www.bethel.edu/its/forms/stw-perms/@@index.html

**Comment by e-jameson** [comment]
I don't think we should.  Something like this should go to whoever controls INB accounts / Dept drives directly, or they should support a way to control access.

**Comment by annmarieven** [comment]
Eric is following up with Randy, per Mike's request. Closing issue.
