### ISSUE TITLE
Create License Folders and Blocks

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#534]
Emily,
Could you create folders and program blocks for each of our licenses?
https://docs.google.com/spreadsheets/d/1EY5kgeUPJIZiTBa9nKzPbuCjs0JiB_AF3Ww516XEEf4/edit#gid=1093195317

Folders will live here: /graduate/academics/licensures/
Enter system name from grid (existing url column)
Hide from navigation in metadata

system names for 2 programs not on grid:
teaching-k-12
teaching-secondary

Create new Academic Program Homepage (in "academics" section in new menu)
System name: index
Enter title from grid

Program blocks will live here: /_shared-content/program-blocks/graduate/licensures/
Enter system name from grid (existing url column)
Enter title from grid

**Comment by annmarieven** [comment]
Now that those items are there, can you create a program details folder with an index page for each license folder?

Within each license folder, create a new folder.
system name: program-details
display name: Program Details
title: Name of License Program Details (ex: Director of Education License Program Details)

Then create a flex page inside of the program details folder.
system name: index
display name: Program Details
title: Name of License Program Details (ex: Director of Education License Program Details)

**Comment by emily-johnson** [comment]
The program blocks are now linked to the program details index of each corresponding license

**Comment by annmarieven** [comment]
@emily-johnson if the setup blocks are all created with the admissions buttons, image banks, site title, and program block linked up, can you mark it as 'done' on each sheet in this grid? https://docs.google.com/spreadsheets/d/1EY5kgeUPJIZiTBa9nKzPbuCjs0JiB_AF3Ww516XEEf4/edit#gid=2045791505

let's look at the navigation order of each one too and mark it as 'done'. I'll walk you through the first one.
