### ISSUE TITLE
GS Academics Nurse Educator Certificate Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#535]
Proofing this site. Depending on how it goes, maybe we'll launch this week!
https://staging.bethel.edu/graduate/academics/certificates/nurse-educator

I will do testing on the most recent version of Safari and iOS 8 on iPhone 6.
@donowenskid can you do testing on the most recent versions of Chrome and FF?

Migration grid: 
https://docs.google.com/spreadsheets/d/11K-MAuCwqoMSQuA5tQAMvcVxkqdjoRO8hFBeWrgq3qk/edit#gid=0

Redirects:
https://docs.google.com/spreadsheets/d/1KruqZIXdKvLNxT5m3wL7VUw-0azZ4uk6gfmE66p8QRU/edit#gid=0

- [x] Create redirects 
- [x] Close footprints job 14721
- [x] Tag analytics 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
@johjacb courses is a little tight to the white box with the delivery info.

https://staging.bethel.edu/graduate/academics/certificates/nurse-educator/program-details/

**Comment by annmarieven** [comment]
@johjacb also, the program details pages have a larger margin than the rest of our pages when I view it on iOS 8 on iPhone6.

everything else on iOS 8 looks good.
Safari looks good too.

@donowenskid I added you to this issue. Can you look at Chrome & FF? Then reassign to me :blush: Thanks!

**Comment by donowenskid** [comment]
Site looks great on both Chrome and FF

**Comment by annmarieven** [comment]
Need to send to Diane Dahl for final proof before launch (after we get total credits and program length)

**Comment by annmarieven** [comment]
@hamtim Can you send this to Diane for a final proof? (url is above)

**Comment by hamtim** [comment]
Sent to Pam Friesen and Barb H in nursing (Diane said to send to them).

-t


----------
Timothy Hammer
Senior Strategist
Web & Creative Services

Bethel University
3900 Bethel Drive
St. Paul, MN 55112
o: 651.638.6784 c: 515.971.5659

**Comment by annmarieven** [comment]
Made a few fixes via the FP job. Scheduling launch for Monday.

**Comment by donowenskid** [comment]
Site ready. Jmo, another rule please?

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
Site launched. Looks awesome!
