### ISSUE TITLE
GS Academics Gerontology Certificate Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#536]
Proofing this site. Depending on how it goes, maybe we'll launch this week!
https://staging.bethel.edu/graduate/academics/certificates/gerontology

@a-parrott will do testing on the most recent versions of Chrome, FF, Safari, and her Android.

Migration grid: 
https://docs.google.com/spreadsheets/d/11K-MAuCwqoMSQuA5tQAMvcVxkqdjoRO8hFBeWrgq3qk/edit#gid=663055073

Redirects:
https://docs.google.com/spreadsheets/d/1dZ4Vtao_wNjlNNv60PxATlZ93EfIoEZMfTM5fgBq0iI/edit#gid=0

- [ ] Create floodlight tag @vedmic 
- [x] Create redirects @emily-johnson 
- [x] Close footprints job 14719
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by a-parrott** [comment]
Everything looks great!

**Comment by annmarieven** [comment]
Site is live. @e-jameson ready for the rule!

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
@emily-johnson using the grid above, can you put in the 2 redirects? I will also give you access to google analytics and show you how to add a note.

Once those 2 things are done, check the boxes above. Thanks!

**Comment by annmarieven** [comment]
@e-jameson can you archive the old site?

from here: https://editor.its.bethel.edu/silva/gs/academics/certificates/edit/tab_edit
to here: https://editor.its.bethel.edu/silva/archive/gs/academics/edit/tab_edit -- I tried to create a certificates folder but Silva broke. :(

**Comment by annmarieven** [comment]
I archived the site.

Passing to @vedmic for floodlight tag.

**Comment by vedmic** [comment]
We don't have floodlight tags for certificates yet. I'll reach out to Haworth to get these.

Thanks.
