### ISSUE TITLE
Event times

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#537]
See this page as an example:
https://www.bethel.edu/events/2015/admissions/seminary-summer-series-ii-spiritual-and-personal-formation

if times are both am or pm the first am or pm should be dropped.

Instead of:
1 p.m. - 2 p.m.
it should be:
1-2 p.m.

Thanks!

**Comment by c-schwarze** [comment]
Updated.

**Comment by annmarieven** [comment]
I'm still seeing this even on a newly published page. https://cms.bethel.edu/entity/open.act?id=34fbcde08c5865130265fd80a32da194&type=page

Reassign to me when it's done for testing and then I'll republish the whole events folder. Thanks!

**Comment by annmarieven** [comment]
Nevermind. For some reason the 'live' tab was showing something different than the layout tab. I'll republish the whole events folder sometime.... It might clog up the queue for a while
