### ISSUE TITLE
Remove Spotlight Code on Academic Program Page

### ISSUE THREAD

**Issue by donowenskid** [betheluniversity/cascade#538]
Most academic home pages have spotlight sections, but the license pages won't. Can you remove the spotlight code from the license pages?

https://staging.bethel.edu/graduate/academics/licensures/technology-educators/

https://cms.bethel.edu/entity/open.act?id=6421ce938c5865137c9c2c89d343f189&type=page&

**Comment by c-schwarze** [comment]
Updated.
