### ISSUE TITLE
GS Academics Certificate in International Baccalaureate Teaching and Learning Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#539]
Proofing this site. Still waiting for total credits and program length so we won't be able to launch till then. But we're getting everything else ready.
https://staging.bethel.edu/graduate/academics/certificates/international-baccalaureate/

I will do testing on the most recent version of Safari and iOS 8 on iPhone 6.
@donowenskid can you do testing on the most recent versions of Chrome and FF?

Migration grid: 
https://docs.google.com/spreadsheets/d/11K-MAuCwqoMSQuA5tQAMvcVxkqdjoRO8hFBeWrgq3qk/edit#gid=774636362

Redirects:
https://docs.google.com/spreadsheets/d/1jX5FswG4e6fQ5Sa0Yb7Ym3m-UC7Kh_vCdbNG7esLRpM/edit#gid=0

- [x] Create redirects
- [x] Close footprints job 14622
- [x] Tag analytics
- [x] Close and archive old site

**Comment by annmarieven** [comment]
@hamtim no courses are getting pulled from banner. There was some confusion about the name. Dave emailed on May 27 with the new name but in early June the folks asked for a different name. We're going with the official one that we got from Dave: Certificate in International Baccalaureate Teaching and Learning

Safari looks good.
iOS 8 looks good too.

@emily-johnson can you look through this site and update all references to the program to the official name: Certificate in International Baccalaureate Teaching and Learning

**Comment by emily-johnson** [comment]
I went through the /graduate/academics/certificates/international-baccalaureate folder and changed everything to the name that Dave sent out.

**Comment by donowenskid** [comment]
Site looks great on both Chrome and FF

**Comment by annmarieven** [comment]
Still not getting IB courses. Assigning to @hamtim

**Comment by annmarieven** [comment]
Scheduling launch for Monday (without courses). @emily-johnson can you unhide the index page so it shows up in the left hand nav? 

Then reassign to me for launch.

**Comment by emily-johnson** [comment]
Done

**Comment by donowenskid** [comment]
Site is launched. Jmo, can you put a rule in?

**Comment by e-jameson** [comment]
Rule is in but site is 404ing

https://www.bethel.edu/graduate/academics/certificates/international-baccalaureate/

**Comment by annmarieven** [comment]
Site launched. Looks fantastico!
