### ISSUE TITLE
Homecoming registration widget

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#540]
FP job 15156.

From Erin Ekstrand:
For the past two years our reunion pages have included a feature/widget that lists the names of those who have registered for that particular reunion. It has updated in real time, based on Wufoo registrations. How do I include that feature on each of the reunion pages this year?

**Comment by e-jameson** [comment]
@annmarieven , when do they need this live by?

**Comment by annmarieven** [comment]
She said they're hoping to have registration up and running within the next week or so. Which is not a very long turn around time for us. So I would shoot for end of July? Is that possible?

**Comment by e-jameson** [comment]
Up to you. I don't think it will take too long to move over.

**Comment by annmarieven** [comment]
Let's shoot for July 24 then.

**Comment by e-jameson** [comment]
Waiting on a SQL Procedure from Dave H.

**Comment by e-jameson** [comment]
@annmarieven, this is ready.

Example page:

https://www.bethel.edu/_testing/jmo/block-pages/homecoming-guest-list

Example Block:

https://cms.bethel.edu/entity/open.act?id=d0b3598b8c58651314811f9c31ef0bb2&type=block&

Data def:

https://cms.bethel.edu/entity/open.act?id=d0ae0fcd8c58651314811f9cddf33e00&type=structureddatadefinition

I didn't create an asset factory or base asset.

**Comment by annmarieven** [comment]
created a base asset and an asset factory. followed up with Erin.

**Comment by annmarieven** [comment]
From Erin:
Entered on 08/05/2015 at 09:14:10 CDT (GMT-0500) by erin-ekstrand@bethel.edu:
Hi Web Services!

Thank you for publishing the Class Reunion pages that I submitted
yesterday! Unfortunately, the Guest List block appears to be publishing the
names of alumni who registered for last year's reunions. Is it possible to
get this corrected this morning?

Thank you!
Erin

**Comment by annmarieven** [comment]
jmo fixed this.
