### ISSUE TITLE
Nursing Courses

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#542]
Nursing isn't pulling courses from banner

https://www.bethel.edu/adult-undergrad/academics/nursing/program-details/

**Comment by e-jameson** [comment]
Two issues here:

1. CORE320 was entered as a core course, which is not a course for this program. 

2. My code didn't handle the extra course correctly and failed. This has been fixed so the page loads normally, but it would probably be good to remove this from the block.
