### ISSUE TITLE
Tagging school, degree, program

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#545]
Can you go through each school's academic folder and all the program blocks to make sure the following are tagged?

School
Degree type
Program

/_shared-content/program-blocks/ -- make any needed changes but don't publish because blocks don't need to be published

/undergrad/academics/
* index page for each program - publish to production 
* event feed
* news article feed
* proof point collection
* quote collection

/adult-undergrad/academics/
* index page for each program - publish to production (except what's in the certificate folder)
* event feed
* news article feed
* proof point collection
* quote collection

/graduate/academics/
* index page for each program - publish to production (except what's in the certificate and licensure folder)
* event feed
* news article feed
* proof point collection
* quote collection

/seminary/academics/
* index page for each program - don't publish anything
* event feed
* news article feed
* proof point collection
* quote collection

**Comment by emily-johnson** [comment]
Update: sem and undergrad are done

**Comment by annmarieven** [comment]
ugh. we have to go back and update 2 things.

make sure ONLY the program name is tagged on event feeds. 
make sure ONLY the program name is tagged on news article feeds.

sorry em!

**Comment by emily-johnson** [comment]
Ok I think it's all done finally! :+1: :grinning:
