### ISSUE TITLE
Seminary Academic Program Feeds and Collections

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#546]
@emily-johnson can you go into /seminary/academics/ and make sure each program folder has the following 4 items:

event feed
news article feed
quote collection
proof point collection

Check existing ones to see naming structure, tags, feed/collection settings, etc.

Once they're created, link each one up to the program folder's index page.

Thanks!

**Comment by emily-johnson** [comment]
When creating an event feed, there are no Seminary program options, which is probably why none of the Sem programs have event feeds as of now.

@e-jameson @c-schwarze Can one of you add the Sem programs? Or are they not there for a reason?

**Comment by c-schwarze** [comment]
The seminary program options were in the edit/metadata portion of the event feeds. They should now be where the rest of the metadata is (inline).

**Comment by emily-johnson** [comment]
Awesome, thanks!

**Comment by emily-johnson** [comment]
Every sem program has all four items now, and they are linked to the index
