### ISSUE TITLE
GS Academics Leadership Foundations Certificate Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#547]
We'll launch on Monday. 
https://staging.bethel.edu/graduate/academics/certificates/leadership-foundations/

I will do testing on the most recent version of Safari and iOS 8 on iPhone 6.
@donowenskid can you proof this site and do testing on the most recent versions of Chrome and FF?

Migration grid: 
https://docs.google.com/spreadsheets/d/11K-MAuCwqoMSQuA5tQAMvcVxkqdjoRO8hFBeWrgq3qk/edit#gid=2015994949
 
Redirects:
Not in Silva. No redirects needed.

- [x] Close footprints job 14620
- [x] Tag analytics

**Comment by donowenskid** [comment]
Looks great in both Chrome and FF

**Comment by annmarieven** [comment]
Fixed news and event feeds. Tested on Safari and iPhone 6. Looking good!

Publishing now. No rules or redirects needed since it didn't exist in Silva before. Will add to the current certificate page.

**Comment by annmarieven** [comment]
Site launched, looks good!

**Comment by annmarieven** [comment]
@emily-johnson can you add this program to the certificate section on this page: http://gs.bethel.edu/academics/ (it's in silva)

once that's done and you've proofed it live and made sure the link works, you can close the issue. thanks!

**Comment by emily-johnson** [comment]
Done. I also removed Postsecondary Teaching from the certificates site since we no longer offer it.
