### ISSUE TITLE
apply.bethel.edu errors

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#548]
1. The form on the left hand side of this page is formatted strangely.

2. Going to this URL (https://www.bethel.edu/admissions/apply/?uid=false) should show an error message, it doesn't look like it is anymore.

**Comment by c-schwarze** [comment]
Looks like it was using jQuery. ill look into it

**Comment by c-schwarze** [comment]
1) @johjacb is updating the form classes

2) The jQuery has been updated.

**Comment by c-schwarze** [comment]
fixed.
