### ISSUE TITLE
Calendar links redirecting to Silva

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#549]
https://editor.its.bethel.edu/silva/seminary/academics/calendars/index/edit/tab_edit

The links on this page are supposed to lead to the calendar pages in cascade, but are redirecting to silva and therefore saying the page doesn't exist. Can you fix it? 

Thanks!

**Comment by e-jameson** [comment]
We are going to remove this redirect rule tomorrow, which will fix these issues.

**Comment by emily-johnson** [comment]
@e-jameson this is your reminder to create those individual redirects :) Thanks!

**Comment by emily-johnson** [comment]
@e-jameson You're off the hook! Peter was able to take care if it yesterday :+1:
