### ISSUE TITLE
Post Office Migration

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#550]
@emily-johnson can you take care of a few things before I proof the site?

Right now it looks like a lot of p tags have an extra class="p" but it should just be < p > (but with no spaces. I can't do the actual html or github thinks I'm coding stuff into the issue. :stuck_out_tongue: )

- [x] HTML clean up --- p tags, heading tags (h2 or h3), remove any &#160; code and replace it with a space
- [x] Check any times that they follow Bethel format - 9 a.m. instead of 9:00 a.m.
- [x] Check phone numbers for Bethel format (periods instead of dashes)
- [x] Remove any instances where all caps are used on the site
- [x] Link text rather than including the actual url on the pages
- [x] Write descriptions for each page - a short, one sentence description about what information is on the page (see other Cascade pages for examples)

**Comment by e-jameson** [comment]
You can do \`\<p\>\` to put in HTML tags (the fancy tick above ~) looks like this:

`<p>`

:)

**Comment by emily-johnson** [comment]
@annmarieven The totals in the table of intra-campus distribution numbers aren't right, but I don't know if the totals or the other values are wrong. Can we check what those numbers should actually be?

**Comment by emily-johnson** [comment]
I emailed the post office asking if they had updated numbers for the table

**Comment by emily-johnson** [comment]
I updated the table in cascade with the updated numbers from the post office

**Comment by c-schwarze** [comment]
Can this be closed?

**Comment by annmarieven** [comment]
assigning to @emily-johnson for redirects and site launch (if/when it's ready for that)

**Comment by emily-johnson** [comment]
@a-parrott can you take a look at the content? Then I'll go through all the steps to publish

**Comment by emily-johnson** [comment]
**Redirects:**
Rule:
https://bethelnet.bethel.edu/postoffice/ 
to
https://www.bethel.edu/post-office

**Launch To Dos:**
- [ ] Proof on Chrome, Firefox, Safari, and iOS 9.3.1 on iPhone 6
- [ ] Move site
- [ ] Redirect rule @e-jameson 
- [ ] Tag analytics
- [ ] Web author access
- [ ] Close and archive old site

**Comment by emily-johnson** [comment]
@e-jameson Ok, site is live (not archived), appears that there is a redirect rule, and multiple redirects in tinker, no web author

https://www.bethel.edu/post-office/

**Comment by emily-johnson** [comment]
Just went back and tagged analytics

**Comment by emily-johnson** [comment]
@vedmic Should we be setting up a web author for the Post Office?

Also, can I archive the old site?

**Comment by hamtim** [comment]
@emily-johnson you can archive the old site. They won't have a web author for now.
-t

**Comment by emily-johnson** [comment]
Oops, this is done! Closing
