### ISSUE TITLE
Missing Banner Data

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#551]
@emily-johnson can you go through this grid and take care of a few things? 
https://docs.google.com/spreadsheets/d/1zEs-6RFad9aTQVtVf1nsTd7RLxz3OwGj_WgwwJeah8Q/edit#gid=0

- [x] Add the program name next to each code
- [x] Indicate whether or not courses are pulling - may need to check multiple concentration pages if the program has concentrations (enter yes or no into the courses column)
- [x] Check the program block to see if we're getting data for each code (enter yes or no into the program details column)

**Comment by annmarieven** [comment]
One more thing - can you also add any codes that we have in blocks that aren't in the grid and fill out the program name, courses, and data for those as well?

**Comment by emily-johnson** [comment]
Done!
