### ISSUE TITLE
Videos on Event Pages

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#552]
I've added a block chooser so we can embed videos onto event pages.

Can someone make them appear just like event images do?

There's also a caption field which would be great if it appeared for either an image or a video.

Let me know if you need any more info from me.

**Comment by c-schwarze** [comment]
Here is a test: https://staging.bethel.edu/_testing/caleb-schwarze/events/acsd-student-leadership-conference

Also, a couple things:
1) If there is both a image and a video, it will default to a image.
2) images/videos currently only appear IF there is a 'event description'. Let me know if this needs to be changed.

**Comment by annmarieven** [comment]
great! tested and looks good.
