### ISSUE TITLE
remove jQuery from wufoo block

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#553]
After the change, we'll need to coordinate with @annmarieven about republishing all the pages with Wufoo blocks, and then coordinate with @johjacb about removing jQuery.

**Comment by e-jameson** [comment]
@annmarieven, this is ready for @emily-johnson to go through and publish/test all the pages with Wufoo blocks on them.

**Comment by emily-johnson** [comment]
Ok I went through and published everything (except for about/caps-gs because it wouldn't let me)

**Comment by emily-johnson** [comment]
Just kidding there are five more pages of blocks... haha I'll do that now

**Comment by emily-johnson** [comment]
Done!

**Comment by e-jameson** [comment]
@c-schwarze can you try and get a list of all the Wufoo blocks (https://cms.bethel.edu/entity/relationships.act?id=ba13cf0d8c586513100ee2a77e570c1c&type=structureddatadefinition) that have Use Preload set to "Yes".

**Comment by c-schwarze** [comment]
Unfortunately, Cascade's search doesn't allow for that to work. Only because the "Content" being searched is stored as "Yes", which would trigger the other thousand blocks with options set to "Yes"

**Comment by c-schwarze** [comment]
I was able to get the Cascade search to find all of the wufoo blocks and publish them automatically.

They are still being published at the moment.

**Comment by e-jameson** [comment]
I removed jquery from the body-end.php file and confirmed forms are working.

**Comment by e-jameson** [comment]
@emily-johnson, can you go through this again and publish everything just to make sure we got them all? We got a couple cases this morning about forms not working.

**Comment by emily-johnson** [comment]
Done republishing!
