### ISSUE TITLE
Purchasing Services Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#554]
We launched the purchasing site and everything looks good.

bethel.edu/purchasing

Now we just need a few redirects.

@e-jameson 
bethelnet.bethel.edu/purchasing -- > https://www.bethel.edu/purchasing
bethelnet.bethel.edu/purchasing/bus-request-form --> https://www.bethel.edu/purchasing/transportation/bus-request

@emily-johnson can you put these redirects in?
purchasing/stationery/ --> https://www.bethel.edu/purchasing/printed-materials/stationery/
communications-marketing/services/printed-materials/namebadge --> https://www.bethel.edu/purchasing/printed-materials/name-badges/
/communications-marketing/services/printed-materials/business-cards --> https://www.bethel.edu/purchasing/printed-materials/business-cards/
/communications-marketing/services/printed-materials/custom-envelopes --> https://www.bethel.edu/purchasing/printed-materials/stationery/custom-envelopes

Can you actually make sure all the namebadge, custom envelope, and business card pages and blocks get moved out of the comm site and either deleted (pages) or moved (blocks -- if they aren't already built) to the purchasing site?

**Comment by emily-johnson** [comment]
The redirects are done and I deleted the pages from the comm and marketing site

**Comment by annmarieven** [comment]
@emily-johnson can you also update the purchasing links in these 2 areas:
https://blink-cms.bethel.edu/channels/forms/bu-forms/edit/tab_edit -- bus request and name badge

https://blink-cms.bethel.edu/channels/offices-departments-programs/offices-departments/edit/tab_edit -- office sites g-z

**Comment by e-jameson** [comment]
@annmarieven, is `bethelnet.bethel.edu/purchasing -- > https://www.bethel.edu/purchasing` a rule or redirect? A rule would cover the second one, but are there things in bethelnet.bethel.edu/purchasing that sill need to be accessed?

**Comment by emily-johnson** [comment]
Just for the record, I did updated those links last week and updated the footprint case relating it

**Comment by e-jameson** [comment]
redirects are done

**Comment by annmarieven** [comment]
Everything's looking great!

**Comment by annmarieven** [comment]
@emily-johnson can you look into this broken button on this page? 

https://www.bethel.edu/purchasing/printed-materials/name-badges/

looks like the redirects aren't working.

**Comment by emily-johnson** [comment]
I changed the link to go straight to the new page in cascade, I'll look at the redirects again

**Comment by emily-johnson** [comment]
There was an error in the three redirects, but now they are fixed
