### ISSUE TITLE
Elective Course Description in Program Block

### ISSUE THREAD

**Issue by donowenskid** [betheluniversity/cascade#555]
Cascade putting the program description in the course description field in the program block.

Extra content is in the elective section on live page:
https://www.bethel.edu/graduate/academics/counseling-psychology/program-details/child-adolescent-counseling

Link to the program block:
https://cms.bethel.edu/entity/edit.act?id=9a5fe5928c58651357534482da2f5a44&type=block

**Comment by e-jameson** [comment]
Fixed, needs to be republished.
