### ISSUE TITLE
Staff listing block not working

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#557]
Can someone see why the staff listing block isn't working on this page?
https://www.bethel.edu/parents/contact/team/

thanks!

**Comment by c-schwarze** [comment]
Fixed. Kind of complicated.

The staff listing block was including 'basic' pages, which each included the 'staff-bio'.

Now staff listing blocks can include basic pages, which include 'staff-bio's

**Comment by annmarieven** [comment]
The pages should be going to the staff pages in the parent site though, not alumni.

Any thoughts there?

**Comment by annmarieven** [comment]
bethel.edu/parents/contact/jim and
bethel.edu/parents/contact/erin

**Comment by c-schwarze** [comment]
Oh. Sure. Updated.

**Comment by annmarieven** [comment]
Looks good!
