### ISSUE TITLE
Program block data confusion

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#558]
This page is pulling information from the higher education concentration instead of k-12 administration.

https://www.bethel.edu/graduate/academics/education-doctorate/program-details/k-12-administration

https://www.bethel.edu/graduate/academics/education-doctorate/program-details/higher-education

block:
https://cms.bethel.edu/entity/edit.act?id=9a60534e8c58651357534482f316a934&type=block

**Comment by e-jameson** [comment]
@annmarieven, this one is fixed. I had to change some code that I don't think should have been there, but could you spot check a few other programs to make sure they still look okay?

**Comment by annmarieven** [comment]
@emily-johnson can you spot check a few programs to make sure the data that's entered into the program block matches what's live on the concentration/program details pages?

**Comment by emily-johnson** [comment]
I looked at the special ed, mba and counseling psych concentrations and they all look good.
