### ISSUE TITLE
Social Media Links disappeared

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#559]
We used to have social media site features appear at the bottom of pages, if they were entered into the setup block.

They seem to have disappeared.

Block:
https://cms.bethel.edu/entity/open.act?id=ab3a30098c5865132a1de4efda4bc643&type=block&
Live site:
https://www.bethel.edu/dining-services/ (I just published the index page again to make sure it wasn't an issue that would be fixed with a republish)

Also, could we add instagram?

**Comment by e-jameson** [comment]
This page has social media links: http://screencast.com/t/F3bPAlGsKNF

**Comment by annmarieven** [comment]
oops. I forgot my blockers don't show the social media... my bad. sorry!
