### ISSUE TITLE
Add Instagram to Social Media & Adjust Spacing

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#560]
I added instagram to the data definition. Can we get that to appear on the bottom of sites if a url is entered?

Also, the icons look like they're almost touching the text. Can we get a little more space?

**Comment by e-jameson** [comment]
@johjacb I added instagram to this file. Not sure if our SVG file has an instagram icon or not, but I'm passing this to you to look at that and spacing.

**Comment by johjacb** [comment]
@annmarieven what is the url that you are looking at? 

@e-jameson instagram should already be in the file, its in our global footer

**Comment by annmarieven** [comment]
@johjacb bethel.edu/dining-services

**Comment by johjacb** [comment]
i added some space

**Comment by e-jameson** [comment]
i added Instagram to the site-features check and confirmed Dining Services is working in staging.

**Comment by emily-johnson** [comment]
I published the whole site to prod and let Chris know it was done.
