### ISSUE TITLE
Seminary Program Descriptions

### ISSUE THREAD

**Issue by a-parrott** [betheluniversity/cascade#561]
@donowenskid can you finish the last of the Seminary Program Descriptions? These would be: Mental Health Counseling, Ministry Practice, Theological Studies, and Transformational Leadership.

Please load the descriptions in the corresponding program blocks. Content for the descriptions can come from the homepage. 

Let me know if you have any questions. Thanks!

**Comment by donowenskid** [comment]
Sure! I'll take a look at it.

On Tue, Aug 11, 2015 at 2:39 PM, a-parrott <notifications@github.com> wrote:

> Assigned #561 <https://github.com/betheluniversity/cascade/issues/561> to
> @donowenskid <https://github.com/donowenskid>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/betheluniversity/cascade/issues/561#event-379566021>.
>



-- 
Chris Owen
Bethel University
Shipping/Receiving Clerk
Ext: 6481

**Comment by a-parrott** [comment]
@donowenskid how's this going? Any questions?

**Comment by donowenskid** [comment]
I should have these done this afternoon.

On Mon, Aug 17, 2015 at 11:25 AM, a-parrott <notifications@github.com>
wrote:

> @donowenskid <https://github.com/donowenskid> how's this going? Any
> questions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/betheluniversity/cascade/issues/561#issuecomment-131879078>
> .
>



-- 
Chris Owen
Bethel University
Shipping/Receiving Clerk
Ext: 6481

**Comment by a-parrott** [comment]
@donowenskid Great. Just load them to the corresponding program blocks when they're ready. Thanks!

**Comment by donowenskid** [comment]
@a-parrott...you got it!

**Comment by donowenskid** [comment]
@a-parrott Descriptions are loaded. Take a look and let me know if you have any thoughts or edits.

**Comment by a-parrott** [comment]
Thanks @donowenskid. 

This is done.
