### ISSUE TITLE
Update to maps/directions and instructions for guests on event pages

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#562]
We're going to create an automated link to our maps and directions page if someone chooses on campus for the location. This is going in the location field.

We're also going to create an Instructions for Guests field.

@a-parrott did you take notes about this and could you fill in any missing gaps?

@e-jameson where do we start?

**Comment by a-parrott** [comment]
Here's my notes on this:

If the event is on-campus then the location field will be auto-populated.
If it’s off-campus then the user has to write in the location. 

The location field will have the auto-populated info or the written in info

There will be a new Instructions for Guests field where users can write info about parking, for example.

**Comment by e-jameson** [comment]
Lets look at this after the maps/directions updates are done.

**Comment by c-schwarze** [comment]
Updated. Let me know what you think. A couple of tests on staging:

https://staging.bethel.edu/events/2015/admissions/degree-fair
https://staging.bethel.edu/events/2016/irondale-high-school-orchestra-concert-

**Comment by annmarieven** [comment]
Can we add a sentence that says "View maps and directions to ...." and then have the location with the link?

**Comment by c-schwarze** [comment]
Updated. Here is an example:

https://staging.bethel.edu/events/2015/african-america

**Comment by annmarieven** [comment]
Right now we have a 'location' field and a 'directions' field. Example: https://www.bethel.edu/events/2015/admissions/adult-undergrad-and-graduate-information-session

I changed the label of the maps and directions field to be, "Instructions for Guests" on this data definition: https://cms.bethel.edu/entity/open.act?id=ba13d00a8c586513100ee2a7ae9cca17&type=structureddatadefinition

Can we make sure that change takes place on the tinker event form and the live pages themselves?

**Comment by c-schwarze** [comment]
Done. All events will have to be republished to see this. Tinker is live.
