### ISSUE TITLE
Setup blocks and empty folders

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#563]
Can we change the way setup blocks pull content for the left hand nav? Can it skip over folders if there is no published content in it?

**Comment by c-schwarze** [comment]
I updated the nav to hide folders/pages if they have never been published. 

Cascade only knows if a page has ever been published. So if things get unpublished/published, then it will still show up in the nav. It would take a lot more work to check if the page is currently published or not. We could do it, but it would slow page load time.

Also, pages will have to get republished to have the updated nav. :(

**Comment by annmarieven** [comment]
Sounds good. Thanks @c-schwarze !
