### ISSUE TITLE
CAPS Academics B.S. in Finance Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#564]
Now that we're getting data, we are closer to launching this site.
https://staging.bethel.edu/adult-undergrad/academics/finance/

However, 2 major things before we can go live. There is no faculty on the faculty page cause no one is tagged. @hamtim what do you want to do about this? Also, should anyone review this site before we launch? Assigning to @hamtim before we do anything else.

@donowenskid want to give the site a final proof and do testing on Chrome?

I'll take care of Safari, Firefox, and iOS 8 on iPhone 6

Migration grid:
https://docs.google.com/spreadsheets/d/13YMTx5qrCCXtTerntuDIguVhKPH6mcQK0plCeaNbCh4/edit#gid=89710057

Redirects grid:
No redirects needed. Brand new program. Just create a short url. (on grid)

- [ ] Create floodlight tag
- [x] Close footprints job 14736
- [x] Tag analytics @emily-johnson 
- [x] Add program to caps.bethel.edu/academics, caps.bethel.edu/academics/bachelors, and bethel.edu/adult-undergrad/admissions/ @emily-johnson

**Comment by hamtim** [comment]
@annmarieven let's launch and we'll let Molly know when it's done.

As for faculty, can we tag Molly Wickam and then in my launch email to her, I'll tell her that she'll need to get more faculty.

**Comment by annmarieven** [comment]
@emily-johnson can you tag Molly Wickam and republish the faculty page?

**Comment by emily-johnson** [comment]
I tagged Molly and republished to staging

**Comment by annmarieven** [comment]
Molly just emailed asking about the status of this site. @donowenskid think we can proof today so we can launch on Monday?

**Comment by donowenskid** [comment]
Content proofed. Looks great in Chrome.

**Comment by donowenskid** [comment]
Closed issue on accident.

**Comment by annmarieven** [comment]
Looks good on Safari, Firefix, and iOS 8 on iPhone 6.

@donowenskid I assigned the FP job to you for updating the headline on the sell sheet. Could you update here as well?

**Comment by donowenskid** [comment]
Done.

**Comment by annmarieven** [comment]
@emily-johnson can you take care of the few things assigned to you and then reassign to me for the floodlight tag?

**Comment by annmarieven** [comment]
oh, and... the site is launched and looks great. woo!

**Comment by annmarieven** [comment]
Not marketing this program yet - no flood light tag.
