### ISSUE TITLE
Share to Facebook Widget

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#565]
Can we create a new block that allows people to share something to their Facebook account?

For example, the development office wants to have this feature on the confirmation page after someone makes a gift.

Let me know what you need from me to get started.

**Comment by e-jameson** [comment]
Before I do this... @annmarieven @johjacb is this something we can style so it looks good being its own block?

**Comment by annmarieven** [comment]
yes, let's make it a block.

**Comment by e-jameson** [comment]
@c-schwarze can you have a student look at this?

**Comment by e-jameson** [comment]
@c-varberg  can you start looking into this?

**Comment by c-varberg** [comment]
Alright I got a working prototype. Let me know if there is anything you want me to change. 

block is here - https://cms.bethel.edu/entity/open.act?id=b81c36428c58651314811f9c20474966&type=block&

test page is here - https://staging.bethel.edu/_testing/calebv/test

The article it shares will use the current page metadata to find a photo, description, title, etc...
If we want to be able specify what is shared I'll have to look into it more.

**Comment by c-varberg** [comment]
There are also a couple different styles for the button itself.
The little 'layout' drop down on this page lets you see all the styles.

https://developers.facebook.com/docs/plugins/share-button

**Comment by e-jameson** [comment]
@annmarieven can we close this?
