### ISSUE TITLE
Moving admissions forms to Cascade

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#566]
@emily-johnson can you move this form to Cascade?

https://www.bethel.edu/undergrad/admissions/enroll/deposit

It should live in the same exact spot in the Cascade site. Once the page has been published to production, proof/test it live (make sure the preload is working), and then close the Silva page.

Let me know if you have any questions!

**Comment by annmarieven** [comment]
Can you do these too?
https://www.bethel.edu/seminary/admissions/enroll -- it's preload as well.

https://www.bethel.edu/adult-undergrad/admissions/enroll  -- it's preload as well.

**Comment by emily-johnson** [comment]
Done!
