### ISSUE TITLE
Mission, Vision, and Values page in About site

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#568]
Put mission and vision content onto a new page.

System name: mission-vision
Title: Mission, Vision, and Values
Display name: Mission and Vision

Delete and redirect Values page to the new mission, vision, values page.

**Comment by annmarieven** [comment]
@emily-johnson can you touch base with me on this?

bethel.edu/about

**Comment by emily-johnson** [comment]
Content was updated, system name and display name were changed, redirect was created and site was published for the left hand nav change
