### ISSUE TITLE
Program block delivery option

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#569]
We need to add a sentence about evening classes for SemPM.

**Comment by annmarieven** [comment]
Added this sentence for SemPM.

"You'll meet for evening classes only at one of our convenient locations."

@c-schwarze do we need to do anything to get that to show up if it's selected?

data definition for program block:
https://cms.bethel.edu/entity/open.act?id=703ebc8d8c5865132395524d89bfaeb9&type=structureddatadefinition

live page example:
https://www.bethel.edu/seminary/academics/childrens-ministry/program-details/

**Comment by c-schwarze** [comment]
You should only need to republish the pages that will need to display "You'll meet for evening classes only at one of our convenient locations."
