### ISSUE TITLE
Seminary Academics M.A. in Children's and Family Ministry Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#571]
Getting ready to launch this site: 
https://staging.bethel.edu/seminary/academics/childrens-ministry/

We'll plan to launch Monday morning if everything goes well.

@donowenskid can you proof content, Firefox, and Chrome?
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=1353725850

Redirects:
https://docs.google.com/spreadsheets/d/1fS-qVFq0p6aF-ZDtYnhws4su8kZvhiMTqxZeTVoRszw/edit#gid=0

- [x] Create redirects @emily-johnson 
- [x] Close footprints job 13694
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
@e-jameson or @c-schwarze do you know why the teaching specialty is showing up on the faculty list but not on her actual bio page?

List: https://staging.bethel.edu/seminary/academics/childrens-ministry/faculty
Actual bio page with empty teaching specialty section: https://www.bethel.edu/academics/faculty/muir-kjesbo-denise

**Comment by c-schwarze** [comment]
Should be fixed!

**Comment by annmarieven** [comment]
wait.. I think there was some confusion.

We still want the teaching specialty section to show up on the listing page. Touch base with me if you're not sure :)

**Comment by c-schwarze** [comment]
Oh sure. Its back now :)

**Comment by donowenskid** [comment]
Proofed and edited content. "Visit Us" link directs to error in both chrome and FF:

"The directory which you have requested does not have an index file."

https://www.bethel.edu/seminary/admissions/events/

Everything else looks great.

**Comment by annmarieven** [comment]
Proofed on Safari and iOS 8 on iPhone 6.

Fixed the broken visit link.

Publishing now.

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
@emily-johnson can you do the redirects and short url and tag analytics?

Then reassign to me and I'll take care of the archiving the old site.

**Comment by emily-johnson** [comment]
Done!

**Comment by annmarieven** [comment]
Site launched. Looks good.

Old site archived.
