### ISSUE TITLE
Homepage Banner Features

### ISSUE THREAD

**Issue by a-parrott** [betheluniversity/cascade#572]
Features from the  /_homepages/www/www-text-over-media-collection are not filtering to the Undergrad homepage. I'm not sure where the Undergrad features currently on that page are coming from. 

The Seminary homepage is pulling a text-over-media block that is not part of the www-text-over-media-collection. That block is this one: https://cms.bethel.edu/entity/open.act?id=ec1569c48c5865137938fc88ebf441b6&type=block

Thanks!

**Comment by c-schwarze** [comment]
Closing. This moved to #573
