### ISSUE TITLE
Text Over Media Collections # of items order

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#573]
Can we change the order for the question that asks how many items should be displayed so that it shows them in order from newest to oldest?

Data definition: https://cms.bethel.edu/entity/open.act?id=03f3c1788c5865134b095345659b5d7f&type=structureddatadefinition&

**Comment by c-schwarze** [comment]
Updated so that it grabs the most recent instead of random. 

Also, published the 5 homepages so the affect is live.
