### ISSUE TITLE
Meta descriptions for program homepages

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#575]
@donowenskid can you take a look at each of our adult program homepage meta descriptions? I looked at a few and some are all over the place while others are missing completely.

This shows up in search engine results so they should be roughly 130-155 characters in length.

Let me know if you have any questions!

**Comment by annmarieven** [comment]
@donowenskid if this is done, can you close it?

**Comment by e-jameson** [comment]
@donowenskid ^ is this done?

**Comment by donowenskid** [comment]
@e-jameson  Let me sift back through this this week. I'll close it when it's done. Thanks for catching it.

**Comment by c-schwarze** [comment]
I'm just cleaning out the github queue. @donowenskid is this done?

**Comment by donowenskid** [comment]
Closing
