### ISSUE TITLE
Seminary Academics M.A. in Christian Thought Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#576]
Getting ready to launch this site: 
staging.bethel.edu/seminary/academics/christian-thought

We'll plan to launch Monday afternoon (pending approval from Jen).

@donowenskid can you proof content, Firefox, and Chrome?
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=883867518

Redirects:
https://docs.google.com/spreadsheets/d/1W-2RPq2T4ev1_nBv7LxtrAOlgyr0DUTWHlFDL43M0B4/edit

- [x] add main image
- [x] Create redirects @emily-johnson 
- [x] Close footprints job 13623
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
@emily-johnson can you check the news/events feeds? looks like they're pulling all news and events. update, republish the index to staging, and then mark the news/event feeds as done on the migration grid. could you also do the redirect grid for this program so we can launch on Monday? thanks!

**Comment by annmarieven** [comment]
@emily-johnson can you do the redirect grid for this one so we can launch Monday?

**Comment by emily-johnson** [comment]
Redirects doc is created and linked in the Seminary Programs Migration Grid

**Comment by annmarieven** [comment]
@emily-johnson can you go through the seminary proof points in the shared content folder and make sure they're all tagged appropriately? I'm seeing a children's ministry one showing up on christian thought. Adjust tags as needed, then go to the xml folder (in shared content) and publish the proof point xml page to production. Lastly, republish the christian thought site to staging :)

Thanks!

**Comment by annmarieven** [comment]
@emily-johnson can we pull this photo out of the header images and load it as the main image? 

Here's the link to the grid which hopefully has the link to the original Flickr photo: https://docs.google.com/spreadsheets/d/1xU2p1-aQfUgIZ2psK8tdSVEgYx0WZUyzvxFwYVtBV3Q/edit#gid=1259590273

It needs to be downloaded from Flickr, cropped to 16x9, compressed, and loaded into the images folder (not site-images) as 'christian-thought-main-image.jpg'. Then link it up to the program index page.

We'll need to delete the old photo out of Cascade and remove it from the site image bank block.

Let me know if you have any questions!

**Comment by emily-johnson** [comment]
Main photo is added and removed from the image bank

**Comment by donowenskid** [comment]
Edits done. Looks great on Chrome and FF.

**Comment by annmarieven** [comment]
Proofed on Safari and iOS 8. Fixed the faculty page. Sent to Jen for approval.

**Comment by annmarieven** [comment]
waiting for approval from Ken. @vedmic is touching base with Jen about who should approve and giving a deadline.

This most likely won't launch today.

**Comment by e-jameson** [comment]
rule is done.

**Comment by emily-johnson** [comment]
Redirects and analytics tag are done

**Comment by annmarieven** [comment]
Site launched. Looking good. Closing github
