### ISSUE TITLE
Seminary Academics M.A. in Marital and Family Therapy Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#577]
Getting ready to launch this site: 
https://staging.bethel.edu/seminary/academics/marital-family-therapy/

We'll plan to launch Tuesday morning (pending approval from Jen).

@donowenskid can you proof content, Firefox, and Chrome?
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=673133178

Redirects:
https://docs.google.com/spreadsheets/d/1_cU51dXwS3M1rb_LSbwND1revWtPGcGSFemOWpqsJiI/edit#gid=0

- [x] Add main image @emily-johnson 
- [x] Create redirects 
- [x] Close footprints job 13388
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by donowenskid** [comment]
Edits complete. Good to go on Chrome and FF

**Comment by annmarieven** [comment]
@emily-johnson can we use the photo of the guy and girl at the table as the main image?

Here's the link to the grid which hopefully has the link to the original Flickr photo: https://docs.google.com/spreadsheets/d/1xU2p1-aQfUgIZ2psK8tdSVEgYx0WZUyzvxFwYVtBV3Q/edit#gid=1259590273

It needs to be downloaded from Flickr, cropped to 16x9, compressed, and loaded into the images folder (not site-images) as '[PROGRAM-NAME]-main-image.jpg'. Then link it up to the program index page.

Let's also LEAVE the photo in the header images (since there are only 4 photos as it is.)

**Comment by emily-johnson** [comment]
Photo has been uploaded and added to the index spotlight

**Comment by donowenskid** [comment]
Edits complete. Looks great in Chrome and FF.

**Comment by annmarieven** [comment]
Looks good on Safari and iOS 8. 

The only thing I noticed is the proof point is still animating even though it's set to not. @c-schwarze can you take a look? https://staging.bethel.edu/seminary/academics/marital-family-therapy/
proof point: https://cms.bethel.edu/entity/open.act?id=ba137e948c586513100ee2a78b805db0&type=block_STRUCTUREDDATA

We're going to move forward with the launch but it'd be good to take a look at that issue.

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
Redirects are in. Site is live and looks good!

Keeping open for @emily-johnson to tag analytics and @c-schwarze to look at proof point animation.

**Comment by emily-johnson** [comment]
Analytics tag is done

**Comment by c-schwarze** [comment]
@c-varberg could you look at the proof point animation issue?

**Comment by c-varberg** [comment]
Proof points are working correctly on staging now. @annmarieven does anything else need to be done for this?

**Comment by annmarieven** [comment]
perfect! closing issue.
