### ISSUE TITLE
Proof Point - Text after

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#578]
@johjacb Can you look into making the text after even with the number in a number proof point? Ex: 
![number proof point](https://cloud.githubusercontent.com/assets/13204220/9551780/c9a8550e-4d78-11e5-96eb-21e969d16a76.png)
 (15 is the number and -20 is the text after).

Thanks!

**Comment by c-schwarze** [comment]
Could the text all be put in the "Number" field?

**Comment by emily-johnson** [comment]
Since it's a number proof point, it will only allow you to do the one number so only 15 shows up

**Comment by c-schwarze** [comment]
A possible solution is to put "15-" in the text before field and "20" in the Number field. 

Unless @johjacb has a fancy way to fix this.

**Comment by emily-johnson** [comment]
Oops! That's actualy what it's at now. 15 is text before and -20 is the number

**Comment by emily-johnson** [comment]
As far as I can tell, either way the -20 is higher

**Comment by annmarieven** [comment]
We confirmed that no matter what, the items aren't aligned.

**Comment by johjacb** [comment]
Should be better now, although not perfect. The odometer number gets special css.

I would recommend against trying to put part of the number in the suffix field. The fields are handled differently and could produce undesirable results. :sob:

**Comment by annmarieven** [comment]
just going to leave it for now.
