### ISSUE TITLE
Mobile device web issue

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#579]
Hi Eric, we received this email, could you look into the issue?
![image_20150830124213_512913](https://cloud.githubusercontent.com/assets/10466261/9586775/59dc2930-4fe4-11e5-9965-003322f364d4.jpg)

Attached is a jpg of what people see when they use an Ipad to look at our
department page. The rolling numbers that work on the desk top does not
work on the Ipad and the numbers state "zero." I tried on my smart phone
and the numbers do work. It seems to be a problem isolated to Ipad's.
(Chuck and I both tried it on our Ipads and both had the problem. )

Thanks!

**Comment by e-jameson** [comment]
@c-varberg if you get time could you look into this. I can give you more details and an iPad to test with.

**Comment by c-varberg** [comment]
@ale73233 I wasn't able to replicate the problem. I have been working on the proof point animation a little bit the last couple days, so it's possible I accidentally fixed it. Can you try it out again to see if everything is working for you?

**Comment by ale73233** [comment]
Do you have an iPad I could test it one?

**Comment by c-varberg** [comment]
No I don't sorry. I borrowed one from jacob

**Comment by annmarieven** [comment]
@ale73233 can you test on an ipad? Jake should have one for you to look at .

**Comment by annmarieven** [comment]
@c-schwarze if you're looking at the proof point section on a page and refresh it, the proof points won't animate. can you touch base with caleb or jmo on fixing this?

**Comment by annmarieven** [comment]
oops. mean to give this to @c-varberg

**Comment by c-varberg** [comment]
This should be working now. Skrollr wasn't fully initialized before the first check to see if proof points were on the page was done. This was throwing off the page height. I added a slight delay onto the check, so skrollr has a chance to finish. Everywhere I've tested it works now.

**Comment by johjacb** [comment]
@c-varberg i'm seeing white space at the bottom of some of the pages

https://www.bethel.edu/graduate/
https://www.bethel.edu/adult-undergrad/
https://www.bethel.edu/seminary/

**Comment by e-jameson** [comment]
@johjacb is this related to the fix Caleb put in? If it is, do you know what is causing the whitespace?
