### ISSUE TITLE
CAS Quicklinks

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#580]
https://bethelnet.bethel.edu/ureg/cas/

Can you remove the QuickLinks sub menu in the left hand nav and instead have it just link to this page: https://bethelnet.bethel.edu/ureg/cas/quick-links

**Comment by annmarieven** [comment]
This is done. @emily-johnson can you follow the steps that were taken in the job to make sure these links work? even within the blink iframe?

**Comment by emily-johnson** [comment]
Any of the links that aren't in Cascade (bethelnet.bethel or cas.bethel) weren't working unless I right-clicked and chose to open it in a new tab. I changed all of the links to open in a new window and now they all work.
