### ISSUE TITLE
Seminary Academics M.A. in Mental Health Counseling Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#581]
Getting ready to launch this site: 
http://staging.bethel.edu/seminary/academics/mental-health-counseling

Not sure when we're launching.. with the roar day site and my absence on Thursday/Friday of this week.

@donowenskid can you proof content, Firefox, and Chrome?
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=237187200

Redirects:
https://docs.google.com/spreadsheets/d/1L-Zz3vjLZaTcgC6Cl4XyD42pB_Vskhra49WspGUyQdw/edit#gid=0

- [x] Add main image @emily-johnson (let's do the one with the 3 guys in a row in class. keep it in the header images too)
- [x] Create redirects @emily-johnson 
- [x] Close footprints job 13386
- [x] Tag analytics @emily-johnson 
- [ ] Close and archive old site

**Comment by donowenskid** [comment]
Edits complete. Good to go in Chrome and FF.

**Comment by annmarieven** [comment]
@emily-johnson can you take care of the main image today? We'll shoot for launching tomorrow.

**Comment by e-jameson** [comment]
rule is done.

**Comment by emily-johnson** [comment]
Main image, redirects and analytics tag are done!

**Comment by annmarieven** [comment]
Site launched. Everything looks good!
