### ISSUE TITLE
Auto publishing adult programs

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#582]
We need to do a few things before we can turn autopublishing on.

- [x] Set up automated email when blocks don't have data
- [x] Adjust program details section on program index page
- [x] Adjust actual program details page

Details about each item below:

**Automated email**
Send to: l-gupta@bethel.edu, s-baumgardner@bethel.edu, emily-jensen@bethel.edu
Subject: No Banner Data Found
Take out the part of each line that says 'in block _shared-content.....'
Add a sentence at the top that says, "The following program codes no longer have banner data associated with them. The live websites now have a message about no cohorts being scheduled. Please address these immediately."

**Index page - program details section**
Remove the location and delivery fields if no data is being delivered

**Program details page**
Keep the white background but put this text in place of the delivery information. 2 options here. @hamtim can you weigh in?
"There are no cohorts scheduled at this time."

OR
"We are in the process of assembling cohorts for this program. Please check back for further details, or contact an admissions advisor with any questions." [admissions advisor would link to either https://www.bethel.edu/adult-undergrad/admissions/advisors/ or https://www.bethel.edu/graduate/admissions/advisors/]

**Comment by e-jameson** [comment]
@c-schwarze can you look at making these other two changes? These changes are for if there is no "Banner Data" in a block.

**Comment by c-schwarze** [comment]
@annmarieven I updated these changes. I used the "There are no cohorts scheduled at this time" option. Let me know if anything needs to change.

**Comment by e-jameson** [comment]
@annmarieven can we close this?

**Comment by annmarieven** [comment]
@c-schwarze per a request from admissions, we have to change the text in the white block on the program details page when there is no banner data.

For graduate program pages can it say:
Please contact admissions at 651.635.8000 or graduate-admissions@bethel.edu for more information on start dates.

For caps program pages can it say:
Please contact admissions at 651.635.8000 or adult-undergrad-admissions@bethel.edu for more information on start dates.

Let me know if you have any questions for me :)

**Comment by c-schwarze** [comment]
Do you have any that I could test?
