### ISSUE TITLE
Undergrad Homepage Banner Features

### ISSUE THREAD

**Issue by a-parrott** [betheluniversity/cascade#583]
The undergrad homepage banner feature block needs to pull the most recent 5 CAS features. Right now there's only 4 features on the page.

https://cms.bethel.edu/entity/open.act?id=c173ad978c5865132802f1614d009134&type=page

**Comment by c-schwarze** [comment]
@c-varberg could you look at this when you have a chance?

**Comment by c-varberg** [comment]
should be fixed now. It looks like I can't publish to the live page though.

**Comment by a-parrott** [comment]
Looks good!
