### ISSUE TITLE
CAPS Academics Human Resource Management Certificate Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#584]
Getting ready to launch this site: 
https://staging.bethel.edu/adult-undergrad/academics/certificates/human-resource-management/

We'll plan to launch mid next week.

@donowenskid can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/18NizqD2T-hDa2fx3tC9DHXMuEEK2Up65DtcPJh95nrM/edit#gid=1418805418

Redirects:
https://docs.google.com/spreadsheets/d/1X94bPsFV0xww3qvrh163d3d_mJnvPEZBe0ZG9N3UczE/edit#gid=0

- [x] Use site image bank from human services program site @emily-johnson 
- [x] Close footprints job 14723
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by emily-johnson** [comment]
@annmarieven It looks like you created the migration grid on June 1: https://docs.google.com/spreadsheets/d/1X94bPsFV0xww3qvrh163d3d_mJnvPEZBe0ZG9N3UczE/edit#gid=0

**Comment by donowenskid** [comment]
Looks great in Chrome and FF.

**Comment by annmarieven** [comment]
everything looks good for me except the site image bank isn't showing up. @c-schwarze could you look into this for me?

**Comment by c-schwarze** [comment]
Republishing https://staging.bethel.edu/adult-undergrad/academics/certificates/human-resource-management/ fixed the image bank issue.

**Comment by annmarieven** [comment]
whaaaat???? i did that!!!! dumb cascade.

**Comment by e-jameson** [comment]
rule is done.

**Comment by annmarieven** [comment]
Site is live and redirects are in. @emily-johnson can you tag analytics?

**Comment by emily-johnson** [comment]
Tag is done.
