### ISSUE TITLE
CAPS Academics Addiction Studies Certificate Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#585]
Getting ready to launch this site: 
https://staging.bethel.edu/adult-undergrad/academics/certificates/addiction-studies

We'll plan to launch mid next week.

@donowenskid can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/18NizqD2T-hDa2fx3tC9DHXMuEEK2Up65DtcPJh95nrM/edit#gid=1142176740

- [x] Use site image bank from graduate/counseling-psychology program site @emily-johnson 
- [x] Close footprints job 14441
- [x] Tag analytics @emily-johnson 

This site didn't exist in Silva so there was no rule, redirects, or archiving.

**Comment by emily-johnson** [comment]
@annmarieven According to this migration grid (https://docs.google.com/spreadsheets/d/18NizqD2T-hDa2fx3tC9DHXMuEEK2Up65DtcPJh95nrM/edit#gid=1093195317) we don't need redirects because it wasn't in Silva

**Comment by donowenskid** [comment]
Good to go in FF and Chrome. No edits.

**Comment by annmarieven** [comment]
This certificate is actually called "Addiction Studies Certificate" -- @donowenskid can you go through and make the changes to the site before we launch?

We'll need to change the system name of the folder as well, which will require an unpublish and republish. Let me know if you have questions about that. 

I also need to change the metadata so everything will need to be retagged.

**Comment by annmarieven** [comment]
new url: https://staging.bethel.edu/adult-undergrad/academics/certificates/addiction-studies

**Comment by annmarieven** [comment]
Changed the name on the site and in the metadata. Retagged program block, all feeds in the site, and the program pages that have tags.

Will proof in Safari and then launch.

**Comment by annmarieven** [comment]
@emily-johnson can you tag analytics and then close this issue?

**Comment by emily-johnson** [comment]
Tag done.
