### ISSUE TITLE
Seminary Academics M.A. in Marriage and Family Therapy Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#586]
Getting ready to launch this site: 
https://staging.bethel.edu/seminary/academics/marriage-family-therapy/

@donowenskid can you proof content, Firefox, and Chrome?
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=673133178

Redirects:
https://docs.google.com/spreadsheets/d/1KQj6HRSgxQpJoOL7O1nYPzEORmyQuXqwwqyGaThC46U/edit#gid=0

- [x] Add main image 
- [x] Create redirects 
- [x] Close footprints job 13490
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by donowenskid** [comment]
Good to go. Edits complete...looks great in Chrome and FF.

**Comment by annmarieven** [comment]
desktop Safari and mobile Safari on iOS 8 on iPhone 6 looks good.

ran into issue with proof points which @c-schwarze is looking at.

**Comment by annmarieven** [comment]
proof point issue fixed. ready for the rule @e-jameson !

**Comment by e-jameson** [comment]
rule is done.

**Comment by annmarieven** [comment]
Site done launching! Keeping open for @emily-johnson to tag analytics and me to archive the old site.

**Comment by emily-johnson** [comment]
Tag done

**Comment by annmarieven** [comment]
Closing issue.
