### ISSUE TITLE
Seminary Academics M.A. in Transformational Leadership Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#587]
Getting ready to launch this site:
https://staging.bethel.edu/seminary/academics/transformational-leadership/

@donowenskid can you proof content, Firefox, and Chrome?
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=1843370763

Redirects:
https://docs.google.com/spreadsheets/d/1PmKv2X4e2qZr31mL-aVlRvOOPr2k991QssoVsIcqXnI/edit#gid=0

- [x] Add main image 
- [x] Create redirects 
- [x] Close footprints job 13503
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
Looks good on desktop safari and mobile safari on iOS 8 iPhone 6.

**Comment by donowenskid** [comment]
Good to go in Chrome and FF. No edits.

**Comment by e-jameson** [comment]
rule is done

**Comment by annmarieven** [comment]
Site launched! Keeping open for tagging analytics and archiving the old site.

**Comment by emily-johnson** [comment]
Tag done

**Comment by annmarieven** [comment]
Archived old site. Closing issue.
