### ISSUE TITLE
Seminary Academics M.A. (Theological Studies) Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#588]
Getting ready to launch this site:
https://staging.bethel.edu/seminary/academics/theological-studies/

@donowenskid can you proof content, Firefox, and Chrome?
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=2051097123

Redirects:
https://docs.google.com/spreadsheets/d/1qY12CGg0BV1pahvKUT36NeshVBk3pW9q2Tats3nkh3s/edit#gid=0

- [x] Add main image 
- [x] Create redirects 
- [x] Close footprints job 13780
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by donowenskid** [comment]
Great in Chrome and FF

**Comment by annmarieven** [comment]
desktop Safari and mobile Safari on iOS 8 on iPhone 6 look good.

**Comment by e-jameson** [comment]
rule is done.

**Comment by annmarieven** [comment]
Site launched! Keeping open for analytics tag and archiving old site.

**Comment by emily-johnson** [comment]
Tag is done

**Comment by annmarieven** [comment]
Archived old site. Closing issue.
