### ISSUE TITLE
Check for bad email address

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#589]
@c-varberg can you add a javacript check to this form, before its submitted, to make sure email is in a correct format? If you want to get super fancy you can just disable the button and show an error alert if its  not valid, rather than making them press submit and having an alert. 

Format: https://cms.bethel.edu/entity/open.act?id=6e21e2a58c5865137ec8ee9de97cf8f5&type=format&

Page: https://staging.bethel.edu/admissions/apply/

**Comment by c-varberg** [comment]
I updated it to check for this regex
/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i
It seems to be accepted on the googles. 

I published the page. Everything is working. I even accidentally applied for Bethel
