### ISSUE TITLE
Seminary Academics M.A. in Ministry Practice Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#590]
Getting ready to launch this site: 
http://staging.bethel.edu/seminary/academics/ministry-practice

@donowenskid can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=1750158536

Redirects:
https://docs.google.com/spreadsheets/d/12Z7aVhRK9Z2swN5BRe4K69JAYDbkfGV1Ehmyl_m6Myk/edit#gid=0

- [x] Add main image (Monday)
- [x] Create redirects @ale73233 
- [x] Close footprints job 13778
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
Looks mostly good on desktop Safari and mobile Safari on iOS8 on iPhone 6.

Noted to @johjacb that there is a little extra spacing between the carousel and the headlines.

**Comment by donowenskid** [comment]
Great! GTG on FF and Chrome

**Comment by e-jameson** [comment]
rule is done

**Comment by ale73233** [comment]
redirects done

**Comment by annmarieven** [comment]
This site is live. Keeping issue open for a few additional things on Monday.

**Comment by emily-johnson** [comment]
Tag is done

**Comment by annmarieven** [comment]
Archived old site. Closing issue.
