### ISSUE TITLE
Seminary Academics Master of Divinity Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#591]
Getting ready to launch this site: 
https://staging.bethel.edu/seminary/academics/divinity/

@donowenskid can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=533167092

Redirects:
https://docs.google.com/spreadsheets/d/1_dGqhNzaP2FgdOP-B9lVH1N232mhZvKXjMaDLsc2AFw/edit#gid=0

- [ ] Add main image
- [x] Create redirects @ale73233 
- [x] Close footprints job 13735
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
looks good on desktop Safari and mobile Safari on iOS 8 on iPhone 6

**Comment by donowenskid** [comment]
Done. GTG

**Comment by e-jameson** [comment]
rule is done

**Comment by emily-johnson** [comment]
Tag is done

**Comment by annmarieven** [comment]
@emily-johnson can you pull this photo out of the carousel and put it as the main image?
https://cdn3.bethel.edu/resize/unsafe/800x0/smart/https://www.bethel.edu/seminary/academics/divinity/images/site-images/student-discusses.jpg

walk @kathrynmagnuson through it so she knows how to do it on the other githubs I've assigned to her.

Close the issue when you're done.

**Comment by annmarieven** [comment]
@emily-johnson and @kathrynmagnuson, where are we with this?

**Comment by annmarieven** [comment]
@e-jameson just got a request about this and am wondering if the 2nd rule got missed. can you put it in? here's the grid: https://docs.google.com/spreadsheets/d/1_dGqhNzaP2FgdOP-B9lVH1N232mhZvKXjMaDLsc2AFw/edit#gid=0&vpid=A1

**Comment by e-jameson** [comment]
done.

**Comment by e-jameson** [comment]
nvm there is a checkbox open still.

**Comment by annmarieven** [comment]
@kathrynmagnuson and @emily-johnson looks like this github got missed. review the previous descriptions and close the issue when it's done.

thanks!

**Comment by emily-johnson** [comment]
Oops! I'll add the main image now and walk Kathryn through it

**Comment by emily-johnson** [comment]
Done!
