### ISSUE TITLE
Seminary Academics Doctor of Ministry Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#592]
Getting ready to launch this site: 
https://staging.bethel.edu/seminary/academics/doctorate-ministry/

@donowenskid can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/a/bethel.edu/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=1484608204

Redirects:
https://docs.google.com/spreadsheets/d/1sDCd4dUa398zkNGwJ0WUPM54H_FPWwa1k2CqtDRBkpI/edit#gid=0

- [x] Add main image
- [x] Create redirects @emily-johnson 
- [x] Close footprints job 13696
- [x] Tag analytics @emily-johnson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
@donowenskid just realized we need descriptions for each page in the program details folder. they'll be added to the program block.
https://staging.bethel.edu/seminary/academics/doctorate-ministry/program-details/

**Comment by donowenskid** [comment]
@annmarieven program block is updated. descriptions are included in staging.

**Comment by annmarieven** [comment]
Oops. Just looked through the whole site in Chrome already. So, Chrome is good!

**Comment by annmarieven** [comment]
desktop Safari and mobile Safari in iOS 8 iPhone 6 look good.

**Comment by donowenskid** [comment]
Edits done. GTG in Chrome and FF.

**Comment by e-jameson** [comment]
rule is done.

**Comment by a-parrott** [comment]
Redirects done.

**Comment by emily-johnson** [comment]
I loaded the main image in Cascade, I'll have to go back and publish it when we turn it back on

**Comment by annmarieven** [comment]
@emily-johnson can you do 2 things here?
finish the image thing you were referring to above and can you also copy and paste folders from here:
http://zope6.its.bethel.edu:8080/silva/seminary/academics/st-paul-programs/doctorate-ministry/edit/tab_edit
to here:
http://zope6.its.bethel.edu:8080/silva/archive/seminary/academics/st-paul-programs/doctorate-ministry/edit

apparently the publication was too big so we have to cut and paste folder by folder. once the folder is empty in the first spot and everything is moved over, delete the original folder.

let jmo know if you have any questions.

then you can close the issue :) thanks!

**Comment by emily-johnson** [comment]
I published the main image and @e-jameson archived the site (I didn't have the right IP address)
