### ISSUE TITLE
GS Academics Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#593]
We need to finish migrating the root of the gs academic sites.

Can you take a look at the content on these pages and revamp as needed? This hasn't been touched in a while so it's probably not in our updated brand or anything.
http://gs.bethel.edu/academics/masters/
http://gs.bethel.edu/academics/doctorate/
http://gs.bethel.edu/academics/certificates/
http://gs.bethel.edu/academics/licensures/

Some of the GS pages have been built out already here: https://cms.bethel.edu/entity/open.act?id=d1cf51ae8c58651314811f9ce7130352&type=folder&

**Comment by annmarieven** [comment]
If this could be done by Thursday, October 1, that'd be great!

**Comment by donowenskid** [comment]
Masters, doctorate, and certificate content is updated. Licensure content is great. Left it alone.

**Comment by annmarieven** [comment]
GS Academics is live!

Here's the google doc in case anyone wants to reference anything:
https://docs.google.com/spreadsheets/d/1C1IXgA2jgj0V2_mONHispe90NW7voEbAzXe7UOm28O4/edit#gid=1990816065

@c-schwarze is putting the rule in.

**Comment by annmarieven** [comment]
one thing to look at. the faculty page doesn't appear to be pulling all faculty: 
https://cms.bethel.edu/entity/open.act?id=01db519a8c5865137c9c2c89ffff67a7&type=page

once this is fixed, the issue can be closed.

**Comment by c-schwarze** [comment]
Fixed.

**Comment by ale73233** [comment]
404 error:
https://www.bethel.edu/graduate/academics/counseling-psychology/program-details/child-index
https://www.bethel.edu/graduate/academics/education-k12index
https://www.bethel.edu/graduate/academics/special-education/program-detaindex
https://www.bethel.edu/graduate/academics/mba/prindex
https://www.bethel.edu/graduate/academics/education-doctorate/program-detindex
500 internal server error:
https://www.bethel.edu/graduate/academics/certificates/nurse-educator/index

**Comment by c-schwarze** [comment]
Try republish the page that has those links

**Comment by ale73233** [comment]
I published it an they work now.
