### ISSUE TITLE
CAPS Academic Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#594]
We need to finish migrating the root of the caps academic sites.

Can you take a look at the content on these pages and revamp as needed? This hasn't been touched in a while so it's probably not in our updated brand or anything.
http://caps.bethel.edu/academics/bachelors/
http://caps.bethel.edu/academics/certificates/
We'll actually need a license page for caps as well because of the new Alcohol and Drug Counseling License site.

The CAPS pages are here: https://cms.bethel.edu/entity/open.act?id=9c622b9a8c5865132a1de4ef3c48c2e3&type=folder&

**Comment by annmarieven** [comment]
If this could be done by Thursday, October 1, that'd be great!

**Comment by a-parrott** [comment]
Associates, Licenses, and Certificates are here: https://cms.bethel.edu/entity/open.act?id=3dd2cbe28c5865135795f1afd550f9e7&type=folder&

The Bachelor's page was already created, so revised content is in the academics folder.

**Comment by ale73233** [comment]
checked all of the links and they all work.

**Comment by annmarieven** [comment]
caps site is live. closing issue.
