### ISSUE TITLE
STEM/TESOL left hand nav/block issues

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#595]
Hi Eric,

We recieved an issue today Job # 15821: (she created the TESOL minor on a basic page, and not on a major minor page, could that be why these webpages are pulling the two minors?)

Over the summer, I added the STEM minor to the Education department. Today
I created a Basic page to feed in TESOL minor information (from Modern
World Languages).

Both minors appear in the left-hand navigation of the Education site pages,
except on the Majors and Minors page.

Only STEM appears on the index page block:
https://www.bethel.edu/undergrad/academics/education/

Neither appear on the Majors and Minors page, either in the left-hand nav
or on the block:
https://www.bethel.edu/undergrad/academics/education/majors-minors/.

I republished the whole site to see if that would help, but it doesn't
appear to have done so.

**Comment by c-schwarze** [comment]
Updated and Published to staging. For whatever reason, our format disappeared. I pieced it together, but it might not be the most current edition of the major/minor table.

@ale73233 could you make sure that the pages are good to go before publishing to production?

Thanks a bunch!

**Comment by ale73233** [comment]
This page still isn't showing the TESOL minor: https://www.bethel.edu/undergrad/academics/education/
but the other page looks good.

**Comment by c-schwarze** [comment]
@c-varberg could you look at this?

**Comment by c-varberg** [comment]
Should be working now. I ended up switching the TESOL to a major minor page as one of the formats requires there to be a program-type which basic pages don't have. Let me know if that causes any problems.
