### ISSUE TITLE
Conference and Event Services Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#596]
Launching this site:
https://staging.bethel.edu/conference-event/

No new features so proofing on different browsers or devices isn't vital.

Redirects grid:
https://docs.google.com/spreadsheets/d/17j-8WzizMAIZGELGylz8nfxqAgbd6_Ah3H1yDsJiL_s/edit#gid=0

Rule:
https://www.bethel.edu/conference-services/ TO https://www.bethel.edu/conference-event/

- [x] Redirects
- [x] Close old site
- [x] Update link on offices list
- [x] Tag analytics

**Comment by e-jameson** [comment]
rule is done.

**Comment by annmarieven** [comment]
will assign to Kathryn tomorrow when she creates a github account. for tagging analytics and doing these updates:
https://docs.google.com/spreadsheets/d/17j-8WzizMAIZGELGylz8nfxqAgbd6_Ah3H1yDsJiL_s/edit#gid=0

**Comment by annmarieven** [comment]
@kathrynmagnuson can you take a look at this? (see previous description)

**Comment by kathrynmagnuson** [comment]
A couple of things: 
1. I can't change "Conference Services to be Conference and Event Services (linking to index page)"
2. For https://www.bethel.edu/marketing/resources/ it says to remove Events completely, can you check on that?

**Comment by annmarieven** [comment]
@kathrynmagnuson can you clarify what you mean by #1 here? Also, can you tag the analytics? We launched on Sept 24.

**Comment by kathrynmagnuson** [comment]
I have no idea what I meant by the first thing...analytics are tagged.

**Comment by annmarieven** [comment]
Can you look back at the google doc i included on Sept 24 and make sure everything there is updated? If that's all taken care of, reassign the issue back to me.

Can you also update the conference link on this page? https://www.bethel.edu/offices

**Comment by annmarieven** [comment]
archived the old site.

@kathrynmagnuson I don't think the link is updated on the bethel.edu/offices page. Once that's done, can you check the box at the top of this issue and then close it?
