### ISSUE TITLE
New Faculty Job Titles

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#597]
- [x] 1) Update Data Def (AMV)
- [x] 2) Tinker Sync (Caleb)
- [x] 3) Update Tinker Form (by Oct. 6) (Caleb)
- [ ] 4) Faculty make changes (AMV)
- [ ] 5) Update Faculty Formats (Caleb)
- [ ] 6) Fix Data Def again (AMV)

@c-varberg When you get the list of faculty with only 1 job title/school/department, post the staging.bethel.edu url here. Thanks!

**Comment by c-varberg** [comment]
Heres the list
https://staging.bethel.edu/_testing/calebv/facultybiolistpage

**Comment by annmarieven** [comment]
@ale73233, @emily-johnson, and @kathrynmagnuson can you start working through the list of faculty above?

we need to plug in the school, department, and job title, into the "Job Title -- NEW" fields in Cascade.

If their existing job title is "something AND something else",  we'll need to create 2 job titles in the NEW section. (ex: Rollin King is "Professor and Chair of Chemistry")

There's a TON here so maybe let's do the first couple together before we tackle them all.

**Comment by annmarieven** [comment]
@ale73233 how did this go yesterday? did you run into any questions?

**Comment by ale73233** [comment]
I had question, for example like Rollin King, I enter in the school (CAS) and department (Chemistry) but no field should up for his job title?

**Comment by ale73233** [comment]
And are we supposed to just submit them, or publish them at all?

**Comment by c-schwarze** [comment]
@annmarieven  The faculty bio data definition seems to be broken. Maybe we should remove the new job titles section, and try again?

**Comment by annmarieven** [comment]
dang. okay. i'll try that.

**Comment by annmarieven** [comment]
@ale73233 publish them as you make the change. here's a few more rules since we turned the smart fields off (which auto showed or hid certain fields).

Choose school
Choose ONE program out of ONE school program drop down. Leave the rest of the school program fields blank.
If CAS -- answer dept. chair question.
If CAPS or GS -- answer program director question
If SEM -- answer 'for this program i am the...'
If NO or OTHER for any of the above questions -- enter something into job title field (don't put anything in here if you answered YES or selected LEAD FACULTY/PROGRAM DIRECTOR)

Do a few, publish them, and then put the live urls in here so I can review before you keep going. Thanks!

**Comment by annmarieven** [comment]
Lauren Pareigat said the Department Chair title isn't showing up in the faculty bio list. Can we change that so it does?

**Comment by annmarieven** [comment]
@kathrynmagnuson will you look at my comment to allie on oct. 21 and start on 1 or 2 of these?

**Comment by kathrynmagnuson** [comment]
https://staging.bethel.edu/academics/faculty/king-rollin We made the switch on the job title fields, but the job title is broken.

**Comment by kathrynmagnuson** [comment]
Did these bios: Rollin King, Ashley Mahoney, Trey Maddox, Matthew Neibergall, Wade Neiwert, Ken Rohly, Brandon Winters, Chuck Hannema, Rudy Cardona, Tim Essenburg, Leo Gabriel, Mary Ann Harris, Brian Holland, Joyce LeMay, Dmitri Medvedovski, Jay Milbrandt, Bruce Olsen, Bethany Opsata, Kirk Freeman, Amanda Hamilton, Jessica Henderson, Wayne Roosa, Kenneth Steinbach, Lex Thompson, Michelle Westmark, Jeff Wetzig, Meg Zauner, Brent Adams, Rick Rees, Adam Johnson, Ruth Nelson, Katherine Nevins

**Comment by ale73233** [comment]
I did up through g-w carlson, and we can publish them now!

**Comment by ale73233** [comment]
I did up through michael holmes skipped jolene pearson, andrew gess

**Comment by kathrynmagnuson** [comment]
@annmarieven I can explain any/all of this on Monday. 
1). Skipped Susan Brooks (not sure how to format her 4 job titles)
2). Mark Bruce and Susan Brooks are Co-Chairs of the English Department, should they both be labeled as "Department Chair"? 
3). Daniel Ritchie in the English Department is the "Western Humanities Program Director" (not sure how to label that; didn't publish to production) 
4). Jessica Samens is "Instructor in Communication Studies" and "Assistant Director of Forensics" (which department?) 
5). Christopher Carroll & Janet Johnson are listed under Athletic Training & Biokinetics, but only have job titles for Biokinetics 
6). Check on formatting for Athletic Training/Biokinetics department (their titles are super long...) 
7). Did through Janet Johnson

**Comment by ale73233** [comment]
skipped chad osgood
skipped greta schutte (not sure how to do assistant athletic trainer)
skipped christine osgood (adjunct faculty?)
skipped mark anderson (multiple job titles)
skipped diane strike (multiple job titles in grad school)
skipped Jay Tracy (LP)
Skipped sara werner (LP, RPT-S)?
did up through john hite

**Comment by kathrynmagnuson** [comment]
skipped:
Steve Kaatz ("retired") 
Don Johnson (no department listed)
Alex Chan (no department listed)
Ngozi Mbibi (no school or department listed, name in directory is Ngozi Martin-Oguike)
Jodi Baker (no department listed)
Kari Christensen (no department listed)
Gregory Nelson (no department listed)
Janet Nelson (no department listed)
Jeff Overlie (no department listed, "recent faculty" but still in directory)
Shawn Suave (job title "none," listed as adjunct in directory, name spelled "Sauve" in directory)
Ron Hultgren ("recent faculty" but still in directory) 
note:
weird formatting on Mary Jensen's page (no individual school, just Bethel University, puts in extra punctuation)

**Comment by ale73233** [comment]
skipped philippe gagnon
skipped:
diana olsen
shelby reigstad
john kantke
jim stern
did up to laurel mckeever

**Comment by ale73233** [comment]
skipped justin irving

Finished!!!! :)))))))

**Comment by emily-johnson** [comment]
@ale73233 The programs got lost, so we now have to go in and look at the previous version, see what program they are a part of, and then go in and tag it. We are going through the list in the same way as before.

Kathryn or I can show you how to do it quick next time you're in

**Comment by kathrynmagnuson** [comment]
Looked at all of them through Jolene Pearson. Her page is tagged as CAS but it's not showing up

**Comment by emily-johnson** [comment]
@kathrynmagnuson @ale73233 Just a note, Eric reminded me to make sure we aren't sending the bios through a workflow when we submit them

**Comment by c-schwarze** [comment]
I just did Carrie Peffley through Laura Zukanoff.

**Comment by c-schwarze** [comment]
I have updated all of the programs for these. We shouldn't have to edit these anymore!

**Comment by emily-johnson** [comment]
All of them? How!? :D

**Comment by c-schwarze** [comment]
Many hours...

**Comment by c-schwarze** [comment]
I'm going to close this for now. Open if any issues come up!
