### ISSUE TITLE
Duplicating Course Descriptions

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#600]
There is a description for the core courses but not the following 3. However, Cascade is pulling the description from the core courses and just duplicating it for the following 3.

live page:
https://www.bethel.edu/adult-undergrad/academics/human-services/program-details/

block:
https://cms.bethel.edu/entity/open.act?id=9a5db2398c586513575344824dad9aa8&type=block&

**Comment by c-schwarze** [comment]
Fixed. Its kinda funky that there are 3 different "Choose one from:" sections, that each only have 1 course.

**Comment by e-jameson** [comment]
@annmarieven can we close this?

**Comment by annmarieven** [comment]
beautiful. thanks folks.
