### ISSUE TITLE
Remove credit sentence from CAPS Associate Programs

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#602]
Can you remove this sentence from the CAPS Associates Program: "You need to have 60 credits to start this program." Only CAPS bachelor programs should have it. 

Here are the links:
Associate of Arts
<https://www.bethel.edu/adult-undergrad/academics/associates/program-details/associate-arts>&
the Associate of Science
<https://www.bethel.edu/adult-undergrad/academics/associates/program-details/associate-science>

**Comment by c-schwarze** [comment]
Sure thing. They are updated and republished.

Let me know if anything else needs to be changed, thanks!
