### ISSUE TITLE
GS Academics Child and Adolescent Mental Health Certificate Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#603]
Getting ready to launch this site: 
https://staging.bethel.edu/graduate/academics/certificates/child-adolescent-mental-health/

Launching today.

@donowenskid can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/11K-MAuCwqoMSQuA5tQAMvcVxkqdjoRO8hFBeWrgq3qk/edit#gid=126388933

Redirects:
New site. No redirects needed.

- [x] Close footprints job 14717
- [x] Tag analytics @kathrynmagnuson

**Comment by annmarieven** [comment]
desktop and mobile Safari look good. 

Chris is publishing the xml to fix the proof point. If that doesn't work, we'll need to talk to Caleb.

**Comment by annmarieven** [comment]
@c-schwarze can you look at why there is a space between the number and the percent signs on the proof points on this page? we checked the proof points themselves and there don't appear to be any extra spaces. https://staging.bethel.edu/graduate/academics/certificates/child-adolescent-mental-health/

**Comment by annmarieven** [comment]
publishing to production since this is minor. assigning to @c-schwarze to look at proof points. 

@kathrynmagnuson can you do the analytics tag for this?

**Comment by donowenskid** [comment]
GTG in Chrome and FF

**Comment by kathrynmagnuson** [comment]
did analytics tag for this page.

**Comment by c-schwarze** [comment]
Fixed proof point issue.
