### ISSUE TITLE
GS Academics Teaching License Site Launch and Issue

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#604]
Getting ready to launch this site on Tuesday, Oct. 6:
https://staging.bethel.edu/graduate/academics/licensures/teaching/

@a-parrott can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/1EY5kgeUPJIZiTBa9nKzPbuCjs0JiB_AF3Ww516XEEf4/edit#gid=282667469

Redirect:
http://gs.bethel.edu/academics/licensures/teaching 
TO
https://www.bethel.edu/graduate/academics/licensures/teaching/

- [x] add main image @kathrynmagnuson 
- [x] Tag analytics @kathrynmagnuson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
I got this feed back from Judith Landrum. @a-parrott could you see about adding this to the license?

1.  Visual arts, not art --- *i don't know what she's talking about with this and am following up with her*
2.  Please add these content areas:  Spanish, social studies, and ESL
3.  In the narrative, please note that it is an initial teaching license, for those who do not have a teaching license.  That is a confusing point for many applicants, and it needs clarification.
4. Start dates are April and August. -- *letting her know this is banner data*
5. We are required by our accreditors to publicly post specific information about our programs.  So, please add the info below:
    MTLE pedagogy passing rates are consistently  97%-100%
    Program completion over the past few years is consistently over 90%; usually closer to 100%

**Comment by a-parrott** [comment]
Changes made. I tweaked the text for #5 and put it on the program details page: 
MTLE pedagogy passing rates for Bethel students who complete our program are consistently 97% to 100%.

**Comment by a-parrott** [comment]
Looks good in Chrome and Firefox.

There are no courses or cohort info on the program details page. "There are no cohorts scheduled at this time."

**Comment by annmarieven** [comment]
Looks good. Launching now.

**Comment by e-jameson** [comment]
redirect is done.

**Comment by annmarieven** [comment]
Passing to @kathrynmagnuson. We can touch base on how to do things in the checklist above. When they're done, check them off and close the issue.

Thanks!

**Comment by annmarieven** [comment]
use this for the main image: https://cdn1.bethel.edu/resize/unsafe/800x0/smart/https://www.bethel.edu/graduate/academics/teaching/images/site-images/student-learning-classroom.jpg

**Comment by kathrynmagnuson** [comment]
uploaded the main image and linked it to the index, but we're having issues with it showing up on the actual page.
