### ISSUE TITLE
Nurse-Midwifery events 

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#605]
https://www.bethel.edu/graduate/academics/nurse-midwifery/
Since there isn't any news on this webpage, the events should be showing up on the left instead of the right, could you look into this?

Thanks!

**Comment by annmarieven** [comment]
@johjacb do you need to look at this or do you want to assign it to a student to check it out?

**Comment by johjacb** [comment]
we did have a checkbox option to hide if empty in the form. that got moved to JS so that all empty feeds are hidden. we'll need to add it back to the form and remove the JS bit if we want to make this happen. It could default to hide if none.

**Comment by annmarieven** [comment]
I'm a little confused. I think the checkbox still exists in the data definition for event and news feeds.. https://cms.bethel.edu/entity/open.act?id=40e5d51b8c5865137464be9cb6126055&type=structureddatadefinition&

Also, we don't want all feeds to automatically hide if they're empty, only if we specifically choose that option in the feed itself.

Let me know if we need to touch base more about this.

**Comment by johjacb** [comment]
Going to need Caleb or Jmo's help here

**Comment by e-jameson** [comment]
@annmarieven @ale73233 this is fixed. Any other pages with the same issue will need to be republished.
