### ISSUE TITLE
GS Academics Superintendent License Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#606]
Getting ready to launch this site on Tuesday, Oct. 6:
https://staging.bethel.edu/graduate/academics/licensures/superintendent/

@a-parrott can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/1EY5kgeUPJIZiTBa9nKzPbuCjs0JiB_AF3Ww516XEEf4/edit#gid=1869524300

Redirect:
http://gs.bethel.edu/academics/licensures/superintendent
TO
https://www.bethel.edu/graduate/academics/licensures/superintendent/

- [x] add main image @kathrynmagnuson 
- [x] Tag analytics @kathrynmagnuson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
I got this feed back from Judith Landrum. @a-parrott could you see about adding this to the site?

Please add the Two-track option that appears elsewhere. They may get a license AND earn an Ed.D. or just earn the license.
----
There is info about the 2-track option on the silva page (url above)

**Comment by a-parrott** [comment]
Added as a program highlight: 

Two-track license option
You can choose to earn just your Superintendent License or earn your license as part of completing Bethel's Doctor of Education program.

**Comment by a-parrott** [comment]
Looks generally good in both Firefox and Chrome. 

We have a few courses with question marks in the description:
EDUC800
EDUC815
EDUC860

**Comment by annmarieven** [comment]
Everything looks good for me. Launching now.

**Comment by e-jameson** [comment]
redirect is done

**Comment by annmarieven** [comment]
Passing to @kathrynmagnuson. We can touch base on how to do things in the checklist above. When they're done, check them off and close the issue.

Thanks!

**Comment by annmarieven** [comment]
use this for the main image:
https://cdn4.bethel.edu/resize/unsafe/800x0/smart/https://www.bethel.edu/graduate/academics/education-doctorate/images/site-images/professor-teaching.jpg
