### ISSUE TITLE
GS Academics K-12 Principal License Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#607]
Getting ready to launch this site on Tuesday, Oct. 6:
https://staging.bethel.edu/graduate/academics/licensures/k-12-principal/

@donowenskid can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/1EY5kgeUPJIZiTBa9nKzPbuCjs0JiB_AF3Ww516XEEf4/edit#gid=654344244

Redirect:
http://gs.bethel.edu/academics/licensures/k12-principal
TO
https://www.bethel.edu/graduate/academics/licensures/k-12-principal/

- [x] add main image @kathrynmagnuson 
- [x] Tag analytics @kathrynmagnuson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
I got this feed back from Judith Landrum. @donowenskid could you see about adding this to the site?

Please add the Two-track option that appears elsewhere. They may get a license AND earn an Ed.D. or just earn the license.

--
There is info about the 2-track option on the silva page (url above)

**Comment by donowenskid** [comment]
Two-track option added...GTG in FF and Chrome.

**Comment by annmarieven** [comment]
Looks great for me too.

**Comment by e-jameson** [comment]
redirect is done.

**Comment by annmarieven** [comment]
Passing to @kathrynmagnuson. We can touch base on how to do things in the checklist above. When they're done, check them off and close the issue.

Thanks!

**Comment by annmarieven** [comment]
use this as the main image: https://cdn4.bethel.edu/resize/unsafe/800x0/smart/https://www.bethel.edu/graduate/academics/education-doctorate/images/site-images/professor-teaching.jpg (you can actually just use the same one that we're using for the superintendent license)
