### ISSUE TITLE
GS Academics Director of Special Education License Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#608]
Getting ready to launch this site on Tuesday, Oct. 6:
https://staging.bethel.edu/graduate/academics/licensures/director-special-education/

@donowenskid can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/1EY5kgeUPJIZiTBa9nKzPbuCjs0JiB_AF3Ww516XEEf4/edit#gid=64960278

Redirect:
http://gs.bethel.edu/academics/licensures/director-special-education
TO
https://www.bethel.edu/graduate/academics/licensures/director-special-education/

- [x] add main image @kathrynmagnuson 
- [x] Tag analytics @kathrynmagnuson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
I got this feed back from Judith Landrum. @donowenskid could you see about adding this to the site?

Please add the Two-track option that appears elsewhere. They may get a license AND earn an Ed.D. or just earn the license.

--
There is info about the 2-track option on the silva page (url above)

**Comment by donowenskid** [comment]
GTG in Chrome and FF.

**Comment by annmarieven** [comment]
Looks good in mobile and desktop Safari.

**Comment by e-jameson** [comment]
redirect is done.

**Comment by donowenskid** [comment]
Two-track language updated to match other pages.

**Comment by annmarieven** [comment]
Passing to @kathrynmagnuson. We can touch base on how to do things in the checklist above. When they're done, check them off and close the issue.

Thanks!

**Comment by annmarieven** [comment]
use the same image we're using for superintendent and principal.
