### ISSUE TITLE
GS Academics Teacher Coordinator of Work-based Learning License Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#609]
Getting ready to launch this site on Tuesday, Oct. 6:
https://staging.bethel.edu/graduate/academics/licensures/work-based-learning/

@donowenskid can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/1EY5kgeUPJIZiTBa9nKzPbuCjs0JiB_AF3Ww516XEEf4/edit#gid=0

Redirect:
http://gs.bethel.edu/academics/licensures/work-based-learning
TO
https://www.bethel.edu/graduate/academics/licensures/work-based-learning/

- [x] add main image @kathrynmagnuson 
- [x] Tag analytics @kathrynmagnuson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
Judith Landrum proofed. No changes.

**Comment by annmarieven** [comment]
Looks good on desktop and mobile Safari.

**Comment by donowenskid** [comment]
GTG in Chrome and FF

**Comment by e-jameson** [comment]
redirect is done.

**Comment by annmarieven** [comment]
Passing to @kathrynmagnuson. We can touch base on how to do things in the checklist above. When they're done, check them off and close the issue.

Thanks!

**Comment by annmarieven** [comment]
use the same image we are using for the teaching license.
