### ISSUE TITLE
GS Academics Technology for Educators License Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#610]
Getting ready to launch this site on Tuesday, Oct. 6:
https://staging.bethel.edu/graduate/academics/licensures/technology-educators

@a-parrott can you proof content, Firefox, and Chrome? 
I'll proof on Safari and iOS 8 on iPhone 6.

Migration grid:
https://docs.google.com/spreadsheets/d/1EY5kgeUPJIZiTBa9nKzPbuCjs0JiB_AF3Ww516XEEf4/edit#gid=2045791505

Redirect:
http://gs.bethel.edu/academics/licensures/teachers-of-computer
TO
https://www.bethel.edu/graduate/academics/licensures/technology-educators/

- [x] add main image @kathrynmagnuson 
- [x] Tag analytics @kathrynmagnuson 
- [x] Close and archive old site

**Comment by annmarieven** [comment]
Judith Landrum proofed. No changes.

**Comment by a-parrott** [comment]
Looking good in Chrome and Firefox.

**Comment by annmarieven** [comment]
This one looks good too. Launching now.

**Comment by e-jameson** [comment]
redirect is done

**Comment by annmarieven** [comment]
Passing to @kathrynmagnuson. We can touch base on how to do things in the checklist above. When they're done, check them off and close the issue.

Thanks!

**Comment by annmarieven** [comment]
use the same image as the teaching license.

**Comment by kathrynmagnuson** [comment]
uploaded the main image and linked it to the index, but we're having issues with it showing up on the actual page.
