### ISSUE TITLE
Maps and Directions block update

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#611]
I added a field for office number to the group of fields for offices. Can this appear below the office name when the flag appears on the map?

data definition:
https://cms.bethel.edu/entity/open.act?id=ba13ceec8c586513100ee2a74d4ccfdd&type=structureddatadefinition

let me know if there are questions or if this isn't clear enough :)

**Comment by c-schwarze** [comment]
@c-varberg could you look at this?

**Comment by c-varberg** [comment]
@annmarieven It should all be working now. Did you want me to bold the office names? To me it looks a little off having the names and numbers being the same font, but I'm not really an artsy person, so I don't trust myself when it comes to that stuff.

**Comment by annmarieven** [comment]
@c-varberg sorry for the delay on this. can you bold the office names? I think that's a good idea. Will you assign it to @emily-johnson for testing when you're done?

Thanks!

**Comment by c-varberg** [comment]
Alrighty this should be working. Let me know if you have any problems

**Comment by annmarieven** [comment]
@emily-johnson can you do a few tests with this?

**Comment by annmarieven** [comment]
@emily-johnson if you tested and followed up with brooke, can you close this issue?
