### ISSUE TITLE
Proof Points

### ISSUE THREAD

**Issue by a-parrott** [betheluniversity/cascade#612]
We have a couple of itinerant proof points: 
https://cms.bethel.edu/entity/open.act?id=19eefb248c5865135795f1af763ccf56&type=block&
https://cms.bethel.edu/entity/open.act?id=19ed831e8c5865135795f1af68caf70a&type=block&

Right now they are showing on Graduate School program homepages, though they are tagged only as "Graduate School." The proof points on the program homepages should only be those that are tagged with that program's name.

When the proof points remained completely untagged, they ended up on the Adult Undergrad program homepages. 

Seems like a fix is needed. Thanks!

**Comment by c-schwarze** [comment]
@c-varberg could you look at this?

**Comment by c-varberg** [comment]
Me and Caleb discussed this a bit. The way it is set up right now when you automatically select proof points it checks if schools, departments, or topics match. In order for us to make this work correctly we would have to check if schools and departments match, but if we did this nothing would match for homepages since they don't have any schools selected. 

The solution we came up with is adding a topic called "homepage" that would need to be selected for any proof points that we want to appear on a homepage. We could also just commit to selecting proof points for homepages manually. Do either of those sounds like they would work for you, or do you have any better ideas?

**Comment by a-parrott** [comment]
Thanks!  A couple questions - 

What is the "premium proof point"? And why is it in the meta-data versus the data definition? 

Based on those answers, we're wondering if there can be an option to "hide this proof point unless manually selected." It could go in the metadata or the data definition.

**Comment by c-varberg** [comment]
Not quite sure about the premium proof points. @c-schwarze what are premium proof points?

Adding that option should be pretty straight forward. Caleb, do you see any problem with that? 

Are you thinking of manually selecting proof points for department homepages then?

**Comment by a-parrott** [comment]
We wouldn't manually select proof points. Instead, we would keep everything as is, but use the hide option.

**Comment by c-schwarze** [comment]
Premium proof points are proof points that should appear first, before non-premium proof points. A premium CAS PP appears before a CAS PP.

We can definitely add the "hide-unless-selected" option.

**Comment by a-parrott** [comment]
@c-schwarze - so are premium proof points those that appear on first page load? When the page gets refreshed, does the non-premium proof point appear? 

Is it possible that premium proof points would always appear so that users only see the premium proof points?

Would it be better to add the "hide" option in the data definition or the metadata?

**Comment by c-schwarze** [comment]
If a premium proof point matches the metadata of the Proof point collection, then it will always appear. (assuming there aren't more premiums proof points than proof points to show).

That is how it should be currently working, but let us know if it isn't.

The 'hide' option should be in the data definition.

**Comment by a-parrott** [comment]
OK - I can add it to the data definition. And then I'll assign it back to @c-varberg.

**Comment by a-parrott** [comment]
Added.

**Comment by c-varberg** [comment]
Alright, should all be working now. I went ahead and updated the two proof points above to be hidden. Let me know if you notice anything off.

**Comment by a-parrott** [comment]
@c-varberg - The proof points are still appearing. I republished the xml and republished one of the graduate academic pages, and the proof points still appeared. So I untagged graduate school, republished the xml, and now they are back on the adult undegrad academic pages: https://www.bethel.edu/adult-undergrad/academics/business-management/

**Comment by c-varberg** [comment]
@a-parrott uhps my fault. I forgot to make the new code live on www. Should be working now. Let me know if you have any problems with it now :)

**Comment by a-parrott** [comment]
Looks good! Thanks!
