### ISSUE TITLE
Box Office Seating Chart Not Loading

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#614]
https://www.bethel.edu/events/arts/box-office

@c-schwarze The seating chart for the box office isn't loading (I tried republishing), can you take a look at it? Thanks!

**Comment by c-schwarze** [comment]
Updated. Some pages with galleries will have to be republished.

@johjacb our galleries currently are using jquery. Just letting you know that I added the jquery include to galleries.
