### ISSUE TITLE
Adjunct Faculty Job Listing

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#615]
@c-schwarze Can you take a look at this too? The Apply Now button is not showing up on this page: https://www.bethel.edu/employment/openings/postings/2014/november/adjunct-faculty

The /adjunct-generic page in the same folder has it right, and the only differences I saw were options like is a resume required or not, or the application type. Would these affect the button? 

Thanks!

**Comment by c-schwarze** [comment]
You are correct, there needs to be an application-type set, in order for the "Apply Now" button to appear. :)

@annmarieven Do you have a default url that we can have the apply button go to? For cases like these?

**Comment by annmarieven** [comment]
They should choose an application type. I'll make that field required and let her know. Thanks!
