### ISSUE TITLE
Anchor Link Issue

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#616]
The anchor links aren't working for the seminary library pages. 
Here are a couple examples, click on the "Directions and Parking" link and you'll see that they are going to the San Diego part of the page instead of St. Paul. 
https://www.bethel.edu/library/about/locations/seminary-san-diego/ 
https://www.bethel.edu/library/about/locations/seminary-st-paul/ 

FP issue 15866

**Comment by e-jameson** [comment]
@annmarieven I believe this needs to go directly to the Library. Can you confirm and close if so?

**Comment by annmarieven** [comment]
@kathrynmagnuson can you create yourself a folder in the '_testing' folder? Then create a basic page. If Allie or Em are around, ask them to show you how to create an anchor link. If they're not, I can show you.

I'd like to test this to see if it's an issue with all anchor links in Firefox or if it's just an issue with the library site.

Thanks!

**Comment by annmarieven** [comment]
@kathrynmagnuson navigate to '_testing' in the asset tree in Cascade. Click on it and then create a new folder in there for yourself.

**Comment by annmarieven** [comment]
I got another issue about anchor links (FP job 16057).

https://www.bethel.edu/graduate/academics/physician-assistant/program-details/#certifying

So I'm thinking this is a larger issue with all of our anchor links. @e-jameson can you take a look?

**Comment by e-jameson** [comment]
The library anchor links seem to work fine to me. 

@johjacb and I talked about the anchor links on the other page. If you watch closely it looks like its anchoring and then the page height is adjusting height so its going to the bottom. Not sure there is much we can do about that.

**Comment by annmarieven** [comment]
Can you look at these @johjacb?
Here are a couple examples, click on the "Directions and Parking" link and you'll see that they are going to the San Diego part of the page instead of St. Paul. 
https://www.bethel.edu/library/about/locations/seminary-san-diego/ 
https://www.bethel.edu/library/about/locations/seminary-st-paul/

**Comment by johjacb** [comment]
should be fixed.

assigning to @annmarieven to verify. close if good

**Comment by annmarieven** [comment]
This is working. Closing issue.
