### ISSUE TITLE
Program Spotlight Image Issue

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#617]
We put an image in the spotlight section of this page but it isn't showing up (it's requiring content in the heading and paragraph fields in order for it to show up). Can you take a look at this? Thanks! 

https://cms.bethel.edu/entity/open.act?id=6421ce938c5865137c9c2c89d343f189&type=page

**Comment by c-schwarze** [comment]
Thanks for catching that. I updated it to display the image, even if there is no heading.
