### ISSUE TITLE
Wrong Faculty Photo

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#618]
We got a footprints case saying that James D Smith III has the wrong photo for his faculty bio. When I went in to cascade to look at it, the correct photo was listed as smith-james.jpg and that correct photo was linked to his bio. 

I tried doing a cache-test, republishing everything, clearing my cache, using a different browser, etc. but it is still showing the wrong photo. @c-schwarze can you take a look? Thanks!

 https://www.bethel.edu/academics/faculty/smith-iii-james-d

**Comment by c-schwarze** [comment]
Should be fixed. It looks like the image was being cached by PageSpeed. Unfortunately when that happens, you will have to let us know to clear the server cache.

Thanks!
