### ISSUE TITLE
Event Feed and Galleries

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#619]
Can we make art galleries disappear off the event feeds after 3 days? This should happen on all feeds except the ones on the galleries site itself: https://www.bethel.edu/events/arts/galleries/

Let me know if you have any questions or if there's anything else you need from me!

**Comment by c-varberg** [comment]
Alright this should be good to go. I had to update a format so pages will need to be republished. Also it also might not work on www until it gets approved by Caleb or Eric.

**Comment by c-schwarze** [comment]
@c-varberg  if the code is working, go ahead and pull the change.

**Comment by c-varberg** [comment]
K should be live now

**Comment by annmarieven** [comment]
can you clarify what needs to be republished? any event feed that is set to pull gallery events?

**Comment by annmarieven** [comment]
I'm wondering if this has something to do with an issue we're running into. FP job 16258.

Nothing in the Johnson Gallery feed here - https://www.bethel.edu/events/arts/galleries/

But this event is tagged with Johnson Gallery - https://www.bethel.edu/events/arts/galleries/exhibits/2015/the-plastic-a-study-of-love
cascade link: https://cms.bethel.edu/entity/open.act?id=ae9f3d898c58651344b52cc343d7cb55&type=page

**Comment by c-varberg** [comment]
The problem appears to be with the cache. Since this started 5 days ago it seems to be stuck using saved cached events on that page. If I turn off the cache everything works fine. Is this something that needs to be addressed @c-schwarze , @e-jameson or can we just clear the cache and see if it happens again?

**Comment by c-schwarze** [comment]
You updated the php code to use the cache for the whole function, but not the xml, right?

**Comment by e-jameson** [comment]
@c-varberg ^

**Comment by c-varberg** [comment]
righteo, I think the double cache was just keeping things around way longer then they should have been.  @c-schwarze

**Comment by c-schwarze** [comment]
cool. closing
