### ISSUE TITLE
Program Feed List

### ISSUE THREAD

**Issue by a-parrott** [betheluniversity/cascade#620]
Can you make the program feed alphabetical by program name? So for example, the program feed on the adult undergrad bachelor's landing page would look like: https://www.bethel.edu/adult-undergrad/academics/bachelors

B.S. in Accounting
B.S. in Business Management
B.A. in Christian Ministries
etc.

Thanks!

**Comment by a-parrott** [comment]
@josiahtillman: Have you had a chance to look at this?

**Comment by annmarieven** [comment]
Based on our conversation this morning, we're actually going to change the way the feeds are reading.

Can it be formatted this way:

Program Block Title (Degree Field)
OR
Display Name (if there is something in the display name field, it overwrites everything else)

The selection in the degree field should be formatted as follows:
Associate of Arts -- A.A.
Bachelor of Arts -- B.A.
Bachelor of Music -- B.M.
Bachelor of Science -- B.S.
Bachelor of Fine Arts -- B.F.A.
Certificate
Post-grad Certificate
Master of Arts -- M.A.
Master of Science -- M.S.
Master of Divinity -- M.Div
Doctor of Ministry -- D.Min
Doctor of Education -- Ed.D.

**Comment by josiahtillman** [comment]
I believe I have changed this properly. Could you check https://staging.bethel.edu/adult-undergrad/academics/ to see if it is formatted the way you guys want? Thanks!

**Comment by annmarieven** [comment]
Looking good! One thing I noticed. If there is something in the display name field, the list should pull that instead of the program block title + degree field.

For example, check out this block's display name: https://cms.bethel.edu/entity/open.act?id=9a5edad38c58651357534482227ac423&type=block&

**Comment by annmarieven** [comment]
Josiah,
This is looking great here! https://www.bethel.edu/adult-undergrad/academics/

2 more things:
Can the certificates and licenses have "Certificate" or "License" added to the end of the title.
Could they not be in parenthesis like the B.S., B.A., M.S., etc.?

Let me know if you have any questions about this! Thanks!

**Comment by josiahtillman** [comment]
Ok, I've added the Certificate and License, you can see it here: https://staging.bethel.edu/adult-undergrad/academics/  but for some reason, the formatting is strange, so I will look into that now.

**Comment by josiahtillman** [comment]
Formatting fixed! Everything should be good now on that link! Could someone check to make sure it's 100% how you guys want it?

**Comment by annmarieven** [comment]
https://www.bethel.edu/graduate/academics/ -- i have display names for the following items:

Certificate in International Baccalaureate Teaching and Learning
Ed.D. in Leadership

So they should haven't have "Certificate" and (Ed.D) on the end.

**Comment by josiahtillman** [comment]
Ok! This problem should be fixed as well: https://staging.bethel.edu/graduate/academics/
