### ISSUE TITLE
Update autoCache logging and key name

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#621]
Hey Caleb, there were some false cache-hits in the PHP memcache autoCache function. I updated the auto-generated cache key, but its pretty gross right now. Its appending all the items in the $inputs array to a string, but this is creating names 100's of characters long. Can you try generating better names? Maybe if we keep the same formula but do something like (http://php.net/manual/en/function.md5.php) to make it a shorter length? Up to you...

While you are at it go ahead and try and clean up the log in general. Its kinda hectic. 

Thanks!

**Comment by c-varberg** [comment]
alrighty It uses the md5 hashes now. I made the logs more compact but tried to keep the same information. Is there any information you wanted me to just  not log?
