### ISSUE TITLE
Missing headline and text for spotlight paragraphs

### ISSUE THREAD

**Issue by a-parrott** [betheluniversity/cascade#623]
On the individual program index pages we're missing the headline and text of our spotlight paragraphs. Only the photo (located at about the middle of the page) is visible. This appears to be the case for our caps, gs, and seminary programs.

A couple examples: 
https://www.bethel.edu/adult-undergrad/academics/nursing/
https://www.bethel.edu/graduate/academics/teaching/

**Comment by c-varberg** [comment]
should be fixed now. Everything will need to be republished. Below is the page I was testing on
https://staging.bethel.edu/adult-undergrad/academics/nursing/

**Comment by a-parrott** [comment]
Thanks! Pages republished. This is done.
