### ISSUE TITLE
Program Feeds for Marketing Pages

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#625]
I'm going to add an option on the data definition to indicate if the program feed is on a marketing landing page. Then it should be formatted differently - see https://staging.bethel.edu/_testing/build-out/marketing-pages/health-sciences/

If it's on a marketing page, the program feed shouldn't be in a bulleted list and it should pull the program name and program description (both items are in the program block). Also the heading style will change.

**Comment by annmarieven** [comment]
@josiahtillman, I've added the field to the data definition. Let me know if you have questions.

**Comment by e-jameson** [comment]
@josiahtillman can you look at this first thing tomorrow. @annmarieven @johjacb can you provide some more specific details for the new formatting?

**Comment by johjacb** [comment]
Caleb fixed this

**Comment by annmarieven** [comment]
Sorting by degrees, then certificates, then licensures.

Within degrees - by degree type (bachelors, masters, doctorate)

Alphabetically within each list

**Comment by c-schwarze** [comment]
Updated. Let me know if you would like any changes.
