### ISSUE TITLE
CAPS Academics Alcohol and Drug Counseling License Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#626]
We just launched this site:
https://www.bethel.edu/adult-undergrad/academics/licensures/alcohol-drug-counseling/

@a-parrott can you give it a final proof?
I've tested in Chrome and in Safari on iOS 6.

No migration grid or redirects because it didn't exist before.

- [x] Add main image @kathrynmagnuson (let's use the same image that is used on the addiction studies certificate site)
- [x] Close footprints job 15779
- [x] Tag analytics @kathrynmagnuson

**Comment by a-parrott** [comment]
Looked at Firefox, Chrome and Safari on desktop. Looks good! 
The course description for HUSE455 has a couple question marks that are out of place (i.e. ?self of the therapist?).

**Comment by annmarieven** [comment]
@kathrynmagnuson can you tag analytics and then load the main image?

The main image is already cropped/loaded into the adult undergrad human services program. Let's just link it up to the alcohol-drug-counseling/index page, publish to staging, proof it live, then publish it to production if everything is good.

Try to take a stab at it on your own first but let me know if you run into any issues.
