### ISSUE TITLE
Faculty Bios and Left Hand Nav

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#628]
Did something change in August with our faculty bios? I adjusted the base asset to hide left hand nav. But I'm not sure why we're just now encountering this.

See Lauren's comments below from FP job 16138:

Entered on 10/27/2015 at 13:45:11 CDT (GMT-0500) by Lauren Pareigat:
There is a problem with some faculty profiles when viewed individually. It
seems to be those profiles that were added in August of new faculty. Some
have a photo and some don't.

They are showing the left-hand navigation of ALL faculty names. I have
tried re-publishing the pages, but it hasn't helped. I added these directly
to Cascade (not created through Tinker).

https://www.bethel.edu/academics/faculty/peterson-gene
https://www.bethel.edu/academics/faculty/shypulski-eydie
https://www.bethel.edu/academics/faculty/eaton-alex
https://www.bethel.edu/academics/faculty/stoeckman-angela
https://www.bethel.edu/academics/faculty/dikkers-seann
https://www.bethel.edu/academics/faculty/kepple-lisa
https://www.bethel.edu/academics/faculty/robey-nathan
https://www.bethel.edu/academics/faculty/may-claudia
https://www.bethel.edu/academics/faculty/leafblad-erik
https://www.bethel.edu/academics/faculty/lancaster-steven

Melissa Cordes is the only one of this group who's page is looking clean.
She has made updates through Tinker since her page was created.

**Comment by c-schwarze** [comment]
Nothing has changed in the base-asset. I think we just didn't notice because we never create faculty bios outside of tinker (which does it correctly). And now that the base-asset is fixed, we shouldn't run into this problem anymore. 

Are those ones she listed the only issues? If so, manually updating them to hide the nav will resolve this issue.

**Comment by annmarieven** [comment]
we manually adjusted these. closing issue.
