### ISSUE TITLE
Rules for Seminary Pages

### ISSUE THREAD

**Issue by donowenskid** [betheluniversity/cascade#629]
@e-jameson Will you apply rules to the following seminary sites?

https://docs.google.com/spreadsheets/d/12Z7aVhRK9Z2swN5BRe4K69JAYDbkfGV1Ehmyl_m6Myk/edit#gid=0

https://docs.google.com/spreadsheets/d/1qY12CGg0BV1pahvKUT36NeshVBk3pW9q2Tats3nkh3s/edit#gid=0

https://docs.google.com/spreadsheets/d/1_dGqhNzaP2FgdOP-B9lVH1N232mhZvKXjMaDLsc2AFw/edit#gid=0

Thanks!

**Comment by e-jameson** [comment]
done.
