### ISSUE TITLE
Marketing Resources

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#630]
Do you know why the mailing labels document doesn't download as a word document template?

under templates here:
https://www.bethel.edu/marketing/resources/

**Comment by c-schwarze** [comment]
Its a .dot instead of a .doc

https://www.bethel.edu/marketing/resources/mailing-labels.dot

**Comment by annmarieven** [comment]
We need it to be a .dot though because it's a word doc template.

**Comment by e-jameson** [comment]
Cascade might not know what to do with .dot?

**Comment by annmarieven** [comment]
What do we do?

**Comment by c-schwarze** [comment]
Doesn't seem like it is a feature that Cascade offers (and no one else has done it). I will pose the question on the Cascade Help site.

**Comment by c-schwarze** [comment]
![screen shot 2015-11-25 at 8 36 31 am](https://cloud.githubusercontent.com/assets/7849657/11399895/bbbc10c6-934f-11e5-93ba-56480fd12625.png)

Dot files are outdated... Also, browsers cannot render a .dot file. However, we could just rename the .dot file to a .doc file to make it work. What do you think?

**Comment by annmarieven** [comment]
@ale73233 can you try reloading the files on the page above as .doc and see if the download works correctly for you?

**Comment by ale73233** [comment]
I reloaded it as a .doc and it works!:)

**Comment by annmarieven** [comment]
@ale73233 i went here but got an error when i tried clicking on mailing labels: https://www.bethel.edu/marketing/resources/

random question - can you remove (doc) from the word templates link. it actually goes to a web form, rather than a word doc

**Comment by annmarieven** [comment]
@emily-johnson can you look into this?

**Comment by emily-johnson** [comment]
It looks like the index just never got published, so the link was still pointing to the .dot file

**Comment by ale73233** [comment]
Hello!

Is there a way I can be removed from getting these emails?

Thanks!!:)

**Comment by annmarieven** [comment]
@ale73233 I think that's something only you can do. I can't change that on our end. Sorry!

**Comment by e-jameson** [comment]
@annmarieven you can remove her account from the BU organization. Might stop some of them from sending. I just made you an owner so you probably couldn't do this before. https://github.com/orgs/betheluniversity/people
