### ISSUE TITLE
Seminary Program block

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#631]
Hi Caleb,
we recieved this job, I tried republishing the pages to see if that would do anything to make the information from the program block show up but it didn't could you look into this?

"I looked through the curriculum changes on the website and realized that
the two SemPM program detail pages don't list the Face to Face Evening
options:
MDiv (https://www.bethel.edu/seminary/academics/divinity/program-details/)
MAMP (
https://www.bethel.edu/seminary/academics/ministry-practice/program-details/
)
I placed the information about the SemPM delivery details on the program
block but they don't seem to have carried over to the webpage. Could you
look into why this isn't showing up?"

Thanks!!

**Comment by c-schwarze** [comment]
I'm looking at the block and it looks like everything is showing up correctly.
https://cms.bethel.edu/entity/open.act?id=ba3f8ab58c58651370c56c6d34d44f38&type=block&

What is supposed to be showing up that isn't? What is a "Face to Face Evening
option"?

**Comment by ale73233** [comment]
If you go back into the program block and look at (5/14) in the concentration >> banner info, it shows in the "How is this cohort delivered" option "You'll meet for evening classes only at one of our convenient locations." But that information is not showing up on the page https://www.bethel.edu/seminary/academics/divinity/program-details/

**Comment by c-schwarze** [comment]
We are going to talk about this in our next Cascade meeting to figure it out (11/2/15).

**Comment by vedmic** [comment]
![screen shot 2015-11-09 at 12 25 46 pm](https://cloud.githubusercontent.com/assets/6525476/11042544/5b3a676c-86dd-11e5-8daa-49cd4fe451dc.png)

**Comment by annmarieven** [comment]
@c-schwarze when you start working on this, can you touch base with me about the daytime/evening headings and how those will work?

**Comment by c-schwarze** [comment]
here is an example of the new cohort displays.

https://staging.bethel.edu/graduate/academics/special-education/program-details/academic-behavioral-strategist

**Comment by annmarieven** [comment]
@c-schwarze i think we weren't going to divvy up online stuff for now but just the face to face ones. can you confirm this on Thursday? I won't be there but may try to call in for the meeting.

Also, do you want to run it by @johjacb for design?

**Comment by c-schwarze** [comment]
Yeah I will bring it up on Thursday. 

@johjacb thoughts?

**Comment by c-schwarze** [comment]
We decided to always show the subheading, even if there is only 1 subheading. @johjacb I just updated it to include proper padding/margins. Let me know what you think.

**Comment by johjacb** [comment]
@c-schwarze can you add a mb1 class to the subhead? Good after that.

**Comment by c-schwarze** [comment]
done
