### ISSUE TITLE
Physician Assistant event feed

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#632]
Hi Caleb,

the event feed is not showing up here https://staging.bethel.edu/graduate/academics/physician-assistant/
and it should be showing events because we know there is a nov. 19th event. Could you look into this?

Thanks!

**Comment by c-schwarze** [comment]
I republished the event and the event xml. 

Fixed!

**Comment by c-schwarze** [comment]
I republished the event and the event xml.

Fixed!
