### ISSUE TITLE
GS Academics Teaching License Descriptions

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#633]
@donowenskid and @a-parrott ,
Can you guys divide up the teaching licenses and write descriptions for them?

Here's a nice list so you can see them all:
https://staging.bethel.edu/graduate/academics/licensures/teaching/program-details/

Here's the block where the descriptions will need to be added: https://cms.bethel.edu/entity/open.act?id=64262dbe8c5865137c9c2c89655f37e9&type=block&

**Comment by annmarieven** [comment]
@a-parrott and @donowenskid any update on these?

**Comment by donowenskid** [comment]
License descriptions are done and the pages are published to production.
