### ISSUE TITLE
Seminary Academics Main Site Launch & Issues 

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#634]
This content needs to be looked at. Some (or all) needs to be reworked and revamped.

http://seminary.bethel.edu/academics/
http://seminary.bethel.edu/academics/delivery-options/
http://seminary.bethel.edu/academics/delivery-options/residential/
http://seminary.bethel.edu/academics/delivery-options/residential/st-paul
http://seminary.bethel.edu/academics/delivery-options/residential/san-diego
http://seminary.bethel.edu/academics/delivery-options/distance-learning

The pages can be built out here: https://cms.bethel.edu/entity/open.act?id=d1d793198c58651314811f9ce8327815&type=folder&

**Comment by annmarieven** [comment]
so... we're changing the way the root of the site is laid out and now we need content for a few additional pages:
certificates: https://cms.bethel.edu/entity/open.act?id=d35804958c58651344b52cc3e6e2e48c&type=page&
doctorate: https://cms.bethel.edu/entity/open.act?id=d357be438c58651344b52cc3b0d014b7&type=page&
masters: https://cms.bethel.edu/entity/open.act?id=d35747138c58651344b52cc35b633c24&type=page&

**Comment by annmarieven** [comment]
we launched bethel.edu/seminary/academics yesterday.

@ale73233 a few things here...

can you put in these redirects? https://docs.google.com/spreadsheets/d/1ss1KGPDF90K540GHx9Hr9m8XSECde7-VK6JAEpAJuiQ/edit#gid=0

can you create an image carousel at the top of the sem academics home page? Pull some seminary photos from flickr.

add a happy, computer using student image to the top of the 'online' page (within delivery options folder). this page isn't ready to be published. see these 2 examples: https://www.bethel.edu/adult-undergrad/academics/online and https://www.bethel.edu/graduate/academics/online

**Comment by ale73233** [comment]
submitted it to staging, check tomorrow

**Comment by annmarieven** [comment]
opened a different github for the online page. closing this issue.
