### ISSUE TITLE
Ghost Pages

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#636]
The following are ghost pages that weren't unpublished before they were moved:
https://www.bethel.edu/undergrad/bsg/clubs-organizations/student-ministries/
https://www.bethel.edu/undergrad/bsg/clubs-organizations/student-ministries/mentoring/
https://www.bethel.edu/undergrad/bsg/clubs-organizations/student-ministries/mentoring/woven-lives.pdf
https://www.bethel.edu/undergrad/bsg/clubs-organizations/student-ministries/mentoring/registration
https://www.bethel.edu/undergrad/bsg/clubs-organizations/student-ministries/mentoring/iron-for-iron.pdf
https://www.bethel.edu/undergrad/bsg/clubs-organizations/student-ministries/bible-studies/
https://www.bethel.edu/undergrad/bsg/clubs-organizations/student-ministries/bible-studies/registration
https://www.bethel.edu/undergrad/bsg/clubs-organizations/student-ministries/bible-studies/reimbursement

**Comment by e-jameson** [comment]
these have all been removed.
