### ISSUE TITLE
Online Program Feed

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#637]
Can we merge our online program feed with the existing program feed block?

I added a field for it in the data definition:
https://cms.bethel.edu/entity/open.act?id=98476db08c586513091377e50bd6ef0a&type=structureddatadefinition

**Comment by annmarieven** [comment]
@vedmic would also like to be able to filter by location. I added a field for that. Can we do that?

https://cms.bethel.edu/entity/open.act?id=98476db08c586513091377e50bd6ef0a&type=structureddatadefinition

**Comment by c-schwarze** [comment]
The existing program feed block now works with online and can also filter by location. Let me know if its not working as expected!

**Comment by annmarieven** [comment]
I filtered by location and that seems to work great!
