### ISSUE TITLE
PA How to Apply

### ISSUE THREAD

**Issue by a-parrott** [betheluniversity/cascade#638]
Physician Assistant How to Apply: the content for Step 5 has been removed, but it still appears in staging. https://staging.bethel.edu/graduate/academics/physician-assistant/how-to-apply/

@c-schwarze could you take a look at this? 

Thanks!

**Comment by e-jameson** [comment]
@a-parrott This is fixed and published.

**Comment by a-parrott** [comment]
Sorry @e-jameson - I just received an email that a section in Step 3 is appearing on the live site although it is not in Cascade. I've checked, and it is indeed not in Cascade. It's the second section of bullet points:

CASPA Application
Interview with Program Director or Enrollment Counselor
Official College Transcripts
PA Questionnaire ($50 fee)
Reference: Professional
Reference: Professional

**Comment by e-jameson** [comment]
@a-parrott, that section is being loaded from Banner. They banner data will need to be adjusted if that shouldn't be there. (the idea with these pages is mostly the content is loaded from banner).
