### ISSUE TITLE
Seminary Online Programs Feed Not Working

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#639]
This feed isn't working:
https://cms.bethel.edu/entity/open.act?id=ecea38128c5865137ffab4532f79c113&type=block&

page embedded on:
https://cms.bethel.edu/entity/open.act?id=d358891c8c58651344b52cc3d1851b36&type=page&

I'm hoping to launch sem academics tomorrow but could wait on this page if it's not fixed by then. I have no idea how complicated this is to fix or what's going on so don't worry about it if it won't be finished.

**Comment by c-schwarze** [comment]
Updated. Seminary program feeds work now.

I added online programs to the program feeds (all online program feeds can be replaced by normal program feeds).

I added another field to choose to display all to fix an issue: some of the programs don't currently have banner data, so they can't match the search.

Let me know what you think!

**Comment by annmarieven** [comment]
any idea why it says no programs are online here? https://cms.bethel.edu/entity/open.act?id=d358891c8c58651344b52cc3d1851b36&type=page

**Comment by c-schwarze** [comment]
Fixed!

**Comment by annmarieven** [comment]
a couple programs are showing up that I don't think should be..
https://cms.bethel.edu/entity/open.act?id=ed2e86c88c5865137ffab45340a81a77&type=block& -- this block has no data for delivery but is appearing on the online page.

same with a few others but i'm assuming once this issue is fixed for one it'll be fixed for all.

**Comment by c-schwarze** [comment]
It looks like the seminary online feed (https://cms.bethel.edu/entity/edit.act?id=fd970bbb8c586513739ca2fddef6bf4a&type=block) has selected "all deliveries".

**Comment by annmarieven** [comment]
weird... i wonder if the data def changed from when i first created it. i fixed it but it's still doing the same thing as far as pulling blocks that don't have any data in them.

https://cms.bethel.edu/entity/open.act?id=d358891c8c58651344b52cc3d1851b36&type=page&

**Comment by c-schwarze** [comment]
fixed. any program with no data will not show up on the feeds.

**Comment by annmarieven** [comment]
do you still see the 3 certificates at the bottom?
https://cms.bethel.edu/entity/open.act?id=d358891c8c58651344b52cc3d1851b36&type=page&

i know they have links but they don't have any delivery data indicating that they're online programs so i feel like they shouldn't be in this list... right?

**Comment by annmarieven** [comment]
also, now it looks like we're having an issue with this feed: https://www.bethel.edu/seminary/academics/certificates

**Comment by c-schwarze** [comment]
Oh. I think I misunderstood the issue. If a program has no data, it will be hidden from the list. Sorry about that!

Note: no seminary cert has any data.
