### ISSUE TITLE
Faculty Appearing on Wrong Faculty Lists

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#640]
@parlau sent this request in. FP job 16249

https://www.bethel.edu/undergrad/academics/biology/faculty

Katie Bonawitz and Jessica Samens do not belong. Why would they suddenly show up on the wrong page?

I checked the tags on the page and the 2 bios but everything is tagged appropriately.

**Comment by c-schwarze** [comment]
@c-varberg could you fix this when you get in next?

**Comment by parlau** [comment]
There's also issues with the job titles on a number of the pages... maybe they just need to be republished?

**Comment by parlau** [comment]
I also just found Donna LeGrand on the Music page: https://www.bethel.edu/undergrad/academics/music/faculty

I have no idea what is going on on the Nursing page (Education, Comm Studies, Seminary--oh my): https://www.bethel.edu/undergrad/academics/nursing/faculty
...and social work: https://www.bethel.edu/undergrad/academics/social-work/faculty
...and theatre: https://www.bethel.edu/undergrad/academics/theatre/faculty

**Comment by c-varberg** [comment]
Should be working now. it was some weird error where velocity was using the job-titles information of the last person it looked at if the current person didn't have any new job titles defined. 

Let me know if anyone shows up out of place again

**Comment by c-varberg** [comment]
@c-schwarze is this fine to be closed? all the pages will need to be republished? is there a way to do that all at once?

**Comment by c-schwarze** [comment]
Unfortunately, there is not a way to do it all at once. They have to be manually republished.

**Comment by c-varberg** [comment]
alright I republished all the ones mentioned. They all look good. Closing case

**Comment by parlau** [comment]
@c-varberg where did all the BTS faculty go now?
https://www.bethel.edu/undergrad/academics/biblical-theological/faculty
