### ISSUE TITLE
Events not showing up

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#641]
I updated this page https://www.bethel.edu/events/2015/admissions/mba-masl-4 to have MBA and MA Strategic Leadership tagged, but it isn't showing up in the events feed on the MBA page https://www.bethel.edu/graduate/academics/mba/

**Comment by c-schwarze** [comment]
The event page and the event.xml needed to be republished.

**Comment by kathrynmagnuson** [comment]
Now two events are showing up on the MBA page (https://www.bethel.edu/graduate/academics/mba/) but not all of them. There are supposed to be events showing up on March 14th and April 28th, they are both tagged as MBA events in cascade. 
https://cms.bethel.edu/entity/open.act?id=dca805128c58651346a52c6d5c6d2603&type=page& https://cms.bethel.edu/entity/open.act?id=dcad15c08c58651346a52c6dcdde6ee9&type=page

**Comment by kathrynmagnuson** [comment]
They're all showing up now.
