### ISSUE TITLE
Marketing Page - Business and Leadership Build Out & Launch

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#642]
Opening an issue for the migration of this page:
https://www.bethel.edu/academics/business/

It can be built here: https://cms.bethel.edu/entity/open.act?id=b508b8a88c58651344b52cc32b29af68&type=folder

Looks like there's already some content in that folder but i'm not sure what it's from. Feel free to do with it whatever you like.

We're templating it after the healthcare page:
https://cms.bethel.edu/entity/open.act?id=8fa032218c58651335cd27f34de51036&type=folder&

**Comment by donowenskid** [comment]
Page built out. Sifting through flickr for replacement image

**Comment by donowenskid** [comment]
The content needs reworked with adwords. and the wufoo form needs to be updated.

**Comment by donowenskid** [comment]
Content is updated. Emily is updating the form to match program feed. Descriptions are added to program list.

Replacing image.

**Comment by emily-johnson** [comment]
Form is updated

**Comment by annmarieven** [comment]
Launched this page yesterday.

Keeping open for final form decisions.

**Comment by annmarieven** [comment]
Updated how did you hear about us (but it will eventually be going away due to tracking stuff), keeping which number is this for now (carmen is going to talk to admissions about removing this), made sure no forms were sending confirmation emails.

Closing issue.
