### ISSUE TITLE
Marketing Page - Leadership Build Out & Launch

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#643]
Opening an issue for the migration of this page:
https://www.bethel.edu/academics/leadership/

It can be built in a 'leadership' folder here: https://cms.bethel.edu/entity/open.act?id=67fd41f58c5865132e8da033daf13e78&type=folder&

We're templating it after the healthcare page:
https://cms.bethel.edu/entity/open.act?id=8fa032218c58651335cd27f34de51036&type=folder&

**Comment by donowenskid** [comment]
@vedmic I thought I left comments when i assigned this to you along with the link to the staging site...

Here you go:

https://staging.bethel.edu/_testing/build-out/marketing-pages/leadership/

Take a look. I'm sorting out some new images for this and the business page. See what you think about the use of adwords in the content.

**Comment by vedmic** [comment]
Please adjust the program listings and undergrad descriptions accordingly.

**Comment by donowenskid** [comment]
This should be ready for launch. Assigning to AMV for final check.

https://staging.bethel.edu/_testing/build-out/marketing-pages/leadership/

**Comment by annmarieven** [comment]
Launched this page: https://www.bethel.edu/academics/leadership/

We'll touch base about it in our Cascade meeting.
Photo questions
Form notification questions - sem-data@bethel.edu
Confirmation page

**Comment by annmarieven** [comment]
Updated how did you hear about us (but it will eventually be going away due to tracking stuff), keeping which number is this for now (carmen is going to talk to admissions about removing this), made sure no forms were sending confirmation emails.

Closing issue.
