### ISSUE TITLE
Marketing Page - Education Build Out & Launch

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#644]
Opening an issue for the migration of this page:
https://www.bethel.edu/academics/education/

It can be built here: https://cms.bethel.edu/entity/open.act?id=680728008c5865132e8da033fb8172b5&type=folder

Looks like there's already some content in that folder but i'm not sure what it's from. Feel free to do with it whatever you like.

We're templating it after the healthcare page:
https://cms.bethel.edu/entity/open.act?id=8fa032218c58651335cd27f34de51036&type=folder&

**Comment by a-parrott** [comment]
This is set as well: https://staging.bethel.edu/_testing/build-out/marketing-pages/education/

**Comment by a-parrott** [comment]
@vedmic: And here's this one. Let me know of any revisions - https://staging.bethel.edu/_testing/build-out/marketing-pages/education/

**Comment by vedmic** [comment]
Andrea please update the program listing and descriptions accordingly.

**Comment by a-parrott** [comment]
Content updated and program list in wufoo form updated for organization by degree type and program name.

@c-schwarze: The education program feed is missing several programs: the IB certificate, licenses, and the Education K-12 degree. 

https://staging.bethel.edu/_testing/build-out/marketing-pages/education/

**Comment by c-schwarze** [comment]
The feed should be fixed @a-parrott 

passing back to you?

**Comment by annmarieven** [comment]
I removed cas programs from the program feed and manually added it.

@johjacb is there a way to get the alignment to match the program feed and to eliminate some of the spacing in between the 2 sections? (bachelors section and program feed section)

@a-parrott can you add a manual description to the education program?

**Comment by johjacb** [comment]
yes - the columns for the the section need to be set

**Comment by a-parrott** [comment]
Description added.

**Comment by annmarieven** [comment]
@johjacb can we get the bachelors section any closer to the masters section?

**Comment by johjacb** [comment]
i've adjusted the padding

**Comment by annmarieven** [comment]
This page has been launched.

Still need final notification emails for Wufoo form.

**Comment by annmarieven** [comment]
Updated how did you hear about us (but it will eventually be going away due to tracking stuff), keeping which number is this for now (carmen is going to talk to admissions about removing this), made sure no forms were sending confirmation emails.

Closing issue.
