### ISSUE TITLE
Marketing Page - Nursing Build Out & Launch

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#645]
Opening an issue for the migration of this page:
https://www.bethel.edu/academics/nursing

It can be built in a 'nursing' folder here: https://cms.bethel.edu/entity/open.act?id=67fd41f58c5865132e8da033daf13e78&type=folder&

We're templating it after the healthcare page:
https://cms.bethel.edu/entity/open.act?id=8fa032218c58651335cd27f34de51036&type=folder&

**Comment by a-parrott** [comment]
Everything is now added.

**Comment by a-parrott** [comment]
@vedmic: Let me know of any revisions - https://staging.bethel.edu/_testing/build-out/marketing-pages/nursing/

**Comment by vedmic** [comment]
Please adjust program listing and description accordingly.

**Comment by a-parrott** [comment]
Program list in wufoo form updated for organization by degree type and program name.

@c-schwarze The nursing program list was missing Nursing (RN to B.S.) in the program feed. When I published the page to staging, the program list disappeared and says, "No programs to list." I republished, and it's still gone.

**Comment by c-schwarze** [comment]
Fixed.

**Comment by a-parrott** [comment]
@c-schwarze: Republished to staging. Now only the Nursing (RN to B.S.) program is listed in the program feed.

**Comment by annmarieven** [comment]
this page is almost ready for launch. just 1 question for @johjacb and then we're good to go. i can't seem to get rid of the white space at the top of the image - can you? and can you let me know what you do to fix it?

i've compared the section classes for that section and all of the metadata on this page with the healthcare page (which doesn't have the white space) and i can't figure it out.

**Comment by johjacb** [comment]
The padding for the section needs to be set to 0.

**Comment by annmarieven** [comment]
Launched this page: https://www.bethel.edu/academics/nursing/

We'll touch base about it in our Cascade meeting.
Photo questions
Form notification questions
Confirmation page

**Comment by annmarieven** [comment]
Updated how did you hear about us (but it will eventually be going away due to tracking stuff), keeping which number is this for now (carmen is going to talk to admissions about removing this), made sure no forms were sending confirmation emails.

Closing issue.
