### ISSUE TITLE
Marketing Page - Human Services Build Out & Launch

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#646]
Opening an issue for the migration of this page:
https://www.bethel.edu/academics/human-services/

It can be built in a 'human-services' folder here: https://cms.bethel.edu/entity/open.act?id=67fd41f58c5865132e8da033daf13e78&type=folder&

We're templating it after the healthcare page:
https://cms.bethel.edu/entity/open.act?id=8fa032218c58651335cd27f34de51036&type=folder&

**Comment by emily-johnson** [comment]
I got a good start on building it all out today, but I'll finish it tomorrow and make sure things look good. Publishing seems to not be working, so hopefully it will be better tomorrow

**Comment by donowenskid** [comment]
Em...when you're finished with this one, will you assign it to me so I can look at the content?

Thanks!

**Comment by emily-johnson** [comment]
@johjacb did we find anything to help with the picture formatting?

**Comment by johjacb** [comment]
@emily-johnson Could you describe the issue?

**Comment by emily-johnson** [comment]
@johjacb It seems to be working now, I'm not sure who fixed it haha assigning to @donowenskid to look at the content

**Comment by annmarieven** [comment]
confirmation page needed.

**Comment by emily-johnson** [comment]
I updated the program list in the wufoo form to match the feed

**Comment by donowenskid** [comment]
Content is updated and ready to go.

**Comment by annmarieven** [comment]
This page has been launched.

Keeping open for final form decisions.

**Comment by annmarieven** [comment]
Updated how did you hear about us (but it will eventually be going away due to tracking stuff), keeping which number is this for now (carmen is going to talk to admissions about removing this), made sure no forms were sending confirmation emails.

Closing issue.
