### ISSUE TITLE
Marketing Page - General Seminary Build Out & Launch

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#647]
Opening an issue for the migration of this page:
https://www.bethel.edu/about/seminary/

It can be built here: https://cms.bethel.edu/entity/open.act?id=67fd41f58c5865132e8da033daf13e78&type=folder&

We're templating it after the healthcare page:
https://cms.bethel.edu/entity/open.act?id=8fa032218c58651335cd27f34de51036&type=folder&

**Comment by annmarieven** [comment]
First draft done. https://staging.bethel.edu/_testing/build-out/marketing-pages/seminary/

I am temporarily using the sem images that we already had because the search in Flickr wasn't working.

Still need to:
- [ ] update program field in Wufoo form (https://betheluniversity.wufoo.com/build/adm-sem-marketing-request-info/)
- [ ] update how did you hear about us field in wufoo form to match these options: https://www.bethel.edu/about/caps-gs
- [ ] find images
- [ ] revamp content
- [ ] look into extra white space above image

**Comment by emily-johnson** [comment]
Do you want me to differentiate between BSSD and BSSP programs in the drop down list (e.g. Theological Studies), and should I include the BA in Children's Ministries since it is mentioned on the page?

**Comment by emily-johnson** [comment]
@annmarieven @donowenskid

**Comment by annmarieven** [comment]
@emily-johnson don't differentiate in the form. yes, include christian ministries. can you format it as Christian Ministries (B.A.) and put it in alphabetical order?

Then assign the job to @donowenskid for content.

This is high priority for your work today :)

**Comment by annmarieven** [comment]
confirmation page needed.

**Comment by donowenskid** [comment]
Updated description paragraphs.

**Comment by annmarieven** [comment]
@c-schwarze can you see why DMin is showing up so much further below all the others?

https://staging.bethel.edu/_testing/build-out/marketing-pages/seminary/

**Comment by c-schwarze** [comment]
Fixed.

**Comment by annmarieven** [comment]
This page has been launched.

Keeping open for final form decisions.

**Comment by annmarieven** [comment]
Updated how did you hear about us (but it will eventually be going away due to tracking stuff), keeping which number is this for now (carmen is going to talk to admissions about removing this), made sure no forms were sending confirmation emails.

Closing issue.
