### ISSUE TITLE
Marketing Page - General CAPS/GS Build Out

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#648]
Opening an issue for the migration of this page:
http://www.bethel.edu/about/caps-gs

It can be built here: https://cms.bethel.edu/entity/open.act?id=67fd41f58c5865132e8da033daf13e78&type=folder&

We're templating it after the healthcare page:
https://cms.bethel.edu/entity/open.act?id=8fa032218c58651335cd27f34de51036&type=folder&

**Comment by annmarieven** [comment]
@vedmic should the last part of this url change to avoid using caps gs? 'bethel.edu/academics/graduate-adult-undergrad'

**Comment by annmarieven** [comment]
Working on finding a photo. Still need to adjust feeds so the page is formatted better.

**Comment by annmarieven** [comment]
confirmation page needed.

**Comment by annmarieven** [comment]
grabbed all the feeds from allie's page. she's going to double check the tags and look into the undergrad ones not working.

working on finding a photo from flickr. https://staging.bethel.edu/_testing/build-out/marketing-pages/adult-undergrad-graduate/

**Comment by annmarieven** [comment]
well, there are 3 photos to choose from. finding photos is.... wonderful. as always.

@a-parrott can you look at content by thursday and then @vedmic can do a final approval?

**Comment by a-parrott** [comment]
Revised content. I also added a title and apply button to appear over one of the photos (though it appears over two of them). Looks like the list of programs in the program feeds needs updating.

Assigning to @vedmic for review.

**Comment by annmarieven** [comment]
@vedmic this is waiting for your approval. can you approve it please?

thanks!

**Comment by annmarieven** [comment]
This page has been launched.

Keeping open for final form decisions.

**Comment by annmarieven** [comment]
Updated how did you hear about us (but it will eventually be going away due to tracking stuff), keeping which number is this for now (carmen is going to talk to admissions about removing this), made sure no forms were sending confirmation emails.

Closing issue.
