### ISSUE TITLE
Faculty Bio Formatting Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#650]
From Lauren Pareigat:
Also, the formatting on the degrees list, between the degree type and year completed has a space before the comma. There's also an unnecessary space between the department and school in the title area.

**Comment by c-varberg** [comment]
https://www.bethel.edu/academics/faculty/rivera-ruben

How does this look @annmarieven. Let me know if you hear about any other little formatting things.

**Comment by annmarieven** [comment]
look good! 2 more minor things that i'm wondering about.

can we make the job titles separate paragraphs? so the spacing between multiple job titles is the same spacing between multiple degrees?

can we put a space before and after the hyphen in the degree section? and i think the hyphen shouldn't be bolded. ex: Vangard University - B.A., 1986

thanks so much!!

**Comment by parlau** [comment]
How is going getting all of the faculty bio stuff fixed?

**Comment by c-varberg** [comment]
@annmarieven Those should be fixed now. let me know if there is anything else!

**Comment by annmarieven** [comment]
These issues have been fixed.
