### ISSUE TITLE
Program blocks

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#651]
@annmarieven The program blocks' banner data that is manually entered will need to be updated to include the subheading field. 

Here is an example of an updated one: https://cms.bethel.edu/entity/open.act?id=99a57dab8c58651357534482836c133b&type=block&

Here is an example of one that needs updating: https://cms.bethel.edu/entity/open.act?id=ba3f8ab58c58651370c56c6d34d44f38&type=block&

Here is the key that Tim gave me, if it helps:
F2--Evening
F--being phased out (for FD and FE), but for now, I guess we can say "Evening"
FD -- Daytime
FE -- Evening
H/HL/HH--no subheading
O--Fully Online
OI--Online with Intensives
OO--Mostly Online

**Comment by annmarieven** [comment]
I think for Seminary blocks we need to put daytime in the delivery subheading unless they specifically say evening classes only in the delivery description.

**Comment by c-schwarze** [comment]
So make F2 and F default to daytime?

**Comment by annmarieven** [comment]
@ale73233 all of the blocks in this folder need to be updated:
https://cms.bethel.edu/entity/open.act?id=affb0f9a8c5865130265fd80c0748944&type=folder&

Once you're in the edit tab of the block, scroll all the way down and expand the banner info section. Look at each cohort details sections within there. 

If the delivery label is "Face to Face", we need to enter something into the delivery subheading.
If the cohort delivered field says "You'll meet for classes at one of our convenient locations." then enter "Daytime" into the delivery subheading.
If the cohort delivered field says "You'll meet for evening classes only at one of our convenient locations." then enter "Evening" into the delivery subheading.

This block already has the delivery subheadings entered but we'll need to change them based on the info in the paragraph above. https://cms.bethel.edu/entity/open.act?id=99a57dab8c58651357534482836c133b&type=block&

**Comment by ale73233** [comment]
I updated all of the blocks and the special education one in gs.

**Comment by annmarieven** [comment]
@ale73233 can you republish the pages that the seminary blocks are embedded on?

@c-schwarze I'm not entirely sure what F2 and F are... might be a question for @hamtim

**Comment by ale73233** [comment]
I republished the pages.

**Comment by annmarieven** [comment]
@c-schwarze is this done? see my last question/comment to you.

**Comment by c-schwarze** [comment]
I talked with Tim, he says we should just tell Josh to update the codes. Could you send an email to Josh to have him update the codes to "FE" for Face to Face -- Evening or "FD" for Face to Face -- Daytime?

**Comment by annmarieven** [comment]
contacted amara to update the program blocks in cascade. closing the issue.
