### ISSUE TITLE
Faculty Bio Data Definition

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#653]
Still can't edit this and I don't know why :(
https://cms.bethel.edu/entity/edit.act?id=ba13d01c8c586513100ee2a7c13996d9&type=structureddatadefinition

I need to add rules so that our faculty bio approvers can update them.

**Comment by c-schwarze** [comment]
Fixed. The Tinker sync is creating the logic. 

We decided to have the school field show/hide the depts/job title/lead fields.
