### ISSUE TITLE
Graduate/Adult Undergrad Event Feeds not showing up right

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#654]
The event feeds for all of the graduate and adult undergrad pages are messed up (seminary/undergrad looks fine). I tried republishing the index pages, and it worked for a couple of them, but not for the rest. Here are examples from a couple graduate pages: 
https://www.bethel.edu/graduate/academics/strategic-leadership/ 
https://www.bethel.edu/graduate/academics/special-education/  
And an adult undergrad page:
https://www.bethel.edu/adult-undergrad/academics/accounting/

**Comment by c-schwarze** [comment]
I see 4 events for the strategic-leadership page, which looks good to me.

The special-education has no events tagged as "Special Education (M.A.)" ?

The special-education has no events tagged as "Accounting (B.S.)" ?
