### ISSUE TITLE
Info Session program blocks

### ISSUE THREAD

**Issue by ale73233** [betheluniversity/cascade#656]
Hi Caleb,

On this page https://cms.bethel.edu/entity/open.act?id=f04474f98c58651346a52c6d6ab3d40d&type=page& it is not pulling the certificates and licenses program blocks. We looked at the blocks and the actual programs and they are all tagged correctly. Could you look into this?

Thanks!

**Comment by c-schwarze** [comment]
There were no schools tagged. I updated the program feeds, so that if no school is tagged, it assumes all schools are tagged.

**Comment by ale73233** [comment]
Hi Jake,
On this page https://staging.bethel.edu/_testing/build-out/caps-gs-info/ the teaser "Live your life with purpose. Become a leader in your field. Know that what you do matters." shows up twice at the top and on the very bottom of the page. Do we use the teaser field on this page? https://cms.bethel.edu/entity/edit.act?id=f04474f98c58651346a52c6d6ab3d40d&type=page or why would it be showing up twice?

**Comment by johjacb** [comment]
I don't think we use the teaser? I think you'll want to add it to the form below the image. You'll probably want to check with AnnMarie or Andrea.

**Comment by ale73233** [comment]
fixed.
