### ISSUE TITLE
Add share functionality for news stories

### ISSUE THREAD

**Issue by johjacb** [betheluniversity/cascade#657]
Add share buttons

**Comment by johjacb** [comment]
check out the buttons at the bottom on Medium

https://medium.com/swlh/no-ui-is-the-new-ui-ab3f7ecec6b3#.sft3lnr29

**Comment by johjacb** [comment]
@c-varberg could you take attempt to implement this on a test page when you have some time?

https://jonsuh.com/blog/social-share-links/

**Comment by e-jameson** [comment]
@c-schwarze can you work with @josiahtillman to get going on this again?

**Comment by josiahtillman** [comment]
Here is the test page! https://cms.bethel.edu/entity/open.act?id=61c976da8c586513192b273868714e9e&type=page

**Comment by johjacb** [comment]
Made a couple tweaks: https://staging.bethel.edu/news/articles/2016/march/tuition-affordability

@hamtim take a look

**Comment by hamtim** [comment]
@vedmic what do you think?

**Comment by e-jameson** [comment]
@vedmic help
