### ISSUE TITLE
Tinker Event Request

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#658]
@c-schwarze can you (or someone else) look into the event form in tinker? It seems to not be saving the program selection when the event gets created in cascade (I'm specifically looking at the four admissions [PA info sessions](https://cms.bethel.edu/entity/open.act?id=214ef36b8c586513116ff695e1fcff19&type=page) in 2016)

Also, after I went in and selected the program, the event feed was still not pulling it.

Let me know what you find. Thanks! 
Em

**Comment by emily-johnson** [comment]
@c-schwarze Now the two I events changed yesterday are appearing on the index page (it is set to show up to 4 at a time), so does it just take some time?

**Comment by c-schwarze** [comment]
Yeah it takes at least 5 minutes due to caching.

**Comment by emily-johnson** [comment]
Oh I've waited that long yesterday and today... hmm

**Comment by emily-johnson** [comment]
Everything looks good now, it took until the next morning for both batches to update and be pulled on to the page, but it did work.

@c-schwarze Can we look into making sure Tinker keeps the program label when going over to cascade?

**Comment by annmarieven** [comment]
@c-schwarze can you see @emily-johnson's last comment

**Comment by c-schwarze** [comment]
it should be working
