### ISSUE TITLE
Tinker Issue

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#659]
Could you take a look at the issue Rita Haglund is having with tinker? Thanks

"In Tinker - I attempted to make a title change in Beth Peterson's
faculty bio but when I went to submit it gave me an error in an orange box that says a job
title is required when I had already entered her job title. I tried several times and got the same
error. I also attempted to make a change to her title in the biography box as well and
that would not save."

**Comment by c-schwarze** [comment]
I updated Tinker, it appears to work properly with Beth Peterson's bio. Could you let Rita know that she can try again? 

Thanks! Sorry for all of the issues.

**Comment by e-jameson** [comment]
@kathrynmagnuson can you confirm with Rita it is working correctly?

**Comment by annmarieven** [comment]
Lauren just contacted me about Beth Peterson's bio. I think it's been taken care of.
