### ISSUE TITLE
M.S. Physician Assistant Faculty Bios not showing up 

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#660]
Only one person's bio is pulling on the MS Physician Assistant Faculty page https://www.bethel.edu/graduate/academics/physician-assistant/faculty (I believe @ale73233 looked in cascade and thought all of the settings were the same for each person/they were all tagged). Here are the names of the other faculty that are supposed to be on this page: 
"Wallace Boeve,
Greg Ekbom
Cynthia Goetz
Christy Hanson
Lisa Naser
Dan Leafblad
Timothy Shaw (his bio has been on our page because he teaches one class,
but he is technically not a PA Faculty) It's ok to leave him on there."

**Comment by c-schwarze** [comment]
Hmm. It looks list the job titles are missing a program, therefore they are not showing up on the list. I assume this is an issue on our end. I'll let you know when this is fixed.

**Comment by c-schwarze** [comment]
It appears that all CAPS, GS, and Seminary program headings got lost in the massive changes. Unfortunately, there is no way to get these back automatically. They will have to be manually chosen, or submitted through Tinker. Sorry about the unfortunate news.

**Comment by e-jameson** [comment]
@c-schwarze is this cleaned up?

**Comment by c-schwarze** [comment]
yeah. closing
