### ISSUE TITLE
New Event Category

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#662]
I added a new category to the event metadata.
https://cms.bethel.edu/entity/open.act?id=1a525c038c5865135b5a2d9efa247727&type=metadataset

Dining Services (under offices)

I checked in Tinker but didn't see the change reflected there. Also, it doesn't look like Student Life or Dining Services is appearing on the live calendar list of categories. Is that something that has to be manually updated?

**Comment by c-schwarze** [comment]
@e-jameson could you take this over?

**Comment by e-jameson** [comment]
@annmarieven: the Calendar has a seperate Metadata set, once that is updated, the Calendar page needs to be edited to select the new categories, and then republished. I'll add Dining Services to the Tinker form.

https://cms.bethel.edu/entity/open.act?id=67707b6b8c5865133e4f684601940706&type=metadataset

**Comment by e-jameson** [comment]
AMV and I looked at this together.
