### ISSUE TITLE
Faculty Lists

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#665]
If there is a program director, department chair, or lead faculty member selected for a department, can they show up at the top of the faculty list?

**Comment by annmarieven** [comment]
Assign to @johjacb for design before pushing this out live.

**Comment by c-schwarze** [comment]
@johjacb, the program director, lead faculty, etc. are the first ones listed. Let me know if you need any adjustments.  

This is the one I was using for testing; https://staging.bethel.edu/undergrad/academics/art/faculty

**Comment by johjacb** [comment]
i made a few tweaks - should be ready to go

**Comment by c-schwarze** [comment]
Looks good. I published all of our faculty bios to www.

**Comment by annmarieven** [comment]
@kathrynmagnuson can you go through this list and make sure that all department chairs are tagged?
https://docs.google.com/a/bethel.edu/document/d/1kDNzm5IMOCieQp9Mqgw694GMnE7RKm8P7a77lzwzZLI/edit?usp=drive_web

This will need to be in addition to any other titles they have, not in place of. We can touch base on this if you have questions.

Skip the following departments:
Notes from Lauren -
Chemistry: list Rollin as "Chair" and Ashley as "Associate Chair"
English: list both Mark Bruce and Susan Brooks as "Co-Chair"
Human Kinetics: just list Chad Osgood
Political Science: list Fred Van Geest as "Acting Department Chair" (Stacey is still formally in the role, but out on leave.)

**Comment by annmarieven** [comment]
i'm taking care of this tomorrow morning.

**Comment by annmarieven** [comment]
this is done.
