### ISSUE TITLE
Bethelnet Left Hand Nav

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#666]
https://bethelnet.bethel.edu/facilities-mgmt/edit/tab_template

@e-jameson We are getting an error when we try to go to defaultMenu to change the left hand nav, can you help? Thanks!

**Comment by e-jameson** [comment]
@emily-johnson try this URL: http://zope1.its.bethel.edu:8080/silva/bethelnet/facilities-mgmt/edit/tab_template

If you don't have access swing back sometime and you can make your changes on my computer.

**Comment by emily-johnson** [comment]
It worked, thanks!
