### ISSUE TITLE
blogs list

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#667]
We need a blog post in the “bethel blogs” blog with a list of blogs that are interesting enough to advertise.

**Comment by annmarieven** [comment]
created a blog post with the list of blogs. @e-jameson is there anyway we can get the whole blog post to show up on the homepage so it doesn't look so weird?

blogs.bethel.edu

**Comment by e-jameson** [comment]
@annmarieven I don't see a way to make the homepage show more text. Considering this homepage is probably more useful than the old one, I'm going to close this. But go ahead and re-open if you'd like.
