### ISSUE TITLE
Program Feed Headings

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#668]
We need these headings to appear in the feeds if there are programs that match the selected degree type metadata:

Associates
Bachelors
Masters
Doctorates
Certificates
Licensures

**Comment by c-schwarze** [comment]
Updated. @annmarieven, I added a "Show subheadings" to the Data Def.

Might need some styling help @johjacb 

Here is an example: https://cms.bethel.edu/entity/open.act?id=d358891c8c58651344b52cc3d1851b36&type=page

**Comment by c-schwarze** [comment]
We currently decided to either display Titles or Subheadings, but never both.

**Comment by annmarieven** [comment]
We also decided to say "Master's Degrees"

I think this means we should also say "Bachelor's Degrees" and "Doctoral Degrees"

**Comment by c-schwarze** [comment]
Updated. 

Closing.
