### ISSUE TITLE
Philosophy Faculty Department Chair Issue

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#670]
Sara Shady is being pulled as the department chair for Philosophy as well as Dan Yim. It should be JUST Dan Yim.

I've checked Sara's bio (and republished everything multiple times) and have no idea why it's pulling her too.

https://www.bethel.edu/undergrad/academics/philosophy/faculty

Sara's bio page: https://cms.bethel.edu/entity/open.act?id=00ad58848c586513100ee2a755ed659b&type=page

**Comment by c-schwarze** [comment]
Fixed. Some bios that were dept chairs in other depts were being pulled in as the dept chair.
