### ISSUE TITLE
Faculty lists adjustment

### ISSUE THREAD

**Issue by donowenskid** [betheluniversity/cascade#671]
@c-schwarze 

I noticed on this page that all the lead faculty/ program director/ program chair were pulling to the top of the list. But since it's not a program specific faculty list, we don't want them to go to the top...

https://www.bethel.edu/seminary/academics/faculty

**Comment by c-schwarze** [comment]
Updated. Publishing the faculty listings now.

**Comment by annmarieven** [comment]
This has been fixed. Closing.
