### ISSUE TITLE
Institutional Data and Research Site Launch & Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#672]
@emily-johnson, the IDR office is getting ready to launch the site but I'm wondering if you can help them out with a few things before we go live.

Will you make sure none of their headings are bolded? And can you adjust the bulleted lists? Looks like they all have too much spacing in between each line.

https://staging.bethel.edu/institutional-data-research/

Thanks!

p.s. Could you do this first thing today? Then reassign to me.

**Comment by emily-johnson** [comment]
All set!

**Comment by annmarieven** [comment]
this site has been launched!

@emily-johnson can you go through this site and clean up the html? Will you show @kathrynmagnuson how to do it too?

**Comment by emily-johnson** [comment]
Done!
