### ISSUE TITLE
CAPS/GS Admissions program lists

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#673]
We need to transition these manual lists to program feeds.
https://www.bethel.edu/graduate/admissions/
https://www.bethel.edu/adult-undergrad/admissions/

We've already done so on these 2 pages so you can probably just use the same exact feed blocks.
https://www.bethel.edu/graduate/academics/
https://www.bethel.edu/adult-undergrad/academics/

Because this is such a central, high traffic page, be sure to proof at staging to make sure everything is formatted correctly before publishing it to prod.

**Comment by kathrynmagnuson** [comment]
Done! :)
