### ISSUE TITLE
Past asset versions

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#674]
@c-schwarze or @e-jameson we got this case from Brooke: 

Entered on 01/05/2016 by Brooke Jameson:
"I need to look at a version of this commencement page that is from before April 29 but none of them are working. I just get [this error](http://screencast.com/t/TVe3rjtLi). Can someone help please? Thanks!!"

I'm getting the same error and after playing with it a little, can't figure out what the issue is. Can you take a look?

Thanks!

**Comment by emily-johnson** [comment]
Oops, here's the asset: https://cms.bethel.edu/entity/open.act?type=page&id=85ffceec8c58651317cf8e74d1a9b5a0

**Comment by e-jameson** [comment]
This is fixed. Adding this resource in case this happens again (also might explain why Cascade is crashing...): http://help.hannonhill.com/discussions/bug-reports/1894-invalid-xml-prefix-cascadehref-asset-id-attribute-on-a-tag

@emily-johnson can you close the case and let Brooke know its working.

**Comment by emily-johnson** [comment]
I'm on it, thanks!
