### ISSUE TITLE
Faculty list

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#676]
@c-schwarze 

I tagged Patti Paulson for both the Ed.D and MA in Teaching programs, but she only got added to the Ed.D. faculty list. Is there any reason she wouldn't be getting pulled to the [MAT list](https://www.bethel.edu/graduate/academics/teaching/faculty)?

I did the usual republishing, clearing my cache, etc.

**Comment by c-schwarze** [comment]
The Metadata isn't matched up. Patti has E.d.D. and STEM in K-12 Education Certificate for Graduate School Programs. The Faculty page you posted has 

So I don't believe she shouldn't be showing up in the list.

**Comment by emily-johnson** [comment]
@c-schwarze We're both looking at her academics/faculty/ page, right? I see her as having Ed.D. and Teaching (M.A.)

I'll try republishing again

**Comment by c-schwarze** [comment]
I still don't see the Teaching (M.A.). Are you looking at the 4 Job Titles she has? The Metadata at the top of the page isn't what is being used to put her on the page.

![screen shot 2016-01-12 at 8 15 53 am](https://cloud.githubusercontent.com/assets/7849657/12265789/e145609c-b904-11e5-9a09-8915e5c13521.png)

**Comment by emily-johnson** [comment]
@c-schwarze Ohh.. I thought that's what did pull her. So if we add her other job title for MAT, it should pull her?

**Comment by c-schwarze** [comment]
Yep!
