### ISSUE TITLE
News archives not pulling 2016 articles

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#678]
2016 articles aren't showing up in archive feeds.

https://www.bethel.edu/news/news-archive
articles that should appear:
https://cms.bethel.edu/entity/open.act?id=192078448c58651375cf00e7a471168e&type=page&
https://cms.bethel.edu/entity/open.act?id=0e2c7e718c586513358c1a26e6489775&type=page&

https://www.bethel.edu/president/announcements/
articles that should appear:
https://cms.bethel.edu/entity/open.act?id=22d7b6ca8c58651307c73067f6d89b9f&type=page&

**Comment by e-jameson** [comment]
Looks like this is good? Not sure if any changes were made?

**Comment by c-schwarze** [comment]
Forgot to comment back here. I fixed it.
