### ISSUE TITLE
Update to Academic Program Homepage Template

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#679]
Can we somehow add an option (maybe even admin only) plain text field below 'program details' on the academic program homepage template?

Should I add it to the data definition and then you can get it to show up correctly?

**Comment by c-schwarze** [comment]
Sure. Add it to the DD and i'll update the format

**Comment by annmarieven** [comment]
Let's make it only available to admin for now.

**Comment by c-schwarze** [comment]
@annmarieven have you updated the DD?

**Comment by annmarieven** [comment]
This has been added to the data definition.

**Comment by c-schwarze** [comment]
I updated the format. 

If there is a program block, the text is below the "Program Details" header. If there is no program block, the text is below the Major/minors table (pretty much just CAS). Let me know if this should change.

**Comment by annmarieven** [comment]
looking good and working great.
