### ISSUE TITLE
Institutional Data & Research pdfs 

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#680]
I tried republishing them twice, but these three pdfs aren't working (the one for the CAPS page is). 

https://www.bethel.edu/institutional-data-research/outcomes/debt/cas-graduate-debt14.pdf
https://www.bethel.edu/institutional-data-research/outcomes/debt/gs-graduate-debt14.pdf
https://www.bethel.edu/institutional-data-research/outcomes/debt/sem-graduate-debt14.pdf

Could you take a look at this? Thanks!

FP job 16581

**Comment by c-schwarze** [comment]
It looks like the path is different since one of the folders has changed.

https://www.bethel.edu/institutional-data-research/outcomes/debt/cas-graduate-debt14.pdf
is now
https://www.bethel.edu/institutional-data-research/outcomes/student-debt/cas-graduate-debt14.pdf

**Comment by kathrynmagnuson** [comment]
Thanks!
