### ISSUE TITLE
GS Academics ENVoY Certificate Site Launch & Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#681]
Getting ready to launch the ENVoY site.

Built in testing folder right now: https://cms.bethel.edu/entity/open.act?id=b5a7637c8c58651370c56c6d2ea59f01&sort=fo&type=folder&sortd=ASCENDING

Migration grid:
https://docs.google.com/spreadsheets/d/11K-MAuCwqoMSQuA5tQAMvcVxkqdjoRO8hFBeWrgq3qk/edit#gid=1540206335

Redirects:
None. This is a brand new site.

- [x] Update Marketing google sheet https://docs.google.com/spreadsheets/d/1_6MxnM8nPsFMSzovfBTWV1MgMTUqUhJSGYphkg8gpac/edit?ts=56b23976#gid=0
- [x] Close footprints job 14267
- [x] Tag analytics @emily-johnson 
- [x] Add to marketing forms
- [x] Publish pages with certificate program feeds 
- [x] Add to overnight banner sync publish set

**Comment by annmarieven** [comment]
@c-schwarze I can't get the program details folder to appear in the left hand nav. Could you take a look?

https://staging.bethel.edu/_testing/build-out/graduate-academics/envoy/index.php

**Comment by annmarieven** [comment]
This site has been launched and is looking good!

**Comment by annmarieven** [comment]
@emily-johnson can you put a note in analytics about the launch of this site?

**Comment by emily-johnson** [comment]
Analytics are tagged

**Comment by annmarieven** [comment]
no longer need to do floodlight tags. haworth is doing them.

**Comment by annmarieven** [comment]
marketing grid updated.
