### ISSUE TITLE
GS Academics STEM Certificate Site Launch & Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#682]
Getting ready to launch the STEM site.

Built in testing folder right now: https://cms.bethel.edu/entity/open.act?id=b5ac9cb88c58651370c56c6d60eff03b&type=folder&

Migration grid:
https://docs.google.com/spreadsheets/d/11K-MAuCwqoMSQuA5tQAMvcVxkqdjoRO8hFBeWrgq3qk/edit#gid=817258412

Redirects:
None. This is a brand new site.

- [x] Update Marketing google sheet https://docs.google.com/spreadsheets/d/1_6MxnM8nPsFMSzovfBTWV1MgMTUqUhJSGYphkg8gpac/edit?ts=56b23976#gid=0
- [x] Close footprints job 14265
- [x] Tag analytics @emily-johnson 
- [x] Add to marketing forms
- [x] Publish pages with certificate program feeds 
- [x] Add to overnight banner sync publish set

**Comment by annmarieven** [comment]
@c-schwarze I can't get the program details folder to appear in the left hand nav. Could you take a look?

https://staging.bethel.edu/_testing/build-out/graduate-academics/stem/

**Comment by c-schwarze** [comment]
Fixed.

**Comment by annmarieven** [comment]
Site launched. Looking good.

**Comment by emily-johnson** [comment]
Analytics are tagged

**Comment by annmarieven** [comment]
@emily-johnson  Can we add the "STEM in K-12 Education Certificate" to the following forms?
marketing education
marketing caps/gs

**Comment by emily-johnson** [comment]
Done!

**Comment by annmarieven** [comment]
marketing grid updated.
