### ISSUE TITLE
Move Blink Layout Owners page

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#684]
We need to move this page to either Cascade or as a page in WSAPI. These links need to be only shown to certain groups (ideally) or roles. If we can do only roles the WSAPI is probably a better option. There is a Python script that handles the click. @c-schwarze can you work with a student on this sometime this semester?

Page: https://www.bethel.edu/its-old/blink/layout-owners/index/edit/

Script: https://www.bethel.edu/its-old/blink/layout-owners/lo-login/ZPythonScriptHTML_editForm

**Comment by c-schwarze** [comment]
Unfortunately we cannot link a pull request between repositories....Or move them with ease.

Here is the pull request in Tinker: https://github.com/betheluniversity/Tinker/pull/92

**Comment by c-schwarze** [comment]
@nate-li finished this. closing
