### ISSUE TITLE
CAS Study Abroad & Off Campus Programs Site Migration

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#685]
We're working to get rid of the old study abroad site and revamp the current Cascade page.

content grid (done by office, marked in order of importance, notes from me about each page):
https://docs.google.com/a/bethel.edu/spreadsheets/d/1CWY8tuCIKedjGiCydjmHUytT9X56FK-j6qSyxnhQepk/edit?usp=sharing

old site:
http://cas.bethel.edu/off-campus-programs/

current cascade page:
https://www.bethel.edu/undergrad/academics/study-abroad

I'm open to ideas about how this new page(s) would work. I think the main landing page should have a little more of a marketing feel to encourage students to study abroad. There is an FAQ page in the content grid that has some why study abroad info on it. I have no idea if this is usable but may be a good place to start.

Then if we want to have 2 more pages to go a little more in depth about international studies vs off-campus programs we could. I'm waiting to hear about a financial aid page (note on grid) so we may or may not have to migrate this.

Ultimately this page is going to point people to a new app called Terra Dotta which will house basically ALL the information that was on the old site - info about each program, applying, etc.

Let me know if you have any questions!

We're aiming to have this done the second week of February.

**Comment by annmarieven** [comment]
This got put on hold because Terra Dotta hadn't launched yet. Will still need to be done eventually just not sure of the new launch date. Stefan is working with the office to launch the new app so touch base with him.

Assigning to @hamtim to decide how high priority this is and who the writer will be.

**Comment by e-jameson** [comment]
Melanie Eslinger m-eslinger@bethel.edu
Keep track of any "empty" pages, but don't move them.

**Comment by emily-johnson** [comment]
Emailed Melanie about the pictures

**Comment by emily-johnson** [comment]
Melanie never replied that I can see in FP, emailed her directly

**Comment by emily-johnson** [comment]
Melanie replied and we are working on a few small changes, wait for a reply from MV

**Comment by c-schwarze** [comment]
@emily-johnson where is this at?
