### ISSUE TITLE
Workflow changes for Faculty Bio 

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#687]
@annmarieven We need to change the workflows for all Faculty Bios. Each workflow should submit the faculty listing pages of all 4 schools.

A faculty in CAS and SEM will only go through 1 workflow (and only 1 of the school listings will be published). The issue is that both school listings need to be published in this case.

Let me know if you have any questions!

**Comment by annmarieven** [comment]
each faculty bio workflow has been updated to publish all 4 school's publish sets.
