### ISSUE TITLE
Creating a workflow for E-Announcements

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#690]
@annmarieven, we need a workflow for Christine Ernston to approve e-announcement submissions. The workflow should also publish this Publish Set: https://cms.bethel.edu/entity/open.act?id=7f91a9be8c586513496652d5fa5767be&type=publishset

Users will be able to submit e-announcements through Tinker (similar to faculty bios/events). These submitted e-announcements will need to go to Christine's workflow.

Let me know if you have any questions.

**Comment by annmarieven** [comment]
I created this workflow based off the 'send event for approval' workflow.

https://cms.bethel.edu/entity/open.act?id=a2e7a9748c5865134eb5f740f4c83873&type=workflowdefinition

Let me know if you need anything else from me!

**Comment by c-schwarze** [comment]
Thanks! Closing.
