### ISSUE TITLE
Seminary Academics Online Program Page

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#691]
We need to finish creating and launch the seminary online page.

Page in Cascade:
https://cms.bethel.edu/entity/open.act?id=d358891c8c58651344b52cc3d1851b36&type=page&

- [x] launch page
- [ ] add to this page: https://www.bethel.edu/academics/online

**Comment by annmarieven** [comment]
@kathrynmagnuson can you find me a picture of a student on a computer? if possible, can they look relatively pleasant or happy :)

here are 2 examples:
https://www.bethel.edu/adult-undergrad/academics/online
https://www.bethel.edu/graduate/academics/online

**Comment by kathrynmagnuson** [comment]
![13968822112_3780acd9fb_o](https://cloud.githubusercontent.com/assets/14840641/12819070/26b26158-cb1f-11e5-9b9c-ba1e0104a049.jpg)
![13937033737_5710e23c28_o](https://cloud.githubusercontent.com/assets/14840641/12819068/26af8c8a-cb1f-11e5-8e69-4a9e5259f606.jpg)
![17800950996_ac434aa1e0_o](https://cloud.githubusercontent.com/assets/14840641/12819069/26afd46a-cb1f-11e5-8ef1-da315a0dcbae.jpg)
![13896153579_de10bd7304_o](https://cloud.githubusercontent.com/assets/14840641/12819067/26aee294-cb1f-11e5-8f82-7c1bd6c0b2e0.jpg)

**Comment by kathrynmagnuson** [comment]
Let me know if any of these work :)

**Comment by annmarieven** [comment]
hmmm.... are there any older looking students? those all look like undergrad folks and this is for Sem.

**Comment by kathrynmagnuson** [comment]
![7487497212_72f92c582a_o](https://cloud.githubusercontent.com/assets/14840641/12823589/7533e938-cb32-11e5-9199-b27ce0b40f0e.jpg)
![13996666215_c0263c59b1_o](https://cloud.githubusercontent.com/assets/14840641/12823590/7738546c-cb32-11e5-8d66-501a06a5f352.jpg)
![13997100134_3a48962d54_o](https://cloud.githubusercontent.com/assets/14840641/12823596/816c94ca-cb32-11e5-8d97-29c81ef3d731.jpg)

**Comment by kathrynmagnuson** [comment]
Most of the pictures are either of undergrad students... and most of the seminary pictures are a bit outdated

**Comment by kathrynmagnuson** [comment]
We found the picture Allie uploaded in December and linked it to the page. :)

**Comment by annmarieven** [comment]
This page has been launched.

https://www.bethel.edu/seminary/academics/delivery-options/online

@johjacb could you add it to bethel.edu/academics/online

**Comment by annmarieven** [comment]
@kathrynmagnuson can you link the word 'online' on this page: https://www.bethel.edu/seminary/academics/delivery-options/ to the page we just launched. let's also move the online section above the face to face section.

thanks! then reassign to @johjacb for updating.

**Comment by johjacb** [comment]
I've add it. Published the staging

**Comment by annmarieven** [comment]
Thanks @johjacb.

@kathrynmagnuson once this is done on your end you can just close the issue.

**Comment by kathrynmagnuson** [comment]
This is done!
