### ISSUE TITLE
Academic Program Gainful Employment 

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#692]
@c-schwarze I had to add a few more fields to the data definition of the academic program template. (they're at the bottom below the outcomes section) Could you work your magic to get them to show up?

Unfortunately this is urgent :( Vedder's needs the sites updated by tomorrow so do you think that's a possibility?

**Comment by c-schwarze** [comment]
Updated. 

Let me know if any changes need to be made!

**Comment by emily-johnson** [comment]
@c-schwarze Can we change it so that it will still show up without a heading? Thanks!

**Comment by c-schwarze** [comment]
Yep!

Updated.

**Comment by emily-johnson** [comment]
![screen shot 2016-01-28 at 2 15 18 pm](https://cloud.githubusercontent.com/assets/13204220/12657566/9e664b20-c5c9-11e5-874a-855333275607.png)

Any idea why this is here after I removed the heading? I tried republishing

**Comment by emily-johnson** [comment]
Oh, and then it doesn't show up at all on the live site

**Comment by c-schwarze** [comment]
Whoops. Fixed.

Also, the publish queue had some other things in it, so it published after a few more minutes. I just published that page to prod as well.

**Comment by emily-johnson** [comment]
Awesome, thanks!
