### ISSUE TITLE
Add a link to add an event to your calendar on Event Pages

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#693]
We need to 
- Add a link to add the event to your calendar (your personal calendar on your iPhone, for example)
  - only after RSVP if there is an RSVP form.

**Comment by c-schwarze** [comment]
@mjf78594 could you look into this?

**Comment by c-schwarze** [comment]
Throwing some documentation here for later: https://developers.google.com/apps-script/guides/rest/quickstart/js

I was able to get a simple test working. Now I am going to work on creating a usable prototype

**Comment by c-schwarze** [comment]
Although this is probably still desirable, the request is not active. Closing.
