### ISSUE TITLE
Empty block bug

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#695]
So we are working on setting up the [transportation index](https://cms.bethel.edu/entity/open.act?id=dcc5fc678c5865130265fd809af22214&type=page) to be able to quickly and easily add a block saying that shuttle services are suspended. We settled on a flex page with block at the top and the main content in the section below.

The issue is that when the first section is empty (when the shuttles are running and we don't need the alert), then the second section is not displayed. Help?

Thanks!!

**Comment by c-schwarze** [comment]
Fixed.

It used to only check the first section of the flex page for content/blocks/etc. I believe the example you used had an empty section followed by the next section with data.

I updated the code so that it looks through all sections (not just the first one).

**Comment by emily-johnson** [comment]
Awesome, thanks!!

@johjacb Could you take a look at the spacing now?

**Comment by c-schwarze** [comment]
I got it.

**Comment by c-schwarze** [comment]
should be fixed. You may have to republish.
