### ISSUE TITLE
Timezone on Event Pages

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#697]
We're going to put timezones on event pages. Maybe we can do this automatically with Python or something. Touch base with Jmo to hear his thoughts on that.

**Comment by c-schwarze** [comment]
Whoever ends up working on this, here is some documentation to look at:

https://velocity.apache.org/tools/devel/javadoc/org/apache/velocity/tools/generic/DateTool.html

**Comment by annmarieven** [comment]
Timezones: Pacific, Mountain, Central, Eastern

-- looking at the first update on this issue, was doing it automatically not something that was possible?

**Comment by c-schwarze** [comment]
- [ ] Add checkbox and dropdown fields to cascade
- [ ] Add fields to tinker event form
- [ ] Update Event format in cascade to display timezone (do we want to always mention the timezone?)
- [ ] Add shorthand timezone to calendar?

**Comment by e-jameson** [comment]
Can we not do it based on location, if they select one of the preloaded values?

**Comment by annmarieven** [comment]
Time options will be:
Central <--- this will be default
Pacific
Mountain
Eastern

Will appear on the event forms as:
CT
PT
MT
ET

**Comment by e-jameson** [comment]
This will launch with the new tinker version.
