### ISSUE TITLE
Broken Links: Marketing Page (PowerPoint Downloads)

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#698]
Caleb, 

The Powerpoint links under the Template section of this page are giving a 404. https://cms.bethel.edu/entity/open.act?id=394c5cf68c58651337aebe3f96eb4449&type=page& 
I checked in Cascade and they appear to be linked correctly, & I republished the page but they still aren't working. I also downloaded the Powerpoints in Cascade and was able to view them. 

Could you look in to this? Thanks! 

FB Job 16856

**Comment by c-schwarze** [comment]
It looks like the Powerpoints were not published. I published them all to prod/staging. Looks good to me!

**Comment by kathrynmagnuson** [comment]
Thanks!
