### ISSUE TITLE
Silva Redirects

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#700]
@e-jameson Can you put in these redirects? Thanks!

http://cas.bethel.edu/dept/biblical-theological/index-2 to /undergrad/academics/biblical-theological/

http://cas.bethel.edu/dept/theatre/index-2 to /undergrad/academics/theatre/

http://cas.bethel.edu/dept/comm/index-2 to /undergrad/academics/communication/

http://cas.bethel.edu/dept/mw-languages/index-2 to /undergrad/academics/world-languages/

http://cas.bethel.edu/dept/psychology/index-2 to /undergrad/academics/psychology/

http://cas.bethel.edu/dept/math-cs/index-2 to /undergrad/academics/math-cs/

http://cas.bethel.edu/dept/philosophy/index-2 to /undergrad/academics/philosophy/

http://cas.bethel.edu/dept/anthropology/index-2 to /undergrad/academics/anthropology-sociology-reconciliation/

http://cas.bethel.edu/dept/music/index-2 to /undergrad/academics/music/

http://cas.bethel.edu/dept/nursing/index-2 to /undergrad/academics/nursing/

**Comment by e-jameson** [comment]
@emily-johnson these are done.
