### ISSUE TITLE
Program Feed Update

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#702]
Right now we aren't using the program feed for these online lists but we should be:
https://www.bethel.edu/graduate/academics/online
https://www.bethel.edu/adult-undergrad/academics/online

Program feed data definition:
https://cms.bethel.edu/entity/open.act?id=98476db08c586513091377e50bd6ef0a&type=structureddatadefinition&

What do we need to do in order to be able to list online programs with concentrations listed and linked?

**Comment by c-schwarze** [comment]
You should be able to create a program feed with 'online' selected. Then include that block instead of the online block. I created one using the page the graduate/academics/online page: https://cms.bethel.edu/entity/edit.act?type=page&id=966b6e9f8c5865130265fd80d7f05b6f

Let me know if you have any questions.

**Comment by c-schwarze** [comment]
I realize I overlooked the part with "concentrations listed and linked". I can make that work.

I will add another option to the program feed: "Display by:" with options "Degree Type" and "Program"

This will take a bit of work, so it might not be finished for a week or so.

**Comment by c-schwarze** [comment]
This should be updated. There are limited options when you choose by Program Concentration compared to Degree type.

**Comment by annmarieven** [comment]
@emily-johnson can you see if we can create 2 online feeds for the pages included in the first description (above)?

We need them to look exactly as they do now so don't publish anything to production unless we know it's for sure working correctly.

Thanks!

**Comment by emily-johnson** [comment]
@e-jameson Can you take a look at both of these pages ([Graduate Online](https://www.bethel.edu/graduate/academics/online) and [Adult Undergrad Online](https://www.bethel.edu/adult-undergrad/academics/online)), the graduate page is using Caleb's new feed and the CAPS one is still using the old block, both of which are now broken (?)

Let me know if you have questions! Thanks!

**Comment by e-jameson** [comment]
@emily-johnson sending this back now that its working

**Comment by emily-johnson** [comment]
@e-jameson Can you take a look and link up the concentrations to the actual concentration pages (in the program details) instead of having all of the concentrations go to the program index? Example: [CAPS Business Management concentrations](https://staging.bethel.edu/adult-undergrad/academics/online)

And then also changing it to pull our title instead of the condensed Banner titles. But that can wait until @c-schwarze is back, so assign it to him when you're done :)

**Comment by emily-johnson** [comment]
This is the [old CAPS block](https://staging.bethel.edu/_testing/emj/test-online-block-old), we want it exactly like this :)

**Comment by e-jameson** [comment]
@emily-johnson, this is updated. I published the publish set as well.

**Comment by emily-johnson** [comment]
@e-jameson Can we update the names so that we're using our titles and not banner's?

**Comment by emily-johnson** [comment]
oh or @c-schwarze

**Comment by c-schwarze** [comment]
What title are you wanting changed? 

From what to what?

**Comment by emily-johnson** [comment]
Right now we are using the Banner titles for each program (which are formatted differently and abbreviate concentration). Can we change it to use our cascade titles?

The [old CAPS block](https://staging.bethel.edu/_testing/emj/online-block-old) has them how we want them to look

Thanks!

**Comment by c-schwarze** [comment]
I updated the Concentration titles to be the title of the concentration in cascade. 

I am just removing the "Program Details" text if it is found.

Also, I noticed that the titles of the program are slightly differing.

**Comment by c-schwarze** [comment]
Is this finished @emily-johnson ?

**Comment by emily-johnson** [comment]
Yeah, they look good, thanks!
