### ISSUE TITLE
Financial Aid Cleanup

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#703]
I'm working on changing the fin aid option collection pages to blocks (and deleting the old pages, republishing the pages with relationships, etc.)

**Comment by annmarieven** [comment]
We're also going to clean up the Financial Aid Options.
Content type relationships:
https://cms.bethel.edu/entity/relationships.act?id=b01e8cff8c5865130c130b3abdf08b22&type=contenttype

I've already created the new base asset for this. To get started on this one, create the block version of one of the page financial aid options. Then leave it (one block, one page of the same thing) and assign to @c-schwarze so he can update the financial aid option collection to look at blocks in addition to the page assets.

Once he's done that, he'll reassign it to you and you can do the rest of them.

Let me know if you have any questions!

**Comment by emily-johnson** [comment]
@c-schwarze Here is the first example: [Academic and Achievement option page](https://cms.bethel.edu/entity/open.act?id=d402585f8c586513162f1fd4ad4145b5&type=page&) and [Academic and Achievement option block](https://cms.bethel.edu/entity/open.act?id=0a23d1df8c5865133ad1c90530a9b1ad&type=block&)

**Comment by c-schwarze** [comment]
Done. Just create a flex page and attach the new block that is created.

And surprisingly we actually wrote the code to do this over a year ago. :smile:

**Comment by annmarieven** [comment]
hah. yay! @emily-johnson we don't actually have to embed the blocks anywhere because they'll be pulled to the pages using the financial aid collection.

**Comment by emily-johnson** [comment]
@kathrynmagnuson is working on the options today, and I'm going to try and finish up the collections

**Comment by kathrynmagnuson** [comment]
Here is a [financial aid option](https://cms.bethel.edu/entity/open.act?id=0f0d3f048c5865133ad1c905c1b3c33d&type=block_STRUCTUREDDATA) we just created a block for but don't think it's pulling to the[ staging site]( https://staging.bethel.edu/undergrad/financial-aid/types/military-benefits). can you take a look? @c-schwarze

**Comment by emily-johnson** [comment]
Collections are done!

**Comment by kathrynmagnuson** [comment]
@c-schwarze will you have time to look at this today? Thanks!

**Comment by emily-johnson** [comment]
Here's one of the [collections](https://cms.bethel.edu/entity/edit.act?type=block&id=0f2236338c5865133ad1c9054b5bef5e) that it should be pulling to (this particular option is tagged for all of the schools, the link I gave is the CAS collection)

**Comment by c-schwarze** [comment]
I updated the Collections. Let me know if it still isn't working correctly.

**Comment by emily-johnson** [comment]
@c-schwarze Everything looks good, thanks!

We made a lot of progress today, including finishing the military benefits! Kathryn will keep working her way down the list this afternoon as well

**Comment by emily-johnson** [comment]
@annmarieven I went to go delete the [Bethel Military Scholarship page](https://cms.bethel.edu/entity/open.act?type=page&id=d355e48d8c586513162f1fd49171b75a), but it is linked on the [National Guard page](https://cms.bethel.edu/entity/open.act?id=703126ee8c5865132dfb57c84cdb2619&type=page). I first thought of just replacing the page with the new block I made, but there is already a media-text block linked to the page. What would you like to do? Thanks!

**Comment by emily-johnson** [comment]
We're done!!
