### ISSUE TITLE
Nurse Educator events not pulling

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#705]
Hi Caleb! Could you take a look at why the Nurse educator events on [March 9th](https://cms.bethel.edu/entity/open.act?id=64c0bef78c58651331ed8325fe2d5699&type=page&) and [April 14th](https://cms.bethel.edu/entity/open.act?id=64c335fb8c58651331ed83253e8b7b8d&type=page&) aren't pulling to the [Nurse Educator index page](https://cms.bethel.edu/entity/open.act?id=bb0440298c58651370c56c6d4a0d5e57&type=page)? We looked at the events and the feed and everything seems to be tagged correctly, and the feed is pulling one event, so we know it at least kind of works.. Thanks!

**Comment by c-schwarze** [comment]
It looks good to me on the [staging page](https://staging.bethel.edu/graduate/academics/certificates/nurse-educator/).

Some of our feeds use php, which only shows up on staging.bethel.edu and www.bethel.edu (not the internal Cascade view).

I will create a new issue to display a "Events only appear on staging or prod" on the feed.

Let me know if you have any questions.

**Comment by emily-johnson** [comment]
Hmm.. we were looking on the live site. Maybe it was just taking Cascade extra long to publish. Thanks!

**Comment by c-schwarze** [comment]
It definitely could be. Cascade is pretty slow in publishing these days :disappointed:

**Comment by emily-johnson** [comment]
Any reason you can think of for why the program that they select in tinker wouldn't be pulled into the event in cascade? That was the original issue, that no program was selected in the metadata.

I'll double check and make sure that she is filling it all out in tinker, but I'm pretty sure she is

**Comment by emily-johnson** [comment]
Yeah, she said she is selecting it every time, and it often (or maybe even always) doesn't move over into cascade

**Comment by c-schwarze** [comment]
Should be fixed for all submissions now
