### ISSUE TITLE
Wufoo Issues in Firefox

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#707]
Brooke is having issues with Wufoo forms in Firefox (44.0.2) where the fields aren't expanding correctly & I was able to replicate the issue as well. Could you take a look at this? Thanks! 

FP 16953 (she included a video screenshot which demonstrates the issue).

**Comment by kathrynmagnuson** [comment]
Eric, have you had a chance to look at this?

**Comment by e-jameson** [comment]
@kathrynmagnuson can you send a support ticket to Wufoo asking them if they know of any issues in firefox? http://help.wufoo.com/wufoo_asksupport?l=en_US

**Comment by kathrynmagnuson** [comment]
They said they just fixed the issue yesterday, and I tried it again and it seems to be working just fine.
