### ISSUE TITLE
GitHub Reporting

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#709]
We would like to find a GitHub API that can help us generate useful reporting. Hopefully we can find a Python API. Some examples include: 

* List all users and the number of issues/comments/etc. associated with them for a given date range.
* Various averages on issues. i.e. average time an issue was open
* And anything other report that we can generate that provides cool or useful reporting.

**Comment by phg49389** [comment]
Moving this issue to Tinker, as that's where the code for it is being written.
