### ISSUE TITLE
Program Search

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#710]
We need to create a block in Cascade to search all of our programs.

This block should use JS to dynamically search our programs.

**Comment by c-schwarze** [comment]
Here are some options to search by:

* Program Name (is metadata separate? Do we want both?)
* Cohort info (probably only Online, F2F, and blended?)
* School

Are there any other pieces of info that would be useful? We can figure this out at our next Cascade meeting

**Comment by annmarieven** [comment]
are all programs in cascade and can we find them with exact name
find by cluster
other names for our programs
outcome based search

http://www.gcu.edu/degree-programs/

**Comment by annmarieven** [comment]
Other names and outcomes will be entered in Tinker (or mass upload with a csv) and then stored in Tinker database, csv file created on server.

I will create google spreadsheets for each program with:
Tag            Outcome     Other name
actuary           x                    x
math                                     x

**Comment by c-schwarze** [comment]
```when we say program search, we really mean program concentration search, correct?

AnnMarie Vennerstrom [2:18 PM] 
um… so you wouldn’t just find MBA, you’d find MBA in global something or rather?

Caleb Schwarze [2:19 PM] 
yeah "MBA: Finance Concentration” and "MBA: Global Management Concentration" (edited)

AnnMarie Vennerstrom [2:21 PM] 
hm. that’s a good question. we were doing that with cas but we only were going to make one spreadsheet per program for caps, gs, and seminary.

Caleb Schwarze [2:24 PM] 
We currently are doing both for our Program Feeds (you have the option to do by program or by concentration)```

**Comment by annmarieven** [comment]
@kathrynmagnuson can you go through the MBA sheet and MBA block and for every concentration, make a new tab in the spreadsheet. the name of the tab should be the last part of the system name of the page that it's linked up to (in the block).

We have to do this for every block that has concentrations but the rest can be created as we go through add terms.

**Comment by kathrynmagnuson** [comment]
Here's the spreadsheet with multiple tabs: https://docs.google.com/spreadsheets/d/109CvzGu5p2YiKt248aeuiRte_symdu6kM0bhyzv26Ic/edit#gid=0

**Comment by c-schwarze** [comment]
We decided to the following:
* The program search will display program concentrations, not programs
* The Spreadsheets will be by block with tabs for each concentration and a tab for ALL concentrations

**Comment by c-schwarze** [comment]
Closing.

This has moved to #748
