### ISSUE TITLE
Undergrad Theatre Photogallery Heading

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#713]
We just created this [photo gallery](https://cms.bethel.edu/entity/open.act?id=3405c2628c586513644af8a83cc5857c&type=block)/ [block](https://cms.bethel.edu/entity/open.act?id=34052d288c586513644af8a8caec503b&type=page) and the title is showing up as H3 size font, could you change it to the regular H2 size? Thanks!

**Comment by c-schwarze** [comment]
Done.

**Comment by kathrynmagnuson** [comment]
Thanks!
