### ISSUE TITLE
Add tracking to header

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#714]
@c-schwarze can you add tracking tags to the header links? Something like ?src=head or something like that. 

Lets do this for now but it might be interesting to see if there is anything we can do in Tag Manager to make the tracking less noticeable. Like a class on the <a> that triggers a tag?

**Comment by c-schwarze** [comment]
Added. It feels goofy to have the ?src=head be carried throughout the url, as the user clicks throughout the site.

Thoughts?

**Comment by e-jameson** [comment]
We are doing this 100% in opimizely, so this isn't needed.
