### ISSUE TITLE
Index page redirects

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#717]
When setting up a link in Cascade or using a page chooser, the system forces you to select the actual index rather than just the folder. The index page inevitably redirects back to the folder so we run into a bunch of redirects again.

Can we somehow fix this in Cascade or do something automatically that will remove index from our urls and allow us to point to the folder to avoid the redirect on the live stie?

Thanks!

**Comment by c-schwarze** [comment]
I updated everything I could find/think of. All links should have '/index' removed.

When we publish things the rest of the week, keep an eye out for errors or ones that are missed. I just published everything to staging, so tomorrow I will test around some more.

**Comment by c-schwarze** [comment]
I changed this to be a publish trigger. It appears to be working great. We just need to finish publishing everything today (since it failed twice last night).

**Comment by c-schwarze** [comment]
Everything to staging is published. next time we publish to production, it should be fixed.
