### ISSUE TITLE
Folder Meta Descriptions

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#719]
Marcel pulled a bunch of urls from our site that didn't have meta descriptions. Unfortunately many of these were folders. Is there any way we can make the folders look at the index page and use that description? Or do we need to actually put descriptions in for folder assets?

If we do this, we'll need to do a whole site publish. 

Thanks Caleb!

**Comment by c-schwarze** [comment]
Could you send me a few of the URLs that didn't have descriptions?

**Comment by annmarieven** [comment]
https://docs.google.com/spreadsheets/d/1H5P-3lUTjd12m7Joi4sbLf276EUPGa2SFAn9EheTOjE/edit#gid=1844724333

**Comment by e-jameson** [comment]
We updated the velocity/php template so this shouldn't be an issue. @annmarieven can you re-open once Marcel re-generates the sheet and it looks like its still an issue?
