### ISSUE TITLE
Wufoo form not loading

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#720]
The [Student Employment Application](https://staging.bethel.edu/_testing/financial-aid-form-testing/student-employment-app-1617) isn't loading, and we've checked the form hash, authentication requirements, where it's linked up, republished to staging, etc. multiple times. The other form in the folder works fine, so it seems to just be this one form (it looks fine in wufoo too). Can you take a look? Thanks!

**Comment by e-jameson** [comment]
There is a Javascript error on this page. @johjacb is going to take a look at it.

**Comment by emily-johnson** [comment]
@e-jameson How did you know (for me in the future)? I didn't see any error messages

PS thanks @johjacb!

**Comment by e-jameson** [comment]
@emily-johnson that turned out to be a false alarm. The real issue is the form has was copied/pasted with a space at the beginning, so it was generating an invalid ID for the <div> tag. I fixed the hash and published to staging.

**Comment by emily-johnson** [comment]
Ohh, ok. Darn invisible space. Thanks!
