### ISSUE TITLE
Faculty Bio discipline heading

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#722]
@parlau noticed an issue with faculty bios: 
On https://www.bethel.edu/undergrad/academics/world-languages/faculty, when
you click on "read more" for both Donna LeGrand and De Zhang, their
profiles do not contain those teaching specialty sections on their page.

It works for Sarah Tahtinen-Pacheco and Sandi Weightman, but not Donna and De. I don't know what the extent is of this problem on other profiles...

----

I looked into it a little and think that if a faculty has 'teaching specialty' selected as their heading, it doesn't follow through to their full bio page.

Can we make sure all 3 headings (teaching specialty, area of expertise, research interests) are coded to appear on the full bio page? Each faculty should only be able to select 1 and that 1 should appear on the faculty list in addition to the full bio page.

**Comment by c-schwarze** [comment]
Fixed. Faculty bios will need a republish.

**Comment by annmarieven** [comment]
Doing whole site publish tonight which will roll this out.

Double check tomorrow.

**Comment by e-jameson** [comment]
@annmarieven looks like this is fixed?
