### ISSUE TITLE
Course listings from Courseleaf XML

### ISSUE THREAD

**Issue by e-jameson** [betheluniversity/cascade#724]
We need to investigate creating course listings from our Catalog's XML. I'm not sure the best way to do this, but here is some info:

``` Eric,

Attached is the information regarding the APIs.  There are references to three different ones, you will be interested in the page API for the catalog.  The API has been turned on in Next and on the live catalog.  You can access it by adding /index.xml to the end of any page.

Thank you!

Marissa
```

Mike gave me this site as an example of the type of data and details we need:
http://www.crown.edu/online-graduate-programs/business-administration-mba/

[CourseLeaf - Data Access (APIs).pdf](https://github.com/betheluniversity/cascade/files/170046/CourseLeaf.-.Data.Access.APIs.pdf)

**Comment by c-schwarze** [comment]
Closing, as this is more than 4 years old. I'm pretty sure the requirements have changed.
