### ISSUE TITLE
Job titles in faculty listings

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#725]
https://www.bethel.edu/seminary/academics/faculty

If you look at Paul Ferris, Denise Muir-Kjesbo, and Dan Gurtner, they all have "Professor Professor"

This is because they have the title "Professor" for multiple programs.

Can we brainstorm a way to address this in our next Cascade meeting?

**Comment by annmarieven** [comment]
from our virtual cascade meeting in slack:

AnnMarie Vennerstrom [9:50 AM] 
let’s put a comma between multiple titles and only display unique ones. great idea @c-schwarze

**Comment by c-schwarze** [comment]
@annmarieven could you glance through this [staging page](https://staging.bethel.edu/seminary/academics/faculty)?

**Comment by annmarieven** [comment]
the staging page looks good. one more question in regards to this that just came up today...

If they have the same title within the same school, can we merge departments/programs within the listing on their bio page.

Example:

**Professor**
DMin, Bethel Seminary
MDiv, Bethel Seminary
MATL, Bethel Seminary

as opposed to

**Professor**
DMin, Bethel Seminary

**Professor**
MDiv, Bethel Seminary

**Professor**
MATL, Bethel Seminary

Actual bio: https://staging.bethel.edu/academics/faculty/ferris-paul

**Comment by annmarieven** [comment]
@c-schwarze did you see this?

**Comment by c-schwarze** [comment]
I did not. I will look at it now. Sorry!

**Comment by c-schwarze** [comment]
@annmarieven do you have any updates on this?

**Comment by annmarieven** [comment]
jmo said he thinks we can do both. there would be priority for grouping job titles within a specific program and then secondary would be grouping programs for identical job titles.

let me know if that doesn't make sense :-P

**Comment by c-schwarze** [comment]
@annmarieven I updated the job titles. It works for both now with the priority you mentioned. Could you take a look at a few bios?

https://staging.bethel.edu/academics/faculty/bement-jaroscak-laura
https://staging.bethel.edu/academics/faculty/bonawitz-katie
https://staging.bethel.edu/academics/faculty/daniels-nikki

**Comment by annmarieven** [comment]
looks great! i'm assuming this got pushed out with the last site publish, right?

**Comment by c-schwarze** [comment]
Yep! Closing...
