### ISSUE TITLE
Migrating old e-announcements

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#726]
@emily-johnson we need to migrate e-announcements from old Silva to Cascade. The old content can be found in the following folders:

- [x] https://bethelnet.bethel.edu/e-announcements/articles/2016/april/edit/tab_edit
- [x] https://bethelnet.bethel.edu/e-announcements/articles/2016/may/edit/tab_edit
- [x] https://bethelnet.bethel.edu/e-announcements/articles/2016/september/edit/tab_edit

They can live in the appropriate year and month folders here:
https://cms.bethel.edu/entity/open.act?id=7ebe061e8c586513496652d589b2429c&type=folder&

This video shows you were to find the main content, the metadata, and the dates for the e-announcement: http://screencast.com/t/37fKxIbhyFQZ

Based on the user's name (gather the name from the urls given above), you'll need to find the person's username and email address to enter into Cascade.

As you migrate, check for Bethel style and formatting. Link words rather than including urls, time formatting, date formatting, etc.

Send one per month through the workflow so that the approvers can have some practice.

If we could have these moved over by end of the day tomorrow, that'd be great.

Thanks!

**Comment by e-jameson** [comment]
@annmarieven I think there are some into 2017 too?

**Comment by annmarieven** [comment]
Christine said those were probably an accident.

**Comment by e-jameson** [comment]
ah quite so.

**Comment by emily-johnson** [comment]
@annmarieven Just a few notes: I didn't move over the second [Admitted Student Overnight](https://bethelnet.bethel.edu/e-announcements/articles/2016/april/edit/tab_edit) event, because it looks like a duplicate, and the [History of Science in Europe](https://bethelnet.bethel.edu/e-announcements/articles/2016/april/history_of_scie/edit/tab_edit) announcement has "(unapproved)" next to the preview in silva, so I'm not sure if it should've been moved, but I made it just in case.

Also, some titles are in all caps, do you want that to translate over too? Or do you want to stick to our usually only capitalizing the very first letter?

**Comment by emily-johnson** [comment]
Do we not have a BSOE Staff role? The [Admin Support Listserv announcement](https://bethelnet.bethel.edu/e-announcements/articles/2016/may/administrative/edit/tab_edit) had it selected in silva

**Comment by c-schwarze** [comment]
We removed that role. I would guess you can just use the St. Paul Staff. Maybe check with @hamtim on that.

**Comment by annmarieven** [comment]
@e-jameson can we put a redirect in from the old e-announcement submission page to the new?

https://bethelnet.bethel.edu/e-announcements/add-ann/
to:
https://tinker.bethel.edu/e-announcement/

**Comment by e-jameson** [comment]
done.

**Comment by annmarieven** [comment]
@emily-johnson can you change the 4 pages here to blocks?
https://cms.bethel.edu/entity/relationships.act?id=85dece258c5865130c130b3a3eae7fe6&type=contenttype

Delete and unpublish the original ones.

When the relationships tab is empty (the link above), will you delete the e-announcement content type?

**Comment by emily-johnson** [comment]
Done!
