### ISSUE TITLE
Degree Subtitle

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#727]
Let's get the degree metadata from the program block to show up when the degree subtitle field in metadata on a page (to be created) is set to show.

- [x] Create a 'Degree subtitle' field in metadata w/ options: Do not hide | Hide (default is hide except for academic program homepages, faculty pages, how to apply pages)
- [x] Get the degree field from program block to appear
- [x] Make it look pretty
- [x] Update existing program page metadata and page titles

**Comment by c-schwarze** [comment]
I don't see this on the [program detail](https://cms.bethel.edu/entity/edit.act?type=page&id=c278076c8c5865135753448208e7fd9d) flex pages

**Comment by c-schwarze** [comment]
Also, do we have any programs that have multiple degree types selected?

If so, how should we handle them? Comma separated?

**Comment by c-schwarze** [comment]
[Here](https://staging.bethel.edu/graduate/academics/counseling-psychology/) is a testing page.

**Comment by annmarieven** [comment]
The field is now also on the basic metadata. I had only added it to robust at first.

I don't believe any programs have multiple degree types. @hamtim can you confirm this?

**Comment by annmarieven** [comment]
AP, Vedders, and I are not crazy about how it looks. Too much space or something... @johjacb can you play around with it?

**Comment by johjacb** [comment]
this is with Caleb to implement the css i added

**Comment by c-schwarze** [comment]
It shouldn't make much of a difference if there are multiple degrees (it will be comma separated).

Also I added in jake's css.

And it should work with robust metadata and basic metadata with flex pages

**Comment by c-schwarze** [comment]
it sounds like it is good to go? Ill assign the github back to @a-vennerstrom to update program pages/titles

**Comment by annmarieven** [comment]
@johjacb can you make it not all caps? per the request of @vedmic.

Then reassign to me and we'll go through and update the page titles.

**Comment by johjacb** [comment]
this has been updated

**Comment by annmarieven** [comment]
@emily-johnson we need to update our caps and gs program page titles. Here are examples:

Existing:
M.S. in Physician Assistant
M.S. in Physician Assistant Program Details
M.S. in Physician Assistant Faculty
M.S. in Physician Assistant Application Process

New:
Physician Assistant
Physician Assistant Program Details
Physician Assistant Faculty
Physician Assistant Application Process

There are a few that we'll need to double check before we change them. They are:
MBA
Ed.D.
Associates
Nursing rn to bs

**Comment by annmarieven** [comment]
@emily-johnson, we're good to move forward with this. thanks!

**Comment by emily-johnson** [comment]
Done (CAPS):
Accounting
Business Management (and concentrations)
Christian Ministries
Finance
Human Services
Nursing
Org Leadership (and concentrations)

**Comment by emily-johnson** [comment]
Went back to that previous list and un-hid the degree subtitles and published.

Total list: 
- [ ] Accounting
- [ ] Business Management (and concentrations)
- [ ] Christian Ministries
- [ ] Finance
- [ ] Human Services
- [ ] Org Leadership (and concentrations)
- [ ] Nursing (RN to B.S.)
- [ ] Associates

- [ ] Counseling Psychology
- [ ] Education K-12
- [ ] Gerontology
- [ ] MBA
- [ ] Nurse Educator
- [ ] Nurse-Midwifery
- [ ] Physician Assistant
- [ ] Special Education
- [ ] Strategic Leadership
- [ ] Teaching

Notes:
- Didn't change Associates degree titles since it won't be getting a degree subtitle

**Comment by annmarieven** [comment]
Assigning to @a-parrott for changing 2 sites job titles to 'degree' and 'program'. Analytics will be tagged when that's done.

**Comment by emily-johnson** [comment]
@c-schwarze If "Select" is selected in the degree type field, can we have it not display anything? Thanks!

**Comment by a-parrott** [comment]
@c-schwarze: The degree subtitle is not appearing on some faculty pages and many of the how to apply pages. 
https://www.bethel.edu/graduate/academics/special-education/how-to-apply
https://www.bethel.edu/graduate/academics/gerontology/faculty

**Comment by a-parrott** [comment]
I changed the titles of the following programs: Strategic Leadership Program, Gerontology Degree, Business Management Program, Finance Degree.

Analytics are tagged.

**Comment by c-schwarze** [comment]
Fixed. Pages with degree subtitle selected will look for the program-details/index page to find the program block. Then it will use that degree metadata field.

Pages will need to be republished to see this change

**Comment by emily-johnson** [comment]
Published out all program folders, is this done then? @c-schwarze

**Comment by c-schwarze** [comment]
yes. reopen if any other issues arise.
