### ISSUE TITLE
Seminary Academics Certificate in Church Planting Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#728]
We're still in the build out phase but will be launching the church planting site soon. The site can be found in /_testing/build-out/seminary-academics/certificates/church-planting

link to build out folder in cascade: https://cms.bethel.edu/entity/open.act?id=e2d3f1668c5865135952038794983110&type=folder&

No migration grid or redirects (brand new program)

Launch To Dos:
- [x] Update Marketing google sheet (amv) https://docs.google.com/spreadsheets/d/1_6MxnM8nPsFMSzovfBTWV1MgMTUqUhJSGYphkg8gpac/edit?ts=56b23976#gid=0 
- [x] Tag analytics @emily-johnson 
- [x] Add to marketing forms @emily-johnson 
- [x] Publish pages with program feeds @emily-johnson 
- [x] Add to Seminary Programs publish set (amv)
- [x] Close footprints job 17122

Proofing:
@donowenskid can you review content?
I will proof on Chrome, Firefox, Safari, and iOS 9.3.1 on iPhone 6

**Comment by annmarieven** [comment]
@emily-johnson can you go through each asset in this folder and make sure the certificate in church planting metadata is tagged (for the ones that can be)? 

https://cms.bethel.edu/entity/open.act?id=e2d3f1668c5865135952038794983110&type=folder&

Will you also find a site image bank that seems relatively applicable and link it up? If you can't find one we'll have to create a new one with other Flickr images.

**Comment by emily-johnson** [comment]
I tagged everything with the certificate, and linked up the Transformational Leadership image bank

**Comment by annmarieven** [comment]
@e-jameson can you look at the news feed here? Articles are showing up that shouldn't be and I'm not sure why.

staging page: https://staging.bethel.edu/_testing/build-out/seminary-academics/certificates/church-planting/

news feed block: https://cms.bethel.edu/entity/open.act?id=e418eee38c58651359520387b7c38eda&type=block&

news feed article that's appearing: https://cms.bethel.edu/entity/open.act?id=c37d541e8c58651359520387e038d7e1&type=page

**Comment by e-jameson** [comment]
@annmarieven the page is linked to the Christian Studies certificates feeds still

**Comment by annmarieven** [comment]
waiting on approval from @hamtim.

**Comment by donowenskid** [comment]
Content is proofed. Edits have been adjusted. Good to go.

**Comment by annmarieven** [comment]
running into an issue here.
degree subtitle won't appear on this page:
https://staging.bethel.edu/seminary/academics/certificates/church-planting/how-to-apply

also, the breadcrumb on that page is larger than it is on all other pages. (ex: https://staging.bethel.edu/seminary/academics/certificates/church-planting/program-details/)

not sure if this is @johjacb or @e-jameson

**Comment by e-jameson** [comment]
Looks like the breadcrumb is getting the styling because there is no subtitle. @c-schwarze, any idea why its not getting it?

**Comment by annmarieven** [comment]
oops. forgot we're not doing degree subtitle on seminary programs yet. just caps/gs for now. i'm removing it but can we look at the breadcrumb still?

**Comment by annmarieven** [comment]
Site launched! Working through the post launch to-dos.

**Comment by emily-johnson** [comment]
Added the certificate to both the main SEM and leadership marketing wufoos

Published the Sem Academics index, SEM certificates index, SEM online programs feed, Leadership marketing page

Tagged analytics

**Comment by annmarieven** [comment]
everything is done and good to go. closing job.
