### ISSUE TITLE
Seminary Academics Marriage and Family Therapy Post-Graduate Certificate Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#732]
We're getting ready to launch this site: https://staging.bethel.edu/_testing/build-out/seminary-academics/certificates/family-therapy

link to build out folder in cascade: https://cms.bethel.edu/entity/open.act?id=f827d9ff8c586513739ca2fdd8489c5d&type=folder&

Migration grid: https://docs.google.com/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=0

Redirects: (just one)
https://www.bethel.edu/seminary/academics/st-paul-programs/certificates/family-therapy

Launch To Dos:
- [x] Create redirects @emily-johnson 
- [x] Update Marketing google sheet (amv) https://docs.google.com/spreadsheets/d/1_6MxnM8nPsFMSzovfBTWV1MgMTUqUhJSGYphkg8gpac/edit?ts=56b23976#gid=0 
- [x] Close footprints job 16331 (amv)
- [x] Tag analytics @emily-johnson 
- [x] Add to marketing forms @emily-johnson 
- [x] Publish pages with program feeds @emily-johnson 
- [x] Add to Seminary Programs publish set (amv)
- [x] Close and archive old site (amv)
- [x] Update migration grid

Proofing:
@donowenskid can you review content?
I will proof on Chrome, Firefox, Safari, and iOS 9.3.1 on iPhone 6

**Comment by donowenskid** [comment]
content looks great. Good to go!

**Comment by annmarieven** [comment]
Site proofed. Publishing to prod. @emily-johnson as soon as it goes live, you can do your items here.

**Comment by emily-johnson** [comment]
Redirect done

**Comment by annmarieven** [comment]
Site is launched. Just a few more post-launch things to do here. Assigning to Em.

**Comment by emily-johnson** [comment]
Redirect and analytics tag are done

I tagged the Human Services cluster in the program block and republished the site. I added it to the Sem general marketing form and the human services marketing form

**Comment by emily-johnson** [comment]
Published program feeds
