### ISSUE TITLE
Seminary Academics Certificate in Young Life Youth Ministry Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#733]
We're getting ready to launch this site: https://staging.bethel.edu/_testing/build-out/seminary-academics/certificates/young-life

link to build out folder in cascade: https://cms.bethel.edu/entity/open.act?id=f7c4f3148c586513739ca2fd69928e77&type=folder&

Migration grid: https://docs.google.com/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=0

Redirects: (just one)
https://www.bethel.edu/seminary/academics/st-paul-programs/certificates/young-life

Launch To Dos:
- [x] Create redirects @emily-johnson 
- [x] Update Marketing google sheet (amv) https://docs.google.com/spreadsheets/d/1_6MxnM8nPsFMSzovfBTWV1MgMTUqUhJSGYphkg8gpac/edit?ts=56b23976#gid=0 
- [x] Close footprints job 16332 (amv)
- [x] Tag analytics @emily-johnson 
- [x] Add to marketing forms @emily-johnson 
- [x] Publish pages with program feeds @emily-johnson 
- [x] Add to Seminary Programs publish set (amv)
- [x] Close and archive old site (amv)
- [x] Update migration grid

Proofing:
@a-parrott can you review content?
I will proof on Chrome, Firefox, Safari, and iOS 9.3.1 on iPhone 6

**Comment by a-parrott** [comment]
Content good to go.

**Comment by annmarieven** [comment]
Site has been proofed and is live. Going to go through the post-launch list.

**Comment by emily-johnson** [comment]
Published program feeds, redirected old site and added analytics tag

There's no cluster tagged, so I only added it to the Sem marketing form
