### ISSUE TITLE
Open Enrollment site migration

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#735]
We're getting ready to launch this site: https://staging.bethel.edu/_testing/build-out/open-enrollment

link to build out folder in cascade: https://cms.bethel.edu/entity/open.act?id=1b6391388c58651326dfdb1c61aa0161&type=folder&

Migration grid: https://docs.google.com/spreadsheets/d/1BxUTjlDdgBKo-XZrOHhx-DhXHSCBCzRLGZ4S9KyuyyI/edit#gid=1315737609

**Redirects:**
Rule:
https://www.bethel.edu/offices/human-resources/open-enrollment/...
to
https://www.bethel.edu/human-resources/open-enrollment/...

I'll do the files into the secure-files folder

**Launch To Dos:**
- [x] Move site into HR site
- [x] Redirect rule @e-jameson 
- [x] File redirects
- [x] Tag analytics
- [x] Update migration grid
- [x] Web author access (HR group)
- [x] Close and archive old site
- [x] Close footprints job 17360

**Proofing:**
@a-parrott can you review content?
I will proof on Chrome, Firefox, Safari, and iOS 9.3.1 on iPhone 6

**Comment by emily-johnson** [comment]
@annmarieven how does this look?

**Comment by annmarieven** [comment]
@emily-johnson looks great! I added web author access because that's something that needs to be done for this site.

**Comment by emily-johnson** [comment]
Looks good in the three browsers and on mobile

**Comment by a-parrott** [comment]
Content looks good!

**Comment by emily-johnson** [comment]
@e-jameson Can you let me know when the secure-files authentication is done?

**Comment by e-jameson** [comment]
rule is done.

**Comment by emily-johnson** [comment]
All done!
