### ISSUE TITLE
Cty Rd E2 alert on Tinker event pages

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#736]
Can we add the Cty Rd E2 construction alert that is on the [maps & directions page](https://cms.bethel.edu/entity/open.act?id=ba13b80c8c586513100ee2a718241435&type=page&) to all Tinker pages too? Only events that are on the St. Paul campus I'd assume. Thanks!

**Comment by c-schwarze** [comment]
Added to all Cascade Event pages. 

The alert will always show up, unless "Seminary San Diego" is selected for the school.

**Comment by emily-johnson** [comment]
@c-schwarze do we have to publish them all out?

**Comment by c-schwarze** [comment]
Ah yes. I forgot to mention that.

**Comment by emily-johnson** [comment]
Should we only do the current ones? Like the 2016 folder?

**Comment by c-schwarze** [comment]
Let me play around with making it appear automatically, first.

**Comment by emily-johnson** [comment]
Ok, thanks!

**Comment by c-schwarze** [comment]
Okay, all events 2016 and beyond will need to be republished.

But in the future, we can just update the alert text to apply it to all event pages.

**Comment by emily-johnson** [comment]
Now I'm not seeing it on any events

**Comment by e-jameson** [comment]
example: https://www.bethel.edu/events/2016/library/on-doing-online-instruction-well

**Comment by emily-johnson** [comment]
It now looks like it's on some, but I can't really see a pattern for which ones dont have it

**Comment by e-jameson** [comment]
Caleb's comment in the code 
```
// if the school does not include Seminary San Diego.
// if it is on campus
// if the date is after today
```

**Comment by emily-johnson** [comment]
Hmm.. There are a bunch of events that meet those requirements and don't have it still. I republished the 2016 folder to see if that's all the issue was, but the alert isn't even in the Cascade versions either. Ex: https://cms.bethel.edu/entity/open.act?id=be2bb11c8c58651337fd222103ace0fc&type=page&

Any thoughts @c-schwarze?

**Comment by c-schwarze** [comment]
The alert had to be written in PHP, so it will not show up in the cascade view. It can only be viewed on staging and www. 

The example you gave looks like its working on staging currently.

**Comment by emily-johnson** [comment]
@c-schwarze So we're good to go? From what I can find, we are. I'm checking back with Brooke and Avis again

**Comment by emily-johnson** [comment]
Also, she wants it on the commencement site too, so can I just add it manually like the maps-directions page?

**Comment by c-schwarze** [comment]
Yeah I believe we are good to go.

How many pages is it going to be on? If it is only a few, manually is totally fine.

**Comment by e-jameson** [comment]
so needy.
