### ISSUE TITLE
Seminary Academics Ministry Practice Certificate Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#737]
We're getting ready to launch this site: https://staging.bethel.edu/_testing/build-out/seminary-academics/certificates/ministry-practice

link to build out folder in cascade: https://cms.bethel.edu/entity/open.act?id=60927d548c58651331ed8325ae51f097&type=folder&

Migration grid: https://docs.google.com/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=0

Redirects:
none. there was no site previously.

Launch To Dos:
- [x] Update Marketing google sheet (amv) https://docs.google.com/spreadsheets/d/1_6MxnM8nPsFMSzovfBTWV1MgMTUqUhJSGYphkg8gpac/edit?ts=56b23976#gid=0 
- [x] Close footprints job 16335 (amv)
- [x] Tag analytics @emily-johnson 
- [x] Add to marketing forms @emily-johnson 
- [x] Publish pages with program feeds @emily-johnson 
- [x] Add to Seminary Programs publish set (amv)
- [x] Update migration grid

Proofing:
@donowenskid can you review content?
I will proof on Chrome, Firefox, Safari, and iOS 9.3.1 on iPhone 6

**Comment by donowenskid** [comment]
content good to go!

**Comment by annmarieven** [comment]
site launched and looking good.

assigning to @emily-johnson for post launch to dos.

**Comment by emily-johnson** [comment]
Done!
