### ISSUE TITLE
Seminary Academics Christian Studies Certificate Site Launch and Issues

### ISSUE THREAD

**Issue by annmarieven** [betheluniversity/cascade#738]
We're getting ready to launch this site: https://staging.bethel.edu/_testing/build-out/seminary-academics/certificates/christian-studies

link to build out folder in cascade: https://cms.bethel.edu/entity/open.act?id=60a422878c58651331ed83252af909ac&type=folder

Migration grid: https://docs.google.com/spreadsheets/d/1HuG1V-OM7If-YOM8_scVqYEH3PTH_Y1qyBXWhs4cdFQ/edit#gid=0

Redirects:
none. there was no site previously.

Launch To Dos:
- [x] Update Marketing google sheet (amv) https://docs.google.com/spreadsheets/d/1_6MxnM8nPsFMSzovfBTWV1MgMTUqUhJSGYphkg8gpac/edit?ts=56b23976#gid=0 
- [x] Close footprints job 16336 (amv)
- [x] Tag analytics @emily-johnson 
- [x] Add to marketing forms @emily-johnson 
- [x] Publish pages with program feeds @emily-johnson 
- [x] Add to Seminary Programs publish set (amv)
- [x] Update migration grid

Proofing:
@a-parrott can you review content?
I will proof on Chrome, Firefox, Safari, and iOS 9.3.1 on iPhone 6

**Comment by a-parrott** [comment]
I'm not sure there's information coming from Banner for the How to Apply section. 

@donowenskid - Could you add more content to the Spotlight paragraph? 75 to 100 words is the rule of thumb, less when we have less content to go off of, but it would be nice to have that section filled out a bit more.

Otherwise, looks good!

**Comment by donowenskid** [comment]
Content is ready to go.

**Comment by annmarieven** [comment]
Site launched and looking good.

Assigning to @emily-johnson for post launch to dos.

**Comment by emily-johnson** [comment]
Done!
