### ISSUE TITLE
Silva menu - linking to outside form

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#742]
So I need to add two google forms ([Dept Space Request](https://drive.google.com/open?id=1J_vcYN2pNe_PVGAT9cQ6M_jLji0huApqJScAKydWKF4) and [Moving an Employee](https://drive.google.com/open?id=1OQsY8GJnkRppcBPamfjWrKk--ksJg_-Dp-msE7Ojwic)) to the [Facilities bethelnet site](https://bethelnet.bethel.edu/facilities-mgmt/), and I wanted to do it like the Sign Request, where it just links to an outside URL right from the menu.

I tried just adding the menu item, and then making it an external doc (this is all me just trying to figure it out and messing with it) with the link to the form, but when it's live and you click on the menu item, it refreshes the same page and does nothing. Then I tried making it a tales (vs string) and it gave me an error, I have no idea what those mean. This is what I had:
![screen shot 2016-05-03 at 12 42 49 pm](https://cloud.githubusercontent.com/assets/13204220/14992636/9e07907c-112c-11e6-94ce-d20f574fce74.png)

The Space Request doesn't show up in the menu when I go into edit it, so thats weird, and I couldn't look at it for example. But it seems like it is linking to the old "name-plate" page in silva, and it's just redirecting to the cascade form. Is this what I should do with the two new forms, just create pages for it to link to, and redirect them to the Google form?

**Comment by emily-johnson** [comment]
Wait it just worked! Can you try clicking on the Dept Space Request?

**Comment by emily-johnson** [comment]
The other one worked too, woo! So never mind, as long as this is the best way to do it

I am curious why the sign request menu item doesn't show up though

**Comment by emily-johnson** [comment]
@e-jameson ok it's not working again apparently... :(

**Comment by e-jameson** [comment]
I think we got this all sorted, @emily-johnson can you test the site again from within Blink and let me know?

**Comment by emily-johnson** [comment]
All good!
