### ISSUE TITLE
Majors and Minors Program Blocks

### ISSUE THREAD

**Issue by a-parrott** [betheluniversity/cascade#744]
@kathrynmagnuson - Can you add CAS major and minor page links to each major and minor program block?

See these for examples:
https://cms.bethel.edu/entity/open.act?id=018dc7e08c586513739ca2fdcc55bd77&type=block&
https://cms.bethel.edu/entity/open.act?id=018f38058c586513739ca2fd8b0bbe0d&type=block&

Thanks!

**Comment by kathrynmagnuson** [comment]
I finished the majors and am working on the minors (stopped at cross-cultural-mission-program).

**Comment by vedmic** [comment]
You are a rockstar.


*Michael Vedders*
Director of Marketing
Bethel University
vedmic@bethel.edu
o. 651.638.6094
m. 651.260.8002

**Comment by kathrynmagnuson** [comment]
Ok, these are all finished! :)

**Comment by a-parrott** [comment]
Hey Emily and Kathyrn - Can you add display names to the undergrad program blocks that are for emphases? Thanks!

**Comment by emily-johnson** [comment]
I added the display names to the CAS concentrations yesterday, and they look good in the search
