### ISSUE TITLE
Staging links

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#745]
As of now, any links in staging take you out to www instead of staying in staging, can we fix this (per Eric)? :)

**Comment by c-schwarze** [comment]
Fixed. however, we will need a site-wide publish for this to appear everywhere. 

I think I will keep this issue open until the next site-wide publish.

**Comment by c-schwarze** [comment]
So we had to revert this update, since it broke some staging links.

It appears we have some apache rewrites that are causing us havoc. Will update when it is fixed.

**Comment by emily-johnson** [comment]
@c-schwarze this was fixed right?

**Comment by c-schwarze** [comment]
Yeah! This should be fixed. 

closing
