### ISSUE TITLE
Group permissions

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#750]
I created a new group for the Business Office, with Amy Blaz as the only member. She has access to what she should, but can't create any new assets (only Messages is in her New drop down list).

Andrea and I have compared the group to others and it looks identical

The issue looks to be with the group, and not her account, because when I also added her to the ITS group, she could then create new assets like normal.

Does anyone have any ideas?

**Comment by c-schwarze** [comment]
@emily-johnson I believe you resolved this?

**Comment by emily-johnson** [comment]
Yep! Thanks
