### ISSUE TITLE
New Tinker Issues

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#753]
Under Events:
- [x] Start/End dates should be required
- [x] If your curser is on the left side (left-hand nav.) you can't scroll

General:
- [ ] Is there a way for staff/faculty to save an event/bio/e-announcement and continue working on it later or do they have to do it all at once and submit? (I don't think so. -- Caleb)

**Comment by kathrynmagnuson** [comment]
![tinker-event](https://cloud.githubusercontent.com/assets/14840641/17871472/4f0bbbe0-6881-11e6-8fa6-56cb2c88f699.png)

**Comment by kathrynmagnuson** [comment]
Events: 

- it might be easier (for users) to have a field to choose what school it is, and then have a dropdown with the options that apply, rather than having all the options for all four schools showing at once

- deleted an event through Tinker and it is no longer in Cascade, but it still shows up live/the link still works (https://www.bethel.edu/events/2017/admissions/kmTest2) (Ghost page?) 

Faculty Bios:

- html showing up on test bio
![screen shot 2016-08-23 at 10 20 47 am](https://cloud.githubusercontent.com/assets/14840641/17898049/f85a9258-691b-11e6-85a7-000b73f4269a.png)

- When I click "edit bio" or "delete bio" it sends an error saying "Whoops! Tinker lost its connection" but seems to be working everywhere else

**Comment by kathrynmagnuson** [comment]
Faculty Bio:

- [ ] Under Job Title it asks "Are you the program director?" You can currently select yes and no at the same time, and once you click on one you can't un-click it

**Comment by kathrynmagnuson** [comment]
Office Hours: Web Services is showing up twice for me
![screen shot 2016-08-23 at 2 39 03 pm](https://cloud.githubusercontent.com/assets/14840641/17907009/62d57b7a-693f-11e6-96c6-43cc034493fd.png)

**Comment by kathrynmagnuson** [comment]
Office Hours:

- [ ] maybe add a way for offices to say they are closed for a whole day (i.e. Saturdays & Sundays, since right now it's required to put a time in for every day of the week)

**Comment by kathrynmagnuson** [comment]
Admin Menu: Blink Layout Owners 

- [ ] is this a clitch or can the names be moved to the right a little? 
![screen shot 2016-08-24 at 3 52 51 pm](https://cloud.githubusercontent.com/assets/14840641/17947615/1c0f5f9c-6a13-11e6-9fb9-29020b5fcbc9.png)

**Comment by kathrynmagnuson** [comment]
- [ ] still having issues with Clear Cache, when I click submit nothing happens

**Comment by c-schwarze** [comment]
Closing, those that matter we have taken care of.
