### ISSUE TITLE
Migrating HR News Channel from Blink to Cascade

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#754]
- [x] create DD
- [x] create channel format
- [x] create archive format
- [x] create hr news article format

**Comment by emily-johnson** [comment]
Michelle requested that the Employee Handbook link be added to the bottom, like it used to be, was there a reason we didn't put it in this time?

https://www.bethel.edu/human-resources/handbook

**Comment by emily-johnson** [comment]
@c-schwarze Do you have an estimate on when you'll get the chance to look at this? Thanks!!

**Comment by c-schwarze** [comment]
I have no knowledge of this. Who else would know?

**Comment by emily-johnson** [comment]
@e-jameson I'm pretty sure it was on the previous version in silva, and just now isn't in the Cascade one. Can we add it back? (The handbook link)

**Comment by emily-johnson** [comment]
@e-jameson do you think you'd have time to do this before next week?

**Comment by e-jameson** [comment]
@emily-johnson this is done sorry for delay.
