### ISSUE TITLE
Admission Team pages

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#755]
Can we add phone and email to the bio previews that get pulled into the adm team pages?

[https://www.bethel.edu/adult-undergrad/admissions/team/](https://www.bethel.edu/adult-undergrad/admissions/team/)
https://www.bethel.edu/graduate/admissions/team/
https://www.bethel.edu/seminary/admissions/team/

Thanks!

**Comment by c-schwarze** [comment]
Updated. Republish and phone and email should appear.

Let me know if you want the format to change!

**Comment by emily-johnson** [comment]
Thanks!

Note from Amara:

> I noticed that the phone numbers auto-fill an extension for the first
> number in the set, even though no extension was listed in Cascade for that
> first number. Do you know why? Can we have the extension for the first
> numbers listed removed?

**Comment by emily-johnson** [comment]
@c-schwarze have you had a chance to look at the extensions? ^

**Comment by c-schwarze** [comment]
Oh sorry. Its fixed and looks good on staging.

You will need to republish to www.
