### ISSUE TITLE
Sem Student Life Migration

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#756]
https://bethelnet.bethel.edu/sem-stulife/

/seminary/student-life

[ ] Migrate, copying current structure
[ ] Train Beth Clark into Cascade
[ ] Close and archive old site

**Comment by c-schwarze** [comment]
@emily-johnson where is this at?

**Comment by emily-johnson** [comment]
https://www.bethel.edu/undergrad/student-life/
