### ISSUE TITLE
Proof Point has too many digits

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade#757]
I believe we decided to limit the number of digits in proof points to about 4 (so that the numbers remain in the box). David, could you update this proof point to take care of the issue?

Proof point: https://cms.bethel.edu/entity/open.act?id=8d82a2f78c58651375fc4ed26b4c563c&type=block&
Example Page: https://staging.bethel.edu/undergrad/academics/physics/

![screen shot 2016-09-15 at 4 51 43 pm](https://cloud.githubusercontent.com/assets/7849657/18589567/eac00b90-7bf0-11e6-9a76-51d82b9f4387.png)

**Comment by d-freed** [comment]
Changed to $1.2 M in Cascade. Issue should be resolved.
