### ISSUE TITLE
Sem Faculty Page

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#758]
https://www.bethel.edu/seminary/academics/faculty

Currently one long list, can we split it up?
- Doctoral
- St. Paul
- San Diego
- Online

Change the order? Highlight specific faculty, some hardly ever teach but are at the top because of their name
### Repeating titles

David Howard has three job titles in order for him to show up in three program faculty lists. Each faculty member only has ONE title, can we have one set of info and be able to choose where they should be pulled to?
<img width="276" alt="screen shot 2016-09-23 at 2 46 29 pm" src="https://cloud.githubusercontent.com/assets/13204220/18799310/938e387c-819c-11e6-8bd0-c456330a620a.png">
### On main faculty page:

**Name** 
**Program director OF _____** (no "lead faculty")
**Title** ("Professor _of_ Old Testament")
**Started at Bethel**
**Short marketing blurb** (manually entered)
**Research interest OR area of expertise**
**Email**

Blurb example: Dennis Edwards, lead faculty at church, PhD in new testament

> "Brings his work as a regular teaching pastor and a phd in new testament"
### Levels of faculty/potential titles:
- faculty (instructor, assistant professor, associate professor, professor)
- associated faculty
- adjunct

Side project: have video welcome on program directors (online programs have program directors)

**Comment by emily-johnson** [comment]
Blurb in Highlight field (on main faculty page and in bio). Research, expertise or specialty content moved to highlight (whichever is being used currently)

Work on search for faculty page down the road

Program directors at the top of program pages, but faculty list is totally alphabetical (white boxes for program directors still, but wherever they are in the list)

Sorting by location on main faculty page


Fix job title duplication - discuss other options
Switching highlight
Location tag (once tagged, will add sort option)

**Comment by c-schwarze** [comment]
@emily-johnson This is old, but is there anything left to do?
