### ISSUE TITLE
Proof Point issues

### ISSUE THREAD

**Issue by kathrynmagnuson** [betheluniversity/cascade#759]
- [x]  bu_campus-acerage (has "acres" after 247)
- [x]  cas_anthropology_student-number (large number)
- [x] cas_biology_grad-school-acceptance-8-year ("nearly" in text before number)
- [x] cas_buisness_preparedness ("more than" in text before number)
- [x] cas_business_top-programs ("top" in text before number)
- [x] cas_chemistry_top-program ("top" used)
- [x] cas_communication_europe-term-countries (way too much)
- [x] cas_communication_forensics-scholarship (seems messed up)
- [x] cas_education_student-number
- [x] cas_financial-aid-work-study-earnings
- [x] cas_physics_top-program ("top")
- [x] cas_theatre_audience-members ( number too long - plus this is a really bad proof point) (this is also from 2014-2015, are we keeping this? - km)
- [x] cas_theatre_involvement (number too long)
- [x] cas_vespers-attendance (number too long)
- [x] gs_premier-para-partnership_anoka-hennepin-students (number too big) (at 4 right now)
- [x] gs_teaching_MTLE exams (all messed up)
- [x] sem_number-of-graduates (number too big)
- [x]  sem_online-time-commitment (number likely too big)

**Comment by d-freed** [comment]
completed the last two, looks good
