### ISSUE TITLE
Sociology and Reconciliation Studies - Name Change

### ISSUE THREAD

**Issue by emily-johnson** [betheluniversity/cascade#763]
Anthropology, Sociology, & Reconciliation Studies is changing its name to Sociology and Reconciliation Studies, here are the places we need to update it:

undergrad/academics/anthro...
- [x] folder system name
- [x] block system names and titles
- [x] site title and social media title in setup block
- [x] throughout majors-minors folder
- [x] newsletters/index
- [x] index page titles and content

undergrad/academics/departments
- [x] update dept name in the list

_shared-content/proof-points/
- [x] system names to cas__sociology-reconciliation_...
- [x] update metadata

_shared-content/quotes/
- [x] system names to cas__sociology-reconciliation_...
- [x] update metadata
- [x] images system names as well

**Comment by emily-johnson** [comment]
Once we get the dept folder done, I'll have Jmo do a rule from
/undergrad/academics/anthropology-sociology-reconciliation to
www.bethel.edu/undergrad/academics/sociology-reconciliation

**Comment by kathrynmagnuson** [comment]
I'm checking things off but they're just done to staging until we finish, then eric can put in the redirects before we publish live

**Comment by emily-johnson** [comment]
Blink > Office and Dept Sites  >Depts and Programs (CAS)
- [ ] Dept name and link

**Comment by kathrynmagnuson** [comment]
"Bethel is the only Christian university that integrates sociology, anthropology, and reconciliation studies in a single department" is this statement still true/do we take these sort of things into account when deleting all the anthropologies?

**Comment by d-freed** [comment]
Good question, I will check with Lauren.

**Comment by emily-johnson** [comment]
Redirect rule done, publishing folder now

**Comment by d-freed** [comment]
Lauren doesn't know what to do with that. So...I'd say hold for now.

**Comment by emily-johnson** [comment]
Updated the metadata in tinker, syched it and updated the metadata for the pages/blocks in the main folder

**Comment by emily-johnson** [comment]
Updated the proof point and quote metadata as well
